/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 100 2 ",
"   c #272728",
".  c #0C0C48",
"X  c #0D0D57",
"o  c #04045A",
"O  c #08085F",
"+  c #2F2F5C",
"@  c #030364",
"#  c #090972",
"$  c #00007B",
"%  c #0A0A7A",
"&  c #161676",
"*  c #12127D",
"=  c #2F2F63",
"-  c #313163",
";  c #303068",
":  c #36367F",
">  c #494949",
",  c #545455",
"<  c #51515A",
"1  c #5B5B5B",
"2  c #656565",
"3  c #6C6C66",
"4  c #6C6C6C",
"5  c #737373",
"6  c #7D7D76",
"7  c #77777D",
"8  c #7E7E7E",
"9  c #80806E",
"0  c #84847D",
"q  c #88887B",
"w  c #000083",
"e  c #02028C",
"r  c #15158E",
"t  c #000097",
"y  c #0C0C97",
"u  c #01019D",
"i  c #0D0D98",
"p  c #151591",
"a  c #181897",
"s  c #14149A",
"d  c #19199D",
"f  c #0101A3",
"g  c #0202A9",
"h  c #0909A8",
"j  c #0000B3",
"k  c #0000B8",
"l  c #7D7D8B",
"z  c #7F7F90",
"x  c #0000C0",
"c  c #0000CB",
"v  c #0000D3",
"b  c #0000DC",
"n  c #0101E3",
"m  c #0000EB",
"M  c #0000F7",
"N  c #0000FE",
"B  c #828282",
"V  c #878788",
"C  c #8B8B8B",
"Z  c #858594",
"A  c #8A8A90",
"S  c #959594",
"D  c #989897",
"F  c #939399",
"G  c #9A9A9A",
"H  c #A3A392",
"J  c #ACAC9B",
"K  c #9595A2",
"L  c gray64",
"P  c #ADADAD",
"I  c #B3B3A2",
"U  c #BBBBA9",
"Y  c #B5B5B5",
"T  c #BDBDBD",
"R  c #C1C1B0",
"E  c #C9C9B5",
"W  c #CBCBB8",
"Q  c #D0D0BC",
"!  c #BFBFC3",
"~  c #C4C4C4",
"^  c #CECECE",
"/  c #D6D6C3",
"(  c #D9D9C4",
")  c #DCDCCA",
"_  c #CFCFD4",
"`  c #D5D5D5",
"'  c #DCDCDC",
"]  c #E0E0CC",
"[  c #E6E6D2",
"{  c #E9E9D3",
"}  c #E0E0DF",
"|  c #EDEDDB",
" . c #E5E5E5",
".. c #E7E7EC",
"X. c #EBEBEC",
"o. c #ECECF1",
"O. c #F3F3F3",
"+. c #F8F8F4",
"@. c #F5F5FA",
"#. c #FDFDFD",
/* pixels */
" . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
" . . . . . . .}  . . . .}  .}  . . . .}  . . . .}  .'  . . .}  .}  . . .}  .}  . . .}  .}  . . . .} }  . . . .'  . .}  . . . .}  . . .} }  .}  . .} }  . . . .'  . .}  . .} }  .}  . . . . . . .",
" . . .X.O.O.+.+.O.O.O.O.O.O.O.O.O.O.@.+.O.O.O.O.O.O.O.O.O.O.O.+.O.O.O.O.O.O.O.O.O.O.+.+.O.O.O.O.O.O.O.O.O.@.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.@.O.O.@.O.O.O.O.O.O.O.O.O.@.O.O.O.O. . . . .",
" . .X.^ S D D H S D D D D D D D D D D H S D D D D D D D D D D G D D D D D D D D D D D G D D D D D D D D D D D D D S D D D D S D D D D D D D D D D F D D D D D D D S D D D S D D D D S L  . . . .",
" . .O.D f v c c c c c c c c c c c c c c c c c c b w h v c c c c c c c c c c c c c c c c c c b % J T Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y ~ 2 L T Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y T 4 ' X. . .",
" . .O.D c N N N N N N N N N N N N N N N N N N N N u v N N N N N N N N N N N N N N N N N N M N s ] @.X.o.O.O.X.O.O.O.O.o.o.O.O.O.O.X.O.X.#.C ' O.o.O.X.O.O.O.X.O.O.O.O.o.O.o.O.O.o.X.#.V ` X. . .",
" .' O.D c N N N N N N N N N N N N N N N N M N M N u v N M N N N N N N N N N N N N N N N N M N y / .. . . . . . . . . . . . . . . . . .' O.B ^  . . . . . . . . . . . . . . . . . . .X.0 `  . . .",
" . .O.D c N N N N N N N N N N N N N N N N N N N N f v N N N N N N N N N N N N N N N N N N M N y ( o. . . . . . . . . . . . . . . . . . .O.V ^ X. . . . . . . . . . . . . . . . . . .o.0 ` X. . .",
" . .O.D c N N N N N N N N N N N N N N N N N N M N f v N N N N N N N N N N N N N N N N N N M N y ( X. . . . . . . . . . . . . . . . . . .X.V / X. . . . . . .X. . . . . . .X. . . . .o.0 ` X. . .",
" . .O.D c N N N N N N N N N N N N N N N N N N N N u v N N N N N N N N N N N N N N N N N N N N y ( X. . . . .X. . . .X. . . . .X. . .X. .o.V ^ X. . .X. . . . . . . . . . . . . . . .O.B ` X. . .",
" . .+.D c N N N N N N N N N N N N N N N N N N M N u v N N N N N N N N N N N N N N N N N N M N y ( X. . . . . . . . . . . . . . . . . .} +.V ^ X. . . . . . . . . .X. . . . .X. . . .X.B `  . . .",
" .} +.H c N N N N N N N N N N N N N N N N N N N N f v N N N N N N N N N N N N N N N N N N N N y ( .. .X. . . . . . . . .X. . . . . . . .o.V ^ X. . . . . .X. . . . . . . . . . . . .o.B ' X. . .",
" . .O.D c N N N N N N N N N N N N N N N N N N N N f v N N N N N N N N N N N N N N N N N N N N y ( o. . . . . . . . . . . . . . . . .X. .+.V ^ X. . . . . . . . . . . . .X. . . . . .o.V `  . . .",
" . .O.S c N N N N N N N N N N N N N N N N N N M N u v N N N N N N N N N N N N N N N N N N M N y ( .. . . . . .X.X. . . . . . . . . . . .X.V ^ X. . . . . . .X. . . . . . . . . . .} X.0 ` X. . .",
" . .O.D c N N N N N N N N N N N N N N N N N N N N f v N N N N N N N N N N N N N N N N N N M N y ( .. . . . . . . . .X. . . .X. . . . .} +.V ^ X. . .X. . . . . . . . . . . . . . . .o.V `  . . .",
" . .O.D c N N N N N N N N N N N N N N N N N N M N u v N N N N N N N N N N N N N N N N N N N N y / o. . . .X. . . . . . . . . . . . . . .O.0 ^ X. . . . . .X. . . .X. . . . .X. . . .o.0 ` X. . .",
" .} O.D c N N N N N N N N N N N N N N N N N N N N u v N N N N N N N N N N N N N N N N N N M N y ( .. . . . . . . . .X. . . . . . . .X. .X.V ^ X. . . . . . .X. . . . . . . .X. . . .o.0 `  . . .",
" . .O.D c N N N N N N N N N N N N N N N N N N M N u v N N N N N N N N N N N N N N N N N N N N y ( o. . ... .X. . . . . . . .X. . . . . .o.V ^ X. . . . . . . . . .X. . . . . . . . .O.B ` X. . .",
" .} O.D c N N N N N N N N N N N N N N N N N N N N f v N N N N N N N N N N N N N N N N N N N N y / o. . . . . . . . . . . . . . . . . .} O.V ^ X. . . . . . . . . . . . . . . . . . .o.B ` X. . .",
" . .O.D c N N N N N N N N N N N N N N N N N N M N u v N N N N N N N N N N N N N N N N N N M N y ( o. . . . . . . .X. . . . . . . . . . .O.V ^  . . .X. . . .X. . . . . .X. . . . .} o.0 ` X. . .",
" . .O.D c N N N N N N N N N N N N N N N N N N N N u v N N N N N N N N N N N N N N N N N N N N y ( o. . . . . . . . . . .X. . . . . . . .O.V ^ X. . . . . . . . . . . . . . . . . . .X.B ` X. . .",
" . .@.D c N N N N N N N N N N N N N N N N N N M N f v N N N N N N N N N N N N N N N N N N M N y / .. . . . . . . . . . . . . . . . . . .O.B ^ X. . . . .X. . . . .X. . . . . . . . .X.B ` X. . .",
" . .O.D c N N N N N N N N N N N N N N N N N N N N u v N N N N N N N N N N N N N N N N N N N N y ( o. . . . . . . . . . . . .X. . . . . .o.V ^ X. . . . . . . . . . . . . . . . . . .O.B ` X. . .",
" .} +.H c N M M M N M N M N N M M N M N M N M M N u v N M M N M M N M N N N M N M N M N M M N y /  .}  . . .}  . . . .'  . .}  . . .'  .X.0 ^ X.}  . .}  .}  .} }  . . . . . .'  .} X.8 ` X. . .",
" .} O.D c N N N N N N N N N N N N N N N N N N M N u v N N N N N N N N N N N N N N N N N N M N y { @.O.O.+.O.+.O.O.O.O.O.+.O.+.O.O.O.O.O.#.S ' +.O.O.+.O.O.O.O.@.O.O.@.O.O.O.O.O.O.O.#.C ` X. . .",
" . .O.D $ h u i f u u h i f f u f u u h u f h u h @ w g u u u f u f f u u f f u f u u f f u g @ q D C S S C S A C S C S S A S S S C S C D , B S S A S C S S S A C S A F S S C S S A S 1 '  . . .",
" . .O.D H ( W W Q Q Q Q Q Q Q W Q Q Q Q Q Q W W ) 6 g b v v v v v v v v v v v v v v v v v v n % I ~ R ~ T T R ~ ! T T T T T T T ~ T ! R ~ 4 P ~ T T ~ T T T R ! T T T R T T ~ T R ! ~ 5 ` X. . .",
" . .O.D ! @.o.o.o.o.X.X.o.o.o.X.o.o.X.X.o.o.o. .#.F v N N N N N N N N N N N N N N N N N N M N y ) @.o.o.o.o.o.o.X.O.X.O.o.O.X.X.X.o.O.X.#.C ` O.o.o.X.X.O.X.X.X.O.X.O.X.O.X.O.X.o.o.+.B ` X. . .",
" . .O.D Y o.'  . . . . . . . . . . . . . . . . .O.A v N N N N N N N N N N N N N N N N N N M N y / .. . . . . . . . . . . . . . . . . .} O.0 ^ X. . . . . . . . . . . . . . . . . .} +.0 ` X. . .",
" .} O.D Y O. . . . . . . . . .X. . . . . . . .} +.A v N N N N N N N N N N N N N N N N N N N N y ( o. . . . . . . . . . . . . . . . . . .O.V ^ X. . . . .X. . . . . . .X. . . . . .} o.0 ` X. . .",
" . .O.S Y O. . . . .X. . . . . . . .X. . . . . .+.A v N N N N N N N N N N N N N N N N N N M N y / o. . . .X. . . . .X. . . . . . . . .} o.V ^ X. . . . . . . . . . . . . . . . . . .X.l ` X. . .",
" . .O.D Y O. . . . . . . . . . . . . . . . . . .O.A b N N N N N N N N N N N N N N N N N N N N y ( .. . . . . . . . . . . . . . . . . .} +.V ^ X. . . . . . . . . . . . . . . . . . .o.0 ` X. . .",
" . .O.D Y o. . . . . . . . . . . . . . . . . .' +.A v N N N N N N N N N N N N N N N N N N N N y ( .. . . . . . . . . .X. . . . . . . . .O.V ^ X. . . . . . . .X. . . . . . . . . . .X.B ` X. . .",
" . .O.S Y o. . . . .X. . . . .X. . . .X.X. . . .+.S v N N N N N N N N N N N N N N N N N N M N y ( X. . . . . .X. . . . . . . . . . . . .o.V ^ X. . . . . . . . . . . . .X. . . . . .X.B ` X. . .",
" .} O.D Y +. . . . . . . .X. . . .X. . . . . .} +.A v N N N N N N N N N N N N N N N N N N M N y / o. . . . . . . . . . . . .X. . . . . .+.0 ^ X. .X. . . . . . . . .X. . . . . . . .X.B `  . . .",
" . .O.S Y +. . . . . . . . . . . . . . . . . . .O.A v N N N N N N N N N N N N N N N N N N N N y ( o. . .X. . . . .X. . . . . . . . . .} o.V ^ X. . . . .X. . . . . . . . . .X. . . .O.0 ` X. . .",
" .} O.D Y O. . .X. . . . .X. . . . . . . . . . .+.A b N N N N N N N N N N N N N N N N N N M N y ( X. . . . . . . . . . .X. . . . . . . .o.V ^ X. . . . . . . . . . . . . . .X. . .} +.B ` X. . .",
" . .O.D Y O. . . . . . . . . . . . .X. . . . . .+.A v N N N N N N N N N N N N N N N N N N N N y ( .. . . . . .X.X. . . . . . . . . . . .+.V ^ X. . . . . . . . . . . . . . . . . . .o.0 ` X. . .",
" . .O.D Y O. . . . . .X. . . .X. . . . . . . . .+.A v N N N N N N N N N N N N N N N N N N N N y / .. . .X. . . . . . .X. . . . . . . .' X.V ^  . . .}  . . . . . . . .}  . . . . . .X.l ` X. . .",
" . .O.D Y O. . . . . . . . . . . . . . . . . . .+.S v N N N N N N N N N N N N N N N N N N M N y ( o. . . . . . . . . . . . .X.O.O.O.O.+.#.C ' #.O.O.O.+.O.O.O.O.O.O.O.O.O.X. . . .} o.0 ` X. . .",
" .} O.D Y O. . . . . .X. . . . .X. . . . .X. . .O.A v N N N N N N N N N N N N N N N N N N M N y / X. . . . . . . . . . . .X.^ S G G G D L 1 C G D D D D D D D D G D D D G ' X. . .} o.B ` X. . .",
" . .O.D Y O. . . . . . . . . . . . . . . . . .} +.A b N N N N N N N N N N N N N N N N N N N N y ( o. . . . . . . . .X. . .O.S C T Y I Y Y Y Y P Y Y Y Y Y Y Y Y Y Y P ~ 4 1 } o. . .X.B `  . . .",
" .' O.D Y O. . . . . . . . .X. . . . . . . . . .+.A v N N N N N N N N N N N N N N N N N N M N y ( o. . . .X. . .X. . . . .O.S ~ #.o.o.+.o.X.O.O.o.O.O.o.O.X.O.o.O.O.X.#.G H 7 ' X. .O.B ` X. . .",
" . .O.D Y o. . . . . . . . . . . . .X. . . . . .+.S v N N N N N N N N N N N N N N N N N N N N y ( .. . . . . . . . . . . .O.S Y X.}  . . . . . . . . . . . . . . . . .O.V ^ ^ 5 ' X.X.8 ` X. . .",
" . .O.S Y O. . . . . . . . . . . . . . . . . . .O.A v N N N N N N N N N N N N N N N N N N N N y ( .. . . . . . . . . . .} O.S Y X. . . . .X. . . . . . . . . .X. . .' O.C ~ +.~ 4 ' @.8 ` X. . .",
" . .O.D Y X.'  .}  . . . . .}  . .'  . . .}  .' O.C v N M M N M M N M M M N M M M N M M M M N y /  .}  . . .}  . .'  . .' O.A T +. . . . . . . . . . . . . . . . . . .O.C ~ X.X.~ 4  .C ` X. . .",
" .} O.D ~ #.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.X.#.D v N N N N N N N N N N N N N N N N N N M N y { @.O.@.+.+.+.+.O.+.O.+.O.#.H ! o. .X. . . . . . . . . .X. . . . . . .O.C ~ X. .O.~ 6 4 ` X. . .",
" . .O.D 2 S C C C C C V C V C C C C V C C C C C D , w u t u t u u u t u u u t u u u t u u t f o 6 z l l l l l l l l l l l Z < ! o. . . . . . . .X. . . . . . . . . . .O.C ~ X. . .X.~ > ' X. . .",
" . .O.D G ` ~ ~ ~ ^ ~ ~ ~ ~ ~ ~ ~ ~ ^ ~ ~ ~ ~ ~ ` 7 j n b b b b b b b b b b b b b b b b b b n w x n b n b b b b n b b b b m r Q X. . . . . . . . . . . . . . . . . . .O.C ~ X. . . .O.V ` X. . .",
" .} O.S T +.X.X.X.X.o.X.o.+.o.X.X.X.X.X.o.o.X.X.#.S v N N N N N N N N N N N N N N N N N N N N u b N N N N N N N N N N N N N f Q o. . . . . . . .X. . . . . .X. . . . .O.C ~ X. . . .X.8 ` X. . .",
" .} O.D Y o. . . . . . .|  . . . . . . . . . .} O.C v N M N N N N N N N N N N N N N N N M M N t b N M N N N N N N N N N M N f W o. .X. . . .X. . . . .X. . . . . . . .O.C ~ X. . . .O.B `  . . .",
" . .O.D Y o. . . . . . . .X. . . .X. . . .X. .} +.S v N N N N N N N N N N N N N N N N N N N N u b N N N N N N N N N N N M N f W o. . . . . . . . . . . .X. . . . . . .O.C ~ o. . . .o.0 ` X. . .",
" . .O.D Y O. . . .X. . . . . . . . . . . . . .} +.A v N N N N N N N N N N N N N N N N N N N N t b N N N N N N N N N N N N N g W o. . . . . . . . . . . . . . . . . . .O.C R o. . .} X.B ` X. . .",
" .} O.S Y o. . . . . . . . . . . .X. . . . . . .+.A v N N N N N N N N N N N N N N N N N N M N u b N N N N N N N N N N N M N f W o. . . . . . . . .X. . .X. . .X. . . .O.C ~ o. . . .X.B ` X. . .",
" . .O.D Y O. . . . . . . . .X. . . . . . . . .} +.A v N N N N N N N N N N N N N N N N N N N N t b N N N N N N N N N N N M N f W o. . . .X. . .X. . . .X. . . . . . . .O.C ~ X. . . .O.B ` X. . .",
" . .@.S Y O. . . . . .X. . . . . . . . . .X. . .@.A v N N N N N N N N N N N N N N N N N N M N t b N N N N N N N N N N N M N f W o. . . . . . . . . . . . . . . . . . .O.C ~ X. . . .o.0 ` X. . .",
" . .O.D Y O. . . . . . . .X. . . . . . . . . .} +.A v N N N N N N N N N N N N N N N N N N N N u b N N N N N N N N N N N N N g E o. . . . . . . . . . . . . . . . . . .O.C ~ X. . . .X.B ` X. . .",
" . .O.D Y X. . . .X. . . . . . .X. . . . .X. . .+.S v N N N N N N N N N N N N N N N N N N M N t b N N N N N N N N N N N M N f W o. . . . . . . . . . .X.X. . . . . . .O.C ~ X. . . .X.B ` X. . .",
" . .O.D Y O. . . . . . . . . . . . . . . . . . .+.A v N N N N N N N N N N N N N N N N N N M N u b N N N N N N N N N N N N N f E o. . . . . . .X.X. . . . . . . . . . .O.C ~ X. . . .X.B `  . . .",
" .} O.D Y o. . . . . .X. .X. . . . . . . . . . .O.A v N N N N N N N N N N N N N N N N N N N N u b N N N N N N N N N N N M N f W o. . . . . . . . . . . . . . . . . . .O.C ~ X. . . .O.B ` X. . .",
" . .O.S Y O. . . . . . . . . . . . . .X. . . .' +.A b N N N N N N N N N N N N N N N N N N N N t b N N N N N N N N N N N N N g E X.}  . . . . . . . . . . . . . . . .' O.C ~ X. . .} o.0 ` X. . .",
" . .O.D Y O. . . .X. . . . . .X. . . . . . . . .+.A v N N N N N N N N N N N N N N N N N N M N u b N N N N N N N N N N N M N f ( +.O.O.@.O.O.O.O.O.O.O.O.+.O.O.O.O.O.O.#.D ~ X. . . .o.B ` X. . .",
" .' O.D Y O. . . . . . . . . . .X. . . . .X. . .+.A v N N N N N N N N N N N N N N N N N N M N t b N N N N N N N N N N N M N u 9 K S S S S A S A S S S A S A S S S A S G , T O. . . .X.0 ` X. . .",
" . .O.D Y O. . . . . . .X. . . . . . . . . . . .+.S v N N N N N N N N N N N N N N N N N N N N u b N N N N N N N N N N N N N m o j b c v v c v c c v v c c v c v c v c v c ; / X.}  .O.0 ` X. . .",
" . .O.D Y O. . . . . . . . . . . . . . . .X. . .+.C v N N N N N N N N N N N N N N N N N N N N t b N N N N N N N N N N N N N N n e n N N N N N N N N N N N N N N N N N M N b - ) O.} O.l ` X. . .",
" . .O.D Y o. . . . . . . .X. . . . . . . . . .} +.A v N N N N N N N N N N N N N N N N N N M N u b N N N N N N N N N N N N N N N n $ n N M N N N N N N N N N N N N N N N M N n - ( X.X.B `  . . .",
" .} O.D Y O. . . . . . . . . . . . . . . . . .} +.A v N N N N N N N N N N N N N N N N N N N N u b N M N N N N N N N N N N N N N N n $ b N N N N N N N N N N N N N N N N N N N b ; / @.8 ` X. . .",
" . .O.D Y X.}  .}  . . . . . . . . . . .}  . .} O.C v N M N N N M N M N N M N M M N M N M M N t b N N M M N M N M N M N M N N M M N n % b N M N M N M N N N M N M M M N M N M N b + [ A ` X. . .",
" .} O.D ! #.o.O.+.o.+.o.O.O.o.+.o.+.O.O.O.o.o.o.#.F v N N N N N N N N N N N N N N N N N N N N u b N N N N N N N N N N N N N N N N N N m e n N N N N N N N N N N N N N N N N N N N n : 3 '  . . .",
" . .@.D 2 C V V V V V 0 V q V V V V 0 V V V V 0 C , % a r r r a p p p p p p p p p p p a p r a X * a r a p p p p p p p p p p p p p p p s & . p a p p p p p p p p a a p r p p p a r s #   }  . . .",
" . .O.D H ' ~ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ' B U { ] ) ] ] ) [ ] ) ] ] ] ] ] ) ] ) ] ) | q R { ) ] ] ) ] ] ] ] ] ] ] ] ) ] ] ] ) ) | 0 W { ] ] ] ] ] ] ] ] { ] ] ] ] ) ] ) ] ) | 8 ' X. . .",
" .} O.S ! +.X.X.X.X.X. .X.X.X.X. .X.X.X.X.X.X. .+.S ! @. .X.X.X.....X...X... .X.X...X... ...@.C ^ o.....X.....X.............X.X....... .@.V ` X............. .X.| o.X.X.X...X...X. .O.0 ` X. . .",
" .} @.D Y o. . . . . . . . . . . . . . . . . . .@.A ~ o. . . . . . . . . . . . . . . . . .} O.V ~ X. . . . . . . . . . . . . . . . . . .+.0 ^ X. . . . . . . . . . . . . . . . . . .O.B ` X. . .",
" . .O.S Y O. . . . . . . . . . . .X. . . . . .' O.S R o. . . . . . . . . . .X. . . . . . . .O.C ~ o. . . . . . . . . . . . . . . . . . .o.V ^ X. . . . .X. . . . . . . . . . . . . .X.B ` X. . .",
" .} O.D Y o. . . . . . . . . . . . . . . . . . .O.S T o. . . . . . . . .X. . . . . . . . . .O.C ^ X. . . . . . . . .X. . .X. . . . . . .o.V / X. . . . . . . . . . . . . . .X. . .} o.8 `  . . .",
" . .O.D Y O. . . . . . .X. . . . . . . . . . . .O.S T X. . . . . . .X. . . . . .X. . . . .} O.C ~ X. . . . .X. . . . . . . . . . . . . .O.V ^ X. . . . . . . . .X. .X. . . . . . . .O.B ` X. . .",
" . .O.D Y O. . . . . . . . . . . . . .X. . .X.} @.A T o. . . . .X. . . . .X. . . . . . . . .O.C ~ X. . . .X. . . .X. . . . . . . . . . .X.V ^ X. . . . . . . .X. . . . .X. . . . . .X.0 ` X. . .",
" .} O.F Y O. . . .X. . . . . .X. . . . . . . . .O.F R O. . . . . . . . . . . . . . . . . . .O.V ^ X. . . . . . . . . . . . .X. . . . . .o.V ^ X. . .X. . . . . . . . . . . . . . . .O.V ` X. . .",
" .} @.D Y o. . . . . .X.X. . . .X. . . . . . . .+.S ! o. . . . . . .X. . . . . . . .X. . .} O.C ~ X. . . . . . . . . .X.X. . . . . . . .O.V ^ X. . . . . . . . . . .X. . . . . . . .o.0 ` X. . .",
" . .O.D Y O. . . . . . . . . . . . . . . . . . .O.A R X. . .X. . . . . . . . .X. . . . . . .O.C ~ X. . . . . .X. . . . . . . . . . . . .o.V ^ X. . . . . .X. . . . . . . . . . . .} o.8 ` X. . .",
" .} O.D Y O. . . . . . . . . . . . . . . . . .} O.S T O. . . . . . . .X. . . . . . . . . .} O.C ^ X. . . . . .X.X. . . . . . . . . . . .o.V ^ X. . . .X. . . . . . . . . . . . .X. .o.0 ` X. . .",
" . .O.D Y o. . . .X. . . . .X. . . .X. . . .X. .O.C T o. . . . . . . . . . . . . .X. . . . .O.C ~ X. . . . . . . . . . . .X. . . . . .} +.V ^ X. . . . . . . . .X. . . . . . . . . .X.l ` X. . .",
" . .O.D Y O. . . . . . . . . . . . . . . . . .} O.A R O. . . . .X. . . . . .X. . . . . . .} O.C ~ X. . . . . . . . . . . . . . . . . . .o.V ^ X. . . . .X. .X. . . . .X. .X. . . .} X.0 ` X. . .",
" . .O.D Y O. . . . . . .X. . . . . . . . . . . .+.S ! o. .X. . . . . . . . . . . . .X. . . .O.C ~ X. . . .X. . . . .X. . . . .X. . . . .O.0 ^ X. . . . . . . . . . . . . . . . . . .O.B ` X. . .",
" . .O.S Y o. . . . . . . . . . .X. . . . . . . .O.C ! o. . . . . . . . .X. . . . . .X. . . .O.C ^ X. . . . .X. . . . . . . . . . . . . .+.0 ^ X. . . . . . . . . . . . . . .X. . . .X.B ` X. . .",
" .} O.D Y +.|  .X. . . . . . .X. . . . .X. . .} O.S T O. . . . . . .X. . . . . . . . . . . .O.C ~ X. . . . . . . .X. . . . . . . . . . .o.V ^ X. . .X. .X. . . . .X. . . . . . . . .O.B `  . . .",
" .} O.D Y o. . . . . .X. . . . . . . . . . . . .+.S ! o. . . . . . . . . . . . .X. . . . . .O.V ~ X. . . . . . . . . . . .X. . . . . . .O.V ^ X. . . . . . . . . . . .X.X. . . . . .X.B ` X. . .",
" . .O.D Y +. . . . . . .X. . . . . . .X. . . . .O.A R X. . . . . . .X. . . . . . . . . . .} O.C ~ X.| X. .X. . . . .X. . . . . . . . . .O.V ^ X. . . . . . . . . . . . . . . . . . .O.0 ` X. . .",
" . .O.D Y O. . . . . . . . . . . . . . . . . . .+.S T o. . . . . . . . . . . . . . . . . . .O.V ^ X. . . . . . . . . . . . . . . . . .} O.V ^  . . . . . . . . . . . . . . . . . .} O.0 `  . . .",
" .} O.D Y o.'  . . . . . .}  .}  . . . . .'  . .O.C T X. . .}  . . . . .'  . . . . . .|  .' +.V ~ X.}  . . . . . . . . . .}  .}  . . . .o.V ^ X.}  . . . . . . . .}  . . . .}  . .' X.8 ` X. . .",
" . .O.F ~ +.X.O.X.O.o.o.X.X.O.X.X.o.O.X.O.X.X.X.#.D ~ +.X.o.X.O.X.O.X.O.o.O.X.o.X.O.X.o.X.X.#.S ^ O.o.O.O.X.X.X.o.o.o.o.o.o.o.o.o.o.o.X.#.C ` +.X.O.O.o.X.X.O.X.+.X.o.X.+.X.X.o.O.X.#.V ` X. . .",
" . .O.L 2 V B B 0 V 0 B B B B l 0 B 8 B B B B 0 C 1 5 V 0 l 0 B B B B 0 B 0 B B 0 l l B B 0 V 1 5 V 0 B B B B B 0 0 V B 0 B 0 V 0 B 0 B V , 5 V 0 l 0 0 8 B B B B 0 l 0 B 0 l B 8 B B 2 }  . . .",
" . . . .` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ' ` ` ` ` } ' ` ` ` ` ` ' ` ` ` ` ` ` ' ` ` ` ` ` ` ` ' ' ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` } ` ` ' ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` }  . . . .",
" .X. . .X.X. .X.X.X.X. .X. .X.X.X.X.X.X. .X. .X.X. . .X.X.X.X. . .X. .X.X.X. .X. .X. .X.X.X.X. . . .X.X.X. .X.X.X.X.X. .X.X.X.X.X.X.X.X.X. . .X. .X. .X.X.X.X.X.X.X. .X.X.X.X.X. .X.X. . . . . .",
" . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .X. .",
" . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .X. . . . ."
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"48 48 200 2 ",
"   c #E6E6E6",
".  c gray90",
"X  c #E4E4E5",
"o  c #E4E4E4",
"O  c gray92",
"+  c #EBEBEC",
"@  c #ECECEC",
"#  c gray89",
"$  c #D0D0CD",
"%  c #CECECB",
"&  c #CFCFCC",
"*  c #CFCFCB",
"=  c gray80",
"-  c #CBCBCB",
";  c #CDCDCD",
":  c #1010BD",
">  c #0505E0",
",  c #0808D9",
"<  c #0808DA",
"1  c #0808DF",
"2  c #0808C1",
"3  c #0808BE",
"4  c #0808E0",
"5  c #0707E0",
"6  c #0A0ABF",
"7  c #ABABAD",
"8  c #CBCBCA",
"9  c gray77",
"0  c #C5C5C5",
"q  c #ACACAC",
"w  c #AFAFAF",
"e  c #CACACA",
"r  c blue",
"t  c #0000FD",
"y  c #0000E0",
"u  c #0000DC",
"i  c #0202DE",
"p  c #CCCCCF",
"a  c #F4F4F3",
"s  c #F3F3F3",
"d  c #D0D0D0",
"f  c #0101FB",
"g  c #0000FC",
"h  c #0000DF",
"j  c #0000DB",
"k  c #0101FC",
"l  c #0202DD",
"z  c #C5C5C8",
"x  c #ECECEB",
"c  c #C6C6C6",
"v  c gray79",
"b  c #EAEAEA",
"n  c #C6C6C9",
"m  c #EDEDEC",
"M  c gray78",
"N  c #CCCCCE",
"B  c #F3F3F2",
"V  c #EAEAEB",
"C  c gray95",
"Z  c #0000E7",
"A  c #0000E6",
"S  c #0000C5",
"D  c #0000C2",
"F  c #0202C3",
"G  c #AEAEB1",
"H  c #D1D1D0",
"J  c #B2B2B2",
"K  c #A8A8AC",
"L  c #C7C7CD",
"P  c #C1C1C6",
"I  c #C2C2C7",
"U  c #C0C0C6",
"Y  c #ABABAF",
"T  c #0404BE",
"R  c #0000E3",
"E  c #0202C0",
"W  c #ACACAE",
"Q  c #CDCDCC",
"!  c #C5C5C6",
"~  c #CCCCCA",
"^  c #F5F5F3",
"/  c #EEEEEC",
"(  c #F5F5F2",
")  c #D2D2D0",
"_  c #0505DC",
"`  c #E2E2E3",
"'  c #0505DB",
"]  c gray91",
"[  c gray93",
"{  c #EEEEEE",
"}  c #DADADA",
"|  c gray",
" . c #AAAAAA",
".. c #C0C0C0",
"X. c #C1C1C1",
"o. c gray76",
"O. c gray74",
"+. c gray87",
"@. c gray94",
"#. c gray83",
"$. c gray82",
"%. c #CECECE",
"&. c #D7D7D7",
"*. c #A9A9A9",
"=. c gray61",
"-. c #CDCDCE",
";. c #EBEBEA",
":. c #C6C6C5",
">. c gray84",
",. c #E9E9E9",
"<. c #F1F1F1",
"1. c #B7B7B7",
"2. c gray68",
"3. c #C8C8C8",
"4. c #B1B1B0",
"5. c #0404C0",
"6. c #0000E5",
"7. c #0000DD",
"8. c #0000DE",
"9. c #0101C2",
"0. c #C5C5C7",
"q. c #A8A8AA",
"w. c #D2D2D2",
"e. c #D8D8D8",
"r. c #929292",
"t. c #0000E4",
"y. c #0202E4",
"u. c #0303DD",
"i. c #1616BA",
"p. c #DCDCD2",
"a. c #E8E8EA",
"s. c gray75",
"d. c #F4F4F4",
"f. c #C3C3C3",
"g. c #0101FD",
"h. c #1414D3",
"j. c #DCDCD1",
"k. c #E8E8EB",
"l. c #1515D2",
"z. c #1414D2",
"x. c #D9D9CF",
"c. c #E5E5E9",
"v. c #E3E3E4",
"b. c #E1E1E3",
"n. c #BCBCBE",
"m. c #1515D4",
"M. c #E7E7D8",
"N. c #F5F5F0",
"B. c #F1F1EB",
"V. c #F2F2EC",
"C. c #F0F0EA",
"Z. c #F9F9F3",
"A. c #C9C9C5",
"S. c #D1D1D4",
"D. c #0F0FCD",
"F. c #A4A4AC",
"G. c #ADADCA",
"H. c #AAAAC0",
"J. c #ABABC2",
"K. c #AAAAC1",
"L. c #B0B0C8",
"P. c #8F8FA1",
"I. c #D7D7CD",
"U. c #F3F3F5",
"Y. c #0000F4",
"T. c #0000AB",
"R. c #0000EE",
"E. c #0000E8",
"W. c #0202E9",
"Q. c #5151AB",
"!. c #F5F5DF",
"~. c #C7C7CA",
"^. c #0000FE",
"/. c #0000F8",
"(. c MediumBlue",
"). c #0000F7",
"_. c #0202FF",
"`. c #5757BB",
"'. c #CACABE",
"]. c #CDCDCF",
"[. c #0303E2",
"{. c #0505E2",
"}. c #0505DA",
"|. c #0505D1",
" X c #0404A2",
".X c #0404D9",
"XX c #0505D9",
"oX c #0808E1",
"OX c #0000D7",
"+X c #3F3F7A",
"@X c #D5D5CC",
"#X c #EAEAEC",
"$X c #C9C9C8",
"%X c #D0D0D3",
"&X c #B2B2B0",
"*X c #CACAC9",
"=X c #C9C9C7",
"-X c #D2D2D3",
";X c #A7A7B0",
":X c white",
/* pixels */
"                                                                                                ",
"  .   . X X X X X X X X X X X X X X X X X X X X o . . . . . . . . o o . . . . . . . . . .   .   ",
"    .   O + O + + + + + + O O + + + + + + + + O O @ O O O O O O @ O O @ O O O O O O @ O   .     ",
"  .   # $ % & * * * * * * & & * * * * * * * * & = = = = = = = = = = = = = = = = = = - ; #   .   ",
"  X O $ : > , < < < < , 1 2 3 4 , < < < < , 5 6 7 8 9 0 0 0 0 9 - q w e 9 0 0 0 0 9 e q ; O .   ",
"  X + * < r t r r r r t r y u r t r r r r t r i p a O @ @ @ @ O s ; d s O @ @ @ @ O s - = O .   ",
"  X O & , r f t t t t g r h j r g t t t t k r l z x # o o o o # O c v b # o o o o # O 9 = O .   ",
"  X + * < r t r r r r t r y u r t r r r r t r i n m o         o @ M e @ o         o @ 0 = O .   ",
"  X + * < r t r r r r t r y u r t r r r r t r i n m o         o @ M e @ o         o @ 0 = O .   ",
"  X + * < r t r r r r t r y u r t r r r r t r i n m o         o @ M e @ o         o @ 0 = O .   ",
"  X + * < r t r r r r t r y u r t r r r r t r i n m o         o @ M e @ o         o @ 0 = O .   ",
"  X + * , r k t t t t g r h j r g t t t t g r l z x # o o o o # O c v O # o o o o # O 9 = O .   ",
"  X + * < r t r r r r t r y u r t r r r r t r i N B V @ @ @ @ b s = d C O @ @ @ @ b s e = O .   ",
"  X O & 2 Z h y y y y h A S D Z h y y y y h A F G H v e e e e v d w J d v e e e e v d w = O o   ",
"  o O = K L P I I I I U L Y T R j u u u u j R E W Q ! M M M M c = q w = c M M M M c = q = O o   ",
"  . x = ~ ^ x / / / / x ( ) _ r t r r r r t r i N a V @ @ @ @ O s ; d s O @ @ @ @ O s - = O .   ",
"  . O = 9 V ` o o o o ` b v ' r g t t t t g r l z x # o o o o # O c v b # o o o o # O 9 = O .   ",
"  . O = 0 @ o         o @ e _ r t r r r r t r i n m o         o @ M e @ o         o @ 0 = O .   ",
"  . O = 0 @ o         o @ e _ r t r r r r t r i n m o   .   . # O c v b # o o o o o @ 0 = O .   ",
"  . O = 0 @ o         o @ e _ r t r r r r t r i n m o     . ] @ s ; d s O [ [ @ {   O 0 = O .   ",
"  . O = 0 @ o         o @ e _ r t r r r r t r i n m o   . ] } | M  .q c ..X.X.o.O.+.@.9 = O .   ",
"  . O = 9 O # o o o o # O v ' r g t t t t g r l z O ` o ` + O.O.#.d $.d d d %.&.*.=.O v - @ .   ",
"  . O = e s O @ @ @ @ V B d _ r t r r r r t r i -.( O m ;.a :.>.@.b b O O O ,.<.M M 1.| %.O .   ",
"  o O = 2.%.M 3.3.3.3.M %.4.5.6.7.8.8.8.8.7.6.9.Y -.z n 0.N q.w.,.o . . . . # @ O.e.. r.; @ o   ",
"  o O = 2.%.M 3.3.3.3.M %.4.5.6.7.8.8.8.8.7.t.D 9.y.l i u.6.i.p.a..         o @ s.$.d.f.e @ o   ",
"  . O = e s O @ @ @ @ V B d _ r t r r r r t r 8.8.r t r g.r h.j.k..         o @ s.w.@.0 = O .   ",
"  . O = 9 O # o o o o # O v ' r g t t t t g r 7.7.r g t f r l.j.k..         o @ s.w.<.9 = O .   ",
"  . O = 0 @ o         o @ e _ r t r r r r t r 8.8.r t r g.r h.j.k..         o @ s.w.<.0 = O .   ",
"  . O = 0 @ o         o @ e _ r t r r r r t r 8.8.r t r g.r z.x.c.` v.v.v.v.b.V n.w.<.0 = O .   ",
"  . O = 0 @ o         o @ e _ r t r r r r t r 8.8.r t r g.r m.M.N.B.V.V.V.V.C.Z.A.S.@.0 = O .   ",
"  . O = 0 @ o         o @ e _ r t r r r r t r 8.8.r t r t r D.F.G.H.J.J.J.J.K.L.P.I.U.f.= O .   ",
"  . O = 9 O # o o o o # ;.v ' r k t t t t g r 7.7.r g t t r Y.T.h R.Z E.E.E.E.W.6.Q.!.~.e @ .   ",
"  . O = - s O @ @ @ @ O s d _ r t r r r r t r 8.8.r t r r ^.r /.(.).r ^.r r r ^._.Y.`.'.].O .   ",
"  o O = q = c M M M M ! = w 3 [.' _ _ _ _ ' {.5.5.{.' _ _ _ }.> |. X.X_ ' ' ' ' XXoXOX+X@X#Xo   ",
"  o O = w d v e e e e v d J w d v e e e e v d 4.4.d v e e e e $X%Xw &Xd *Xe e e e =X-X;X8 @ o   ",
"  . O = e s b @ @ @ @ O C d = s ;.@ @ @ @ O B %.%.B O @ @ @ @ O B = d C O @ @ @ @ ;.B ~ = O .   ",
"  . O = 9 O # o o o o # O v ! O # o o o o # V M M V # o o o o # O ! v V # o o o o # O 9 = O .   ",
"  . O = 0 @ o         o @ e M @ o         o @ 3.3.@ o         o @ M e @ o         o @ 0 = O .   ",
"  . O = 0 @ o         o @ e M @ o         o @ 3.3.@ o         o @ M e @ o         o @ 0 = O .   ",
"  . O = 0 @ o         o @ e M @ o         o @ 3.3.@ o         o @ M e @ o         o @ 0 = O .   ",
"  . O = 0 @ o         o @ e M @ o         o @ 3.3.@ o         o @ M e @ o         o @ 0 = O .   ",
"  . O = 9 O # o o o o # b v c O # o o o o # O M M O # o o o o # O c v b # o o o o # O 9 = O .   ",
"  . O = - s O @ @ @ @ O s d ; s O @ @ @ @ O s %.%.s O @ @ @ @ O s ; d s O @ @ @ @ O s - = O .   ",
"  . O ; q e 9 0 0 0 0 9 e w q - 9 0 0 0 0 9 e 2.2.e 9 0 0 0 0 9 - q w e 9 0 0 0 0 9 e q ; O .   ",
"  .   # ; - = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = - ; #   .   ",
"    .   O @ O O O O O O @ O O @ O O O O O O @ O O @ O O O O O O @ O O @ O O O O O O @ O   .     ",
"  .   . . . . . . . . . . o o . . . . . . . . o o . . . . . . . . o o . . . . . . . . . .   .   ",
"                                                                                                "
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"32 32 226 2 ",
"   c gray90",
".  c #E7E7E6",
"X  c #EEEEEA",
"o  c #EEEEEB",
"O  c #EDEDEB",
"+  c gray92",
"@  c #EAEAEA",
"#  c #E6E6E6",
"$  c #E1E1E2",
"%  c #C6C6D0",
"&  c #C5C5D1",
"*  c #C6C6D1",
"=  c gray81",
"-  c #D0D0D0",
";  c gray82",
":  c #E4E4E4",
">  c #0101D6",
",  c #0000EE",
"<  c #0101E9",
"1  c #0000EA",
"2  c #0000E9",
"3  c #0000D2",
"4  c #0000D7",
"5  c #0101E8",
"6  c #0000EF",
"7  c #0F0FD0",
"8  c #C5C5C3",
"9  c gray84",
"0  c #D2D2D2",
"q  c LightGray",
"w  c #D7D7D7",
"e  c #BCBCBC",
"r  c gray77",
"t  c gray74",
"y  c #E9E9E9",
"u  c blue",
"i  c #0000FE",
"p  c #0000FD",
"a  c #0000E5",
"s  c #0000EB",
"d  c #0101FD",
"f  c #0F0FE3",
"g  c #DADAD8",
"h  c #EEEEEE",
"j  c #EFEFEF",
"k  c gray85",
"l  c #0101FC",
"z  c #0F0FE2",
"x  c #D5D5D4",
"c  c #CDCDCD",
"v  c #D5D5D5",
"b  c gray80",
"n  c #D6D6D4",
"m  c #E9E9EA",
"M  c #E4E4E5",
"N  c #0000FC",
"B  c #0000E4",
"V  c #D5D5D3",
"C  c gray83",
"Z  c gray91",
"A  c #DBDBD9",
"S  c #DADADA",
"D  c #0C0CD1",
"F  c #0C0CE8",
"G  c #0D0DE3",
"H  c #0C0CE4",
"J  c #0C0CE3",
"K  c #0D0DE9",
"L  c #0A0ACD",
"P  c #0000D3",
"I  c #0D0DCC",
"U  c #C1C1BF",
"Y  c #CECECE",
"T  c #B9B9B9",
"R  c #C0C0C0",
"E  c gray73",
"W  c gray76",
"Q  c #D3D3D4",
"!  c #D2D2D3",
"~  c #DBDBD8",
"^  c #B3B3C0",
"/  c #0000D8",
"(  c #0000F0",
")  c #0E0ED1",
"_  c #C5C5C4",
"`  c #D8D8D8",
"'  c #C5C5C5",
"]  c gray",
"[  c #D7D7D6",
"{  c #E8E8E9",
"}  c #F2F2EE",
"|  c #C6C6D4",
" . c #E3E3E4",
".. c #EDEDE9",
"X. c #C1C1D0",
"o. c gray89",
"O. c #E2E2E2",
"+. c #C2C2D0",
"@. c #E7E7E7",
"#. c gray94",
"$. c #ECECEC",
"%. c #C1C1CF",
"&. c #D4D4D3",
"*. c #E7E7E9",
"=. c #E2E2E3",
"-. c #E6E6E7",
";. c gray78",
":. c gray72",
">. c #CACACA",
",. c gray79",
"<. c gray75",
"1. c #E8E8EA",
"2. c #F3F3EF",
"3. c #1010E3",
"4. c #DEDED8",
"5. c #ECECE8",
"6. c #F4F4EF",
"7. c #CBCBC8",
"8. c gray88",
"9. c #DDDDDD",
"0. c gainsboro",
"q. c #BBBBBB",
"w. c #CCCCCD",
"e. c #D5D5D2",
"r. c #AEAEBB",
"t. c #0000E3",
"y. c #0C0CCC",
"u. c #B2B2C0",
"i. c #C2C2D3",
"p. c #BDBDCE",
"a. c #C0C0D2",
"s. c #AEAEBA",
"d. c #E2E2E1",
"f. c #CBCBCB",
"g. c gray86",
"h. c #ACACAC",
"j. c #C3C3C3",
"k. c #DCDCD9",
"l. c #B3B3C1",
"z. c #0000D9",
"x. c #0000EC",
"c. c #0000F1",
"v. c #0000DA",
"b. c #0202EA",
"n. c #3131CB",
"m. c #ECECDD",
"M. c #E4E4E7",
"N. c #C5C5D4",
"B. c #0202FC",
"V. c #3131D7",
"C. c #ECECDC",
"Z. c #E4E4E8",
"A. c #C6C6C6",
"S. c #3030D7",
"D. c #E8E8DB",
"F. c #E1E1E7",
"G. c #E2E2E5",
"H. c #E1E1E4",
"J. c #E6E6E9",
"K. c #C3C3C5",
"L. c #0202FD",
"P. c #3434DA",
"I. c #FBFBE0",
"U. c #F3F3EA",
"Y. c #F4F4E9",
"T. c #F3F3E8",
"R. c #F9F9EC",
"E. c #D2D2CA",
"W. c #0101EA",
"Q. c #0101FF",
"!. c #0101E3",
"~. c #0202FB",
"^. c #2121CF",
"/. c #9B9BBC",
"(. c #9696D1",
"). c #9797CA",
"_. c #9797CB",
"`. c #9898CF",
"'. c #8888B1",
"]. c #EAEADD",
"[. c #0000F8",
"{. c #0000D0",
"}. c #0000F5",
"|. c #0202FE",
" X c #0000F7",
".X c #5C5CCC",
"XX c #D2D2C7",
"oX c #D7D7D9",
"OX c #D4D4D1",
"+X c #1010D0",
"@X c #1212E6",
"#X c #1212E1",
"$X c #1212E2",
"%X c #1111E1",
"&X c #1010CB",
"*X c #1010D1",
"=X c #1515DD",
"-X c #1313BB",
";X c #1313E2",
":X c #1515E4",
">X c #1515E3",
",X c #1515E6",
"<X c #0303DF",
"1X c #595998",
"2X c #E0E0D7",
"3X c #E7E7EA",
"4X c #C8C8C4",
"5X c #D8D8D4",
"6X c #D9D9D5",
"7X c #DDDDD9",
"8X c #C2C2BF",
"9X c #C8C8C5",
"0X c #D8D8D3",
"qX c #DDDDDB",
"wX c #C9C9C5",
"eX c #DCDCD8",
"rX c #DFDFDB",
"tX c #BABAC1",
"yX c #EDEDEE",
"uX c gray93",
"iX c #D0D0D1",
"pX c #D8D8D9",
"aX c #D1D1CF",
"sX c #D6D6D7",
"dX c #D4D4D5",
"fX c white",
/* pixels */
"  . X X X X X X o X X X X X X O + + + + + + + + + + + + + @ #   ",
". $ % & * * * * % % * * * * & % = - - - - - = = - - - - - ; : # ",
"X % > , < 1 2 , 3 4 , 2 1 5 6 7 8 9 0 q 0 w e r 9 0 q 0 w t w y ",
"X * 1 u i u p u a s u i u d u f g h y @ y j ; k h y @ y j - 9 y ",
"X * < u d i p u a 1 u p i l u z x y :   : @ c v y :   : @ b 9 y ",
"X * 1 u i u p u a s u i u d u f n m M #   @ c v y   #   @ b 9 y ",
"X * 5 u d p N u B 1 u p p l u z V y :   : y b C Z :   : y b 9 y ",
"X * 1 u i u p u a s u i u d u f A h m @ y j 0 S h @ @ y j - 9 y ",
"O % D F G H J K L P 2 a a B 1 I U 0 Y = Y q T R 0 Y = Y q E w y ",
"+ = W w q Q ! ~ ^ / 6 1 s 1 ( ) _ w q C q ` t ' w q C q ` ] w y ",
"+ - [ h y @ { } | s u i u d u f g h y @ y j ; k h y @ y j - 9 y ",
"+ - 0 y : M  ...X.1 u p i d u z x y :   o.Z b C Z o.: O.y b 9 y ",
"+ - q @   # M X +.s u i u d u f n m     @.#.; k h y @ + $.b 9 y ",
"+ - 0 y :    ...%.1 u p p l u z &.*.=.-.Q ;.:.t >.;.,.<.  - 9 @ ",
"+ - w j @ @ 1.2.| s u i u d u 3.4.} 5.6.7.Q 8.9.0.0.O.T q.,.` y ",
"+ = t 0 c Y w.e.r.P 2 B B t.1 y.u.i.p.a.s.d.y @.Z @.+ f.g.h.w y ",
"+ = j.` C C Q k.l.z.( s x.s c.P v.( b.( n.m.M.    : y '   Y v @ ",
"+ - 9 h y @ { } N.s u i u p u B x.u B.u V.C.Z.  #   @ A.o.Y 9 y ",
"+ - 0 y :    ...X.1 u p i p u B s u B.u S.D.F.G.G.H.J.K.o.Y 9 y ",
"+ - q @   # M X +.s u i u p u B x.u L.u P.I.U.Y.Y.T.R.E.G.c 9 y ",
"+ - 0 y :    ...%.W.u l d l Q.!.W.Q.~.u ^./.(.)._.).`.'.].; v @ ",
"+ - w j @ @ m 2.| s u i u p u B x.u p u [.{.}.u p p |. X.XXXoXy ",
"+ = e ; c c b OXs.+X@X#X$X%X@X&X*X@X#X%X@X=X-X;X:X>X>X,X<X1X2X3X",
"+ = r k v v C S R 4Xk.5X6X5X7X8X9Xk.5X6X0XqX8XwXeX5X6X0XrXtX9 @ ",
"+ - 9 h y y Z h 0 w yX{ y Z h ; ` uX{ y { h iXpXuX{ y Z h aXsXy ",
"+ - 0 y :   : @ Y q y :   : m c C y :   : m w.dX{ :   : m b 9 y ",
"+ - q @   #   @ = C @   #   @ Y C @   #   @ c v y   #   @ b 9 y ",
"+ - 0 y :   : y Y q y :   : y c C Z :   : y b C Z :   : y b 9 y ",
"+ - w j @ @ y j q ` j @ @ y j 0 k j @ @ y j 0 S h @ @ y #.- 9 y ",
"@ ; t - b b b - E ] - b b b - T <.- b b b - T <.= b b b - E ` y ",
"# : w 9 9 9 9 9 w w 9 9 9 9 9 w w 9 9 9 9 9 w w 9 9 9 9 9 `   # ",
"  # y y y y y y y y y y y y y y y y y y y y y y y y y y @ y #   "
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"16 16 151 2 ",
"   c #E3E3E4",
".  c #CDCDDC",
"X  c #CCCCDC",
"o  c #CCCCDB",
"O  c #CDCDDB",
"+  c #D9D9DA",
"@  c #DADADA",
"#  c gray85",
"$  c gray86",
"%  c #E4E4E4",
"&  c #1717E8",
"*  c #0808F5",
"=  c #0C0CF2",
"-  c #0C0CE2",
";  c #0D0DF2",
":  c #1A1AE6",
">  c #CECED4",
",  c #E0E0DE",
"<  c #DADADB",
"1  c #CDCDCD",
"2  c gainsboro",
"3  c gray87",
"4  c LightGray",
"5  c #0C0CF3",
"6  c blue",
"7  c #0101FE",
"8  c #0000EC",
"9  c #0F0FF1",
"0  c #D8D8DF",
"q  c #ECECEA",
"w  c #E6E6E7",
"e  c #D7D7D7",
"r  c gray91",
"t  c #EAEAEA",
"y  c #0000FE",
"u  c #0101FD",
"i  c #1010F0",
"p  c #D5D5DC",
"a  c #E9E9E7",
"s  c gray83",
"d  c gray90",
"f  c #E7E7E7",
"g  c #D3D3DA",
"h  c #7272D7",
"j  c #6E6EE2",
"k  c #7979DE",
"l  c #3131D5",
"z  c #0000ED",
"x  c #0000EE",
"c  c #0E0EDF",
"v  c #C6C6CD",
"b  c #D9D9D7",
"n  c #C5C5C5",
"m  c gray84",
"M  c gray80",
"N  c #DBDBDA",
"B  c #EBEBDA",
"V  c #F5F5E6",
"C  c #FFFFE1",
"Z  c #6B6BE0",
"A  c #D5D5DD",
"S  c #D8D8D8",
"D  c gray92",
"F  c #DBDBDE",
"G  c #E3E3EB",
"H  c #F4F4E6",
"J  c #6363E2",
"K  c #1010F1",
"L  c #DCDCDE",
"P  c #F1F1EA",
"I  c #CACACA",
"U  c #DDDDDD",
"Y  c #D2D2D2",
"T  c #D9D9DD",
"R  c #EAEAD8",
"E  c #5F5FD6",
"W  c #0000F4",
"Q  c #0000F5",
"!  c #0D0DE5",
"~  c #BEBED4",
"^  c #CBCBDC",
"/  c #C7C7CE",
"(  c #E1E1DF",
")  c gray88",
"_  c gray76",
"`  c #DBDBDF",
"'  c #ECECDA",
"]  c #6060D8",
"[  c #0000F6",
"{  c #0303F6",
"}  c #0000E8",
"|  c #0909EA",
" . c #8B8BDB",
".. c #F3F3E8",
"X. c #E3E3EA",
"o. c #DADADE",
"O. c #D1D1D3",
"+. c #E6E6EB",
"@. c #F8F8E5",
"#. c #6767E2",
"$. c #0707FF",
"%. c #0303F2",
"&. c #0505F4",
"*. c #9595DC",
"=. c #F5F5E3",
"-. c #ECECD7",
";. c #DDDDD5",
":. c #DDDDDE",
">. c #E3E3E7",
",. c #F4F4E2",
"<. c #6363E1",
"1. c #0303FF",
"2. c #0000F2",
"3. c #2323DA",
"4. c #4040E0",
"5. c #3A3AE8",
"6. c #3636E0",
"7. c #A2A2CC",
"8. c #E4E4DD",
"9. c #D5D5D7",
"0. c #DBDBD3",
"q. c #9696CA",
"w. c #6E6EE0",
"e. c #7777E1",
"r. c #6F6FD5",
"t. c #7070D6",
"y. c #7777E3",
"u. c #6B6BDC",
"i. c #5E5ED1",
"p. c #6868E4",
"a. c #6262E6",
"s. c #8383C8",
"d. c #E0E0D9",
"f. c #E4E4E5",
"g. c #DDDDD4",
"h. c #F7F7E4",
"j. c #F8F8E6",
"k. c #EAEAD9",
"l. c #ECECDB",
"z. c #F7F7E3",
"x. c #E8E8D4",
"c. c #F9F9E3",
"v. c #FCFCE5",
"b. c #E6E6DB",
"n. c #DBDBDC",
"m. c #E4E4E8",
"M. c #E6E6EA",
"N. c #D3D3D7",
"B. c #DADADC",
"V. c gray82",
"C. c white",
/* pixels */
"  . X X o X X O + @ @ # @ @ $ % ",
". & * = - ; * : > , < 1 2 3 4 2 ",
"X 5 6 7 8 7 6 9 0 q w e r t 2 2 ",
"X 5 6 y 8 u 6 i p a   s d f @ 2 ",
"g h j k l z x c v b 4 n s m M 2 ",
"N B V C Z 6 6 9 A r w S r D $ 2 ",
"@ F G H J 6 6 K L P $ I # S e U ",
"# Y T R E W Q ! ~ ^ / ( ) Y _ U ",
"@ 4 ` ' ] [ { } | W  ...X.o.O.U ",
"@ 3 +.@.#.6 $.%.&.6 *.C =.-.;.:.",
"@ $ >.,.<.6 1.2.W 6 3.4.5.6.7.8.",
"# 1 9.0.q.w.e.r.t.y.u.i.p.a.s.d.",
"@ 2 r f.g.h.j.k.l.j.z.x.c.v.b.n.",
"@ 3 t f 9.m.M.T ` +.>.N.m.+.B.2 ",
"$ 4 2 @ M @ 2 V.Y 2 # M @ 2 Y U ",
"% 2 2 2 2 2 2 2 2 2 2 2 2 2 U d "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
};
const int n_xpm_icons = 4;
