/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.",
"S.A.S.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.A.S.S.S.",
"S.S.A.D.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.F.G.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.A.m.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.m.B.S.A.S.S.",
"S.A.D.M.i.a.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.a.u.x.k.i.a.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.a.u.G.XX}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|..X(.C.S.S.S.",
"S.Z.J.i.F U I I I I I I I I I I I I I I I I I I I I I I I I U D ;.o.G U I I I I I I I I I I I I I I I I I I I I I I I I U S I.UXLXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.a.U ! Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q ! I <.$.U ! Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q ! P U.UXKXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXKXUXsXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q P ,.#.I W W W W W W W W W W W W W W W W W W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q P ,.#.I W W W W W W W W W W W W W W W W W W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q P ,.#.I W W W W W W W W W W W W W W W W W W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q P ,.#.I W W W W W W W W W W W W W W W W W W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W E W Q W W Q W E W W W W W W W W Q P ,.#.I W W W W W W W W W E W Q W W Q E W W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXUXUXIXPXPXPXPXIXUXIXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W E W E U Y Y U R W E W W W W W W W Q P ,.#.I W W W W W W W W E W T U Y Y U W E W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W E ~ r.w.0.i. .Y W W W W W W W W Q P ,.#.I W W W W W W W W Q U %.i.0.r.9.R W W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXIXUXIX%X$X*X.XhXUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W E W W T ` t.Q W <.;.P Q W W E W W W W Q P ,.#.I W W W W W E W W Q L 6.$.Q ^ u.Q E W W E W W W W W Q K U.UXPXUXUXUXUXIXUXIXIXUXFXoXKXIXeX5XUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W E W E T U ) 8.P L &.&.K R R W E E W W W Q P ,.#.I W W W W E W E R E J 2. .P Y q.E T T E W E W W W W Q K U.UXPXUXUXUXUXUXUXUXIXUXGX&XUXUXsX9XUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W E ~ ` ) X.w.E R ;.1.~ ' / E W W W W W Q P ,.#.I W W W W W E W ( ] ~ 8.+.E ! t.] ` ` Q E W W W W W Q K U.UXPXUXUXUXUXIXUXKXCXAXbX@XIXUXuX8XUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W Q U r.t.8.w.C.V.B.S.a.8.9.h./ R W W W W Q P ,.#.I W W W W W Y } j.8.8.h.A.B.C.N.9.8.p.5.P Q W W W W Q K U.UXPXUXUXUXUXPXUX=XXX;X*XJ.G.L.N.rXUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W Y w.Q P E V.F.A.K.o.K J 9.` T W W W W Q P ,.#.I W W W W W U o.2.H J >.L.Z.H.x.P L ' 8.P Q W W W W Q K U.UXPXUXUXUXUXPXUX*XCXUXIXI.B.D.b.rXUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W Y 0.W L R B.A.V.J.o.J J 7.` T W W W W Q P ,.#.I W W W W W U X.<.H H >.J.V.D.z.L K ` 6.P Q W W W W Q K U.UXPXUXUXUXUXPXUX-XCXUXIXU.A.H.m.rXUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W Q U i.<.&.;.S.K.J.L.8.&.&.g.) T W W W W Q P ,.#.I W W W W W U ..d.$.%.y.I.H.P.M.*.&.7.0.L Q W W W W Q K U.UXPXUXUXUXUXPXUX+X3XuXrXG.b.N.l.rXUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W R  .;.&.1.a.o.o.8.e.$.;.$.W E W W W W Q P ,.#.I W W W W W E ~ &.;.$.i.1.O.@.f.;.=.;.[ T W W W W W Q K U.UXPXUXUXUXUXIXUXbXwXyX9X[.hXkX:X0XUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W E W Y P K ~ 8.K J &.$.D I I E W E W W W Q P ,.#.I W W W W E W E I U D <. .K U q.U P P T W E W W W W Q K U.UXPXUXUXUXUXUXUXUXIXUXGX%XUXUXsX8XUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W E W Q R ' 9.J J &.;.I ! Q W E W W W W Q P ,.#.I W W W W W E W Q ! I 5.| K I e.~ W Q W E W W W W W Q K U.UXPXUXUXUXUXIXUXIXPXUXDX$XUXUXaX7XUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W R / h.9.7.g.$.I Q W W W W W W W Q P ,.#.I W W W W W W W W Q P <.s.7.q.s.E W W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXIXUXLX'.=X:X].eXUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W E / ` ` ) W E W W W W W W W W Q P ,.#.I W W W W W W W W W E Q _ ` ` ^ E W W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXIXIXUXGXVXCXZXPXUXIXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W E E W R T T T E W E W W W W W W W Q P ,.#.I W W W W W W W W E W E T T T R W E W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W E W W W W W W E W W W W W W W W Q P ,.#.I W W W W W W W W W E W W W W W E W W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXUXUXUXIXIXIXIXIXUXIXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q P ,.#.I W W W W W W W W W W W W W W W W W W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q P ,.#.I W W W W W W W W W W W W W W W W W W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q P ,.#.I W W W W W W W W W W W W W W W W W W W W W W W W W Q K U.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.a.U ! Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q ! I <.$.U ! Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q ~ P U.UXKXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXKXUXsXm.D.S.S.",
"S.Z.J.i.H Y U U U U U U U U U U U U U U U U U U U U U U U U Y G :.X.F I P P P P P P P P P P P P P P P P P P P P P P P P I A I.UXLXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.A.G.j.o.$.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.$.X.w.e.;.<.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.<.=.P.gXuXiXiXiXiXiXiXiXiXiXiXiXiXiXiXiXiXiXiXiXiXiXiXiXiXuXfX>XN.D.S.S.",
"S.D.N.'.AXnXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXnXAX7X=.@.$.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.%.p.( ` _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ` ^ -.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXpX^ K U I I I I I I I I I I I I I I I I I I I I I I I I P U q.Y R T T T T T T T T T T T T T T T T T T T T T T T T E L +.J.Z.S.S.",
"S.D.M.|.UXLXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXLXUXiX` R Q W W W W W W W W W W W W W W W W W W W W W W W W W ! e.E Q W W W W W W W W W W W W W W W W W W W W W W W W ! U #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W W W W W W W W W W W W W W W W W W E Q e.R W W W W W W W W W W W W W W W W W W W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W W W W W W W W W W W W W W W W W W E Q e.R W W W W W W W W W W W W W W W W W W W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W W W W W W W W W W W W W W W W W W E Q e.R W W W W W W W W W W W W W W W W W W W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXIXUXIXIXIXIXIXIXUXIXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W W E W W W W W E W W W W W W W W W E Q e.R W W W W W W W W W W W W W W W W E W W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W E W R U U U T W E W W W W W W W W E Q e.R W W W W W W W W E E W Y U U U R W E W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXIXUXIXnXkXkXzXJXUXIXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W W E / X.X.o.] E W W W W W W W W W E Q e.R W W W W W W W W W W E { o.X.X.^ E W W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXIXUXSX).5X7X[.uXUXPXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W Q P 3.u.<.4.f.E W W W W W W W W W E Q e.R W W W W W W W W W E ! h.3.<.a.>.P Q W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXIXUXPXLXUXBX=XUXUXtXeXUXKXPXIXUXIXUXUXUXPXUXiX_ T W W W W W E W Q ! I 4.} J P w.~ W Q W E W W W W W E Q e.R W W W W W W E W Q W ) 0.K H o.,.P Q W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXIXUXCX=XUXUXrXrXUXPXUXUXUXUXUXUXUXPXUXiX_ T W W W W E W E P I S <.| J I q.I L L Y W E W W W W E Q e.R W W W W W E W U L K R 0.K J O.,.P Q W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXIXUXpX,X5X;X_.9X9XoX.X7X1X7XPXUXIXUXUXUXPXUXiX_ T W W W W W R / 3.4.<.f.q.,.<.k.4.3.6.o.Y W W W W W E Q e.R W W W W W W Y @.6.2.6.j.,.>.u.:.P Q W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXPXUX.XaXxXhXS.v.m.x.5XcXvX{.ZXUXIXUXUXUXPXUXiX_ T W W W W W U X.u.} | q.U.J.I.m. . .>.q.L Q W W W W E Q e.R W W W W W Q P t.=. .X.V.P.J.Y.=.I Q W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXPXUX*XFXUXJXJ.D.J.N.dXUXUX-XCXUXIXUXUXUXPXUXiX_ T W W W W W U X.<.J J ,.J.B.S.z.P L ` 6.P Q W W W W E Q e.R W W W W W Q I 8./ P Y n.A.B.H.-.I Q W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXPXUX#XFXUXJXG.N.C.v.dXUXUX%XCXUXIXUXUXUXPXUXiX_ T W W W W W U o.4.P I <.I.S.K.c.Y Y { 9.P Q W W W W E Q e.R W W W W W Q I w.` Y E M.J.D.P.=.I Q W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXPXUX-XXX&X+XL.Q.!.P.].&X$X{.HXUXIXUXUXUXPXUXiX_ T W W W W W T ] f.w.q.k.m.z.c.m.e.q.a.1.I Q W W W W E Q e.R W W W W W Q I 5.p.q.r.M.x.l.C.-.P Q W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXIXUXIXLXUXBX=XUXUXrXeXUXKXIXUXIXUXUXUXUXPXUXiX_ T W W W W E W E E ~ I 4. .P Y e.~ Q W R W E W W W W E Q e.R W W W W W E W R Q W ( q.I P @.,.P Q W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXIXUXIXIXUXCX-XUXUXtXtXUXPXIXIXUXUXUXUXUXPXUXiX_ T W W W W W E W W W L 3. .L Y q.Q E E W E W W W W W E Q e.R W W W W W W E W E R ^ 0.P L +.,.P Q W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXIXIXUXCX XVXCX>XwXUXPXIXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W Q L 6.>.` { a.W E W W W W W W W W E Q e.R W W W W W W W W W R ^ a.] ` 2.1.L Q W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXIXUXLX<X:X,X*XMXUXIXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W W Y o.q.6.9.1.R W W W W W W W W W E Q e.R W W W W W W W W W E W 3.8.6.q.| Y W W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W E W Y L P P I W E W W W W W W W W E Q e.R W W W W W W W W E W E I P P L T W E W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXIXUXIXPXPXPXLXIXUXIXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W W E W Q Q Q Q E W W W W W W W W W E Q e.R W W W W W W W W W E W Q Q Q Q W E W W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W W W W W W W W W W W W W W W W W W E Q e.R W W W W W W W W W W W W W W W W W W W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W W W W W W W W W W W W W W W W W W E Q e.R W W W W W W W W W W W W W W W W W W W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXiX_ T W W W W W W W W W W W W W W W W W W W W W W W W W E Q e.R W W W W W W W W W W W W W W W W W W W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXPXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXPXUXiX_ T W W W W W W W W W W W W W W W W W W W W W W W W W E Q e.R W W W W W W W W W W W W W W W W W W W W W W W W W Q I #.J.Z.S.S.",
"S.D.M.|.UXKXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXKXUXuX' E ! Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q ~ r.W ! Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q ! Y $.J.Z.S.S.",
"S.D.M.|.UXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXpX! H L K K K K K K K K K K K K K K K K K K K K K K K K K P 0.J L K K K K K K K K K K K K K K K K K K K K K K K K P D ..K.Z.S.S.",
"S.A.S.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.P.Y.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.H.Y.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.Y.L.A.S.S.S.",
"S.Z.J.u.A L K K K K K K K K K K K K K K K K K K K K K K K K L D ..NXUXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.H.a.Y ~ Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q ~ T $.nXUXKXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXJX#XIXLXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXKXUXsXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W E W Q Q Q Q W E W W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXIXUXIXPXPXPXPXUXIXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXIXPXPXPXPXIXUXIXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W E W E I I I P T W E W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W E ! 0.0.9.t.} Y W W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXPXUXfX+X;X%X<XUXIXIXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXIXUXIX:X&X-X+XlXUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W E W W T ` u./ ^ 3.;.P Q W W W W W W W Q U #.MXUXPXUXUXUXUXUXIXIXLXUX,XtXGXCX XPXUXIXIXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXIXIXUXGX.XSXGX9X5XUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W E W E R Y _ 8.P L &.*.L E E W E W W W W Q U #.MXUXPXUXUXUXUXUXUXUXPXUX3XlXUXUX%XLXUXIXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXIXUXGX&XUXUXsX9XUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W E W / ! } 0.U U =.>.E ( ! E W W W W W Q U #.MXUXPXUXUXUXUXIXUXKXSXUX,XlXUXUX#XSXGXGXIXUXIXUXUXUXIXUXLX$XUXIXUXUXUXUXIXUXIXGXHXVX$XUXUXaX8XUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W Q U w.u.0.r.B.m.n.C.d.0.q.f.^ R W W W W Q U #.MXUXPXUXUXUXIXUXmX_.*X=X(.H.Y.P.P.&X=X}.3XUXPXUXUXUXIXUXLX$XUXIXUXUXUXUXPXUX:X.X*X$XK.I.T.A.eXUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W Y e.! I W C.G.S.L.O.P L 0.` T W W W W Q U #.MXUXPXUXUXUXIXUXkX1XUXUX6Xc.S.M.W.UXUXbX;XUXPXUXUXUXIXUXLX$XUXIXUXUXUXUXPXUX&XCXUXIXI.N.A.v.rXUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W Y 0.W L E B.A.V.H.o.K J 7.` T W W W W Q U #.MXUXPXUXUXUXIXUXlX4XUXUX6XM.J.Z.Q.UXUXnX,XUXPXUXUXUXIXUXLX$XUXIXUXUXUXUXPXUX-XCXUXIXU.A.J.M.rXUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W Q U i.-.+.%.S.L.J.P.5.+.O.f._ T W W W W Q U #.MXUXPXUXUXUXIXUXlX|.kXhX#Xz.M.c.I.fXgX4X*XUXLXUXUXUXIXUXLX$XUXIXUXUXUXUXPXUX+X9XgXsXH.c.M.k.rXUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W T O.1.:.5.d.&.%.w.y.-.1.-.W E W W W W Q U #.MXUXPXUXUXUXIXUXHX9X7XeX}.,XuXtX_.7X9X5XvXUXIXUXUXUXIXUXLX$XUXIXUXUXUXUXIXUXlX5X0X4X`.uXpX%X0XUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W E W U L J ~ 8.K J &.$.D I P E W E W W W Q U #.MXUXPXUXUXUXUXUXUXUXPXUX2XkXUXUX$XLXUXIXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXIXUXGX%XUXUXsX8XUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W E W Q R ] 8.J H %.;.I ! Q W E W W W W Q U #.MXUXPXUXUXUXIXUXIXPXKXUX1XlXUXUX#XKXPXPXIXUXIXUXUXUXIXUXLX$XUXIXUXUXUXUXIXUXPXLXIXDX%XUXUXsX8XUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W R ( j.6.4.f.%.I Q W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXPXUX4X|.2X;X].UXIXIXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXIXUXKX`.>X2X[.qXUXPXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W E ` } } [ Q E W W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXIXUXJXnXnXbXAXUXIXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXIXIXUXZXbXnXmXKXUXIXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W E W W T Y Y Y E W E W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W E W W W W W W E W W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXIXUXIXIXIXIXIXUXIXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXUXIXIXIXIXIXUXIXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.p.I Q W W W W W W W W W W W W W W W W W W W W W W W W Q U #.MXUXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.Z.J.a.U ! Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q ! Y #.mXUXLXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXKX#XUXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXPXKXUXsXm.D.S.S.",
"S.Z.J.i.G Y I I I I I I I I I I I I I I I I I I I I I I I I Y H o.MXUXPXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXIXUXLX$XUXIXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXPXUXdXm.D.S.S.",
"S.A.G.j.o.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.$.o.5.0XhXsXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXaX[.fXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXsXkX1XN.D.S.S.",
"S.S.A.D.K.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.K.H.M.n.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.C.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.n.N.S.A.S.S.",
"S.A.S.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.S.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.A.S.S.S.",
"S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.",
"S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S."
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"48 48 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.",
"S.A.S.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.S.S.S.S.S.S.S.S.S.S.S.S.S.S.A.S.S.",
"S.S.A.S.F.F.F.F.F.F.F.F.F.F.F.F.D.D.F.F.F.F.F.F.F.F.F.F.F.F.S.C.C.C.C.C.C.C.C.C.C.C.C.C.A.S.A.S.",
"S.A.S.A.n.n.n.n.n.n.n.n.n.n.n.n.m.M.n.n.n.n.n.n.n.n.n.n.n.b.V.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.U.D.A.S.S.",
"S.A.F.n.~ Q ! Q Q Q Q Q Q Q ! W ) O.E ! Q Q Q Q Q Q Q Q ~ L w.UXKXLXLXLXLXLXLXLXLXLXPXJXU.C.S.S.",
"S.A.F.n.Q R E E E E W E E E E R ^ o.Y W E E E E E E E E Q J q.UXPXIXUXUXIXIXIXUXUXIXUXLXY.C.S.S.",
"S.A.F.n.! E W W W R Y R W W W R / o.T W W W W T T W W W ! K w.UXPXIXIXIXIXUXIXIXIXIXUXLXY.C.S.S.",
"S.A.F.n.Q E W W E (  .( E W W R / o.T W W W Q { { Q W W ! J w.UXPXIXIXUXSXcXFXUXIXIXUXLXY.C.S.S.",
"S.A.F.n.Q E W E I o.| O.I E W R / o.T W W U ( o.o.( U W ! J w.UXPXIXIXUXgXbXgXUXIXIXUXLXY.C.S.S.",
"S.A.F.n.Q E R ( o.1.2.2.O.) R R / o.T W E | &.4.4.&.| E ! J w.UXPXUXSXhX5X2XpXUXPXIXUXLXY.C.S.S.",
"S.A.F.n.Q W Y  .| 2.`.7.{ X.Y E / o.T W W &.` J.J.` &.W ! J w.UXLXUXlXmX>X9.5XUXPXIXUXLXY.C.S.S.",
"S.A.F.n.Q E R ( O.2.7.3.+._ R R / o.T W E ..&.7.7.&...E ! J w.UXPXUXAXhX3X;XiXUXPXIXUXLXY.C.S.S.",
"S.A.F.n.Q E W E I O.{ +.U E W R / o.T W W U ) X.X.) U W ! J w.UXPXIXIXUXgXmXgXUXIXIXUXLXY.C.S.S.",
"S.A.F.n.Q E W W E ) X._ E W W R / o.T W W W Q | | Q W W ! J w.UXPXIXIXUXAXlXSXUXIXIXUXLXY.C.S.S.",
"S.A.F.n.! E W W W R Y R W W W R / o.T W W W E T T E W W ! K w.UXPXIXIXIXIXUXIXIXIXIXUXLXY.C.S.S.",
"S.A.F.n.~ W Q Q Q Q ! Q Q Q Q W ) X.U E R R R E E R R R W H q.UXLXPXPXPXPXLXPXPXPXPXIXKXY.C.S.S.",
"S.A.F.b.I K L L L L L L L L L K T +.~ / / / / / / / / / ) Y t.UXPXIXUXUXUXUXUXUXUXIXUXLXY.C.S.S.",
"S.S.Z.J.,X<X<X<X<X<X<X<X<X<X<X,X4Xy.{ O.o.o.o.o.o.o.o.o.O. .4.y.q.w.w.w.w.w.w.w.w.w.q.w.V.S.A.S.",
"S.S.C.Y.LXUXIXUXUXUXUXUXUXUXIXPXUX0.F E T T T T T T T T T I  .Y H K J J J J J J J K J L b.F.A.S.",
"S.S.C.U.JXPXLXLXLXLXLXLXLXLXLXKXUXw.K ! W W W W W W W W Q T O.) W ! ! ! ! ! ! ! ! ! Q ~ n.F.A.S.",
"S.S.C.Y.LXUXIXIXIXIXPXIXIXIXIXPXUXw.J ! E W E E E E W E W T o./ R W W W E W R W E W E Q n.F.A.S.",
"S.S.C.Y.LXUXIXIXUXxXiXzXUXIXIXPXUXw.J ! W T ! $.$.! T W W T o./ R W W U ..&. .T W W E Q n.F.A.S.",
"S.S.C.Y.LXUXIXPXDXuXCXuXSXPXUXPXUXw.J ! E ! X.....X.! E W T o./ R E Q ) &.' +.T W W E Q n.F.A.S.",
"S.S.C.Y.LXUXUXmXjX2Xm.:XkXbXUXPXUXw.J ! E $...M.M...$.E W T o./ E T | X.7.K.>.I Q W E Q n.F.A.S.",
"S.S.C.Y.LXUXUXmXjX2Xm.:XkXbXUXPXUXw.J ! E $...M.M...$.E W T o./ E T | X.7.K.>.I Q W E Q n.F.A.S.",
"S.S.C.Y.LXUXIXPXDXuXCXuXSXPXUXPXUXw.J ! E ! X.....X.! E W T o./ R E Q ) &.' +.T W W E Q n.F.A.S.",
"S.S.C.Y.LXUXIXIXUXxXiXzXUXIXIXPXUXw.J ! W T ! $.$.! T W W T o./ R W W U ..&. .T W W E Q n.F.A.S.",
"S.S.C.Y.LXUXIXIXIXIXPXIXIXIXIXPXUXw.J ! E W E E E E W E W T o./ R W W W E W R W E W E Q n.F.A.S.",
"S.S.C.U.JXPXLXLXLXLXLXLXLXLXLXKXUXe.P ^ ! ! ! ! ! ! ! ! ! E +.) W ! ! ! ! ! ! ! ! ! Q ~ n.F.A.S.",
"S.S.C.Y.LXUXIXUXUXUXUXUXUXUXIXPXUX6.V P J J J J J J J J K F [ T H K J J J J J J J K J L b.F.A.S.",
"S.S.Z.J.,X<X<X<X<X<X<X<X<X<X<X<X2Xc.8.e.w.w.w.w.w.w.w.w.w.q.a.r.q.w.w.w.w.w.w.w.w.w.q.w.V.S.A.S.",
"S.A.F.b.I K L L L L L L L L L I S ,XUXLXUXUXUXUXUXUXUXUXIXUXkXFXUXIXUXUXUXUXUXUXUXIXUXLXY.C.S.S.",
"S.A.F.n.~ W Q Q Q Q ! Q Q Q Q ~ I <XUXKXPXPXPXPXPXPXPXPXPXUXjXDXUXPXPXPXPXLXPXPXPXPXIXKXY.C.S.S.",
"S.A.F.n.! E W W W R Y R W W W Q L <XUXLXIXIXIXIXIXIXIXIXPXUXjXFXUXIXIXIXIXUXIXIXIXIXUXLXY.C.S.S.",
"S.A.F.n.Q E W W E ) X._ E W W Q L <XUXLXIXIXPXbXbXPXIXIXIXUXkXFXUXIXIXUXAXlXSXUXIXIXUXLXY.C.S.S.",
"S.A.F.n.Q E W E I O.{ +.U E W Q L <XUXLXIXUXZXkXkXZXUXIXIXUXkXFXUXIXIXUXgXmXgXUXIXIXUXLXY.C.S.S.",
"S.A.F.n.Q E R ( O.2.7.3.+._ R Q L <XUXLXUXxXuX:X:XuXxXUXPXUXkXFXUXUXAXhX3X;XiXUXPXIXUXLXY.C.S.S.",
"S.A.F.n.Q W Y  .| 2.`.7.{ X.Y ! L <XUXLXIXuXCXm.m.CXuXIXIXUXkXFXUXUXlXmX>X9.5XUXPXIXUXLXY.C.S.S.",
"S.A.F.n.Q E R ( o.1.2.2.O.) R Q L <XUXLXUXvXuX2X2XuXvXUXPXUXkXFXUXUXSXhX5X2XpXUXPXIXUXLXY.C.S.S.",
"S.A.F.n.Q E W E I o.| O.I E W Q L <XUXLXIXUXZXjXjXZXUXIXIXUXkXFXUXIXIXUXgXbXgXUXIXIXUXLXY.C.S.S.",
"S.A.F.n.Q E W W E (  .( E W W Q L <XUXLXIXIXPXmXmXPXIXIXIXUXkXFXUXIXIXUXSXcXFXUXIXIXUXLXY.C.S.S.",
"S.A.F.n.! E W W W R Y R W W W Q L <XUXLXIXIXIXIXIXIXIXIXPXUXjXFXUXIXIXIXIXUXIXIXIXIXUXLXY.C.S.S.",
"S.A.F.n.Q R E E E E W E E E E W K <XUXLXUXUXIXIXIXIXUXUXIXUXkXFXUXIXUXUXIXIXIXUXUXIXUXLXY.C.S.S.",
"S.A.F.n.~ Q ! Q Q Q Q Q Q Q ! ~ I ,XUXJXLXLXLXLXLXLXLXLXKXUXhXSXIXLXLXLXLXLXLXLXLXLXPXJXU.C.S.S.",
"S.A.S.A.n.n.n.n.n.n.n.n.n.n.n.n.b.J.T.U.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.P.U.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.U.D.A.S.S.",
"S.S.A.S.F.F.F.F.F.F.F.F.F.F.F.F.F.Z.V.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.A.S.A.S.",
"S.A.S.A.A.A.A.A.A.A.A.A.A.A.A.A.A.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.A.S.S.",
"S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S."
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"32 32 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"A.S.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.F.S.C.C.C.C.C.C.C.C.C.A.S.",
"S.A.M.M.M.M.M.M.M.M.M.N.M.M.M.M.M.M.M.m.C.I.P.P.P.P.P.P.I.P.S.A.",
"D.M.( ! ~ ~ ~ ~ ~ ! (  .Q ~ ~ ~ ~ ~ / P u.UXHXJXJXJXJXJXLXDXP.C.",
"D.M.! R E R Y R E R ! { T E E T T E Q H y.UXPXIXUXUXUXIXUXJXP.C.",
"D.M.~ E E Q { ~ R E ~ } R W T ` ` T ! J y.UXLXUXHXmXKXUXUXJXP.C.",
"D.M.~ R Q  .=.o.! E ~ { R W ) %.%.) ! J y.UXPXLXkXtXZXUXUXJXP.C.",
"D.M.~ Y { =.D.<.| T ~ } T ^ o.j.j.o.( H y.UXUXvX6XC.VXUXUXJXP.C.",
"D.M.~ R ~ o.<.@.^ R ~ { R W ' ;.;.' ! H y.UXPXHXdX6XCXUXUXJXP.C.",
"D.M.~ E R ! | ^ T E ~ } R W T ] ] T ! J y.UXLXUXFXvXHXUXUXJXP.C.",
"D.M.^ W ! Q W Q ! W / { T E E T T E Q H t.UXKXLXPXIXPXLXIXHXP.C.",
"F.m.I H K K K K K J P } ! ~ ~ ~ ~ ~ / P i.UXPXIXUXUXUXIXUXJXP.C.",
"Z.H.-X>X:X:X:X:X:X;X3Xe.) | { } } { } ' >.a.t.y.y.y.y.y.y.u.C.S.",
"C.P.JXUXIXUXUXUXIXPXUXt.G W R T T R R Y ' P H J H H J J G P m.F.",
"C.P.GXPXLXLXDXKXLXJXUXy.J ! E ~ ~ E Q R } / Q ! ! ( ! ! Q / M.D.",
"C.P.JXUXUXAXkXBXUXLXUXy.J Q W  . .W E R { ~ E T ' X.( R E ~ M.D.",
"C.P.JXUXCXiX(.qXNXIXUXy.H /  .r.r. .~ T } ~ T ] ;.k.` T E ~ M.D.",
"C.P.JXUXCXiX(.qXNXIXUXy.H /  .r.r. .~ T } ~ T ] ;.k.` T E ~ M.D.",
"C.P.JXUXUXAXkXBXUXLXUXy.J Q W  . .W E R { ~ E T ' X.( R E ~ M.D.",
"C.P.GXPXLXLXDXKXLXJXUXu.L ^ Q / / Q ! W | / Q ! ! ( ! ! Q / M.D.",
"C.P.JXUXIXUXUXUXIXPXUX0.N L J H H J J F / P H J H H J J G P m.F.",
"Z.H.-X>X:X:X:X:X:X:X<XM.w.u.y.y.y.y.y.y.s.u.y.y.y.y.y.y.y.u.C.S.",
"F.m.I H K K K K K P V -XUXLXUXUXUXUXIXUXnXJXUXIXUXUXUXIXUXJXP.C.",
"D.M.^ W ! Q W Q ! ~ P :XUXKXLXPXPXLXLXUXbXGXIXLXPXIXPXLXIXHXP.C.",
"D.M.~ E R ! | ^ T ! K :XUXLXUXNXNXUXIXUXnXJXUXUXFXvXHXUXUXJXP.C.",
"D.M.~ R ~ o.<.@.^ Q K :XUXKXBXqXqXBXPXUXnXJXUXHXdX6XCXUXUXJXP.C.",
"D.M.~ Y { =.D.<.| W K :XUXDXkX(.(.kXGXUXnXHXUXvX6XC.VXUXUXJXP.C.",
"D.M.~ R Q  .=.o.! Q K :XUXLXAXiXiXAXIXUXnXJXUXLXkXtXZXUXUXJXP.C.",
"D.M.~ E E Q { ~ R ! K :XUXLXUXVXVXUXPXUXnXJXUXUXHXmXKXUXUXJXP.C.",
"D.M.! R E R Y R E W J :XUXLXUXUXUXUXIXUXnXJXUXIXUXUXUXIXUXJXP.C.",
"D.M.( ! ~ ~ ~ ~ ~ ^ I -XUXGXJXJXJXJXJXPXcXDXKXJXJXJXJXJXLXDXP.C.",
"S.A.M.M.M.M.M.M.M.M.m.H.I.P.P.P.P.P.P.I.L.P.I.P.P.P.P.P.I.P.S.A.",
"A.S.D.D.D.D.D.D.D.D.F.Z.C.C.C.C.C.C.C.C.Z.C.C.C.C.C.C.C.C.C.A.S."
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"16 16 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"A.M.M.M.M.N.M.M.N.m.G.I.L.P.P.S.",
"M.' ~ ~ ^ [ ( ~ ( U oXUXFXJXBXP.",
"M.~ ^ ..R / R [ | S +XUXkXKXGXP.",
"N.( O.0./ _ W >.<.F +XUX*XVXFXL.",
"m.I F L D W W W ~ F +XUXJXUXFXP.",
"Z.z.l.k.v.w.^ ) _ Q S.=X+X@XoXG.",
"P.FXUXKXUX@XH ! E ! Q D F D U m.",
"P.FXbX5XUX+XD &.#.E _ ^ <._ ( M.",
"P.FXbX5XUX+XH -.&.! ` ^ <._ ( M.",
"P.FXUXKXUXXXn H D H T F F D U m.",
"Z.z.l.l.h.G.$X+X@X+XXX@X@X@XoXG.",
"m.I F I b d.UXKXIXPXSXUXLXUXFXP.",
"N.( O.e.I l.UX5X8XLXZXGX-XVXFXL.",
"M.~ ^ O.F k.UXbXMXUXSXUXzXKXGXP.",
"M.' ~ ( I z.UXFXJXDXMXGXHXJXBXP.",
"A.M.M.N.m.Z.I.P.P.P.L.P.P.P.P.S."
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
};
const int n_xpm_icons = 4;
