/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 201 2 ",
"   c #55523B",
".  c #68573E",
"X  c #5E5B44",
"o  c #6B5543",
"O  c #655E44",
"+  c #6C5C45",
"@  c #745746",
"#  c #745B46",
"$  c #795E44",
"%  c #735E49",
"&  c #7C5D4A",
"*  c #5D6646",
"=  c #5F704B",
"-  c #646346",
";  c #626748",
":  c #6A6549",
">  c #646B4A",
",  c #696B4B",
"<  c #6D6F47",
"1  c #786047",
"2  c #75624B",
"3  c #7A644C",
"4  c #716F4E",
"5  c #7E684D",
"6  c #796747",
"7  c #65724D",
"8  c #69734E",
"9  c #737A4D",
"0  c #7C7F4F",
"q  c #73704F",
"w  c #756453",
"e  c #7A6550",
"r  c #7D6852",
"t  c #7E6C5A",
"y  c #657553",
"u  c #697650",
"i  c #657A52",
"p  c #6A7B53",
"a  c #6D7E5B",
"s  c #757150",
"d  c #787F50",
"f  c #727E52",
"g  c #6B665A",
"h  c #766C62",
"j  c #815F4B",
"k  c #82644C",
"l  c #8A634E",
"z  c #83684D",
"x  c #8C694E",
"c  c #826945",
"v  c #916F4F",
"b  c #837147",
"n  c #867448",
"m  c #8C734A",
"M  c #827D4B",
"N  c #8C7A4B",
"B  c #92744E",
"V  c #947A4E",
"C  c #836651",
"Z  c #8C6652",
"A  c #846A53",
"S  c #8B6D55",
"D  c #8C6E5A",
"F  c #816B5F",
"G  c #936C53",
"H  c #996D57",
"J  c #906D5C",
"K  c #9C6E58",
"L  c #877057",
"P  c #8A7156",
"I  c #8C7359",
"U  c #947350",
"Y  c #997C50",
"T  c #90765B",
"R  c #9A715B",
"E  c #93785D",
"W  c #997155",
"Q  c #A37057",
"!  c #A3735D",
"~  c #A8755F",
"^  c #B27B5E",
"/  c #82776C",
"(  c #84796E",
")  c #897C6E",
"_  c #947260",
"`  c #877D74",
"'  c #967E72",
"]  c #A77560",
"[  c #A97661",
"{  c #AE7B63",
"}  c #B27F65",
"|  c #B67E69",
" . c #B57A64",
".. c #6B8156",
"X. c #6E8459",
"o. c #6F895B",
"O. c #7B8150",
"+. c #718B57",
"@. c #70845B",
"#. c #728C5D",
"$. c #728254",
"%. c #74905F",
"&. c #748761",
"*. c #769261",
"=. c #7E9765",
"-. c #7F9865",
";. c #7E9B68",
":. c #8C854F",
">. c #9A854E",
",. c #94804B",
"<. c #8B8551",
"1. c #818351",
"2. c #958555",
"3. c #9B8B51",
"4. c #9F9155",
"5. c #A18B4B",
"6. c #A38D53",
"7. c #A18F59",
"8. c #A49154",
"9. c #AA9255",
"0. c #AF9957",
"q. c #A3915A",
"w. c #AD995B",
"e. c #AB975A",
"r. c #B39D55",
"t. c #B29C5A",
"y. c #BAA156",
"u. c #B7A15B",
"i. c #BCA45C",
"p. c #BFA95E",
"a. c #809765",
"s. c #809966",
"d. c #829E69",
"f. c #8C837A",
"g. c #9C8275",
"h. c #9F967C",
"j. c #B38066",
"k. c #B88267",
"l. c #B68268",
"z. c #BA8469",
"x. c #AA9965",
"c. c #A39A7E",
"v. c #A18779",
"b. c #85A16A",
"n. c #C1A757",
"m. c #C1A75B",
"M. c #C1AA5F",
"N. c #C1876C",
"B. c #C3AC61",
"V. c #CBAF62",
"C. c #C7B162",
"Z. c #CCB366",
"A. c #CFB668",
"S. c #D1B666",
"D. c #D2B867",
"F. c #D0B768",
"G. c #D3B969",
"H. c #D9BE6B",
"J. c #8A8783",
"K. c #978F87",
"L. c #958F89",
"P. c #97918C",
"I. c #9B938C",
"U. c #9B9590",
"Y. c #9F9A96",
"T. c #9B9B9B",
"R. c #A19D96",
"E. c #9EA29A",
"W. c #A6A29F",
"Q. c #AAA6A2",
"!. c #ACABA6",
"~. c #ACACAC",
"^. c #A4A9A0",
"/. c #B3ACA9",
"(. c #B9B6AE",
"). c #B4B4B4",
"_. c #BBBBBB",
"`. c #BFBCB3",
"'. c #C3C3C3",
"]. c #C6C7C8",
"[. c #C7C8C9",
"{. c #CCCCCD",
"}. c #D4D4D4",
"|. c #D6D7D9",
" X c #D7D9DA",
".X c #DDDDDD",
"XX c #DCDEE2",
"oX c #DFE0E2",
"OX c #E5E5E5",
"+X c #E8E8E7",
"@X c #E1E3E9",
"#X c #E6E8EA",
"$X c #ECECEB",
"%X c #E8E7E6",
"&X c #F0F0EF",
"*X c #EEEFF1",
"=X c #EFF0F1",
"-X c #F1F1F2",
";X c #F6F7F9",
":X c #F7F8F9",
">X c #F8FBFE",
/* pixels */
"OXOXOXOX%X%X%XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX%XOXOXOX%X%X%XOXOXOX%X@XOXOXOXOXOX%XOXOXOXOX%XOXOXOX%XOXOX%XOXOXOX%XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX%XOXOX%XOXOXOXOXOXOXOXOXOXOXOX%X%XOXOX@XOXOX%X",
"OXOX+XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX%XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX@XOXOXOXOXOXoXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX%XOXOXOXOXOX%X",
"OXOXOXOX$X$X$X+X#X$X$X$X$X$X+X$X$X$X$X$X+X$X$X$X$X$X+X$X$X$X$X+X+X$X$X$X$X$X+X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X%X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X+X$X$X$X$X$X$X#X$X$X$X$X$XOXOXOXOX",
"%XOXOXOX{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.[.{.{.{.{.[.{.{.{.{.[.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.OXOXOXOX",
"%XOX$X{.y &.@.@.@.@.@.@.@.@.@.@.+.X.@.#.@.@.@.@.@.@.@.@.@.o.O 3 e e e e e e e e e r 2 h '.'.'.'.'.'.'.'.'.'.'.{.U.x _ R Z N t.w.w.w.w.w.w.w.e.x.w.w.w.w.w.w.w.w.w.e.e.e.w.w.w.w.w.w.t.2.{.#XOXOX",
"OXOX$X{.#.b.d.d.d.s.s.d.d.d.s.d.s.b.s.s.s.s.b.s.d.d.s.d.s.d.: T I I I I E I E I I I P ` =X$X$X$X$X$X$X$X$X$X$X:X(.~ z.z.~ 9.H.A.G.S.G.S.D.D.D.F.D.D.G.G.S.S.G.G.G.G.G.G.D.D.D.D.G.A.G.t.{.$XOXOX",
"OXOX+X{.X.d.=.a.s.-.=.s.=.=.a.-.=.=.=.=.-.s.s.=.a.s.a.-.a.-.: D I I L I I I I I I I A ) #XOXOXOXOXOXOXOXOXOXoX$X/.Q l.l.] 6.G.C.Z.Z.Z.Z.V.Z.Z.Z.V.Z.Z.Z.C.Z.Z.Z.C.C.Z.Z.Z.Z.V.Z.Z.Z.G.w.{.$XOXOX",
"OXOX$X{.@.d.=.a.s.s.s.s.s.s.s.s.s.s.s.=.=.b.;.-.-.;.-.-.-.;.> I I I I I I I I S I I S ) #XOXOXOX%XOXOXOXOXOXOX$X/.Q l.| ! 6.G.C.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.V.D.w.{.$XOXOX",
"OXOX$X{.a d.a.s.s.-.-.s.s.s.s.s.-.s.-.s.-.> : : : : : : : - 2 I I I I I I I I I I E 5 f.*XOXOXOXOX%XOX%XOXOXOX=X/.Q l.l.! 6.G.C.Z.Z.Z.Z.A.Z.Z.Z.Z.A.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.S.w.{.$XOXOX",
"OXOX$X{.@.d.=.s.s.s.s.s.s.=.s.=.s.-.s.-.; A T P L I L I I I I L I I I I I I I L I z h OX%XOXOXOXOXOXOXOXOXOXOX=X/.Q l.l.! 6.G.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.A.Z.Z.Z.Z.F.w.{.$XOXOX",
"%XOX$X{.@.s.a.s.-.s.s.s.s.s.=.s.-.s.-.; A E L I I I I I I I I I I I I I I I I E A h %X$X@X%XOX%X%XOX%XOXOXOXOX$X/.Q k.l.] 6.G.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.G.w.{.$XOXOX",
"OXOX$X{.#.d.s.d.s.s.-.s.a.s.s.-.-.=.; A I L I I I I I I I I I I I I I L I I I 5 ( OX#XOXOXOXOX#XOXOX%X%XOXOXOX=X/.Q k.l.! 6.G.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.V.G.w.{.#XOXOX",
"OXOX#X{.y &.&.&.X.s.a.=.s.s.=.a.-.> C I I I I I I I I I I I I I I I I I L E z ( OX+XOXOXOXOXOXOX#XOX%XOXOXOXOX-XQ.Q l.l.! 3.H.V.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.G.e.{.$XOXOX",
"OXOX$X{.)..X}. X_.a s.d.=.s.=.d.*.% E D I L I I I I I I I I I I I I I I E 5 ( OX+XOX%XOXOXOX%XOX%XOXOXOXOXOX$X].E j.j.j.| Z t.G.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.G.w.{.$XOXOX",
"OXOX$X{.'.&X#X%X-X'.a s.s.a.=.d.*.: I I I I I I I I I L I I P P L I L E z ( OX%XOXOXOX%XOXOXOXOXOX%XOXOXOX$X].I  .l.} } } l.x t.G.V.V.V.Z.Z.Z.Z.Z.Z.Z.Z.C.Z.Z.Z.Z.Z.A.Z.Z.Z.A.Z.Z.C.G.e.{.$XOXOX",
"OXOX$X{.'.$XOXOXOX&X'.a a.d.d.d.=.4 _ I I I E I E I I E E I T T T E T z h #X#XOXOXOXOX%X%XOX%XOXOXOXOXOX-X].J  .j.} j.j.} } | x t.G.Z.A.A.A.Z.A.Z.A.Z.F.Z.G.Z.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.G.e.{.$XOXOX",
"OXOX$X{.'.$XOXOXOXoX-X'.a +.+.+.... z 6 5 5 1 k 3 5 3 3 1 k z 5 1 5 1 ( oX%XOXOXOXOX%XOXOX%X%XOX#XOXOX#X].D  .j.j.j.{ j.j.j.j.j.x 0.M.M.M.M.M.p.M.B.B.p.p.p.B.G.Z.C.Z.Z.Z.Z.A.Z.A.C.G.w.{.$XOXOX",
"OXOX$X[.'.$XOXOXOXOXOX&X{.W.!.!.E.J.!.W.Q.Q.Q.W.Q.Q.Q.Q.Q.W.J.Q.Q.Q.Q.oX$XOXOXOXOX%XOXOXOXOXOX%X%XOX%X#X' ^ l.j.j.j.j.j.j.j. .j.} T U G G U G H U U G G U G x 8.G.Z.Z.Z.Z.Z.Z.Z.Z.C.S.w.{.+XOXOX",
"OXOX$X{.'.$XOXOX%XOXOXOX$X&X&X-XoX'.;X&X-X-X-X-X=X=X=X=X-X$X_.-X-X-X=X%XOXOXOXOXOX#XOXOX#XOX#XOXOXOXOX#Xg. .} j.j.j.j.j.j.j.j.j.j.l.l.l.k.k.k.l.l.l.l.l.l.l.z.G 8.G.Z.Z.Z.Z.Z.Z.Z.Z.G.w.{.$XOXOX",
"%XOX$X{.'.$XOXOXOXOXOXOXOXOXoXOX}._.+XoXOXoXOXOXOXOXOXoXOXoX).%X.XOXoXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX#Xg.{ l.} j.j.j.j.j.j.j.j.j.{ j.j.} } } } } } } j.j.| { k.G 6.G.Z.Z.Z.Z.Z.Z.Z.G.w.{.$XOXOX",
"%XOX$X[.'.$XOXOXOXOXOXoX$X%X$X$X.X_.$XOXOXOX%XOX%XOXOXOXOXOX).$X%X$X+X$X$X$X$X$X#X$X+X$X%XOXOXOXOXOX%X#Xg.} | j.{ j.j.j.j.j.j.j.j.{ j.j.j.j.j.j.j.j.j.j.j.j.} } k.G 6.G.Z.Z.Z.Z.Z.Z.G.e.{.$X@XOX",
"%XOX$X{.'.$XOXOXOXOXOX&X'.).)._.~._.$XOXOXOX%XOXOXOX%XOXOXOX~.).).).).).).).~.~.).).)._.%XOXOXOXOXOX+XoXF } l.} j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.} j.j.j.j.j.j.} | l.H 8.G.C.Z.Z.Z.Z.G.w.{.$XOXOX",
"OXOX$X{.'.$XOXOXOXOX&X_._.oX.XoX.XOXOXOX%XOXOX%X%X%XOXOXOXOXOXXXoX.XOX.X.XOX{._.OX.XOX~.oX%XOXOXOX#X%Xf.# k l.} j.j.j.j.{ j.j.j.j.j.j.j.j.j.j.j.l.j.j.} } j.j.j.} } k.G 6.G.Z.Z.Z.C.G.e.{.$XOXOX",
"OXOX$X[.'.$XOXOXoX&X_._.&X%XOX#X%XOXOX%XOX%XOXOX%XOXOXOXOXOX%X%X%X#X%XOX%X+X|._.$XOX+X)..XOXOXOX%X#Xf.3 E 5 & k.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.} j.j.j.j.j.j.j.l.} } l.G 6.G.Z.Z.V.S.w.{.+XOXOX",
"%XOX$X{.'.$XOXOX$X_._.$XOXOXOXOXOXOXOXOXOXOXOXOXOXOX%XOXOXOXOXOXOXOXOX$X$X-X.X_.$XOX+X).+X$X$X&X$X` 5 I S T 5 j j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.} l.} } l.G 6.G.G.A.H.t.{.$XOXOX",
"OXOX$X[.'.$XOX%X'.`.&XOXOXOXOXOXOXOXOX#X%XOX#X%X%XOXOXOXOXOXOXOXOX$X.X].[.{._.).$XoX$X~.'.{.[.{.f.3 E I I I T e 3 j.j.{ j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.} j.} j.k.G 6.u.t.t.3.{.$XOX%X",
"OXOX$X{.'.$XOXOX~.$XOXOXOX%X%XOX%XOXOXOXOXOXOX%XOXOX#X%XOXOXOXOX$X}.~.].'.[.).).$XOX=XL.+ e e 3 A I I I I I T e & l.j.j.j.j.j.j.j.j.j.j.j.j.j.j.{ j.j.j.j.j.j.j.j.j.j.j.} } z.@ 2 3 3 + {.$XOX%X",
"%XOX$X{.'.+XOXOX).OXOXOX%XOXOXOXOX%XOX%X%X#XOXOXOX%XOXOXOXOXOX$X}.!.OX$X$X-X.X_.+XOX=XI.x E I T I I I I I I 5 $ l. .j.j.j.j.j.j.j.j.j.j.j.{ j.j.j.j.j.j.j.j.j.j.} } } } l.} | 3 I E T r {.$XOXOX",
"OXOX$X{.'.$XOXoX).#XOXOXOX%XOX#X%XOX#XOXOX%X%XOX%XOX%XOXOXOX#X}.~.OX%XOX%X%X}._.$XOX&XI.5 I I I I I I I T r & l.j.^ j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.} l. .j.j.j.j.j.} } l.& L I I e {.$XOXOX",
"OXOX$X{.'.$XOXOX).#XOX%X%XOXOX%X#XOXOXOXOX%XOXOX%XOXOXOX%X#X}.~.OX%XOXOXOX$X}._.$XoX=XI.A I I I I I I I 5 & } l.j.j.j.j.j.j.j.{ j.j.j.j.j.j.j.j.j.j.j.j.} } j. .{  . .l.} } | 3 L I I e {.+XOXOX",
"%XOX$X[.'.$X%XOX).OXOXOXOXOXOXOXOX%XOX%XOXOXOX%XOX%XOXOXOX%X~.OXOXOXOXOXOX$X}._.$XOX=XQ.$ T I I I I I I . { l.{ j.j.j.j.j.j.j.j.j.j.j.{ j.j.j.j.j.j.j.j.} z.T : 9 s : W l.{ z.& L I E e {.$XOXOX",
"OXOX$X{.'.$XOXOX).OXOXOXOX#XOX%XOXOX%XOXOX%X#XOX#XOXOXOX%XoX_.#XOXOXOXOXOX+X}._.$XOXOX+XP.3 I S I I I I A # j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.} z.z *.;.d.%.S z. .l.j I I I e {.$XOXOX",
"OXOX$X{.'.$XOXOX).#XOX%XOXOX#XOX%XOX%XOXOXOX#XOXOXOXOXOXOXoX).%XOXOXOXOXOX+X|._.$XOXOX%X*XP.1 E L I I L I A # } l.{ j.j.{ j.j.j. .j.j.j.{ j.j.j.j.j.j.j.} z.Z %.s.s.#.S z.{ l.& L I T e {.$XOXOX",
"OXOX$X[.'.+XOXOX).OXOXOX%XOX%XOXOX#XOXOX%XOX%XOXOX%XOXOXOXOX).%XOXOXOXOXOX+X|._.$XOXOXOXOX*XP.& T I I I I I A # } z.z.z.z.z.l.l.z.z.z.z.z.l.j. .j.j.j.j.} k.S %.s.d.#.G N.l.z.k L I T 3 {.$XOXOX",
"OXOX$X{.'.$XOXoX).%XOXOXOXOXOX%XOXOXOX%XOXOXOX%X%XOXOXOXOXOX).#XOXOXOXOX%X$X}.~.-XoXOXOXOXOX*XP.A I I I I L I A & Z Z Z Z Z S S S S S G S x { l.j.j.j.j.} z.z *.d.s.#.& G S Z # L I I e {.$XOXOX",
"OXOX$X{.'.$XOXOX).OXOXOX%X#XOXOXOX%XOXOX%X#XOX%X%XOXOXOX%XoX).%XOXOXOXOX%X%Xc.3.'.*XOXOXOXOX$X{.3 T L I I I I I L r A A 2 = *.+.#.%.#.+.%.i W z.j.j.j.{ z.G p s.a.a.s.*.#.+.#.; L I E e {.$XOXOX",
"%XOX$X{.'.$XOXOX).%X@XOXOX%XOX%XOXOXOXOXOXOX#XOXOX%X%XOXOXoX).%XOX%XOX#X@Xh.i.G.7.'.&XOXOXOX$X].3 I I I I I I I I T I E A p b.s.d.s.d.s.d.@.K k.j.{ | z.G u d.s.=.s.=.d.d.d.d., D I I e {.$XOXOX",
"%XOX+X{.'.$XOXOX).OXOX%XOX%X#XOX#X%XOX%XOX%X%XOXOX%X%XOXOXOX).%XOX%X%X@Xh.m.G.Z.S.q.'.&XOX%X&X[.5 E I I I I I I L P I T z p d.=.=.=.s.s.d.X.! k.j.j.z.G y b.s.=.s.s.a.=.-.-.-.> S I I e {.+XOXOX",
"OXOX$X{.'.$XOXoX).%XOXOXOXOXOXOXOX%XOX%XOXOXOX%XOXOXOXOXOXOX).#XOXOXoXc.m.G.C.Z.Z.S.7.'.XX|.oX_.# A A A A I I I I I I I A p d.a.;.=.%.#.=.i G { ! ~ U u b.s.=.-.s.s.s.-.s.=.d., I I T e {.$XOXOX",
"OXOX$X{.'.*XOXOX).OXOX%XOX%XOX%XOXOX#XOXOX%XOXOXOXOXOXOX&X'._.$XOX$X(.r.G.C.Z.Z.Z.V.Z.w.x.x.x.2.* p u 7 O E I I I I P T + @.d.=.s.> + 2 2 : # 3 2 # * b.=.-.s.s.s.s.s.a.s.=.d.> S I T e {.$XOXOX",
"OXOX$X{.'.$XOXOX).OXOXOXOXOX%XOXOX%X%XOXOX@XOXOXOXOXOX$X].).$XOXOX*X(.y.A.Z.Z.Z.Z.Z.Z.Z.Z.S.G.r.+.b.b.;.: I I I I I T + X.d.a.=.b.> P E I E T I I D u d.=.s.-.s.-.s.-.d.s.-.s., L I T 3 {.$XOX#X",
"OXOX$X{.'.$XOXOX).#XOXOXOXOX%XOX#XOXOXOX%XOXOXOXOXOX$X].).$XOXOXOX$X(.y.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.G.w.X.s.=.=.: I I L L T + X.d.=.s.s.s., S I I L L S I A , ;.-.s.s.a.s.s.a.=.=.s.;., P I T 3 {.$XOXOX",
"OXOX$X[.].*XOXOX).$X$X+X+X+XOXOX@XOX%XOX%X$X+X+X+X*X'.).+XOXOXOXOX&X(.y.G.V.Z.Z.Z.Z.Z.Z.Z.Z.D.r.o.b.s.;.: R I I T + X.d.=.s.=.s.s., S I I T P T E Z , d.=.s.s.s.s.s.s.=.s.=.;.: L I I e {.$XOXOX",
"#XOX$X{.T.`.).).T.).).).~.}.$XOXOXOX%XOX$X'.~.).).~.`.+XOXOXOXOXOX&X(.y.G.Z.Z.Z.Z.Z.Z.Z.Z.V.G.w.; s s ,   : : : - $.d.=.s.=.s.=.d.7 - , : : : : : - u d.-.s.s.=.a.=.=.d.-.s.;.- P I T e {.+XOXOX",
"OXOX$X{._.+XXXOXOXoXoXoXOX/.{.-XOXOXOXOX#X). XOXoXoX+XOXOXOXOXOXOX$X(.y.D.Z.Z.Z.Z.Z.Z.S.Z.Z.D.t.H |  .^ 8 -.-.-.-.d.=.s.a.s.s.-.s.s.=.-.=.=.=.=.-.=.-.-.=.s.s.d.d.=.-.-.-.;.> r I I T e {.$XOXOX",
"OXOX$X{.'.$XOXOXOX%X%XOX#X+X~.{.$XOXoXOX+X).XX%XOXOXOXOXOXOXOXOXOX$X(.r.S.Z.Z.V.Z.Z.Z.V.Z.V.S.t.K z.j. .s d.s.-.a.=.s.=.s.s.s.a.s.;.=.-.;.-.-.s.;.s.=.-.=.=.a.=.=.=.-.-.;.; C T I I I e {.$XOXOX",
"%XOX$X{.'.$XOXOXOXOXOXOXOXOX+X~.{.&X$X$X-X_.OX$X$X$X$X$X$X$X$X$X#X;X`.m.G.G.G.D.F.D.G.D.F.S.H.t.W l.j.{ s ;.s.=.=.s.s.s.s.s.-.s.s.=.=.=.=.=.-.-.s.s.d.d.d.d.d.d.d.d.d.-.> C T I I P T e {.$XOXOX",
"OXOX$X[.'.$XOXOXOX%X%XOXOXOXOXOX/.'.].].{.T.'.[.].[.].].].].].].'.{.R.5.t.t.w.w.t.w.w.w.w.w.t.>.W l.j. ., d.a.-.s.s.s.-.s.-.s.s.s.s.s.s.s.-.s.=.s.s.@.X.X.X.X.X.X.X.@.: 5 T L I L I T 3 {.$XOXOX",
"OXOX$X{.'.$XOXOXOXOXOX%XOX%XOX#X#X[.].[.].'.[.'.{./.+ 5 3 e 3 e 3 e 3 3 3 e 3 3 3 e 3 3 3 3 3 o K k.} l.Z ..b.-.-.s.s.s.s.s.s.s.s.s.s.s.=.d.-.s.d.7 2 3 2 3 e 3 e 3 2 A I I I L I L I e {.$XOXOX",
"OXOX$X{.'.$XOXOX%XOX%XOXOXOXOXOXOX$X$X$X$X&X$X$X-X}.e E I I I T I E I E I I I E I I I T T E _ e K l.} j.z.Z ..d.=.-.-.s.=.-.s.s.s.s.-.=.a.=.-.d.7 2 T I E I I E E I E I I I I I I D T e {.#XOXOX",
"%XOX$X{.'.$XOXOXOX%XOXOXOX%XOXOXOXOXOXOXOXOXOXoX$X[.3 I I I I I L I I L T L L I T L I I L L E 3 W l.j.{ } k.C X.d.-.s.s.s.s.=.s.=.s.s.s.=.=.d.7 3 I I I L I I I I L S I I I I I I P T e {.$XOXOX",
"OXOX$X[.'.$XOXOXOXOXOX%X#XOXOXOXOXOXOXOXOXOXOXOX$X[.e E L I I I I I L T L T T L L T I I I I I 3 R l.j.l.} } z.C X.=.*.*.*.;.s.=.s.-.-.s.s.d.7 3 T I I I I I I I I I I I I I I I I I T e {.$XOXOX",
"%XOX$X{.'.$XOXOX%XOX%XOXOX%XOXOX%XOXOXOX#XOXOXOX+X.Xw P I I I I I I I I I L T I T L T L I I I r k z.} } l.} j.k.C M <.<.<.9 d.a.s.s.-.-.d.X.2 _ I I I I I I I I I I I I I I I I I L T 5 {.$XOX%X",
"OXOX$X[.'.$XOXOXOXOXOXOXOXOXOX%XOX%X#XOXOXOX%XOXOX$X[.w I I I I I I I I I I I I L T I T I I I I 3 l k.} } } l.l.H B.G.S.H.r.8 -.s.-.s.-.d.X.e I I I I I I I I I I I I I I I I I I I I e {.$XOX%X",
"OXOX$X{.'.$XOXOXOX%X%X%X%XOX#XOX%XOX#XOXOX%X%XOXOXOX$X[.w S I I I I I I T I I T I I I I I I I A E 2 x k.} } { l.G p.Z.Z.C.F.m.9 -.s.a.=.d.X.3 I L I I I L I I I I I I I I I I I I I T e {.$XOXOX",
"OXOX$X{.'.$XOX%XOXOX%X%XOXOXOX%XOXOXOXOX%XOXOXOXOXOXOX$X].w P I L I I I L I I L I I T L I I I I D I % Z z.z.z.z.H p.A.Z.Z.V.G.i.8 =.d.;.b.$.5 E I I I E I E I I L I I I I I I I I I I e {.+XOXOX",
"OXOX$X{.'.$XOXOXOX#XOXOX%XOX#X%XOXOXOX%XOXOXOX%XOXOX%XoX=X[.w T I I I I I I I I I I I I I I I I I L E 3 j Z Z Z $ M.S.C.Z.Z.C.G.i.9 f f f , + 3 3 3 + : 2 : 2 P I I I I I I I I I I I e {.$XOXOX",
"OXOX$X{.'.$XOXOXOX%X%XOXOXOXOXOX%XOX#XOXOX%X%X%XOXOXOXOX&XY.r I I I I I I I I I I I I I I I I I P I D I A A e A # M.Z.Z.Z.Z.Z.Z.A.V.p.B.B.B.B.B.M.m.9 *.#.*.> A I I I I I I I I I I T 3 {.$XOXOX",
"OXOX$X{.'.$XOXOXOXOXOX#X#XOX%XOX%XOXOXOXOXOXOXOXOXOXOX=XU.1 E L T I I I I I I I I I I I I I I I I I I I T T I E 5 M.A.Z.Z.Z.Z.Z.Z.Z.G.Z.C.Z.G.Z.A.Z.O.;.s.b.u A I I I I I I I I I L I e {.$XOXOX",
"%XOX$X[.'.$XOXOX%XOX%XOXOX%XOXOXOX%XOXOXOX#X#X%X#X%X=XP.1 E L T L I I I I I I I I I I I I I I I I I I I I L I I 6 M.A.C.Z.Z.Z.Z.Z.Z.V.Z.Z.Z.V.Z.Z.V.0 -.=.b.8 C I I I I I I I I I I T e {.$XOXOX",
"OXOX$X{.'.$XOXOXOX%XOXOX%X%XOXOXOXOXOXOX%XoX X X XXXU.1 E L I I I I I I I I I I I I I I I I I I I I I I I I L T 3 B.Z.Z.Z.Z.S.Z.G.Z.Z.Z.Z.Z.Z.Z.Z.M.O.s.a.s.8 A I I I I I I I I I L T e {.$XOXOX",
"OXOX$X{.'.$XOXOX%X%X%XOXOXOX%X#XOXOXOXOX&XY.2 t t r r I I L I I I I I I I I I I I I I I I I I I I I I I I I I I 3 B.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.O.s.s.d.p A I I I L I I I I I I T 3 {.#XOXOX",
"%XOX$X[.'.$XOXOX@XOXOXOXOXOXOXOXOXOX%XOX=XU.z T I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I 3 m.F.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.0 -.=.d.y A I I I I I I I I I I T e {.$XOXOX",
"OXOX$X{.'.%XoXOXOXOXOXXXOXOXOXOXOXOXOX.X&XU.5 T I L I I I L I L I I I I I I I L I I I I I I I I I L I I I P I I 3 M.F.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.B.O.;.s.d.7 A I I I I I I I I I D I e {.$XOXOX",
"OXOX$X{.[.;X*X*X*X*X*X*X=X*X*X&X*X*X*X*X>XR.k T P T I I I I T P I I I I I I I I I I I I I I I I I I I I I I I I 5 M.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.V.d ;.a.d.u A I I I I I I I I I I T e {.$XOXOX",
"OXOX$X{.` I.K.K.K.K.K.K.K.K.K.K.K.K.L.L.I.g O : : : : : : : + S I I I I I I I I I I I I I I I L I I T A # & & % . M.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.C.V.d ;.a.d.8 A I I I I I I I I I I I e {.$XOXOX",
"OXOX%X{.2 z z z z z z z A z z z z z z z A - =.-.=.-.-.-.-.-.#.- P I I I L I I I I I I I I I I I L I A $ { l.| l.G M.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.V.O.;.a.d.u A I L I I I I I I I I I e {.$XOXOX",
"%XOX$X{.e T I I I E I T I E I I I E I I I : =.-.-.-.-.-.-.a.d.*.O P I D I I P I L I I L I I I I I A % } l.{ | l.G p.A.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.C.V.O.-.=.d.u A I I I I I I I I I L I e {.+XOXOX",
"%XOX$X{.e T I L L I I L I P I L I I D L I : =.-.s.=.s.=.-.s.=.d.%.O S E I E I E T T I I E I I T r # { l.{ j.j.l.G M.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.0 -.=.d.u A I I S I I I I I I E E r {.$XOXOX",
"%XOX$X{.e T I I I I I I I I I I I I I I T - -.s.=.s.=.s.-.-.s.=.d.#.- 3 3 2 3 3 3 3 3 3 3 3 3 2 # j.l.j.j.j.j.l.m p.S.C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.V.9 ;.a.d.8 C I I I I I I I 5 2 2 3 o {.$XOX#X",
"%XOX+X{.3 T I I I I I I I I I I I I I I T 5 > ;.s.=.s.-.s.s.s.s.a.d.*.X.o.o.i M u.t.t.t.t.w.t.r.m { l.j.j.{ j.j.! V S.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.S.3...d.s.%.+ T I I I I E % y #.@.#.u {.+XOXOX",
"OXOX$X{.e T L I I I I I I I I I I I I I S T 3 7 d.s.=.s.=.s.s.=.s.s.s.d.d.b.*.4.H.G.S.G.G.G.S.G.B.m [ l.j.j.j.j.l.! N S.A.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.C.G.3.a d.s.#.O I I I I % i d.d.d.b.#.{.$XOXOX",
"OXOX$X{.e E L I I I I I I I I I I I I I I I E 3 > b.=.=.d.=.s.s.=.s.=.-.=.s.&.3.F.C.V.Z.Z.Z.Z.Z.S.C.m [ l.} j.j.} l.! V A.A.Z.Z.Z.Z.C.Z.Z.Z.Z.Z.Z.Z.Z.G.3.a d.d.+.+ I T % p d.=.a.=.s.@.{.$XOXOX",
"OXOX$X{.e I I I I I I I I I I I I I I I L I L T 3 7 d.=.=.a.=.s.s.s.s.s.s.d.#.6.G.C.Z.Z.Z.Z.V.Z.C.S.C.m [ l.} } j.j.z.R V C.C.C.V.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.D.3.X.s.d.#.- # i d.a.-.a.=.s.@.{.$XOXOX",
"OXOX$X{.e I I I I I I I I I I I I I I I I I L I T o 7 d.s.=.s.-.s.s.=.s.a.s.*.M S.A.Z.Z.Z.Z.Z.Z.Z.C.G.B.B | } j.j.j.} z.~ x U B x V A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.G.3.a d.d.#.a b.=.-.s.d.=.d.@.{.+XOXOX",
"OXOX$X{.e I I I I I I I I I I I I I I I I I I E + K Q u d.s.=.s.=.s.s.s.s.=.d.&.M A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.U } j.j.j.j.j. .l.l.} j.l.W C.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.V.H.2.a d.s.d.=.-.s.s.a.=.d.@.{.$XOXOX",
"OXOX$X{.w I I I L I I I I I I I I I I I I I I + H z.z.R 7 d.a.=.s.-.s.s.=.s.s.d.&.M S.C.Z.Z.Z.Z.Z.Z.Z.C.U | j.j.j.j.j.j.j.j. .j.} U Z.Z.C.A.Z.A.Z.Z.Z.Z.Z.Z.Z.G.3.a d.s.-.s.s.s.s.s.d.@.}.$XOXOX",
"OXOX$X{.r T I I E I I I I I I I L I I I P I # H z.{ j.l.K 8 d.d.=.s.-.s.s.=.s.a.d.&.M S.Z.Z.Z.Z.Z.Z.Z.C.B | j.j.j.j.j.j.j.j.l.l.k.U C.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.G.3.p d.-.s.a.s.s.-.s.@.{.+XOXOX",
"OXOX%X{.o 2 % & # 6 6 5 2 A I L I L I L I 3 H z.j.j.j.j.z.K u d.s.=.s.-.s.s.=.s.a.d.#.<.G.Z.Z.Z.Z.Z.Z.V.U } j.j.{ j.j.l.! v U G G m Z.A.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.C.G.3.X.d.=.-.s.-.-.s.@.{.$XOXOX",
"OXOX$X{.J  .~ ~ m C.B.B.M.n r T I I I I L 3 j.{ j.j.j.l.{ z.K , d.s.=.s.=.s.s.a.s.a.d.d V.Z.Z.Z.Z.Z.Z.Z.B | j.} j.j.l.! N M.B.M.p.V.Z.C.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.C.H.3...d.a.-.s.-.d.@.{.$XOXOX",
"OXOX$X{.R l.l.| Y G.Z.Z.A.A.b r T P I I I & { l.j.j.j.j.j.j.l.R 8 s.s.-.s.-.s.s.=.s.-.d V.Z.Z.Z.C.Z.Z.Z.U } j.j.| l.] m V.S.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.G.Z.Z.Z.Z.Z.D.3.a d.a.s.=.d.@.{.$XOXOX",
"%XOX$X{.R j.j.{ V A.Z.Z.C.A.A.c e E I T I & { l.j.j.j.j.{ j.j.z.K 8 d.-.=.s.-.s.s.a.-.O.S.Z.F.Z.Z.Z.A.C.B } j.} l.] m Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.G.3.a d.d.s.d.#.{.$XOXOX",
"OXOX$X{.R l.j.{ U S.V.Z.Z.Z.Z.S.b 3 e 5 e @ } | { j.j.j.j.j.j.{ z.K 7 d.s.-.s.=.s.s.;.9 y.p.i.p.Z.Z.A.C.U } } l.] B Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.G.3.p #.o.#.y {.$XOXOX",
"OXOX$X{.R l.j.{ V A.Z.Z.Z.Z.Z.Z.Z.6.6.6.8.,.G z.j.j.j.j.j.j.j.j.j.z.R 8 d.=.-.s.=.-.d.; $ 3 5 + t.G.C.C.U | } k.R >.G.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.C.G.w.6.8.8.:.{.+XOXOX",
"OXOX+X{.R l.j.{ V A.C.A.Z.Z.Z.Z.Z.G.G.G.G.H.6.Z l.j.j.j.j.j.j.{ j.{ z.R u d.s.=.s.=.b.> I I T e w.D.V.C.U } } } z.H >.S.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.G.G.F.H.t.{.$XOX%X",
"OXOX$X{.R l.j.{ Y A.V.C.Z.Z.Z.Z.Z.C.Z.Z.Z.Z.G.6.G l. .j.j.j.j.j.} j.j.z.K 7 d.a.s.a.s., L I I 3 0.D.Z.C.U } l.} j.l.H >.G.C.Z.Z.Z.Z.A.Z.Z.Z.Z.A.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.V.Z.Z.Z.Z.V.G.e.{.$XOX%X",
"OXOX$X{.R l.j.{ Y H.G.S.G.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.G.6.G z.j.j.j.j.j.j.} l.{ k.K 8 ;.=.=.;., S I T 3 t.H.G.Z.V } j.j.j.j.z.K >.G.Z.C.Z.Z.Z.Z.A.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.Z.Z.Z.Z.Z.G.w.{.$XOXOX",
"OXOX$X{.R z.{ j.1 n m n b B.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.H.3.R j.j.j.j.j.j.j.} } | k.H < 1.d O.- L I T 3 c Y V B S j.{ j.j.j.j.z.G e.G.Z.A.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.S.Z.Z.Z.G.w.{.+XOX@X",
"%XOX$X{.E k.| j.& F A D % p.Z.Z.Z.A.Z.Z.Z.Z.Z.Z.S.u.W l.} l.} j.l.} j.} } l.] 6.G.V.H.N L I E 3 G | { { l.j.| j.j.j.j.j.! 8.F.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.Z.Z.G.w.{.$XOXOX",
"OXOX$X{.K l.{ } 3 I I T 3 i.G.C.C.Z.C.C.Z.Z.Z.C.A.r.K z.} } } } } } } } j.j.] 6.G.V.G.N A I I 3 K k.} j.} } j.{ j. .j.j.! 6.F.V.V.Z.V.V.Z.Z.Z.Z.C.V.Z.Z.Z.Z.Z.C.Z.Z.C.C.Z.Z.C.Z.Z.V.G.w.{.$XOXOX",
"OXOX+X{.R z.l.z.& I I E 5 M.H.S.G.G.A.G.F.G.G.A.H.u.R z.l.l.l.l.l.k.k.k.l.z.{ 8.H.A.H.N L I _ e ! z.k.k.l.l.l.z.l.l.z.N.~ 9.H.G.F.D.D.D.S.G.G.G.G.S.S.G.G.G.G.S.G.G.G.G.G.G.A.G.A.A.H.t.{.+XOXOX",
"OXOX$X{.Z R R R o e e r + 3.t.w.w.w.w.w.w.w.w.w.t.3.k ! R H R R R R R J R R Z n t.e.t.6 w r r + C R K R R R R R R R R _ Z N t.w.x.w.w.w.w.w.w.w.w.w.w.w.w.w.e.w.w.w.w.w.w.e.w.w.w.w.w.2.{.$XOXOX",
"OXOXOXOX{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.{.OX%XOXOX",
"OXOXOX%X$X$X$X$X$X+X$X$X$X$X$X+X$X$X$X$X$X+X$X$X$X$X$X+X$X$X$X$X$X$X$X$X$X$X$X#X$X$X$X$X$X+X$X$X$X$X$X+X+X$X$X$X$X+X$X$X$X$X$X+X$X$X$X$X$X+X$X$X$X#X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X#X*X$X%XOXOXOX",
"OXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX%XOX%X",
"OX%XOXOXOXOXOX#XOXOX@X%XOXOXOXOXOX%XOXOXOXOXOX%XOXOXOXOXOXOXOXOXOXOXOXOX%XOXOXOXOXOXOXOXOXOXOXOX%XOXOXOXOXOXOXOXOXOXOXOXOXOX#XOXOXOXOXOXOXOX%XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX%XOXOXOXOXOXOXOX"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"48 48 103 2 ",
"   c #7E684F",
".  c #7D6A51",
"X  c #757553",
"o  c #787754",
"O  c #757855",
"+  c #81674B",
"@  c #89664E",
"#  c #82684E",
"$  c #846D54",
"%  c #8B6C55",
"&  c #856F59",
"*  c #867056",
"=  c #8B7157",
"-  c #85705A",
";  c #8C7359",
":  c #867B59",
">  c #887A59",
",  c #90765B",
"<  c #9D735A",
"1  c #A4765D",
"2  c #AB755A",
"3  c #A6785F",
"4  c #A9795F",
"5  c #A27762",
"6  c #AA7760",
"7  c #A27962",
"8  c #AC7B63",
"9  c #A57E6A",
"0  c #AC7E68",
"q  c #B27E65",
"w  c #74855A",
"e  c #768B5D",
"r  c #788E5F",
"t  c #77905F",
"y  c #79905F",
"u  c #778A61",
"i  c #798E61",
"p  c #769464",
"a  c #7B9363",
"s  c #7E9965",
"d  c #7E9468",
"f  c #9B8554",
"g  c #8F9059",
"h  c #92915A",
"j  c #A8865A",
"k  c #A98959",
"l  c #AD9659",
"z  c #AE9A59",
"x  c #B29C5B",
"c  c #B6A05A",
"v  c #BDA65F",
"b  c #BFA95F",
"n  c #819A66",
"m  c #809769",
"M  c #839D69",
"N  c #AE8069",
"B  c #B48166",
"V  c #B88267",
"C  c #B78268",
"Z  c #B98369",
"A  c #B49E61",
"S  c #B4A162",
"D  c #BEA661",
"F  c #BFA965",
"G  c #B6A369",
"H  c #C0A75E",
"J  c #C2AA5E",
"K  c #C8AD5B",
"L  c #C1AA65",
"P  c #C8AF62",
"I  c #C2AC68",
"U  c #CCB366",
"Y  c #CFB668",
"T  c #D1B666",
"R  c #D2B867",
"E  c #D0B668",
"W  c #D3B868",
"Q  c #9E9386",
"!  c #A1958A",
"~  c #A3998E",
"^  c #A79D93",
"/  c #B59F95",
"(  c #9EA892",
")  c #BDB28D",
"_  c #BEB393",
"`  c #C5C4C2",
"'  c #C8C6C5",
"]  c #C9C9C7",
"[  c #CBCBCB",
"{  c #D1D0CE",
"}  c #D6D6D5",
"|  c #D8D7D6",
" . c #D7D8D6",
".. c #D8D8D7",
"X. c #D6D7DA",
"o. c #D7D8DB",
"O. c #DADADA",
"+. c #E5E5E5",
"@. c #E5E6EA",
"#. c #E9E7EB",
"$. c #E7E9EB",
"%. c #E9E9E9",
"&. c #EFEFF0",
/* pixels */
"+.+.+.%.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.#.+.#.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.@.+.+.+.+.",
"+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.",
"+.+.+.+.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.$.%.+.%.%.$.%.%.%.%.%.%.%.#.%.%.%.%.%.%.%.%.+.+.+.#.",
"+.+.+.+.| | ..| | | | | | | | } } } | | ................| | ......| | ..................+.+.+.+.",
"+.+.#...d d d a d d d d d s s i . > ; - ; - ' ..| | ..` 9 6 S I I L F I L L L L L L L G ..%.+.+.",
"+.+.%...d s n s n s s s r r a w $ ; ; ; ; & | %.+.%.%.} 8 4 H T U U U U U Y U U Y U T L ..%.+.+.",
"+.+.%...s n n s s M s O $ $ & $ ; ; ; ; # Q @.+.+.+.%.} 0 4 D Y U U U U U U U P U P U F ..%.+.+.",
"+.+.%.| u i a n s s O % ; ; ; ; ; ; ; # Q #.@.+.+.+.%. .8 4 b Y I U U P U U U U U U Y L ..%.+.+.",
"+.+.%...` ..( e M a $ ; ; ; ; = ; ; # Q #.+.+.+.+.+.$./ q 8 k U Y Y Y Y Y Y U U U U U F  .%.+.+.",
"+.+.%...O.%.#.( t e . * $ $ * & & $ Q $.+.+.+.+.+.@./ 2 B B 8 k b b v b v v U U U U U I ..%.+.+.",
"@.+.%...| +.+.@. .' ` } [ } } ` ' } #.%.@.%.+.+.%.} 1 B q q B q 4 4 4 3 4 3 k Y U U Y F ..%.+.+.",
"+.+.%...| @.+.+.O.} O.%.%.%.%...} O.........+.+.%.| 8 B B B q q B B B B B B 8 k U U U F ..%.+.+.",
"+.+.%...| %.+.]  .| +.+.+.+.+.+.} | O.[ { { O.&.%.~ @ q B 8 B B 0 q q B q q V 8 j U W I  .%.+.+.",
"+.+.%...| @.] +.%.%.+.+.+.+.+.+.%.+.O.{ O.O.' O.~ + = % q B q B B B B q B q q B 8 k b A  .%.+.+.",
"+.+.%.....O...$.+.+.+.+.+.+.+.+.+.` ..[ O...& * $ , $ % 8 B B B B B B B q B q q q 1   * | %.+.+.",
"+.+.#.| ..O...%.+.+.+.+.+.+.+.+.' +.&...O.| $ , ; = % B B B B 8 q q q q B 0 8 8 q 5 $ > | %.+.+.",
"+.+.$.....O.| %.+.+.+.+.+.+.$.....%.+.| ..$.~ # ; = % q V B B V B B B q B 3 w w 8 4 $ ; | %.+.+.",
"+.+.#...O.O.| %.+.+.#.+.+.+.#.....@.%.X...%.%.! & ; & % 4 1 4 1 3 1 q q V 1 a a 1 < & - | %.+.+.",
"+.+.%...O.O...#.+.+.+.+.+.+.%.....$.@._ ) @.&...= ; ; = $   w i a w 8 Z q : s s i w $ ; | %.+.+.",
"+.+.$...O.O...$.+.+.+.+.+.+.$...| #._ K K _ O.` . $ ; ; , $ y M a w < 4 : a n s M i $ ;  .%.+.+.",
"+.+.%.| O.+.| %.+.+.+.+.%.%.+.[ @.| v Y U P L x e w & , % X s e   & $   e M s n s r $ ; ..$.+.+.",
"@.+.%...[ } ' ..+.+.+.+.....' O.%.} L Y U U T v r w   $ X s M i   & *   y n n a M i $ ; ..%.+.+.",
"+.+.%...[ ..| | ] +.%.O.{ O.@.$.$.O.I R U U W L < < w r s n s s r r r y n M M M p o = - | @.+.+.",
"+.+.%.....$.+.%.+.[ O.[ [ O.} } | ` x H v v D x 8 8 r M n n s s n n M s r e e t X % ; ; | %.+.+.",
"@.+.%.....#.+.+.+.+.| | ..' * * * % $ $ * $ $   3 B > p n n n n s n s X $ $ & $ ; ; ; - | %.+.+.",
"+.+.%.O...#.+.+.+.+.+.%.%.| & ; ; = , , = ; , $ 3 V q > y y a n n s X % ; = ; ; ; ; ; ; | %.+.+.",
"+.+.%...| %.+.+.+.+.+.+.+.%.~ # ; ; = ; = ; ; = % q Z 4 x H h p M y $ , ; ; = = = ; = * | %.+.+.",
"+.+.+...| +.+.+.+.+.+.+.+.+.%.^ $ ; = ; ; ; = , $ % 4 < H R U h y w   $ $ $ ; ; ; ; ; * | %.+.+.",
"+.+.%.O.} %.+.+.+.+.+.+.%.%.%.^ $ ; = ; ; ; ; = ; = $   v Y U U v v v z w w $ ; = ; = ; | %.+.+.",
"+.+.%.O.} +.+.+.+.+.+.+.{ | ~ + , = ; ; ; ; = ; = ; ; & v T U U Y Y R b a a $ ; = ; ; * | %.+.+.",
"+.+.%.....%.%.%.%.@.&...- ; $ , ; = ; = ; ; = ; = ; ; % v Y U U U P Y v p r $ ; ; ; ; ; | %.+.+.",
"+.+.$...` } [ } } { | ` . $ $ $ = , = ; = ; = ; ; = $   v U U U U U Y v a r $ ; ; ; ; - | %.+.+.",
"@.+.%.| - * & & & = ; . w a r y X % ; = ; ; ; ; * @ 8 1 v Y U U U U Y c y r & ; = ; ; > ..#.+.+.",
"+.+.%.| ; = ; ; = ; ; $ e M n M s X $ * * * * # % B B 4 v Y U U U P Y v a r # , ; = . $ ..#.+.+.",
"+.+.%.| - ; ; ; ; ; ; ; o a n s n n y w z H b v k 8 B q j U T U U U U U h p o % % O y u | %.+.+.",
"+.+.%.| ; = ; ; = ; = ; % X p n n n M y b W Y Y Y k 8 B 8 j v v I U U U U h p o O s M n | %.+.+.",
"+.+.%.| * ; ; ; ; ; = ; = % ; a M s s p g P U U T v 1 V q q 8 1 v T U U U U h p n n a d | %.+.+.",
"+.+.%.| $ $ $ $ % ; = = % q B : a M s M p g U U T v 8 q B 0 8 1 v Y P U U U U h a n s d ..#.+.+.",
"+.+.%.| 7 1 l P f $ , $ 4 B B q > a M a n a D R U v 4 V 8 k H v U U U U U P U U h p M s | %.+.+.",
"+.+.%.| N 8 v T Y f $   1 V q B q > a n n r z D U v 4 q k U T Y U U U U U U U U U h r i | %.+.+.",
"+.+.%.| 0 4 v R U Y v b k 8 B B B q > p M r   # H P 4 q j U U U U U U U U U U U U U L x ..%.+.+.",
"+.+.%.| 0 4 l v P U Y Y U k 8 B B B q > y w & % x x 3 B 6 j U U U U U U U U P U U U W I ..%.+.+.",
"+.+.#.| 0 4 # $ v W U U W H 4 B q q B 4 c x & $ < 8 q q V 4 H R U U U U U U Y Y U U T L ..%.+.+.",
"+.+.%.| 9 5 & * z I F F I A 7 0 8 0 0 7 D D * & 5 0 0 0 0 5 A I F F I F F F L I L F L G ..%.+.+.",
"+.+.+.+...| | } ................| | | | | | | | | | | | | | ....X.......................+.+.+.+.",
"+.+.+.+.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.#.$.%.%.%.%.%.%.%.%.%.%.+.+.+.+.",
"+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.",
"%.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.@.+.+.+.+.+.+.+.+.+.+.+.+.%.+."
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"32 32 148 2 ",
"   c #77734E",
".  c #7D6C50",
"X  c #7D7555",
"o  c #7C7957",
"O  c #7B7758",
"+  c #7B7E59",
"@  c #83674C",
"#  c #83694E",
"$  c #856C54",
"%  c #8A6D55",
"&  c #836D5B",
"*  c #8B6E5A",
"=  c #926E56",
"-  c #906E58",
";  c #857155",
":  c #8B7256",
">  c #86745C",
",  c #8C735A",
"<  c #927956",
"1  c #9D7B55",
"2  c #90735A",
"3  c #9B725A",
"4  c #947D5D",
"5  c #9B7C5E",
"6  c #A4755C",
"7  c #AC765A",
"8  c #A27E5C",
"9  c #AA7C5E",
"0  c #B0755F",
"q  c #8C7660",
"w  c #9D7E60",
"e  c #917E6A",
"r  c #A37C62",
"t  c #AC7B63",
"y  c #AA7D69",
"u  c #B37E66",
"i  c #76865C",
"p  c #7A845B",
"a  c #758C5C",
"s  c #7E8A5E",
"d  c #7B915E",
"f  c #7B8E60",
"g  c #739762",
"h  c #7C9463",
"j  c #7D9A66",
"k  c #7E9368",
"l  c #7A9E68",
"z  c #7EA069",
"x  c #8A8155",
"c  c #84835D",
"v  c #88835C",
"b  c #838D5B",
"n  c #9F8858",
"m  c #8C945E",
"M  c #8D995F",
"N  c #91955C",
"B  c #AD825F",
"V  c #AB8A58",
"C  c #B08B5E",
"Z  c #A69057",
"A  c #A39D5E",
"S  c #AC9F5D",
"D  c #B3935D",
"F  c #B39A5D",
"G  c #B99C5D",
"H  c #B3A35F",
"J  c #BAA15E",
"K  c #809665",
"L  c #819A66",
"P  c #8D9860",
"I  c #819B69",
"U  c #909A61",
"Y  c #908975",
"T  c #869A72",
"R  c #8B9C7A",
"E  c #AC8160",
"W  c #AE826C",
"Q  c #B48066",
"!  c #BA8067",
"~  c #B38C61",
"^  c #B48269",
"/  c #BD8169",
"(  c #A79261",
")  c #B79E64",
"_  c #AE8570",
"`  c #A68877",
"'  c #AFA166",
"]  c #B3A560",
"[  c #BDA564",
"{  c #BFA961",
"}  c #B5A56E",
"|  c #BFAB6D",
" . c #BDAA70",
".. c #C1A75F",
"X. c #C3AA5C",
"o. c #C0A462",
"O. c #C5AD65",
"+. c #CAAF63",
"@. c #C4AE6B",
"#. c #C6B165",
"$. c #CCB365",
"%. c #C6B16C",
"&. c #CCB36A",
"*. c #D1B666",
"=. c #D3BA66",
"-. c #D0B768",
";. c #D3BB69",
":. c #9F9284",
">. c #A6998C",
",. c #B99A8B",
"<. c #ACA197",
"1. c #ACA298",
"2. c #B1A69B",
"3. c #B2A89E",
"4. c #B6ADA4",
"5. c #BCB4AE",
"6. c #BCB7B3",
"7. c #BDBBB6",
"8. c #C6B88F",
"9. c #C4BDAE",
"0. c #C4BCB6",
"q. c #CABFB9",
"w. c #C3C4BD",
"e. c #D0C5BE",
"r. c #D3CEBF",
"t. c #CAC5C1",
"y. c #CCC9C5",
"u. c #CDCDCD",
"i. c #D6D1C0",
"p. c #D3D1CF",
"a. c #D6D5D4",
"s. c #D9D7D5",
"d. c #D6D8D5",
"f. c #DAD9D5",
"g. c #D6D6D8",
"h. c #D8D7D9",
"j. c #D7D8D9",
"k. c #DCDBDB",
"l. c #DCDDE0",
"z. c #DEE0E2",
"x. c #E5E5E5",
"c. c #E4E5E8",
"v. c #E4E8EA",
"b. c #E8E9E9",
"n. c #EDEFF0",
"m. c #EEF0F3",
"M. c #F1F4F7",
"N. c #F3F7FA",
/* pixels */
"x.x.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.x.x.",
"x.x.f.d.d.d.d.d.g.d.d.a.s.j.d.k.k.k.k.d.f.j.j.f.f.f.f.f.k.j.x.b.",
"b.j.k h K h k j k j O , , # >.x.j.x.0.6 [ @.O.O.O.O.O.#.O.| k.b.",
"b.j.h L L L j + X o ; , , @ 3.n.x.b.e.6 o.$.$.$.$.$.$.$.$.$.k.b.",
"b.k.R I h I + 2 , - , , # 1.b.x.x.b.e.6 G -.$.$.$.$.$.&.$.@.k.b.",
"x.k.l.d.I a . $ $ $ % @ 1.b.x.x.b.a.W u B o.#.#.O.$.$.$.$.@.k.x.",
"b.k.k.b.k.w.7.t.t.w.6.y.b.b.x.x.b.,.7 Q Q t B E E 9 J *.$.@.k.b.",
"b.k.k.b.k.s.x.n.n.b.k.k.g.p.h.b.b.` Q Q Q Q Q Q Q u 9 J *.&.k.b.",
"b.k.k.k.k.x.x.x.x.x.x.z.a.a.u.a.>.# 3 Q u E Q Q Q Q Q t G [ k.b.",
"b.k.k.g.b.x.x.x.x.x.k.g.a.z.4.. % : 3 Q u Q u u Q u u ! = > k.b.",
"x.k.k.g.x.x.x.x.x.x.a.x.z.x.w.# > % Q ^ Q u u u Q r p t 3 > k.b.",
"b.k.k.g.x.x.b.x.x.x.k.b.k.p.m.4.% , = 6 5 w 5 u ! 5 g 4 : > k.b.",
"b.k.k.g.x.x.x.x.x.x.g.x.8.@.k.d.$ : , $ i j a 9 r b j j o , k.b.",
"b.k.k.k.b.b.x.x.x.g.k.r.X.$.%.} i X = X j p # $ + l K I + , k.b.",
"b.k.u.u.a.k.b.j.g.k.M.r.X.-.=.X.v O O h L p > X s l L j o , k.b.",
"b.k.k.x.x.a.k.u.j.s.s.9.J ..o.G 0 v l L L j j l h f h + % q k.b.",
"b.k.k.b.x.x.k.x.u.& , ; % ; : $ t 5 f h k j L p $ $ $ : : q k.b.",
"b.k.k.x.x.x.x.x.z.e % , , , , : 6 / B A P j h . 2 , , , : q k.x.",
"b.k.k.b.x.x.x.x.b.k.q : , : : , $ 3 1 $.+.N b < ; ; , , : q k.b.",
"b.k.k.x.x.x.x.x.b.4.: , , : , : , ; < #.$.+.+.$.P i : , % q k.b.",
"b.k.x.n.n.b.N.5., % , , : , : , , , < $.#.$.$.*.U i % , : q k.b.",
"b.k.1.2.2.2.4.Y   + ; % , : , , ; % 1 $.$.$.$.$.U i , , : q k.b.",
"b.s.$ # $ # #   z L h o $ : : ; = u E #.&.$.$.*.P i % , $ > k.x.",
"b.s., , 2 , , , i j j j a S +.O.C u u D #.$.$.$.] a O $ s K k.b.",
"b.g., : , , , , $ b j L k A *.$.#.B u t E D $.$.*.] s f l I k.b.",
"b.s.* = < $ , $ t t s j j h S *.$.~ u u t D $.$.$.*.H h j I k.b.",
"b.f.t D $.n $ % Q Q t s j j N #.#.C t D #.$.$.+.$.$.*.] h k k.x.",
"b.j.t D ;.$.J F t u Q 9 s j + : #.~ t J -.$.$.$.&.+.&.$.J ) k.b.",
"b.s.t 8 Z $.-.;.G u u Q 6 N x $ V t u 9 ..*.$.$.$.$.*.$.=.&.k.b.",
"b.h.y , > #.@.#.[ y ^ W y o.( & r ^ ^ y ) &.@.@.@.@.@.@.@.| k.x.",
"x.x.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.x.x.",
"x.x.b.b.b.b.b.b.b.b.x.b.b.b.b.x.b.b.b.b.b.b.b.b.b.x.b.b.b.b.b.x."
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"16 16 231 2 ",
"   c #E4E4E4",
".  c #DCDDDB",
"X  c #DADBD8",
"o  c #DADDD9",
"O  c #D9DFD9",
"+  c #DADAD8",
"@  c #DBD9D7",
"#  c #DDDDDC",
"$  c #E1E1E1",
"%  c #DDDBDA",
"&  c #DEDBD7",
"*  c #DEDDD8",
"=  c #DFDDD9",
"-  c #E5E5E4",
";  c #82986B",
":  c #829A69",
">  c #84946A",
",  c #828964",
"<  c #8B7B60",
"1  c #886E56",
"2  c #C6C1BB",
"3  c #E9EEF1",
"4  c #BBA293",
"5  c #C0A562",
"6  c #CCB76F",
"7  c #CAB36D",
"8  c #C9B26A",
"9  c #C8B376",
"0  c #E0DFDC",
"q  c #DEDFDE",
"w  c #B0BAA5",
"e  c #809868",
"r  c #817254",
"t  c #8A6E56",
"y  c #866C51",
"u  c #B3A79B",
"i  c #E9EAEA",
"p  c #E4E3E3",
"a  c #B58E7B",
"s  c #BB995A",
"d  c #CAB263",
"f  c #C8AF62",
"g  c #CDB461",
"h  c #C9B26D",
"j  c #DFDEDB",
"k  c #E8E7EA",
"l  c #D1D2CF",
"z  c #D0CDCA",
"x  c #D5D2CF",
"c  c #CDCBC8",
"v  c gray87",
"b  c #ECF1F4",
"n  c #C9BBB3",
"m  c #AB7559",
"M  c #B18167",
"N  c #B18363",
"B  c #AF8164",
"V  c #BC9C60",
"C  c #CDB970",
"Z  c #E0DEDB",
"A  c #D8D8D8",
"S  c #E4E3E4",
"D  c #E9EAEB",
"F  c #EAEAEB",
"G  c #E0E0E1",
"H  c #D7D7D8",
"J  c #B6ADA2",
"K  c #8F7861",
"L  c #A87960",
"P  c #B88168",
"I  c #B37E66",
"U  c #B27E67",
"Y  c #B07B61",
"T  c #A98F66",
"R  c #DDDDDA",
"E  c #DADADA",
"W  c gray90",
"Q  c #E2E2E1",
"!  c gainsboro",
"~  c #E1E2E4",
"^  c #B6ACA5",
"/  c #87694F",
"(  c #A57961",
")  c #A68063",
"_  c #B08166",
"`  c #A88063",
"'  c #8D815C",
"]  c #937663",
"[  c #DBDBDA",
"{  c #D7D7D7",
"}  c #E7E7E7",
"|  c #E3E4E5",
" . c #DCDBD6",
".. c #CDB97C",
"X. c #CCC4A0",
"o. c #847A5D",
"O. c #856F54",
"+. c #778B5E",
"@. c #8B7358",
"#. c #8B8961",
"$. c #789B63",
"%. c #898164",
"&. c #DEDADA",
"*. c gray88",
"=. c #DADAD9",
"-. c #D4D4D5",
";. c #D1CBC0",
":. c #C1A85D",
">. c #BDA158",
",. c #8D7F5B",
"<. c #789062",
"1. c #7F9564",
"2. c #7D875D",
"3. c #7A9262",
"4. c #7C8D5E",
"5. c #8C7C63",
"6. c #DEDBDB",
"7. c #E4E3E2",
"8. c #E5E6E8",
"9. c #B8AFA5",
"0. c #876F55",
"q. c #8D755A",
"w. c #8C7258",
"e. c #A77961",
"r. c #949362",
"t. c #819B65",
"y. c #78875F",
"u. c #886F57",
"i. c #886F54",
"p. c #917A63",
"a. c #DDDCDB",
"s. c #E5E6E7",
"d. c #ECEDEE",
"f. c #EDEEF0",
"g. c #D0C9C6",
"h. c #8B735A",
"j. c #8C7358",
"k. c #8D7559",
"l. c #8A6D57",
"z. c #B6955D",
"x. c #BEAF64",
"c. c #A6965D",
"v. c #88805A",
"b. c #877055",
"n. c #917B64",
"m. c #DDDCDA",
"M. c #C8C3BD",
"N. c #CFC9C4",
"B. c #B8B3A9",
"V. c #84795B",
"C. c #897257",
"Z. c #8B6F58",
"A. c #876F58",
"S. c #866B56",
"D. c #AE975E",
"F. c #D4B967",
"G. c #CFB666",
"H. c #879260",
"J. c #876E55",
"K. c #927963",
"L. c #DAD9D7",
"P. c #8A735B",
"I. c #866A50",
"U. c #837052",
"Y. c #789460",
"T. c #7B8F62",
"R. c #908359",
"E. c #A9905B",
"W. c #A77B5F",
"Q. c #B89162",
"!. c #C9B364",
"~. c #CCB265",
"^. c #90945F",
"/. c #7C6F54",
"(. c #8A8666",
"). c #DAD8D7",
"_. c #937B62",
"`. c #8B7457",
"'. c #896D59",
"]. c #977B5E",
"[. c #7D9866",
"{. c #879C64",
"}. c #CEB966",
"|. c #C19F64",
" X c #AC7964",
".X c #B28F5F",
"XX c #CDB466",
"oX c #C8B065",
"OX c #88945D",
"+X c #7E9C70",
"@X c #DDDEDB",
"#X c #DBD6D8",
"$X c #B48E66",
"%X c #BEA65B",
"&X c #A18558",
"*X c #B67D62",
"=X c #A27F5F",
"-X c #768F60",
";X c #979159",
":X c #BC975E",
">X c #B0865E",
",X c #C9B161",
"<X c #CBB263",
"1X c #CFB464",
"2X c #C6AE5F",
"3X c #A0A069",
"4X c #DDDDDB",
"5X c #E0DCDA",
"6X c #A5846F",
"7X c #B49F67",
"8X c #D2BD71",
"9X c #B5956B",
"0X c #B48070",
"qX c #AB916A",
"wX c #928361",
"eX c #AB846A",
"rX c #B2876D",
"tX c #C4AD6D",
"yX c #CBB56F",
"uX c #C8B36F",
"iX c #CBB36D",
"pX c #CDB678",
"aX c #DDDBDB",
"sX c #DBDADA",
"dX c #E2DEDB",
"fX c #E0DDDB",
"gX c #DEDCDB",
"hX c #DFDDDB",
"jX c #E0DFDB",
"kX c #DFDEDC",
"lX c white",
/* pixels */
"  . X o O + @ # $ % & * * * = - ",
"X ; : > , < 1 2 3 4 5 6 7 8 9 0 ",
"q w e r t y u i p a s d f g h j ",
"$ k l z x c v b n m M N B V C Z ",
"$ A S D F G H J K L P I U Y T R ",
"$ E W W Q ! ~ ^ / ( ) _ ` ' ] [ ",
"$ {   } |  ...X.o.O.+.@.#.$.%.&.",
"*.A v =.-.;.:.>.,.<.1.2.3.4.5.6.",
"*.$ 7.8.9.0.q.w.e.r.t.y.u.i.p.a.",
"$ s.d.f.g.h.j.k.l.z.x.c.v.b.n.m.",
"v M.N.B.V.C.Z.A.S.D.F.G.H.J.K.% ",
"L.P.I.U.Y.T.R.E.W.Q.!.~.^./.(.. ",
")._.`.'.].[.{.}.|. X.XXXoXOX+X@X",
"#X$X%X&X*X=X-X;X:X>X,X<X1X2X3X4X",
"5X6X7X8X9X0XqXwXeXrXtXyXuXiXpX0 ",
"W aXsXj j a.dXfX6.gXhXjXZ j kXW "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
};
const int n_xpm_icons = 4;
