/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 87 1 ",
"  c #000000",
". c #161633",
"X c #2C2C2C",
"o c #333333",
"O c #303939",
"+ c gray23",
"@ c #7E0000",
"# c #4B4B39",
"$ c #020254",
"% c #06065E",
"& c #09095B",
"* c #234D4D",
"= c #3A4E4E",
"- c #355252",
"; c #007E7E",
": c #444444",
"> c #4D4D4D",
", c #5F4F4F",
"< c #4F4F53",
"1 c #415E5E",
"2 c #535353",
"3 c #5C5252",
"4 c #595959",
"5 c #664949",
"6 c #6B4E4E",
"7 c #6C5A5A",
"8 c #705555",
"9 c #4A6767",
"0 c #4E6B6B",
"q c #516D6D",
"w c #5B6D6D",
"e c #537171",
"r c #646464",
"t c #626E6E",
"y c #7E7E7E",
"u c #840101",
"i c #8B0000",
"p c #820909",
"a c #940000",
"s c #B20000",
"d c #0101F6",
"f c #0000FE",
"g c #008282",
"h c #008989",
"j c #03A2A2",
"k c #788080",
"l c #838383",
"z c #8B8585",
"x c #8D8D8D",
"c c #968484",
"v c #9F8D8D",
"b c #989886",
"n c #849696",
"m c #8D9F9F",
"M c #959595",
"N c #9D9D9D",
"B c #A18E8E",
"V c #A39191",
"C c #AB9191",
"Z c #8FA1A1",
"A c #91A3A3",
"S c #97AAAA",
"D c #9BAAAA",
"F c #A2A2A2",
"G c #A9A2A2",
"H c #AAAAAA",
"J c #B6B6B6",
"K c #BABABA",
"L c #C3C3C3",
"P c #CDCDCD",
"I c #D9D9C6",
"U c #DCDCCA",
"Y c #D5D5D5",
"T c #DADADA",
"R c #E1DCDC",
"E c #EDEDDB",
"W c #DEE0E0",
"Q c #E6E6E6",
"! c #EAE5E5",
"~ c #E5E5E9",
"^ c #E7E9E9",
"/ c #EBEBEB",
"( c #F5EEEE",
") c #F4F4F4",
"_ c #F9F4F4",
"` c #F3F9F9",
"' c #FAFAFA",
/* pixels */
"QQQQQQQQ^QQQQ^QQQQ^Q!QQ^QQQQQQQQQ^QQ^^QQQQQQQQQQQQQQ^QQQQ^QQ^^QQQQQQQQQ^QQ^QQQQQQQQQQQQQQQ^^QQ^Q",
"QQ^QQQQQQQQQQQQ^^QQQQQQQQ!QQQQQ^QQQQQQQ^QQ^QQQQQQQQQQQQ^QQQQQQQ^QQQ^QQQQQQQ!QQQQQQQQQQ^Q^QQQQ!QQ",
"Q^QQ!QQ^^^!QQQQ^^QQQQQ^^^QQQQQ^Q^!QQQQQ!QQQQ^!QQQQQQQ^^Q^!QQQQQ!Q^QQ^QQQQQQ!QQQQQQQQ^QQQQQQQQQQ^",
"QQQ^^QQQQQQQQQ!!QQQQQQQQQQQ^!QQQQQQQQQQQQQQ^W/!QQQQQQQQQQQQQQQQQQQQQQQ^QQQQ^Q^QQQQQQQQQQQQQ!QQQQ",
"^QQQQQ^Q^QQQQQQQ^QQQQQQ^Q^QQ^QQ^QQQQQQQQ~Q)xoL)WQQQQQQQQ!QQQQQQ^QQQQQQQQQQ`xoL)QQQQQQQ^Q^QQQQQQ^",
"^QQQQQQQ!Q^^QQQQQQ!Q^^QQQQ^Q^QQQQQQQQQQQ~)x>z:L)QQQQQQQQQQ^^Q^QQQQQQQQQQQ)x>x:K(QQQQ^Q^QQQ^Q^^QQ",
"!QQQQQQ^QQQQQQQQQ^QQQQQQ!QQQQQQQQQQQQQQQ)x:JLN#K(QQQQQQ^QQQQQQ!Q!QQQQQQQ)x:JLM:L)TQ^Q!QQQ^QQQQQQ",
"!QQQQ^QQQQ^QQQ^QQQQQQ!QQQQQQQ!QQQQQQQQQ)x:JKJLN+L/WQQQQQQQ^QQQQQQQQQQQQ`x:JKJLM:L)TQQ!^QQQQQQ!QQ",
"QQQ!QQQQQQQQQQQQ!QQQQQQQQQQ!QQQQQQQQQQ)x:JKKKJLM=L/QQQQ^QQQQQQQ^QQQQQQ_x:JKJJJLN+L)WW~Q~QQQQQQ!Q",
"QQQ^QQQQQQ!^QQQQQQQQ^QQ!QQQQ^QQQQQQQQ)x:JKJKJKJLM+L)QQQQ^Q!QQQQQQQQQQ)x>KKJKJJJLN+L(EQQQQQQQ^QQQ",
"QQQQQ^^!QQQQ^Q^QQ^Q^QQQQQ^QQQQ!QQQQQ_M>KKJJJKJKJLV:L)QQQQQQQQQ^QQQQQ)M>KKJKJJJJJPV:L)QQQQQQQ^QQQ",
"QQ^QQQQQQ^^Q!Q^QQ^QQQ^^QQQ^QQ^QQ^QQ/loNFJKJKJKJKHHlXJ^QQQ^^Q!Q^QQQQ^lXNFJKJKJKKKHHkXJ/QQQQ^QQQQQ",
"^^QQQ^QQQ^^Q!QQQQQQQQ!^Q^Q^QQQ^^QQ!Q2>4::LJJKJKHX24:z)WQQ^QQQQQQQQ^!4>4::LJKJKKHX<4:z)QQQQQQ^QQQ",
"QQ!^QQQ^QQQQQQQQQ!QQQQQQQQ!Q^QQQQQQQ_''W:LJJKJKD4')'/QQQQQQQQQ^Q^QQQ'_'T:LJKKJKA4'/')QQQQ^^Q^Q!Q",
"QQ!QQQQQ^QQQQQQQQQ^QQQQ^QQQQQQQQQQQQQWQP>LJKJJKF>)TQ!QQQQ^QQ^QQQQQQQQT^P:LJJKKLV<)WWWQQQQQQQQ^QQ",
"QQQQQQQ!^QQ^QQQQ^QQQQQQQ^QQQQQQ!^QQ^QQ/P:LJJKJKF<_QQQQQ!QQ!QQQQ^QQQQ^Q^Y:LJJKKKF2`QQQQQQQQ^QQQQ^",
"QQ^QQQ^QQ^!QQQ!!QQQ^QQ^QQ^QQQ!QQQ^^QQQ^P:LJKKJKD2`QQQQ^^QQQQQQQ^^QQQ^!/Y:LJJKJKF2)QQQQQQQQQQQ^^Q",
"QQQQ^Q^QQQQQQQ^QQQQQQQQQQ^Q^QQ^QQQQQQ!/P:LJJJJKN2_WQ^QQQ^QQQQ^QQQQ^QQ!^P:LJJKKKF<)QQ^QQQQQQQQQQQ",
"QQ^QQQ!QQ^QQQQQQQQQQ^Q^QQQQQQQQQ^QQQQQ/Y:PKLLKLH2_QQQQQQQQQQQQ!QQQQQQQ^P:PKKKKLF2_RQQQQQQQQQ^!Q^",
"QQQQQQQQQ^QQQ^Q^QQQQ!Q^QQQQQQQQ^!QQQQQ^Y+HNFFVFx<_WQ^QQQQ^!QQQQQQQQQQQ^Y+HNFFFFx<_QQQ^Q!QQQQQ!QQ",
"QQQ^Q^QQQQQQQQ^QQQQQQQQQQQ^!^QQQQQQQQQQW4<22<22:l)QQQQQ^Q^^QQQ^QQ^Q!QQQW4222222:l)WQQQ^^QQ^QQ^Q^",
"^^QQQQQ^!^QQQQ!QQQQQQQQQ^QQQQQQQQQQQQQQQ`_`)_)_`)QQQQQQQQQQQ^Q^QQ^Q^QQQQ__`_`_`_)QQQ^QQQ^Q^QQQQQ",
"!!QQQQQ^QQ^QQQQ^^QQQQ^QQ^Q^QQQQQ^Q^QQQQQQWEWQQTQWQQQQQQQ!QQ^QQQQQQQQQQQQQWQWQTQQQQQQQQQQ!^QQQQQQ",
"QQQQQQQ!^QQQQQQ^^Q!^QQQ^QQQQ^QQQQQ^QQQQQQ~QQQQ^QQQQQQQQQQQQQQQQ!^QQ^QQQQQQQQQQQQQQQQQQQQQQQ^^QQQ",
"QQQQ^QQQQQQQQQQQQ!!QQQQQQQQQ~QQQQ!!^!!^!^QQQQQQQQ^QQQQQQQQ~~QQQQQQQ^QQQQQQQQQ^QQQQ~QQQQQQQQQQQQQ",
"QQQQQQQ^^!QQQ^^QQ^QQQQQQ^QQQQWQWWWWWWWWWWWQWRQWQQTQWQRQWEQWWQWTQQWQTWQ!TTQQTQTQWWEQWQWWWQWQWQQQQ",
"Q^QQQ^QQQ^QQQQQQQQQQ^!^QQQQ^````````````````````````````)```````````````````````````````````QQQQ",
"QQQQQQ^QQQQQQQQQQQQQQQQQQ!^T5566666666666665565666666566566666666656666666666666565666666658R^QQ",
"QQQQ^!QQ^QQ^QQQQQQQQ^QQ^QQ`3su@@@@@@@u@@@@@iau@@@@@@@@@@@@@@u@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@pRQQQ",
"^Q^QQ!QQ^QQQQ^QQQQ^Q^QQQQR`6ueDmmmmmmmmmmmSO wSmmmmmmmmmmmZnwAmmmmmmmmmmZmmmmmmmmmmmZmmmmZmZQ!QQ",
"QQQQQQQQ!QQQQ!QQ^QQQ!QQQQT`6@D'__________)'3 H'___________'(H')_____________________________QQQQ",
"Q^^QQQQQQQQQ^!QQQQQ^QQQQQQ`6@m_TWQQWQQWQQW_> N)TQQWQQWQWQQQYN/TQQWQQWQQWQWQQQWQQWQQWQWQQQWQWQQQ^",
"^QQQQQQQQQQQ~QQQ!!Q^QQ^QQQ`6@m_QQQQQ^QQQ~W_> N_WQQQQQQ^^Q!^TN/Q^QQQQQ^QQ^^QQQQQQQQQ!QQQQQ^QQQ!QQ",
"QQ^Q^QQ^QQQQQQQQQ^QQ^QQQQW`6@m_W^QQQQQ^Q~T'< D)QQQQQQQQQQ!^TN/QQQQQ^QQQQQQQ^^Q!QQQQ^QQ^QQQQ^QQ^Q",
"Q^^QQQQQQQQQQQQQQQ^QQQQQQW`5@m_QQQQQQ^QQQE'> F`QQQ^QQQQ!QQQTN/!QQQ^Q^!QQQQQ!^QQQQQ^Q^QQQQQ!QQQQQ",
"QQQQQQQQQQQ/QQQQQQQQQ^QQQQ`6@m_QQQQ^QQQ^QQ`> V`Q^QQQQQQ^QQ^TN/QQ!QQQQQQQQQQQQQ^Q^QQQQQ^QQQQQQQQ^",
"^QQQQQQQQW`l4`Q~QQQQQQQQQT`6@m_WQQ^Q^^!!~W_< V`TQQ^!QQQQQQ^TN/Q^QQQ^QQQQQQQQQQQQQQQQQQQQQQ^^^QQQ",
"!QQQQQQ~Q(MX<_EWQQQQQQQQQQ`6@m_Q^QQQQQQQQW_< D_QQQQQQQ^QQ!^TN/QQQQQQQQQ!Q^QQQQQQQQQQ!QQQ^QQQQQ^Q",
"^QQQQQQQ_x>N3'^(/^^/QQQQQT`6@m_QQQQQQQQQQW'< D`!^^QQQQQQQQ/TN/QQ!QQQ^QQQQQ^!^^QQ^QQ!Q^QQQQQQQ^QQ",
"QQQQQQW_x:LF>TPPPPYPQQQQQQ`6@m_WQ^QQQQQQQE`< V_TQQQ^QQ^QQQ^TN/QQQQ^^QQ^Q^QQQQQQ!^QQ^QQQ^QQQ!QQQQ",
"Q^QQQQ)x:KKJ:=::::>o2_QQQQ`6@m_QQQ^!Q^QQ^R`> N_QQ^^QQ^QQQQ^TN(QQQQQQQQQQQQQQQQQQQQQQQQQQQQ^QQ^QQ",
"Q!QQQ)x:JKKKLLLLLLPH2_WQQQ`5@m_W^QQQQQQQQQ'> F`QQQQQQQQQQQ^TN^TWWQQWWQWQQWQWQQQQQ!QQ!QQQ^QQQQ^Q!",
"QQQQ_x:JKJKJJJJJJJKN2`QQQT`6@m_QQQQQQQQQQR'> N_W^!Q^QQ^QQQ^TG')(_((_((_(((__(QQQ^QQQQQ^QQQ^QQQQQ",
"QQ!^x>JKJKJKJJJJKJKF2_WQQQ`6@m_QQQQQQQQQQQ'> N`QQ!QQ^QQQQQ^Rt9qq000000q000q1k/Q!QQ^Q^QQQQQ!QQ^QQ",
"QQQQ+xLJJJJJJKKJKKKF2`QQQQ`6@m)Q^QQQQQQQQQ'> D_QQQQQQQQQQ!^T*g;;;;;;;;;;;;;jhv`WQ^QQ^QQ^QQQQQQQQ",
"QQQQL:MLJJJKJJJJJKKF2_WQQQ`5@m_W^QQQQ^QQ^T`> V`TQQQQQQQQ!!^QzBvBBBBvvvvBBvC=gv`QQQ^Q^QQQ^Q!QQQQ!",
"QQQQ(L=MLJKJKLKKKKLF2_QQQT`6@m_QQ^!QQQQ!QQ_> V`QQQQQQQQQQQ^TF'_`_'```'''``'e;v`W!QQQQQQQQ^QQQQQQ",
"QQQQQ(L+MLJKJVDFFFFx2`T!QQ`6@m_QQQQQQ^^!QQ_> D'Q^QQQQQQQQQ^TN/TQWQWQWQWWQT(q;B'WQQQQQ!QQQQQ^^Q^Q",
"QQQQQQ/K:MLHX422<22:l)QQQT`6@m_WQQQ^Q!^QQW`< N_WQQ^QQQQQQQ^TN/Q^^QQQQQQQQW(0;v`QQQQQ^QQQ^Q^QQQQQ",
"QQQQQQQ)L:NH2')___`')!QQQQ`6@Z_Q!^QQQQQQQE'> F_QQQ^QQQ^QQQQTN/!^QQ!QQQQ!QQ_0;B_QQQQQQQQQQQQQ^Q^^",
"QQQQQQQW/L:y4)TQQWQRWQQQQT`6@Z_WQQ^QQQQ^QW_< F`W!^QQQQ^QQ!QTN/QQQ^QQQQQQQQ(q;B`!^QQ!Q^QQQ^QQQQQQ",
"^QQQQQQQQ)LX>'WQQQQQQQQQQQ`6@Z_QQQQQQQQ^~W'> N)WQQQ^QQ!Q^!^TN^QQQ^QQQ^^QQQ(0;B`W^QQ^QQ!QQQQQQ!QQ",
"QQ!QQQ!!QW)Kl/QQQQ^^Q^QQQ!`5@Z_~QQ^QQQQQQW'> N_QQQQ^!Q^QQQ^TN(QQQ!QQQ!^QQW_q;B`QQQQ!Q^QQ!QQQQQ!Q",
"QQ^QQQQ^QQQ/)QQQQQQQQQQQQQ`6@Z_WQQ^QQQQQQW'> N`QQQQ^QQQQQQ^TN/QQQ^QQQQQQQW(0;v`WQ^QQQ^Q^QQQQQ^QQ",
"^^QQQQQQQQQQQQQQQQQ!Q^QQQE`5@m`W!QQQQ!Q^QW_< F`WQQQQQQQ^QQ^TN/QQQQ^QQQQQQQ(0;v`Q^QQQQQQQQQQ^QQ^Q",
"QQQ^QQ^QQQQQQQQQQQQ^QQQQQW`5@Z_QQQQ^Q^QQQQ_> F)TQQ^QQQQQQQ^TN/QQ^QQQQQQQ^W(q;v_QQQQQQQQQ!^QQ^QQQ",
"QQ!^QQ!QQQ^QQ^QQQ^!QQQ^!QQ`6@m_RQQ!QQQQQQQ_> F`EQQQQQQQQQQ^TN(QQ!QQQQQ!QQQ(0;B`WQ^QQQQQQQQQQQQQQ",
"QQQQQQQQQQQQQQQ^Q^QQQQQQ!W`6@Z_QQQQQQQQQQR`> N_QQQQQQQQQQQ/TN/QQQ^QQQQQQ!R_0;B`Q!!QQQQQQ!QQQQQQQ",
"QQ^QQQQ^QQQQQQQ^QQQQQ^QQQT`6@Z'!^^^^^^^^^!'> F'Q^^^^^^^^^^/TN/QQ^^^^^^^^QQ_q;V'^QQ^^^^^^^/^^QQQQ",
"QQQQ^QQ^QQQQQ^QQ^QQQQQQ^QQ`6@n/YTTTTTTTTTY/> M^YTTTTTTTTTTTPNQYTTTTTTTTTTY!9gc/YTTTTTTTTTTTTQQQQ",
"QQ^QQQ^QQQQQ^QQQQQ!QQQQQQT`6uwHNNNNNNNNNNNDxrFNNNNNNNNNNNNNMlNNNNNNNNNNNNNG-h7HNNNNNNNNNNNNFQQQQ",
"^Q^QQQQQQQQQ!QQQ^QQQQQQQQQ`6@A'/////(//////(_////(/////()/)WN_//////)////^'0;V'/(///(///////QQQQ",
"QQ!QQQQ^Q^^!QQQQ^QQQ^QQQQW`6@m_TQQQ!QQQQQQWQQQQQQQQQQQWQQEQTN/QQQQEQQQ!QQT_0;v`WQQQQQQQQQQQQQQQQ",
"QQQQQ!QQQQQQ^Q^QQQ^^QQQQQQ`6@Z_QQQQQQQQQQQQQQQQQQQQQQQ~Q~W^TN/QQ~~WQQQQ^QQ(0;B`WQQQQQQQQQQQQQQQQ",
"QQQQQQQ^QQQQQQQQQQQQ^QQQ!W`6um_QQQQQQQQQQQQQQ~QQQ^!Q~QQQQQQTN/QQQQQQQQQQQQ(0;B`!QQQQQ^QQQQQQ!QQQ",
"^QQQQ^QQQQQQQQQQQQQQQQ^Q^W`6@m)QQ!QQQQ~!QQQQ~~QQQQQQQQ~!Q!^TN/QQQQQ^Q^QQQW(0;v`QQQQQQ^Q!QQ^QQQQQ",
"QQQQQQ^QQQQQ^QQQ!Q^QQQQ!!W`6@m_QQQ~Q^/^^^/^/^/^/^^/^QQQQ^!^TN(QQQQQQQQQ^QQ(0;v`WQQQQQQQQQ^QQQQQ^",
"Q^!QQQQ!QQQ/QQQQQQ^QQQQQQW`6@Z_RQQ^!TUUUYUUUUUUUUUUTQQQQ^Q!TN/QQQQQQQQQQ!Q(0;v'QQQQQQQQQQQQ^^^QQ",
"QQQQQQQQQQ)l2)QQQQQ!QQQQQQ`6@m_QQQ^T.%&&&&&&&&&&&&%.T^QQQQ^TN/QQQQQ!^QQ^QW(0;B`Q^QQQQQQ!QQQQQQQQ",
"QQQQQQQQQ_MX<)EQQQQQQQQ^QW`6@m_WQQ^U&fdffffffffffff&U/Q^QQ^TN/QQQQQQQQQQQW_q;B`W^Q!QQQQ^QQQ!Q!QQ",
"QQQ!QQQQ`x<N4'Q^/^^^QQQQQQ`5@Z_QQQ/U&fdffffdfffdfdf&U^QQQQ^YN/WQQ^QQ^Q^QQQ(0;B'QQQQQQQQQQ^QQ^QQQ",
"QQQQQQQ)x:KF>WPYPYYPW^QQQT`6@Z_W^~^U&ffffffffffffff%U^QQQQ^TN)QQQQ^QQQ^QQQ(0;v`WQ^Q^^Q^QQQ^QQQ^Q",
"QQQQQQ)x:KKJ::::::>o4_QQ^Q`5@m_QQQ^U%fdffffffffffdf&U/Q~QQ^TN)QQ^Q^Q!QQQQE(9;B`Q^QQQQQQ^^QQ^QQQQ",
"QQQQ!)x:JKJJLLLLLLLH<)WQQR`6@m_WQQ^U&ffffffffffffff&IQWQWWQYN/QQQQ!QQQQQQQ)0;B`QQQ^^!^QQ!QQ^Q^Q!",
"QQQQ(x:JKJKJJJJJJJKD2_QQQQ`6@m_Q~Q/U&ffffffffffffff&E'_`'''/N/QQQQQQQ^Q^Q~)0;B_WQ!QQQQQQQQQQ^QQQ",
"QQQ^M>JKJKJKKJJKJJKN2`WQQQ`5@m_Q~~/U&ffffffffffffff$#<<<>><:x)WQ^QQQQ^QQ!W(0;B`!QQQQQQQQQQQQQQQQ",
"QQQQ+xLJJJJKKJKJKJLV<)Q~QQ`6@m_WQQ^U&ffffffffffffff$        r`QQQQ^QQQQQQW(q;B`WQQQQQQ!Q!QQQQQQ^",
"QQQ/L:MLJKJJKJKKJJLF2`EWQW`6@m_QQQ^U&fdffffffffffdf&bFFNFVFMD(QQ^QQQQ^QQ^W(0;B`QQQQ^^QQQQQ^^^QQQ",
"QQQQ/L=MLJJJKKLKKKLF2_WQQW`6@Z_QQQ/U&ffffffffffffff&E'))`_`^M/QQQQQQQQ!Q!W(q;v`WQQQ^^Q^QQQQQQQ!Q",
"QQQQQ(L+MLJKHNFNFDFx<_QQQQ`5@Z_WQ~^U&ffffffffffffff&IQQWQQQYV)QQQ!QQ^QQQ~Q(q;v'Q!^QQQQQQQQQ^QQQQ",
"QQQQQW)L:MLHX22>222:y)QQQT`5@m_QQQ^U%ffffffffffffff&U/QQQQQTN/QQQQQQQQQ!QW(0;B'WQQQQQ^QQQQQQQQ^Q",
"QQQQQQW(L+NH3')`___')QQQQQ`6@Z_WQQ^U&fdfdfdffffdfdf&UQQQQQ^TN/!QQ!Q^QQQQQQ_0;B`WQQQQQQQ^Q^^Q^Q!Q",
"Q^QQQQQQ)L>y4)TQQQQW!QQ^QR`6@m_QQQ/U&ffffffffffffff&U/QQQQ^TN/QQQQQQQQ^QQW_0;v`!^Q^QQQQQQQQQQQQQ",
"QQQQQQQQT)LX>`QQQQQQQQQQQQ`6@Z_W^Q^T.%&&&&&&&&&%&&%.T/QQQQQTN)QQQQ^QQ^QQQ!(0;v`QQQ^QQQ!Q!QQQQQQQ",
"QQ^QQ^QQQQ)Kz)W^QQQQQQ^QQW`6@m_QQQQQTUUUUUIUUUUUUUUTQQQQQQ^TN/QQ^^QQQQQ^QQ(0;v`WQ!QQ!QQ^QQQ^^^QQ",
"QQ^QQQQQQQQ^/QQQQQQQQ^QQQQ`6@Z_W^Q~Q^^/Q^///~/^^^^^^QQQQQQ^TN/QQQQ^QQQQQQW(0;v'QQQ^QQQQ^Q!QQQQQ^",
"Q^QQQQQQQQQQ!QQQQQQQQQQQQQ`5@m_Q^QQQQQQQ~QQQ~QQQQQ^!!QQQQ!^TN/QQQQQQ!QQQQW_0;v'WQQQQQQQQQQ^QQQQ!",
"QQQ^QQQQQQQQQQQQQQQQQQ^QQW`6@Z_WQQQQQQQQ^!QQ~Q~QQQQQ^QQQQ^^TN^QQQQQ!QQ^^QQ(0;B`WQQQ^QQ^QQQQQQQQQ",
"^!Q^Q!!Q^!QQQQQQQQQ!QQQQQQ`6@m_QQQQQQQQQQQQQQQQQQQQQQQQQQQ^TN(QQQQQQQQQ^QW(0;B'Q^QQQQQQQQ^QQQ^QQ",
"QQQ^Q^QQQQQQQQ!^QQQ^QQQQQT`6@m_WQ!QQ^QQQQQQQ^QQQQQQQQQQ^QQ^TN/QQQ^Q!QQQQQW_q;v`WQQQQQ^QQQQQQQQQ^",
"QQQQQQQQQ^QQQQQQQQQQQQ^!^R`6@Z_QQ^Q^QQQ!QQ^!QQQQ^^Q!!!Q^QQ^TN)QQQQQQ!Q^QQQ_0;B`!QQ!Q^QQQ^^QQQQQ^",
"QQQQQQQQQ^Q^Q^^QQQ^QQ^QQQQ`8uZ_WQ^QQQ^^!Q^QQ^Q!^QQQ^Q^QQQQ^TN/QQQ^^QQQ^QQQ(e;B`QQ^QQ^QQ!QQQ!Q!QQ",
"Q!QQQQQQQQQQ!^^Q^^QQQQ^^QQQRTQQQQQQQQQQQQQ^!QQ^Q^QQQQQQQQQQQQQQQQ^^QQQQQQQQWW!QQQQ!QQQQQ^QQQQQQ^",
"Q!^^QQQ^QQ^Q!QQQQQ^Q^QQQQQQQ^^QQQQQQQ^QQ^QQ!^QQQQQ^^QQQQQQQQQQQQQQQQQQ^QQQQQQQQQ^QQQ^Q^QQQ^QQQQQ",
"QQQQQ^QQQQQQQQ^QQQ!QQQQQ^QQQQQQQ!Q^Q^QQQQQQQQQQQQQQQQQQQQQQQQQQQ^QQQQ!QQQQQQQQQQQ^QQQQQ!QQQQQQ^Q",
"QQQ^QQQ^QQQQQQQQQQQQ^QQQQQQQQQQQ^QQQ^QQQQQQQQQQQ!^^QQQQQQQQQQQQQ!QQQQQQ^QQQQQQQ^QQQQQQQQQ^QQ!Q^Q"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"48 48 98 2 ",
"   c #3B1515",
".  c #323232",
"X  c #353A3A",
"o  c #742121",
"O  c #0B6F6F",
"+  c #267272",
"@  c #337D7D",
"#  c #397D7D",
"$  c #5A5A47",
"%  c #515151",
"&  c #5C5C5E",
"*  c #7F4F4F",
"=  c #676767",
"-  c gray43",
";  c #747474",
":  c #7D7D7D",
">  c #855252",
",  c #966363",
"<  c #996666",
"1  c #9B6B6B",
"2  c #9F7474",
"3  c #A07575",
"4  c #A37A7A",
"5  c #838370",
"6  c #111195",
"7  c #18189C",
"8  c #1111A9",
"9  c #1717B7",
"0  c #2B2BA6",
"q  c #2B2BAF",
"w  c #2121B5",
"e  c #2323B8",
"r  c #3232B4",
"t  c #474794",
"y  c #7A7AA5",
"u  c #7B7BA8",
"i  c #0000DF",
"p  c #0101ED",
"a  c #0000F2",
"s  c #0202FE",
"d  c #4B8383",
"f  c #578F8F",
"g  c #599090",
"h  c #6D9393",
"j  c #7FA5A5",
"k  c #838384",
"l  c #8C8C8C",
"z  c #949494",
"x  c #9C9C9C",
"c  c #AD8282",
"v  c #8282A4",
"b  c #8A8AA5",
"n  c #8484A9",
"m  c #8A8AAB",
"M  c #9B9BAD",
"N  c #80A6A6",
"B  c #8FA1A1",
"V  c #83A8A8",
"C  c #99B4B4",
"Z  c #A3A3A3",
"A  c #ACACAC",
"S  c #B6B6B6",
"D  c #B4BDBD",
"F  c #BBBBBB",
"G  c #BBBBC1",
"H  c #B7C5C5",
"J  c #B9C6C6",
"K  c #BFC8C8",
"L  c #C3C3C3",
"P  c #C0C9C9",
"I  c #CBCBCB",
"U  c #D5CBCB",
"Y  c #CBD6D6",
"T  c #D6D5D5",
"R  c #DDDCDC",
"E  c #E1DEDE",
"W  c #E6E6D2",
"Q  c #E5E5DC",
"!  c #EAEADF",
"~  c #DEE0E0",
"^  c #E5E5E5",
"/  c #EBE5E5",
"(  c #E9E8E6",
")  c #E6E6EB",
"_  c #E7E8E8",
"`  c #EBEAEA",
"'  c #F2EDED",
"]  c #FBEFEF",
"[  c #F5F4EB",
"{  c #FFFFED",
"}  c #EDF7F7",
"|  c #ECF7F9",
" . c #EFF9F9",
".. c #F1F1F1",
"X. c #FAF0F0",
"o. c #F7F7FC",
"O. c #F0FBFB",
"+. c #FBFEFE",
/* pixels */
"^ ^ _ ^ ^ ^ _ ^ _ ^ ^ ^ ^ _ _ ^ ^ ^ ^ ^ ^ ^ _ ^ ^ ( ^ ^ _ ^ ^ _ ^ ^ ^ _ ^ ^ ^ ^ ^ ^ _ ^ ^ _ ^ _ ",
"^ ^ ^ ^ ^ ( ^ ^ / ^ _ ^ ^ ^ / ^ ^ _ ^ ^ ^ ^ ^ ^ ^ ^ ^ _ ^ ^ ^ ^ _ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ",
"^ ( ^ ^ ^ ^ _ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ _ ^ ^ _ ^ ^ ^ ^ ^ ^ _ ^ _ ^ ^ ^ ^ _ ^ ^ ^ ^ ( _ ^ ^ _ _ ^ ",
"_ ^ ^ _ ( _ ^ ^ _ ^ ^ _ _ ^ ^ _ ^ ^ ^ ^ ^ _ R / ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ _ Q ^ _ ^ ^ ^ ^ ^ ^ ^ ^ ^ ",
"^ ^ ^ ^ ^ ^ ^ ^ ^ ^ _ ^ ^ ^ ^ ^ ^ _ ^ ^ ..Z ; I ' ^ ^ ^ ^ _ ^ ^ _ ^ _ R 2 l _ _ ^ ^ ^ ^ ^ ^ _ ^ ",
"^ _ ^ _ ^ _ ^ _ ^ _ ^ ^ ( ^ _ ^ ^ ^ ^ ..Z l F : L ' ^ _ ^ ^ ^ ^ ^ ` R k C Z l ^ _ ^ ^ ^ ^ ( ^ ^ ",
"( ^ ^ ^ ^ ^ ^ ( ^ ^ ^ ^ ^ ^ ^ _ ^ ^ ` A z F F F l I / ^ _ ^ ^ ^ _ ~ l A D F Z z _ _ ^ ^ ^ ^ ^ ^ ",
"^ ^ ^ _ ^ ^ _ ^ ^ _ ^ ^ _ ^ ^ ^ ^ ' S & x F S S k = R _ ^ ^ ^ ^ ` : ; A S F A = z ` ^ ^ _ ^ ^ _ ",
"_ ^ _ ^ ^ _ ^ _ ^ _ ^ ^ _ ^ ^ _ ^ ^ R R l S F x M ^ R ^ ^ ^ ^ ^ ^ ^ S l G F k I E ^ ^ ^ ^ _ ^ ^ ",
"^ ^ ^ ^ ^ ^ ^ / ^ ^ ^ ^ ^ ^ ^ ^ ( ^ _ ` z S L Z A [ ^ ^ ^ _ ^ ^ ^ ..I z L L z T ' ^ ^ ^ ^ / ^ _ ",
"^ _ _ ^ ^ _ ^ ^ ^ ^ _ ^ _ ^ _ ^ ^ ^ ^ _ l Z S z A ..^ ^ ^ ^ ^ _ ^ ` L l S A l T _ ^ ^ ^ ^ _ ^ ^ ",
"^ ^ ^ ^ ^ ^ _ ^ ^ _ ^ ^ ^ ^ ^ ^ ^ ^ ^ ' Z l x l L ` ^ ^ ^ ( ^ ^ _ ` T l z z z ^ _ ^ _ ^ ^ ^ ^ ^ ",
"^ _ _ ^ ^ ^ _ ^ / _ ^ ^ ^ ^ ^ ^ ^ ^ E ^ ` ` / ` / ^ E ^ ^ ^ ^ E ~ E ^ ` ` / ` E E ^ E ^ ^ ^ ^ ^ ",
"^ ^ ^ ^ ^ _ ^ ^ ^ ^ _ ^ ^ ^ `  .O.O.O.}  .O.}  .} O.O.O. .O.O. .O.O.o. .O.O.O.O.O.O.O.O.^ ^ ^ ^ ",
"^ ^ / ^ ^ ^ ^ _ _ ^ _ ^ ^ ` T 4 2 3 2 3 3 3 c 2 2 2 3 2 2 3 3 2 3 2 2 2 3 2 3 2 3 3 2 3 E ^ ^ ^ ",
"_ ^ _ ^ ^ _ ^ / ^ ^ ^ ^ / ..4 o 1 , , , < *   < , , , , , > , , , , , , , , , , , , , < E _ ^ _ ",
"^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ( ^ O.2 1 +.} O. .+.P X +.O.O.O. .O.Y } O.O.O.O.O.O.O.O.O.O.O.O.O._ ^ ^ ^ ",
"_ ^ _ ^ ^ ^ ^ ' ^ ^ ^ ^ ~ O.3 , } E ^ E ' S . ` E ^ ~ Q _ L E ^ E ~ ^ ^ E ^ ^ E ^ E E ^ ^ ^ ^ ^ ",
"^ ( ^ ^ ^ ^ ` S R _ ^ ^ ^ ..2 , O.E ^ ^ ..S . ` ^ ^ ^ ^ _ L ~ ( ^ ^ ^ ^ ( ^ ^ ^ ^ _ ( ( / _ _ ^ ",
"^ ^ ^ ^ ^ ` A = ~ ` _ _ ^ O.3 , O.^ ^ ^ ..S . ..^ ^ ^ ^ _ L ~ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ",
"^ ^ ^ ^ ..Z z x k z k Z ` O.2 , O.^ ^ ^ ` S . ` Q ^ ^ ^ _ I / ' ' ' ` ' ` ^ ^ ^ ^ _ ^ ^ ^ _ _ ^ ",
"^ ^ ^ _ Z l G F S S A x ` } 2 , O.E ^ ^ ..S . ..^ ^ ^ ^ / F G J J J J H K ^ ^ ^ ^ ^ _ ^ ^ ^ ^ ^ ",
"^ ^ _ R ; F S F F L S x ` O.2 , O.^ ^ ^ ..S . ` ^ ^ ^ ^ ` M + @ # @ @ # O C ..^ ^ ^ ^ ^ ^ ^ ^ ^ ",
"^ ( ^ ` I k S S x x z l `  .2 , O.^ ^ ^ ' S . ..~ ^ ^ ^ ( L / _ / / / X.g j X.^ _ ^ ( ^ _ ^ ^ _ ",
"^ ^ ^ ^ ` L l k x S Z L ^ O.2 ,  .^ ^ ^ ..S . ' ^ ^ _ ^ _ L ~ _ ^ ^ ~ X.g j X.~ ^ _ ^ _ ^ ^ ^ ^ ",
"^ ^ ^ ^ ^ ..I = ^ ....' E O.3 ,  .~ ^ ^ ..S . ' ^ ^ ^ ^ _ L Q ^ ^ ^ ~ X.g j X.^ ^ ^ ^ ^ ^ _ ^ _ ",
"( ^ ^ ^ ^ ^ ` R ~ ^ ~ ^ E O.2 , O.^ ^ ^ ..S . ..^ ^ ^ ^ ( L ~ _ ^ ^ ^ ] g j X.~ ^ _ ^ ^ _ ^ ^ ^ ",
"^ _ ^ _ ^ ^ ^ _ _ ^ ^ _ ^ o.2 , O.~ ^ ^ ..S . ` ^ ^ ^ ~ ( J ^ ^ ^ ^ ^ ] g j X.^ ^ ^ ^ ^ ^ ^ ^ ^ ",
"^ ^ ( ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ O.2 , o.^ _ _ ..F . .._ _ _ _ / I ^ _ _ _ ^ X.g V X.( / _ / _ _ ^ ^ ^ ",
"^ _ ^ ^ ^ ^ ^ ^ ( ^ ^ ^ ~ O.3 > Y L L L I A = I L L L L L A G L L L L U d h U G L L G I E ^ ^ _ ",
"^ _ ^ _ ^ ^ ^ ^ ^ ^ ^ ^ E O.3 , } E ~ ~ ~ ^ ` ^ ~ E Q ~ ^ G E ^ ^ R R ] g N ' E ~ ~ ^ ^ ^ _ ^ ^ ",
"^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ( ^ ^ O.2 , O./ _ ) ) ) ^ ) ) ) ( ( _ L ^ ^ ^ _ ^ X.g N X.^ ( ( ^ ^ ^ ^ ^ ^ ",
"( ^ ^ ^ ^ ^ _ ` ^ ^ ^ ^ ^ O.3 ,  .^ ^ W W W W W W Q ^ ^ _ L ^ ^ ^ ^ ^ ] g N X.~ ^ ^ ^ ^ ^ ( ^ _ ",
"^ _ ^ ^ ^ ` R : ^ ' ` _ ~ O.3 , } ' b 8 e 9 w q 9 t ! ^ _ L R ^ ^ ^ ^ ] g N ] ^ ^ ^ ^ ^ ^ ^ ^ ^ ",
"^ ^ ^ ^ ` R l ; F I L T ^ O.3 , | [ u a s s s s s q W ~ ^ L ^ ^ ^ ^ ~ X.f N ' ^ ^ _ ^ _ ^ _ ^ _ ",
"_ ^ ^ _ E k A A k z l l / } 2 , } [ u p s s s a s r { o.+.U R _ ^ ^ ^ X.f j ] ^ ^ ^ ^ ^ ^ ^ ^ ^ ",
"^ ^ _ ~ : A F F F G S z ` O.3 , } [ y a s s s s s 6 $ $ % ; _ ^ ^ ^ ^ ] f j ] ^ ^ ^ ^ _ ( _ ^ ^ ",
"^ ^ ^ ^ z x F F F F S x / O.3 , } [ y a s s s s s 7 5 y : z _ ^ ^ ^ ^ X.g N ..~ _ ^ ( ^ ^ ^ _ ^ ",
"^ ^ ^ _ ` l Z Z l l k z ` } 2 , o.' h p s s s s s r { o.+.I Q ^ ^ ^ ^ X.f j X.^ ^ ^ ^ ^ ^ ^ ^ ^ ",
"( ^ ^ ^ _ _ z - U R T ~ ^ O.2 , O.] u p p p p p a 0 Q ^ Q L ^ ^ ^ ^ ~ X.g N X.^ _ ^ _ ^ ^ _ ^ ( ",
"_ ^ ^ ^ ^ _ _ z ^ _ _ ^ ^ O.2 ,  ._ G v m m m m n M ( ^ _ L ~ _ ^ ^ ^ ] f N ..^ ^ ^ ^ ^ _ ^ ^ _ ",
"^ ^ ^ ^ ^ ^ ^ ' ^ ^ ^ ^ ^  .3 , O.~ ' X.[ X.[ X.[ [ ^ ^ / L E _ ^ ^ ^ ] g N X.~ ^ ^ ^ _ ^ ^ ^ ^ ",
"^ ^ ^ _ ^ ^ ^ ^ ^ ^ ^ ^ ^ O.2 , O.^ ^ ^ ~ ^ ~ ~ ^ ~ ^ ^ ` L ^ ^ ^ ^ ^ ] g N X.^ _ ^ _ ^ ^ _ ^ _ ",
"^ _ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ O.3 < ..^ ^ ^ _ _ _ _ _ ^ _ ( ) L E ^ ^ ^ ^ ] g V ' ^ ^ ^ ^ ^ ^ / ^ ^ ",
"^ ^ ^ ^ ^ ^ _ ^ ^ ^ ^ ( ^ ^ R T / _ ^ ^ ^ ^ ^ ^ ^ _ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ R ~ _ ^ ( ^ _ ^ ^ ^ ^ _ ",
"^ _ ^ _ ^ _ ^ ^ ^ _ ^ ^ ^ ^ ( _ ^ ^ _ ^ _ ^ _ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ / / ^ _ ^ ^ ^ ^ _ ^ ^ ^ ",
"^ ^ ^ ^ ^ ^ ^ ^ _ ^ ^ _ ^ ^ ( ^ ^ ^ ^ ^ ^ ^ ^ _ _ ^ ^ ^ _ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ _ ^ / ^ ^ ^ ",
"_ ^ _ ^ ^ _ ^ ( ^ ^ ^ ^ ^ ( ^ ^ ^ _ ^ ^ _ ^ ^ ^ ^ ^ ^ _ / ^ ^ ^ _ ^ _ ^ ^ _ ^ ^ ^ _ ^ ^ _ ^ ^ _ "
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"32 32 89 1 ",
"  c #5E5E7A",
". c #666161",
"X c #727272",
"o c #757878",
"O c #8F5C5C",
"+ c #925C5C",
"@ c #966363",
"# c #986666",
"$ c #6F6F8A",
"% c #7F7F81",
"& c #5454B4",
"* c #5555BE",
"= c #5C5CBD",
"- c #6868B5",
"; c #6D6DBD",
": c #7373B1",
"> c #2828C6",
", c #2A2AC8",
"< c #0000EB",
"1 c #0000F1",
"2 c #0202FE",
"3 c #5C5CC0",
"4 c #6E9696",
"5 c #6D9E9E",
"6 c #729E9E",
"7 c #799F9F",
"8 c #73A0A0",
"9 c #7BA1A1",
"0 c #828282",
"q c #8A8A83",
"w c #8C8C8C",
"e c #949494",
"r c #9C9393",
"t c #9C9C9C",
"y c #B89A9A",
"u c #A3A39D",
"i c #8383B4",
"p c #83A8A8",
"a c #8FABAB",
"s c #91ADAD",
"d c #9AB6B6",
"f c #9CB8B8",
"g c #A5A5A5",
"h c #ACACAC",
"j c #B9A3A3",
"k c #A5B7B7",
"l c #A4BCBC",
"z c #B4B4B4",
"x c #BBB5B5",
"c c #BBBBBB",
"v c #C2B6B7",
"b c #CABFBF",
"n c #AFAFCB",
"m c #BCBCC6",
"M c #B0B0CC",
"N c #ADC2C2",
"B c #BAC9C9",
"V c gray77",
"C c #CEC2C3",
"Z c #C1C1CA",
"A c #CCCBCB",
"S c #D2C6C6",
"D c #D3CBCB",
"F c #DACDCD",
"G c #C3D0D0",
"H c #D4D4D4",
"J c #DBD5D5",
"K c #D5D5D8",
"L c #DADADA",
"P c #E5DEDE",
"I c #DFDFE1",
"U c #DDE0E0",
"Y c #E5E5E5",
"T c #E8E5E5",
"R c #E6E9E9",
"E c #EBEBEB",
"W c #F6EFEF",
"Q c #F8EFEF",
"! c #EEF1E0",
"~ c #EDF0EA",
"^ c #F6F6E7",
"/ c #F9F9E7",
"( c #F4F3EA",
") c #F9F9E8",
"_ c #ECF3F3",
"` c #F4F4F4",
"' c #F9F2F2",
"] c #F4FBFB",
"[ c #FCFDFD",
/* pixels */
"YYTYYYYTYTRYYYRRYTYYYYYYTRYYYYYY",
"YYRYRTYRYTYYYRLYRYTYYYYTYIEYTYYT",
"RYRYTYYYYRTTELwgERYYYYRRteLRYYYR",
"TYTYRYTRYYYRHrcggYYYYYYthztLRYYT",
"TYTYYTRYRYYReeVz0cEYYEz0ccqgEYYY",
"YYRYYYTYYYYYEgcgVEYYYY~xhzhWYYYT",
"RYYRRTRYYYYYEtgecEYYYYEzttgEYYYY",
"TYTYYYYYYPYYTAzzJYYYYPTHzzATYYYR",
"RTYRYYYYY~___`]]________]]`___RY",
"YYTYYYRYEy+#@@+@@@@@@@@@@@@@@#JR",
"YYYYYYYY_@jDCJ.rFCSxvSCCCCCCCCYY",
"YTYRTYYY_#D_R[oz]R`LU_ER_EE_EEYY",
"RYEHe_RT_@CEU]Xh`PYHHYYYYYYYYYYY",
"YRLeegtA]@CEY]Xh`YRHT'WWWTYYYRYY",
"TLexccgc]@CEL`Xh`UED49665GEYRYTY",
"TYggzgex]@CEY`Xh`YEHkNlB6pWYYTYR",
"YTRg0mcJ_@C_I]Xh`YRHYQE'lpQYYYYY",
"YTRYcWET_@CEP`Xh~YYHHRYWdpWYYYYY",
"YYYYEYIT_@SEY]Xz`YELLEY'dp'YRRRY",
"RYYYYYYY_@vLHYXgUHLCAHHPs7PHJHYY",
"TYYYYYYY_@vUKKKKKLLAALHTs9THLLYY",
"YYYREYYI_@S_((^))RELLEYQdp'YRRYY",
"TYRYz_WR_@S!:3-3&mEALRYWdpQYYYYT",
"YRTt0zhH_@C!>222<M[YLRYWdp`YYTYY",
"TYthzhtx]@C!,222<$grJRUQdpQYYYYR",
"RLezcztc]@C!,2221 qoLRYQdp'UYYYY",
"YRPtqhgA_@S!>222<M[YKRUQdpQYRYYR",
"TYELg_(R_@CEi;;;-ZRHLRYWdpQYTYTY",
"YRYTEYYI_@C_(^^^)YRHJRYWdp(YYYTY",
"YYYYIYYY_#CEIIYYYYRHLRYWdpQYYRRY",
"TYRYYYYYRJIYRYTYYYTYYYYYIITYYTTY",
"YRYYTRYTYETYRYYYRTYYYYYYRRYRYYRY"
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"16 16 139 2 ",
"   c #E6E6E6",
".  c gray90",
"X  c #E9E9E9",
"o  c gray88",
"O  c #EAEAEA",
"+  c gray91",
"@  c gray78",
"#  c gray66",
"$  c #D0D0D0",
"%  c #CECECE",
"&  c #A7A7A7",
"*  c #CACACA",
"=  c #E5E4E4",
"-  c #E6E5E5",
";  c #B0AFAF",
":  c #A2A1A1",
">  c #B9B8B8",
",  c #E8E7E7",
"<  c #E7E7E7",
"1  c #B6B5B5",
"2  c #B2B1B1",
"3  c #E7E8E8",
"4  c #F1F5F5",
"5  c #DADEDE",
"6  c #B2B6B6",
"7  c #E3E7E7",
"8  c #EEF2F2",
"9  c #EFF3F3",
"0  c #E1E5E5",
"q  c #B0B4B4",
"w  c #DDE1E1",
"e  c #E5E6E6",
"r  c #DAD2D2",
"t  c #BFA7A7",
"y  c #C2ADAD",
"u  c #C0ABAB",
"i  c #C1ABAB",
"p  c #C2ACAC",
"a  c #C5AFAF",
"s  c #C3AFAF",
"d  c #E2E0E0",
"f  c #BFAAAA",
"g  c #D0C8C8",
"h  c #8F8787",
"j  c #D7CCCC",
"k  c #CABFBF",
"l  c #CDC2C2",
"z  c #D5CACA",
"x  c #D1C6C6",
"c  c #D2C6C6",
"v  c #D4C9C9",
"b  c #E4E2E2",
"n  c #C3AEAE",
"m  c #D8D0D0",
"M  c #E8EDED",
"N  c #A0A2A2",
"B  c #F0F3F3",
"V  c #E1E3E3",
"C  c #DDE2E2",
"Z  c #E4EAEA",
"A  c #EBEDED",
"S  c #EAECEC",
"D  c #C4AFAF",
"F  c #D2C7C7",
"G  c #E3E5E5",
"H  c gray61",
"J  c gray92",
"K  c #D7D8D8",
"L  c #9CB4B4",
"P  c #99B6B6",
"I  c #97B4B4",
"U  c #E8E6E6",
"Y  c #E4E4E4",
"T  c #E5E8E8",
"R  c #9E9D9D",
"E  c gray93",
"W  c #DFDEDE",
"Q  c #E3E2E2",
"!  c #EEECEC",
"~  c #9FBABA",
"^  c #E4E5E5",
"/  c #CDC1C1",
"(  c #DBDEE0",
")  c #9B9B9E",
"_  c #E2E2E4",
"`  c #D5D5D5",
"'  c gray84",
"]  c #DFDFDF",
"[  c #98B3B3",
"{  c #DBDCDC",
"}  c #CCC1C1",
"|  c #E8EBE0",
" . c #E2E2D2",
".. c #E4E4DD",
"X. c #D6D6D7",
"o. c #D8D8D8",
"O. c #E1E0E0",
"+. c gainsboro",
"@. c #E0DFDF",
"#. c #E0E4E5",
"$. c #D0C4C1",
"%. c #5255DB",
"&. c #2423E4",
"*. c #7979D3",
"=. c #ECECDF",
"-. c #DDDDE0",
";. c #EAE9E9",
":. c #9EB9B9",
">. c #B1B5B5",
",. c #C6B1B2",
"<. c #CCC1BB",
"1. c #2225EC",
"2. c blue",
"3. c #3A3ABF",
"4. c #A7A794",
"5. c #D9D9DE",
"6. c #E9E8E8",
"7. c #9CB8B8",
"8. c #E2E3E3",
"9. c #CEC3BF",
"0. c #5659D8",
"q. c #2929E0",
"w. c #7A7AD0",
"e. c #E6E6DA",
"r. c #DCDCDE",
"t. c #9DB8B8",
"y. c #E3E4E4",
"u. c #D4C9CA",
"i. c #F1F4E8",
"p. c #EEEEDC",
"a. c #EDEDE5",
"s. c #DEDEDF",
"d. c #A1BBBB",
"f. c #E4E4E7",
"g. c #E3E3E7",
"h. c #E4E4E6",
"j. c #E5E5E4",
"k. c #DEE1E1",
"l. c white",
/* pixels */
"        .   X o O . . O o X     ",
"      . . + @ # $ + + % & * + . ",
"    .   = - ; : > , < 1 : 2 < . ",
"  .   . 3 4 5 6 7 8 9 0 q w 9 e ",
". . = 3 r t y u y i i p a p s d ",
"  + - 4 f y g h j k l z x c v b ",
"X @ ; 5 n m M N B V C Z A A S   ",
"o # : 6 D F G H J K L P I U Y . ",
"O $ > 7 p z T R E W Q ! ~ ^ +   ",
". + , 8 i / ( ) _ ` ' ] [ { ] . ",
". + < 9 i } |  ...X.o.O.[ +.@.. ",
"O % 1 #.n $.%.&.*.=.-.;.:.^ +   ",
"o # : >.,.<.1.2.3.4.5.6.7.8.  . ",
"X * 2 w n 9.0.q.w.e.r.+ t.y.  . ",
"  + < B s u.i.p.a.s.] + d.y.  . ",
"  . . e d b f.g.h.j..   k..   . "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
};
const int n_xpm_icons = 4;
