/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXhXfXgXkXlXkXlXlXlXlXlXlXkXlXjXgXgXjXlXkXlXlXlXlXlXlXlXkXlXkXgXgXkXlXkXlXlXlXlXlXkXlXkXgXfXhXkXlXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXCXKXFXxXkXlXkXlXlXlXlXlXlXjXNXJXGXvXkXlXkXlXlXlXlXlXlXlXkXjXDXSXlXkXlXlXlXlXlXlXlXkXxXFXKXVXkXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXxXI.4.l.eXcXkXlXlXlXlXlXkXjXbX}.w.p.4XvXjXlXlXlXlXlXlXkXkXkXbXm.n.jXlXkXlXlXlXlXlXkXxXrXz.7.W.cXkXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXzX1.*.2 U CXhXkXlXlXlXlXkXhXCX%.I i f gXlXkXlXlXlXlXkXlXgXAXS.  h uXxXkXlXlXlXlXlXhXBX{.m W   H.VXhXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXcXyXc.t *.ZXhXkXlXlXlXlXkXlXkXaXUXx.@ aXxXkXlXlXlXlXlXjXmX-X) ;.m xXzXkXlXlXlXlXlXkXzXsXVXNX$ s.SXgXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXnXtX5.y 1.mXjXkXlXlXlXlXlXlXhXSX~.w U.BXhXlXlXlXlXlXkXjXMX/ W { , ^.mXjXlXlXlXlXlXlXjXnXkXI ^ zXzXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXtXW.yXU u lXlXkXlXlXlXlXkXhXNXZ.  -.&XpXzXkXlXlXlXlXkXlXlX4.G r   u.VXhXlXlXlXlXlXjXcXrXk u /.6XlXkXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXtXL i c T.mXjXkXlXlXlXlXkXgXZX/ < h h <XvXjXlXlXlXlXlXkXlXNXUXn.K bXlXkXlXlXlXlXlXhXVX_.% x 6 p.NXjXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXnXlXnXmXkXlXlXlXlXlXlXlXlXkXvXcXkXzXlXkXlXlXlXlXlXkXkXlXhXgXkXzXjXlXkXlXlXlXlXlXlXkXzXbXlXzXzXkXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXlXkXjXlXkXkXlXlXlXlXlXkXlXkXkXlXlXlXkXlXlXlXlXlXlXlXlXkXlXkXkXkXlXlXlXlXlXlXlXkXlXkXkXlXlXlXkXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXkXkXlXlXlXlXlXlXlXlXlXlXkXkXkXkXkXlXlXlXlXlXlXlXlXlXlXlXkXkXkXlXlXlXlXlXlXlXlXlXkXkXkXkXkXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXhXjXlXkXlXlXlXlXlXlXkXlXjXhXhXkXlXkXlXlXlXlXlXlXkXlXkXhXhXkXlXkXlXlXlXlXlXlXkXlXkXhXhXjXkXlXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXzXCXvXkXlXlXlXlXlXlXlXlXkXvXCXVXlXkXlXkXlXlXlXlXlXlXkXzXBXCXcXkXlXlXlXlXlXlXlXlXkXzXBXZXnXkXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdX).7XxXkXlXlXlXlXlXkXkXxX9X).[.gXxXkXlXlXlXlXlXlXkXzXaX X`.rXxXkXlXlXlXlXlXlXkXzXfX XW.<XvXkXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXhXVX..  d.CXhXkXlXlXlXlXkXgXZXo.u , Q zXkXkXlXlXlXlXlXhXMX}.h . I.VXhXlXlXlXlXlXlXjXmX=XD B * W.BXhXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXZXZ.W j d.DXgXlXlXlXlXlXkXkXzX:XDXn.+ uXxXkXlXlXlXlXlXkXjXcX>X7 P.VXhXkXlXlXlXlXlXkXkXlX,XA.$ S.ZXhXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXvX4Xg D.a &.vXkXkXlXlXlXlXlXlXhXSX8Xp 5.NXjXkXlXlXlXlXlXlXhXMX3X3 I.ZXhXlXlXlXlXlXlXlXhXZXI.f w $XnXjXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXMX{.t p O 4 *XmXhXlXlXlXlXkXjXbX@X0 $.lXjXkXkXlXlXlXlXlXkXjXvX=X3 G.NXhXkXlXlXlXlXlXkXzXqXyXjX; ,.CXhXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXyXu r.ZXhXkXlXlXlXlXkXgXSXI   i f ,XbXjXlXlXlXlXlXhXMX Xa o 4 C.NXhXlXlXlXlXlXhXNXY.e a i {.mXjXkXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXzXlX3XyXxXkXlXlXlXlXlXkXkXzX8X>X%X=XfXlXkXlXlXlXlXlXkXzXiX&X>X&XqXxXkXlXlXlXlXlXkXlXgX<X&XiXnXkXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXnXcXkXlXkXlXlXlXlXlXlXkXbXMXMXMXzXkXlXlXlXlXlXlXlXkXxXNXmXNXvXkXlXlXlXlXlXlXlXkXzXmXMXxXjXlXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXjXkXlXkXlXlXlXlXlXlXkXlXjXjXjXjXkXlXkXlXlXlXlXlXkXlXkXjXjXjXkXlXkXlXlXlXlXlXkXlXkXjXjXkXkXlXkXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXkXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXnXMXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXMXxXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzX<X&X-X-X-X-X-X-X-X-X-X-X-X-X-X=X-X-X-X-X-X-X-X-X-X-X-X-X-X=X&X&X&X&X&X&X&X&X&X&X&X&X&X*X*X&X&X&X&X&X&X&X&X&X&X&X*X%XpXzXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX+.Z H F F F F F F F F F F F F H F F F F F F F F F F F F D K R T T T T T T T T T T T R I Y R T T T T T T T T T T W S OXNXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX-.Y %.$.$.$.$.$.$.$.$.$.$.%.+.[ &.$.$.$.$.$.$.$.$.$.$.$.*.W f j j j j j j j j j j j f D c h j j j j j j j j j j j k &XMXjXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXkXkXlXlXlXlXlXlXlXlXkXjXnX*.T d.d.d.d.d.d.d.d.d.d.d.g.t.%.j.s.d.d.d.d.d.d.d.d.d.s.z.R   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXlXlXlXkXlXlXlXlXlXlXlXkXjXnX*.Y u.u.y.y.y.y.y.y.y.y.y.i.0.@.a.y.y.y.y.y.y.y.y.y.y.t.f.T   X . . . . . . . . . X   f =   . . . . . . . . . X   : =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXxXlXlXlXkXlXlXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXnX,Xg h r (.VXhXlXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXMX%X< f.E.pXxXkXlXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXmX=Xd h s }.mXjXkXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXdXgXCXr [ BXjXkXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXNX[.K { # v.BXhXkXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXeXz.7.R.xXlXkXlXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXFXKXVXkXkXlXlXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgXfXhXkXlXkXlXlXlXlXlXlXkXjXnX*.Y u.u.y.u.u.u.u.u.u.u.y.i.0.@.a.y.u.u.u.u.u.u.u.u.u.t.f.T   X . . . . . . . . . X   f =   . . . . . . . . . X   : =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX*.Y s.s.s.s.s.s.s.s.s.s.s.f.r.$.h.a.s.s.s.s.s.s.s.s.s.p.k.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX=.U <.<.<.<.<.<.<.<.<.<.<.1.;.| 2.,.<.<.<.<.<.<.<.<.<.,.4.E w y t t t t t t t t t y w B d r t t t t t t t t t y t p &XMXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX;.G = % % % % % % % % % % # < l + & % % % % % % % % % & $ b 3 2 2 2 2 2 2 2 2 2 2 3 > v q < 2 2 2 2 2 2 2 2 2 3 1 0 *XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX;.F o                       % f   .                       k                       .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgXgXgXjXlXkXlXlXlXlXlXlXkXjXnX;.F O                       & g   .                       k .                     X   d =   .                 .   : =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXxXFXHXJXbXjXlXlXlXlXlXlXlXkXjXnX;.F o                       % f   .                       k                       .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXbX6X) L A |.NXhXlXlXlXlXlXlXkXjXnX;.F o                       % f   .                       k                       .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXMX$X: 9.g.3XbXjXlXlXlXlXlXlXkXjXnX;.F o                       % f   .                       k                       .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXMX%X< v ) 5XvXjXkXlXlXlXlXlXkXjXnX;.F o                       % f   .                       k                       .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXaX:X,X1 +.VXjXkXlXlXlXlXlXkXjXnX;.F o                       % f   .                       k                       .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXmX+X7.V.$ 6.VXhXkXlXlXlXlXlXkXjXnX;.F o                       % f   .                       k                       .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXbX<X[ K 8.sXxXkXlXlXlXlXlXlXkXjXnX;.F o                       % f   .                       k                       .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXvXGXHXAXzXkXlXlXlXlXlXlXlXkXjXnX;.F o                       % f   .                       k                       .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgXgXgXkXlXkXlXlXlXlXlXlXkXjXnX;.F O                       & g   .                       k .                     X   d =   .                 .   : =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX;.F o                       % f   .                       k                       .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX-.H 5 2 2 2 2 2 2 2 2 2 2 < q g   .                       c 4 2 2 2 2 2 2 2 2 2 2 3 > c %                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX-.H i t t t t t t t t t t u 9 8.=X XXXXXXXXXXXXXXXXXXX X&X .8 u t t t t t t t t t y q A {.oX.XXXXXXXXXXXXXXXXX X=Xx.}.BXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX;.F o                     X   n.UXKXUXUXUXUXUXUXUXUXUXLXUX%.  X                   .   z GXUXIXUXUXUXUXUXUXUXUXLXUXXX_.CXhXlXlX",
"lXkXlXkXgXfXjXlXkXlXlXlXlXlXlXkXlXkXhXfXjXlXkXlXlXlXlXlXlXlXkXjXnX;.F O   . . . . . . . . . o   b.UXGXKXKXKXKXKXKXKXKXKXGXUX$.  O . . . . . . . . . o   z SXPXKXKXKXKXKXKXKXKXKXHXUX X`.CXhXlXlX",
"lXlXkXcXFXHXbXkXlXlXlXlXlXlXlXlXkXzXAXJXMXkXlXlXlXlXlXlXlXlXkXjXnX;.F o                     X   n.UXKXUXUXUXUXUXUXUXUXUXLXUX%.  X                   .   z GXUXIXUXUXUXUXUXUXUXUXLXUXXX_.CXhXlXlX",
"lXkXcX9Xk.y.<XvXjXlXlXlXlXlXlXkXzXsXZ.0.|.bXjXlXlXlXlXlXlXlXkXjXnX;.F o                     X   n.UXKXUXUXUXUXUXUXUXUXUXLXUX%.  X                   .   z GXUXIXUXUXUXUXUXUXUXUXLXUXXX_.CXhXlXlX",
"lXjXmXOXJ o K.CXhXlXlXlXlXlXlXjXvX9X| o 3.CXhXlXlXlXlXlXlXlXkXjXnX;.F o                     X   n.UXKXUXUXUXUXUXUXUXUXUXLXUX%.  X                   .   z GXUXIXUXUXUXUXUXUXUXUXLXUXXX_.CXhXlXlX",
"lXlXhXBXwX9 L.VXhXkXlXlXlXlXlXlXkXxXVXn 2.CXhXkXlXlXlXlXlXlXkXjXnX;.F o                     X   n.UXKXUXUXUXUXUXUXUXUXUXLXUX%.  X                   .   z GXUXIXUXUXUXUXUXUXUXUXLXUXXX_.CXhXlXlX",
"lXlXhXMX6X5 W.DXgXlXlXlXlXlXlXlXkXzXbXz 8.JXgXlXlXlXlXlXlXlXkXjXnX;.F o                     X   n.UXKXUXUXUXUXUXUXUXUXUXLXUX%.  X                   .   z GXUXIXUXUXUXUXUXUXUXUXLXUXXX_.CXhXlXlX",
"lXkXlXfXU.: u.pXlXkXlXlXlXlXlXkXlXgX#Xt ] wXkXkXkXlXlXlXlXlXkXjXnX;.F o                     X   n.UXKXUXUXUXUXUXUXUXUXUXLXUX%.  X                   .   z GXUXIXUXUXUXUXUXUXUXUXLXUXXX_.CXhXlXlX",
"lXhXMX|.h w r B.NXhXlXlXlXlXlXjXvX9XG q 9 2.bXjXkXlXlXlXlXlXkXjXnX;.F o                     X   n.UXKXUXUXUXUXUXUXUXUXUXLXUX%.  X                   .   z GXUXIXUXUXUXUXUXUXUXUXLXUXXX_.CXhXlXlX",
"lXkXlXkXlXxXlXkXlXkXlXlXlXlXlXlXlXkXkXxXzXkXlXlXlXlXlXlXlXlXkXjXnX;.F o                     X   n.UXKXUXUXUXUXUXUXUXUXUXLXUX%.  X                   .   z GXUXIXUXUXUXUXUXUXUXUXLXUXXX_.CXhXlXlX",
"lXlXkXlXlXkXlXlXkXlXlXlXlXlXlXlXkXlXlXkXlXlXkXlXlXlXlXlXlXlXkXjXnX;.F o                     X   n.UXJXIXIXIXIXIXIXIXIXIXKXUX%.  X                   .   z GXUXPXIXIXIXIXIXIXIXIXKXUXXX_.CXhXlXlX",
"lXlXlXkXkXkXkXkXlXlXlXlXlXlXlXlXlXkXkXkXkXkXlXlXlXlXlXlXlXlXkXjXnX;.F o                     X   n.UXKXUXUXUXUXUXUXUXUXUXLXUX%.  X                   .   z GXUXIXUXUXUXUXUXUXUXUXLXUXXX_.CXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX;.F o                     .   x.UXZXDXDXDXDXDXDXDXDXDXZXUX$.  & # # # # # # # # # %   v FXUXIXUXUXUXUXUXUXUXUXLXUXXX_.CXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX=.P } { { { { { { { { { { } ' { <.:.:.:.:.:.:.:.:.:.:.:.1.W s h g g g g g g g g g h d S G A S S S S S S S S S S D B $XMXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXnX*.T f.g.f.f.f.f.f.f.f.f.f.h.y.#.d.u.i.i.i.i.i.i.i.i.i.u.h.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXlXjXhXkXlXkXlXlXlXlXlXlXkXjXnX*.Y y.u.y.y.y.y.y.y.y.y.y.i.0.#.s.y.u.u.u.u.u.u.u.u.u.y.f.T   X . . . . . . . . . X   f -   X X X X X X X X X o   > =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXnXCXzXkXlXlXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXbX4X'.sXzXkXlXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXvXeXq $ $XmXhXkXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXmX$.^ p ;XMXhXlXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXCXn.A B.; E.nXjXkXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXkXhXBXq.8 e   I cXkXkXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXmXR.< #XMXjXkXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXxXsX1XgXzXkXlXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXzXnXlXkXlXlXlXlXlXlXlXkXjXnX*.Y i.i.u.i.i.i.i.i.i.i.u.p.q.#.s.u.i.i.i.i.i.i.i.i.i.y.g.T   .                   .   d *                     .   ; =XmXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXjXkXlXkXlXlXlXlXlXlXkXjXnX=.T i.i.i.i.i.i.i.i.i.i.i.a.w.$.d.u.i.i.i.i.i.i.i.i.i.u.g.R   o X X X X X X X X X o   g -   X X X X X X X X X o   > -XmXjXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXmX@.J t.t.t.t.t.t.t.t.t.t.t.u.8.X.p.r.t.t.t.t.t.t.t.t.t.e.s.P   .                   .   p &                     .   = &XMXhXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXjXbXe.X.4.3.3.3.3.3.3.3.3.3.3.3.1.-.4.2.3.3.3.3.3.3.3.3.3.2.4.#.~ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ~ } ) ~ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ / ! ;XmXjXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXcXvXzXzXzXzXzXzXzXzXzXzXzXzXzXcXzXzXzXzXzXzXzXzXzXzXzXzXzXvXNXMXMXMXMXMXMXMXMXMXMXMXNXnXMXNXMXMXMXMXMXMXMXMXMXMXNXmXlXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXjXkXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"48 48 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXhXjXlXkXkXlXjXjXkXlXkXkXlXjXjXlXkXkXlXjXjXlXlXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXBXvXkXlXlXkXmXBXkXkXlXlXjXbXbXjXlXlXkXMXNXkXlXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXgX{.6XcXkXkXvX*X}.lXlXkXjXMX4X2XvXkXkXvX#X.XzXkXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXkXnX>.,.SXgXjXcX>X_ <XnXjXzXfXE s.SXgXkXcX%X) 8XvXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXhX9.>.CXhXhXVXF./ sXxXhXnX>XI :.CXhXhXVXm.] hXzXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXsX[.0XxXkXjXvX#X(.aXzXkXjXnXsX8XcXkXkXvXOX_.dXzXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXBXcXkXlXlXkXMXVXzXkXlXlXjXzXvXkXlXlXkXMXVXzXkXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXgXjXlXkXkXlXjXgXjXlXkXkXlXjXjXlXkXkXlXjXgXkXlXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXnXcXkXlXkXlXjXnXcXkXlXlXkXvXxXkXlXlXlXkXmXzXkXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXhXZXM.Z.ZXhXjXbX'.-.0XvXjXzXhX1.-XmXjXjXmX!.*.sXxXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXjXnX3Xc %.VXhXjXbX;X{ 0XvXkXhXZX6.~.CXhXjXvX-XS 3XnXjXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXgXI.M.mXjXhXCXb.*.aXxXjXlXjX<.Z.MXjXjXvXT.w.uXxXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXVXNXkXlXlXjXmXmXkXlXlXlXkXmXvXkXlXlXlXzXNXxXkXlXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXhXjXlXkXkXlXjXjXlXlXkXkXlXjXkXlXkXkXkXkXhXkXlXkXlXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXjXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXhXjXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXMXCXCXCXCXCXCXCXCXCXCXCXCXVXBXBXBXBXBXBXBXBXBXBXBXVXmXkXlXlXlX",
"lXlXlXlXlXlXlXlXkXlXkXjXlXkXkXkXcX_.C.D.D.D.S.D.D.S.D.D.D.S.H.I.I.I.I.I.P.P.I.I.I.U.J.}.vXkXkXlX",
"lXlXlXlXlXlXlXlXlXkXvXbXkXlXkXjXmX>.` %.@.@.#.X.| $.@.@.+.=.K % : ; ; = 2 5 = ; ; ,   o.ZXgXkXlX",
"lXlXlXlXlXlXlXkXkXzXqX4XlXlXkXjXnX9.9.k.f.f.h.u.w.j.f.g.d.v._   .       & :       o   ..AXgXkXlX",
"lXlXlXlXlXlXlXkXjXNX..3.bXkXkXjXnX7.3.a.y.u.i.q.6.p.y.u.t.h.^   X . .   * :   . . O   ..AXgXkXlX",
"lXlXlXlXlXlXlXkXkXcXS.T eXcXkXjXnX7.3.s.u.u.p.w.7.a.u.u.y.j.^   .       & ;       o   ..AXgXkXlX",
"lXlXlXlXlXlXlXkXkXcX].~.zXkXkXjXnX7.2.p.t.t.u.0.5.i.t.y.r.g.~   .       & ;       o   ..AXgXkXlX",
"lXlXlXlXlXlXlXlXlXkXMXBXlXkXkXjXnX8.q.z.h.j.k.p.e.l.h.j.g.n._   o . X   * >   X . +   ..AXgXkXlX",
"lXlXlXlXlXlXlXkXkXlXfXfXlXkXkXjXmX6.c B N N M V Z M N N M B b 1 2 2 2 < 9 w < 2 2 5 @ %.ZXhXkXlX",
"lXlXlXlXlXlXlXlXlXkXVXmXkXlXkXjXmX4.          $ :           2 X         & ;       o   ..AXgXkXlX",
"lXlXlXlXlXlXlXkXjXnXh.C.bXkXkXjXmX4.. . X X   & ,   X . X   3 X         & ;       o   ..AXgXkXlX",
"lXlXlXlXlXlXlXkXjXnX9.] dXzXkXjXmX4.          $ :           2 X         & ;       o   ..AXgXkXlX",
"lXlXlXlXlXlXlXkXkXcXI.&.pXxXkXjXmX4.    .     % ,   X . X   3 X     .   & :   X . +   ..AXgXkXlX",
"lXlXlXlXlXlXlXkXkXzXiXxXcXkXlXjXmX4.          $ :           2 X         & ;       o   ..AXgXkXlX",
"lXkXlXkXjXkXlXkXlXkXlXkXkXlXkXjXmX5.- : > : ; 3 a 0 w w w w a > : : : - 5 a 0 w w t , -.CXhXkXlX",
"lXlXkXzXmXlXkXlXlXkXbXcXkXlXkXjXmX4.# % % % % O *XUXZXSXCXUXl.  = % % $ % 3XIXZXSXSXGX*XgXlXkXlX",
"lXkXzXaX-XhXlXkXkXxX1X9XxXkXkXjXmX4.            ,XUXLXUXKXUXx.  o       . 0XUXLXUXIXUX;XgXlXkXlX",
"lXkXzXdX .5XnXjXjXCXN.i.DXgXlXjXmX4.            >XUXKXIXJXUXx.  O       . 9XUXLXIXPXUX;XgXlXkXlX",
"lXkXkXvX{ ).NXjXhXVXU.+.MXjXkXjXmX4.            ,XUXLXIXJXUXx.  o       . 0XUXLXIXIXUX;XgXlXkXlX",
"lXkXxXuXA.@XbXjXkXvX[.H.fXzXkXjXmX4.. . . . X   >XUXLXIXJXUXx.  o       . 8XUXJXLXKXUX-XgXlXkXlX",
"lXlXkXzXAXmXkXlXlXkXNXZXlXkXlXjXmX4.            ,XUXLXUXKXUXc.  @ o o X O 0XUXLXUXIXUX;XgXlXkXlX",
"lXkXlXkXgXjXlXkXkXlXgXdXkXlXkXjXmX6.W [ ` ` ' / t.M.v.v.c.Z. .* 3 1 2 < 7 R Q W W ! K r.NXhXkXlX",
"lXlXlXlXlXlXlXkXlXjXvXBXkXlXkXjXnX8.0.z.h.h.k.p.4.r.w.e.q.a.!   .       & ;       o   ..AXgXkXlX",
"lXlXlXlXlXlXlXlXjXMX,Xf.nXkXkXjXnX7.2.p.t.y.u.0.7.s.i.p.u.k./   X       & ,   o o @   X.AXgXkXlX",
"lXlXlXlXlXlXlXkXkXxXo.V dXzXkXjXnX7.3.s.u.u.p.w.7.a.u.i.y.j.^   .       & ;       o   ..AXgXkXlX",
"lXlXlXlXlXlXlXkXlXkX~.:.iXxXkXjXnX8.4.s.u.u.p.w.7.a.u.i.y.j./   o . X   = >   X . +   X.AXgXkXlX",
"lXlXlXlXlXlXlXlXkXlXBXNXzXkXlXjXmX5.2.s.u.u.p.q.6.p.u.u.t.h.~   .       % -       o    .AXgXkXlX",
"lXlXlXlXlXlXlXkXlXkXhXjXkXlXkXjXnXi.4.i.t.t.y.q.8.u.t.t.r.s...t s a a i k x i a a f 7 2.CXhXkXlX",
"lXlXlXlXlXlXlXlXlXlXkXkXlXlXkXkXlXfXpXpXpXpXiXpXpXiXpXpXpXiXsXkXjXjXjXjXjXhXjXjXjXjXjXhXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXzXxXxXxXxXxXxXxXxXxXxXxXxXzXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXkXlXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlXlX"
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"32 32 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXlXlXlXlXlXlXlXlXkXnXxXkXkXxXnXkXlXkXxXxXkXkXxXnXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXkXkXlX5XsXzXzXuX5XzXkXcXsXpXzXzXiX4XlXkXkXlX",
"lXlXlXlXlXlXlXlXlXlXkXjXVXq.F.ZXcX>X>.kXkXMX#.Z.ZXxX3X:.gXzXkXlX",
"lXlXlXlXlXlXlXlXlXlXkXkXcXL.#XbXbX&XM.cXkXxXR.|.nXbX;Xn.zXkXkXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXkXvXvXkXkXxXbXkXlXlXNXnXkXkXxXnXkXlXlXlX",
"lXlXlXlXlXlXlXlXlXlXlXlXkXmXcXkXlXkXbXlXkXkXcXlXkXlXlXmXlXkXlXlX",
"lXlXlXlXlXlXlXlXlXlXkXjXmXU.#XmXxX7XS.kXkXnXE.7XvXcX9Xm.jXlXkXlX",
"lXlXlXlXlXlXlXlXlXlXkXkXcXX.D.CXbX#X-.zXhXCXd./.BXxX4XX.aXxXkXlX",
"lXlXlXlXlXlXlXlXlXlXlXkXzXgXaXlXxXeX<XzXkXzX3XqXxXzXuX8XzXkXkXlX",
"lXlXlXlXlXlXlXlXlXkXlXjXhXjXkXhXgXzXvXhXhXgXcXzXgXgXkXxXgXhXlXkX",
"lXlXlXlXkXlXkXkXlXlXkXmXVXBXBXBXVXBXNXBXVXCXVXVXCXCXVXVXZXMXkXlX",
"lXlXlXlXlXkXlXlXkXkXvX(.N.S.A.A.A.A.A.A.C.M.N.N.N.N.N.B.v.Q.cXkX",
"lXlXlXlXkXlXkXlXlXjXmXq.&.3.2.:.-.2.,.8.P   .   + %   o   Y CXhX",
"lXlXlXlXhXVXl.F.BXgXnXd.e.f.d.y.r.f.p.x.(   X   # =   O   E CXhX",
"lXlXlXkXjXNXJ.x.BXgXnXa.7.i.u.q.9.u.r.g.~   .   @ *   o   R CXhX",
"lXlXlXlXkXlXdXkXlXjXnXs.t.j.h.p.y.j.d.b._   + . % - . @   E CXhX",
"lXlXlXlXlXjXNXbXjXjXNX5.q f a g j a s d a = - * < 4 * >   / VXhX",
"lXlXlXlXjXbXoX<XvXgXVX,.  X   @ &       ; .     @ *   o   R CXhX",
"lXlXlXkXhXCXp.r.ZXfXVX,.  O   $ - X O o > X     @ -   @   E CXhX",
"lXkXkXlXkXvX=X+XvXgXVX,.  X   @ &       ; .     @ *   o   R CXhX",
"kXlXkXkXlXkXbXmXkXhXBX1.X ; * , x z z c g & = * > x z c i $.NXhX",
"lXjXlXlXkXlXhXkXkXhXVX<.  # O + qXUXGXUXN.  % + . 4XUXKXUXeXdXzX",
"xXiXv.lXjXBXQ.].BXfXVX,.  X     qXUXGXUXm.  O     4XUXKXUXeXdXzX",
"zXdX4.rXzXVXI.M.CXfXVX,.  O . X 0XUXGXUXm.  O     2XUXGXUXwXdXzX",
"lXhXuXhXlXlXpXiXlXhXVX,.  X     qXUXGXUXM.  @ o   4XUXKXUXeXdXzX",
"kXlXcXlXlXkXvXmXjXjXmXe.~ } { ' g.Z.m.H.X.O : = > L R R G 4.mXjX",
"lXkXkXkXkXcXtX3XvXhXnXs.y.k.j.a.7.e.0.a.Q   .   @ *   o   R CXhX",
"lXlXlXkXhXCXe.2.SXfXnXa.7.i.u.w.w.a.u.k./   O   $ : o $   Q CXhX",
"lXlXlXkXkXcX>XXXvXhXnXu.7.i.u.q.9.i.r.g.!   .   + &   o   T CXhX",
"lXlXlXlXlXkXnXMXkXjXbXz.e.d.s.u.t.d.p.k.o.w a u f j u s 7 +.BXhX",
"lXlXlXlXkXlXjXjXlXkXlXgXsXsXsXsXsXsXsXsXfXkXkXkXkXjXkXkXkXjXkXlX",
"lXlXlXlXlXlXlXlXlXlXkXzXzXzXzXzXzXzXzXzXzXlXlXlXlXlXlXlXlXlXkXlX"
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"16 16 256 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c #808080",
"p. c #818181",
"a. c gray51",
"s. c #838383",
"d. c #848484",
"f. c gray52",
"g. c #868686",
"h. c gray53",
"j. c #888888",
"k. c #898989",
"l. c gray54",
"z. c #8B8B8B",
"x. c gray55",
"c. c #8D8D8D",
"v. c #8E8E8E",
"b. c gray56",
"n. c #909090",
"m. c gray57",
"M. c #929292",
"N. c #939393",
"B. c gray58",
"V. c #959595",
"C. c gray59",
"Z. c #979797",
"A. c #989898",
"S. c gray60",
"D. c #9A9A9A",
"F. c #9B9B9B",
"G. c gray61",
"H. c #9D9D9D",
"J. c gray62",
"K. c #9F9F9F",
"L. c #A0A0A0",
"P. c gray63",
"I. c #A2A2A2",
"U. c gray64",
"Y. c #A4A4A4",
"T. c #A5A5A5",
"R. c gray65",
"E. c #A7A7A7",
"W. c gray66",
"Q. c #A9A9A9",
"!. c #AAAAAA",
"~. c gray67",
"^. c #ACACAC",
"/. c gray68",
"(. c #AEAEAE",
"). c #AFAFAF",
"_. c gray69",
"`. c #B1B1B1",
"'. c #B2B2B2",
"]. c gray70",
"[. c #B4B4B4",
"{. c gray71",
"}. c #B6B6B6",
"|. c #B7B7B7",
" X c gray72",
".X c #B9B9B9",
"XX c gray73",
"oX c #BBBBBB",
"OX c #BCBCBC",
"+X c gray74",
"@X c gray",
"#X c gray75",
"$X c #C0C0C0",
"%X c #C1C1C1",
"&X c gray76",
"*X c #C3C3C3",
"=X c gray77",
"-X c #C5C5C5",
";X c #C6C6C6",
":X c gray78",
">X c #C8C8C8",
",X c gray79",
"<X c #CACACA",
"1X c #CBCBCB",
"2X c gray80",
"3X c #CDCDCD",
"4X c #CECECE",
"5X c gray81",
"6X c #D0D0D0",
"7X c gray82",
"8X c #D2D2D2",
"9X c LightGray",
"0X c gray83",
"qX c #D5D5D5",
"wX c gray84",
"eX c #D7D7D7",
"rX c #D8D8D8",
"tX c gray85",
"yX c #DADADA",
"uX c gray86",
"iX c gainsboro",
"pX c #DDDDDD",
"aX c gray87",
"sX c #DFDFDF",
"dX c gray88",
"fX c #E1E1E1",
"gX c #E2E2E2",
"hX c gray89",
"jX c #E4E4E4",
"kX c gray90",
"lX c #E6E6E6",
"zX c #E7E7E7",
"xX c gray91",
"cX c #E9E9E9",
"vX c #EAEAEA",
"bX c gray92",
"nX c #ECECEC",
"mX c gray93",
"MX c #EEEEEE",
"NX c #EFEFEF",
"BX c gray94",
"VX c #F1F1F1",
"CX c gray95",
"ZX c #F3F3F3",
"AX c #F4F4F4",
"SX c gray96",
"DX c #F6F6F6",
"FX c gray97",
"GX c #F8F8F8",
"HX c #F9F9F9",
"JX c gray98",
"KX c #FBFBFB",
"LX c gray99",
"PX c #FDFDFD",
"IX c #FEFEFE",
"UX c white",
/* pixels */
"lXlXlXlXkXzXiXdXgXuXlXtXzXyXhXlX",
"lXlXlXlXjXmXOX3XqX.XzXE.bX`.yXxX",
"lXlXlXlXlXkXxXzXkXlXlXcXkXkXlXkX",
"lXlXlXkXjXmX}.<X0X|.lX`.bX(.eXcX",
"kXlXkXjXkXvXkXxXxXgXNXgXBXjXbXlX",
"lXkXlXnXxXeX#X%X$X&XXXoX.X.X%XkX",
"kXlXjXXXMX'.-.6.2.e.p   &   j xX",
"kXlXkX$XnX}.0.s.y.z.h   -   z xX",
"kXlXkXqXVXQ.- 8 0 9 , o >   n xX",
"lXlXjX!.NXE.  + O   @   %   k xX",
"jXjXlXkXCXW.  , s.H.n   P Z.Z.hX",
"wXXXbX(.BXE.  % sXUXW   >.UXcXsX",
"hXaXzXgXBX^.u b `.9XJ   W Q.U.gX",
"lXzXkX).nX{.w.f.3.e.p   &   j xX",
"kXkXkX2XnXXXr.f.d.n.F 3 s 6 U xX",
"lXkXlXbXlXhXpXaXaXaXaXaXaXpXsXkX"
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
};
const int n_xpm_icons = 4;
