/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 44 1 ",
"  c #0000FF",
". c #0B0BFC",
"X c #1313FB",
"o c #1B1BF9",
"O c #2525F7",
"+ c #2B2BF6",
"@ c #2121F8",
"# c #3434F4",
"$ c #3B3BF3",
"% c #4D4DEF",
"& c #5353EE",
"* c #5D5DEC",
"= c #4444F1",
"- c #4949F0",
"; c #6464EB",
": c #6A6AEA",
"> c #7575E7",
", c #7D7DE6",
"< c #7272E8",
"1 c #A7A7A7",
"2 c #AAAAAA",
"3 c #B4B4B4",
"4 c #BCBCBC",
"5 c #A4A4DE",
"6 c #ABABDD",
"7 c #B4B4DB",
"8 c #BBBBDA",
"9 c #8484E4",
"0 c #8A8AE3",
"q c #9494E1",
"w c #9A9AE0",
"e c #C5C5C5",
"r c #C9C9C9",
"t c #C6C6D7",
"y c #CCCCD6",
"u c #C2C2D8",
"i c #D5D5D5",
"p c #DCDCD3",
"a c #D5D5D8",
"s c #D8D8D8",
"d c #E3E3D1",
"f c #E2E2E2",
"g c #EFEFEF",
"h c #FFFFFF",
/* pixels */
"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiiiiiiisiiiiiiiiiiiiii",
"iiiiiiiiisiiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipiiiiiiiisiiiiiiiiiiiiiiiiiiiiisiisiiiii",
"iiiiiiiiiiiiiiiiiiaiiiiiiiiiiiiiiiiiiiiiiiaiiiiiiiiiiiiisiiiiiiiipiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
"iiiiiiiiiiisiiisiiiisiiiisiiiiiisiisiisiiiiisissiiiisiiiiiiiiiiiiiiiisiiiisiiiiiiiiiiiiiiiiiiiii",
"iiiihhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhheeiiiiiiiiiiiiiiiiiiiiiiiiiipsiiiiisiisiiiiiispii",
"iiiifdfpfffffffdfpfffffdfdfpfffffffddffffpffffp1esiiiiiipiiiiiiiiiiiiiiiiiiiiiiiiiiiipiiiiiiiiii",
"iiiiayiiiririiayiiiriiirayiiiiriiyiyyryiiiriiii1esiiiiiisiiiiiiisiiiiiiiiiiiiiisiiiiiiiiisiiiiii",
"iiiiaaiiiiiiiiiiiiiiiiiiaaiiiiiiiiddddiiiiiiiii1esiiiiiiiiiiiisiiiiiiiisiiiiiiiiiiiiiiiiiiiiiiii",
"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiidyq00q8diiiiiii1esiiiisiiiiiiiiiiiipsiiisiiiiiisiiiiiiiiiiiiiiii",
"iiisiiiiiiiiissiiiiiiiiiiiiiiydy:@    o*tpiiiii1epiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiii",
"iiiiiiiiiiiireeeiiiiiiiiiiiiip8#        o6piiii1esiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiisii",
"iiiiiiiiisi321123eiiiiiiiiiiiy+          o8iiii1esiiiiiiiiisiiiiiiisiiiiiiiiiiiiisiiiiiiiiiiiiii",
"iiiiiiiisr32222212esiiiiiiiid;            -iiii1esaiiiiiiiiisiiiiiiisiiiiiiiiiiiiiiiiiiiipiiisii",
"iiiiiiiii4222222221riiiiiiipuX             6pii1epiiiiiiiiisiiiiiiiiiiiiiipiiiiiiiiiiiisisiiiiii",
"iiiiiiisr22222222214iiiiiiyd0              ;dii1esiiiiiiiiipiiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiiiii",
"iiisiiise22222222113iiiiiiid:              -dyi1esiiiiisiiiiiiiiiiiiiiiiiiiiiiiiiipsiiiiiiiiiiii",
"iiiiiiise12222222213iiiiiiid;              -dii1rsiiiiiiiiiiisiisiiiiisiiiiiiiisiiiiiiiiiiiiiiii",
"iispiiise12222222313iiiiiiid>              &dai1esiiiisiiiiiiiiiiiiiiipiiiiiiiiiisiipiiiiiisiiii",
"iiiiiiiii3222222221eiiiiiiii5.             0iii1esiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiisiiiiiipiiis",
"iiiiiiiise222222214iiiiiiiiii$            oyiii1esiiiiiiiiiiiiiiiiiiiiiiiiispiiiiiiiiiiiiiiiiiii",
"iiiiiiiiii42112113iiiiiiiiiip5.           0diii1esiiiiisiiiiiiiiiiiiiispiiisiiiiiiiiiiiiisiiiiii",
"iiiiiiiiiiir4334eiiiiiiiiiiiap9          ;piiii1esiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiii",
"iiiiiiiiiiiipiiiiiiiiiiiiiiiiipqo      X9iiiiii1esiisiiiiiisiipsiiiiiiiiiiiiiiiisiiiiiiiiiiiiiii",
"iiiiiiiiiiiiiiiiiiipiiiiiiiiiiidy0-++$,8diiiiii1esiiiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
"iiiiiiiiisiiiiiiiiiiiiiiiiiiiiiiippppppiiiiiiii1esiiiiiiiiiiiiiiiiiiiiiiisiiiipiiiiiipsiiipiiiii",
"iiiiiiiiipiiiiiiiiiiiiiiiiiiiiiiiiaiiiiiiiiiiii1epiiiiisiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiisiiisi",
"iiiiiisiiiiiiiiiiiiisiipiiiiiiiiiiiiiiiiiiiiiii1epiiiiiiiisisiiiiiiisiiiiiiiiiiiiiiisiiiiiiiiiii",
"ispiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiiii1rsiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
"iiiiiiiiiiiiiiiiiiiiiiiiiipsiiiiiiiiiiiiiiiiiii1esiiiiiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiiiiiiiiiiii",
"iisiiiiiisiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii2esiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiiisiisii",
"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii1esiiiiiiiiiiiiiiiiiiipiiiiiiiiiiiiisiiiiiiiiiiii",
"iiiiiiiiiiiiisssiiiiiiiiiiiiiiiiiispisiiiiiiiii2esiiiiiiisiiispiiiiiisiisiiiiiiiiiiiiiiiiiiiiiii",
"iisiiiiisiiie44eipiiiiiiiiiiiiiisie44eiiiiiiiii1esiiiiiiiiiiiiiiisiiiiiisiiiiiiiiiiiiiiiiiiiiiii",
"iiiiiiiiipr3211224iiiiiiiiiiiiise321122esiiiiii1esiiisiiiisiiiiiiiiiiiiiiiiiiiiiiiiiiiisisiiiiii",
"iiiiiiiiir222222214iiiiiiiiiiiie11222212esiiiii1esiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiiiiipiii",
"iiiiiiiii4222222222ripiiiiiiiii3122222222riiiii1eiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipsiiiiiiiisiii",
"iiiiiiise22222222224iiiiiiiiise12222222214iiiii2epiiiiiiiiiiisiiiiiiiiiiipiisiiiiiiiiiiiiiiiiiii",
"siiiiiise12222222213iiiiiiiiip412222222213psiii1esiiiiisiiiiiiiiisiiiiiiisiiiiiiiiiiiiiiiiiiiiii",
"iiiiiiise12222222212iiiiiiiiii413122212214iiiii1esiiiiiiiiiiiiiiiiiiissiiiiiiiiiiiiiiiiiiisiiiii",
"iiiiiiipr22222222214iiiiiiiiiie22222232224iiiii1esisiiiiiispiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiii",
"iiiiiiiii3222222221eiiiiiiiiiii2122222222rpiiii1esiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiiisiiiiiiiii",
"iiiiiiiiir222222214iiiiiiiisiiie222221214siiiii1eiiiiiiisiiiiiiiiisiiiiiiiiiiiispsiiiiiiiisiiiii",
"siiiiiiiiir2211124iiiiiiiiiiiiiie2111124iiiiiii1esiiiiiiiiiiiiisiiiiisiiiiiiiiiiiiiiiiiiiiiiiiii",
"iiiiiiiiiiiie434rsiiiiiiiiiiiiiiii4444iiiiiiiii1esiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiisiiiiiiiiiiiii",
"iiiiiiiiiiiiissiiiiiiiisiiiiiiiiiiisssiiiiiiiii1esiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiiii",
"isiiiiiiiiiiiiiiiiisiiiiisiiiiiiiiiiiiiiiiiiiii1episiiiiiiiiiipiiiiiiiiiiiiiiiiiiiiiiiiiisiaiiii",
"iiiiiipsiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii1eaiiiiiiiriiyaiiyaiiriiiiyiiriiiiaiyiiiyiayiiiii",
"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiii2affdfffffffffffdffdffffffffdffffdfffffdffdfiiiii",
"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiifhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg2iiii",
"iiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiiiiiiiaaiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipr1iiii",
"siiiiiiiiiiiiyaiyiiiiiiiiiiiiiiiiayiaariiiiiiiiiiiiiiiiriyiyiiiiiiiiiiiiiiiiiryiyyiiiiiiiie2riii",
"iiiiiiiiiiipdddddiiiiiiiiiiiiiiiiidddddiiiiiiiiiiiiiiaidddddpiiiiiiiiiiiiiiridddddpiiiiiise1iiii",
"iiiipiiiipp7;-$&0ydiiiiiiiiiiiipi5;=-&qipiiiiiiiiiiiipiq*==*widyiiiiiiiiiiidy0&==;6piiiiise2iiii",
"iiiiiiiap8=      o9iiiiiiiiiiip6#      Owpiiiiiiiiiydw+      #5diiiiiiiiiii0o      =8piiiie1iiii",
"iiiiiiip5o         ;piiiiiiiidq.         ,piiiiiiiid>         .qdiiiiiiiii;         o6piiir1riii",
"iiiiiiitO           ,diiiiiii7X           wpaiiiiydq           X6iiiiiiip9           @usisr1iiii",
"iiiiiid;            X8iiiiiii=            +rsiiiiiaO            =piiiiipuX            *dise1iiii",
"iiiiiiuo             ,piiiii7X             qpiiiipq             .6piiiii,             ouiar1iiii",
"iiiiydq              $iiiiad>              &diiiid*              >diiiid$              qdar1iiii",
"iiiiid0              Opiiiid:              =diiiid-              ;dyiiiiO              0dae1iiii",
"iiiiid0              @iiiiyd:              =diiiyd-              ;diiiidO              0dir1iiii",
"iiiiydw              =diiiid,              ;diiiid;              ,diaiip-              wpie2iiii",
"iiiiiiyO             0diiiii8X             5iiiiii5             .8iiiiii0             Oypie1iiii",
"siiiiad<            @tiiiiiip&            $iiiiiiii$            &piiiiisy@            <diie1iiii",
"iiiiiiii#           qdyiiiiii8@          .6diiiiiii7.          oupiiiiiiiq           #iiiie1iiii",
"iiiiiiii8#        .9piiiiiiiid6@        XqpiiiiiiiipqX        o6diiiiiiiid9.        #8piiir1iiii",
"iiiiiiiipy;X    .#5diiiiiiiiiid8%X    .=7piiiiiiiiiip7-.    X&8pyiiiiiiiiyd5#.    o;yiaiiie1iiii",
"iiisiiiiiidt0:;>5ipiiiiiiiiiiiiid89::,7ppriiisiiiiiiidi7,:;98dpiiiiiiiiiiiiii6>;:0udiiiiiir1iiii",
"iiiiiiiiiiiidddddiiiiiiiiiiiiiiiiiddddiiiiiiiiiiiiiiiyipddddiiiiiiiiiiiiiiiiidddddsiiiiiisr1iiii",
"iiiiiiiiiiiiyiiyyiiiiiiiiiiiiiiiiiiyiyiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiyriiiiiiiipe1iiii",
"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipiiiiiiiiiiiiiiiiiiiiiiiiiir1riii",
"siiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiise1iiii",
"iiiiiiiiiiiiyiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiir1iiii",
"iiiiiiiiiiipdpppppyiiiiiiiiiiiiiippppidiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipdipidiyiiiise1iiii",
"iiiiiiiiipyq%OO#<7diiiiiiiiiiiidt0=OO$,8piiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiip7<#OO%qydiiiise1iiii",
"iiiiiiiip5+       :iiiiiiiiiiiiqo      X9iiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiii:.      +5iiiiir1iiii",
"iiipiiipq.         %iiiiiiiiip,          ;iiiiiisiiiiiie4234eiiiiiiiiiiiii%         .qpiise1iiii",
"iiiiiii8X           :piiiiiip5.           0piiiiiiiiii42221224iiiiiiiiiid:           X8sisr2iiii",
"siiiiid%            .7iiiiiii#            otiiiiiiiii4122222214iiiiiiiip7.            %diie1riii",
"iiiiii8o             <piiiip5.             0piiiiiiir2122222222iiiiiiiid<             o8iie1iiii",
"iiiiidq              #diiiid<              &diiiiiis42222222222esiiiiiid#              0dir1iiii",
"iiiiyd0              Opyiiid;              =dyiiiiip422222222214siiiiiyiO              0dir1iiii",
"iiiiid0              Opiiiyd:              -diiiiiii412223222214siiiiiidO              0dar1iiii",
"iiiiyd5              %piiiid0              ;diiiiiii41222222222eiiiiiiii&             .wdae1riii",
"iiiiiiy+             qdiiiiiuX             6piiiiiiii2222222213iiiiiiiidq             Oiise1iiii",
"iiiiiid,            #yiiiiiid;            %iiiiisiiiir22222212rsiiiiiiiia+            ,disr1iiii",
"iiiiiiis%          .5dyiiiiiiy#          o8iiiiiiiiiiir322124riiiiiiiiiip5.          -iiiie1iiii",
"iiisiiiiy%        Xwdyiiiiiiid8#        O6paiiiiiiiiiiiireeriiiiiiiiiiiiidwX        %yiiiie1iiii",
"iiiisiiiii0O.   o&8piiiiiiiiiipi:O    o;ypiiiiiiiiiiiiiisssiiiiiiiiiiiiiiid8&o    #,iiiiisr1iiii",
"iiiiiiiiiidi500q8diiiiiiiiiiiiiidyw00wudiiiiiisiiiiiiiiiiiiiiiiiiiiiiiiiiiiip8q005rdiiiiiie1iiii",
"iiiiiiiiiiiipdddiiiiiiiiiiiiiiiiiiddddiyiiiiiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiddddiiiiiiise1iiii",
"iiiiiiiiiiiiiiyiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiispiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiir2iiii",
"iiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
"isiiisiiiiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiisiiiiipiiiiisiiiiiiiiiiipsiiiiiiiiiiaiiiiiiiiiiiii",
"iiiiipiiiiiiisiiiiiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiiiisiiiiiiiiiiiiiiiiiiiiii"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"48 48 46 1 ",
"  c #0101FE",
". c #0A0AFC",
"X c #1313FA",
"o c #1B1BF9",
"O c #2525F7",
"+ c #2B2BF6",
"@ c #2121F8",
"# c #3434F4",
"$ c #3B3BF3",
"% c #4444F1",
"& c #4949F0",
"* c #7676E7",
"= c #7B7BE6",
"- c #7171E8",
"; c #A6A6A6",
": c #ABABAB",
"> c #B3B3B3",
", c #BEBEBF",
"< c #C1C1BE",
"1 c #9E9EDF",
"2 c #BEBEC1",
"3 c #A3A3DE",
"4 c #ABABDD",
"5 c #BDBDD5",
"6 c #B0B0DC",
"7 c #BBBBDA",
"8 c #8484E4",
"9 c #8B8BE3",
"0 c #9494E1",
"q c #9B9BE0",
"w c #C1C1C1",
"e c #CCCCCC",
"r c #DDDDCF",
"t c #C6C6D7",
"y c #CDCDD5",
"u c #C2C2D9",
"i c #CECED9",
"p c #D5D5D5",
"a c #DDDDD3",
"s c #D6D6D8",
"d c #DCDCDC",
"f c #E1E1D3",
"g c #E3E3E3",
"h c #EDEDE7",
"j c #E6E6E9",
"k c #EAEAE9",
/* pixels */
"pppppppspppppppppppppppppppppppppppppppaspppppsp",
"ppppppppppppsppppppppppppppppsppppppspppppsppppp",
"pppppppppepppppppppppyppppppppppspppppppppppaspp",
"ppppsdddddddddddsdddddddppppspppappspppppppppppp",
"pppphhjkhjhkkkjhhjhhjjhpespppppppppppspppppppppp",
"pppppppeppeppepprptpaep,espppppppppppappppsapppp",
"ppppppppyppppppa1#X+9asweppppppappspppppppppppsp",
"ppppppp>:>epppf1     9f2eppppppsppppppppsppppppp",
"pspppp>;:;:pppp$     Opwepppppppaspppspspppppaps",
"pppppp:::::epppo     .tweppppppppppppppppsppsppp",
"pppppp>;:::pppp$     @d<eppppppppppppppppppppppp",
"pppprpp>::epppf1     8f<eppppppppppppppppppppppp",
"ppppppppeppppppr1#.+9ps<esppappsppppsppppasppppp",
"ppppppppppppppppaptprps<eappppppppsppppppppppppp",
"pppppppppppppppppppppps<epppppppppsapppppppppspp",
"sppppppppppppppppppppps<espppppppppppppppspppppp",
"ppppppppepppppppppppppd2eppppppppspppppspspppppp",
"ppppppe>::epppppe>::epp<esppppppppppppppppppppsp",
"pppppp>;:;:ppppp>;:;:pd<epppppspppppppsspppppppp",
"pprppp>:::;epppp:::::ep,epppppppppppppppsppppppp",
"pppppp>;:;:ppppp>;:;>pd<epppsppppppppppppppppppp",
"ppppppp>:>epppppe>::epsweppppppppppppppppppppppp",
"pppsppppeppppppppppppppwwspppppppppppppypppppppp",
"sppppppppppppppppppppppwpgddddgfgddfddddfgddpppp",
"ppppppppppppppppppppppppkhjhhkjjkhjjjkhhjkkeeppp",
"ppppppfpuyfppppprpupappppyry5erpeppery5prep,eppp",
"pppppa1@.o*apppp9O.o=apppa9@.o8ppppa8@.o9ad,eppp",
"ppppa1     *fpa1     =fpr9     8fyf9     9f2eppp",
"ppppa$     oypp$     oppp+     Oppp+     +s,edpp",
"ppppp@      5ayo     .uppo     XtptX     Xi<eppp",
"ppppa&     @ypa%     +ppp$     +ppp#     #a2eppp",
"ppppa4.    9apa4     9fyf1     1fyfq     qf,eppp",
"pppppp4$o#0ppppa3$o$1ppppa3$o#1apppp1$X$3ap,eppp",
"ppppppaappfpppppfpppappppprppprpppppfappapd<eppp",
"ppppppppapppppppppapypppppppppppppppypapypp,eppp",
"ppppppap5tfpppppap7yfpppppppppppppppfy7yfpp<eppp",
"pppppa9o X-ppppa9o X*appppppeppppppa=o o8ap,eppp",
"ppppf0     -fyp1     *rpppe:::epppr8     8f2edpp",
"ppppa$     oypp$     opppp:;:;:pppp+     +d,eppp",
"ppppp@      5ayo     .tppp:::;:pppy.     Xp<eppp",
"ppppf&     @ppp&   . +pppp>;:;>pppp$ .   #d,eppp",
"ppppa6.    9app4     0apppp>:>ppppa1     3f,eppp",
"pppppa6&@$1apppr4%o$1apppppppppppppr3$@$3ap<espp",
"pppppppfpaapppppafpaappppppppppsppppafprfps,eppp",
"pppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppsp",
"pppppsppppppppppppppppppppppspspppppppppppsppppp",
"ppppppppppppppppppppppppppprpppppppppppppppppppp"
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"32 32 53 1 ",
"  c #0202FE",
". c #0A0AFC",
"X c #1313FB",
"o c #1A1AF9",
"O c #2F2FF5",
"+ c #2222F8",
"@ c #3434F4",
"# c #3D3DF2",
"$ c #4141EF",
"% c #4E4EEF",
"& c #5454ED",
"* c #5B5BEC",
"= c #4141F2",
"- c #4949F0",
"; c #6565EA",
": c #6E6EEB",
"> c #7C7CE6",
", c #7070E8",
"< c #A6A6A6",
"1 c #ABABAB",
"2 c #B4B4B4",
"3 c #BCBCBC",
"4 c #9E9EDF",
"5 c #A4A4DD",
"6 c #ABABDC",
"7 c #BEBED6",
"8 c #B5B5DB",
"9 c #BBBBDA",
"0 c #8282E5",
"q c #8C8CE3",
"w c #8282E8",
"e c #9393E2",
"r c #9B9BE0",
"t c #A2A2E1",
"y c #C4C4C4",
"u c #CDCDC3",
"i c #CDCDCE",
"p c #D4D4C2",
"a c #C7C7D7",
"s c #CDCDD3",
"d c #C2C2D8",
"f c #D4D4D5",
"g c #DCDCD3",
"h c #D4D4D8",
"j c #DBDBDC",
"k c #F2F2CF",
"l c #E2E2D2",
"z c #EAEAD0",
"x c #E5E5DE",
"c c #EAEADD",
"v c #F1F1DF",
"b c #DDDDE0",
"n c #E2E2E2",
/* pixels */
"ffffsfifffifsffiffffffffffffffff",
"ffjjjjjjjxjjhjjjffffffffffffffgf",
"ffnxnnnnnncvvcnsiffffffffffffffj",
"fffffiffif7*&6gyijffjfffffjfffff",
"fffi21uffs+  .8uijffffffffffffff",
"ffj3<<1fg4    :pifffffffgfffffff",
"fffy<<2hf6    wpifffffjffjfffjff",
"fffp73fffj;  =huifffffffffffffff",
"ffffjfffffg86fgyifffffffffffffff",
"ffffffffffiggffyifffffffffffjfff",
"ffffifffffjiffjyijffffffffffgfff",
"fffi21yfffu2<yjyiffjffjfffffffff",
"ffj3<<1fff2<<2jyifffffffffffffff",
"fffy<<2jfj3<<2hypjffffffffffjfff",
"ffffyyiffffyyffyiffffffffiffffff",
"ffffffffffffhffijbbjbjjnbjjjxfff",
"ffffllgffffllgffjcccxjxjcccxxuuf",
"ffg9%#egfg8-#rgff6$$5gsg5$$6g7ff",
"ffa+   rlao   6l9X  .6l8.  .8uif",
"fl5    *kq    ;k0 .  ,k,    0pff",
"ff8.   >z6    0z5    4z4    rpsf",
"ffg0. %ffg>  &ffg:  *ffg;  ;gyff",
"fffga9gfffgd9gfffgddgfffgd9gfyif",
"fffflllffffllgffffjfffffglzffyff",
"ffg8#Oqgff6#@qgffhiffffl5@@5gyff",
"ffao   4ldo   5gfu11yjf8    8usf",
"fl4 .  &kq    ;lh2<<1fl>  . >psf",
"ff9.   0z8    qlf7<<3fg4    5uff",
"fffqX *ffg0..;ffifyyfffg,..,gyff",
"ffflaalfffgsdlffgffjfffflaagfyff",
"ffffffffffffffffffffffffffffffff",
"ffffffffffffffffffffffffffffffff"
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"16 16 159 2 ",
"   c #D5D5D5",
".  c gray85",
"X  c #DADADA",
"o  c #DADAD9",
"O  c #D8D8DA",
"+  c #E2E2D8",
"@  c #E4E4D8",
"#  c #D7D7D8",
"$  c gray83",
"%  c gray86",
"&  c #DADADB",
"*  c #E1E1D9",
"=  c #B4B4E2",
"-  c #AFAFE5",
";  c #D9D9D2",
":  c #D0D0D1",
">  c gray84",
",  c #CBCBCB",
"<  c #A5A5A7",
"1  c #CACAC3",
"2  c #BDBDDB",
"3  c #0707FC",
"4  c blue",
"5  c #A4A4D5",
"6  c #D9D9CE",
"7  c #D4D4D6",
"8  c gray81",
"9  c #B1B1B2",
"0  c #CDCDC9",
"q  c #C9C9DA",
"w  c #1D1DF8",
"e  c #1010FC",
"r  c #B3B3D3",
"t  c #D6D6CF",
"y  c #DBDBDA",
"u  c #D6D6D7",
"i  c #DADAD3",
"p  c #CCCCD9",
"a  c #CACADB",
"s  c #D4D4CC",
"d  c #CFCFD1",
"f  c #D6D6D5",
"g  c #D2D2D2",
"h  c gray75",
"j  c #CFCFCE",
"k  c #C9C9C6",
"l  c #C9C9C5",
"z  c #CECECF",
"x  c #D1D1D0",
"c  c #D7D7D7",
"v  c #CACACA",
"b  c #9E9EA2",
"n  c #C1C1C3",
"m  c #ACACB0",
"M  c #A9A9AD",
"N  c #CECECE",
"B  c #D1D1D5",
"V  c #D2D2D3",
"C  c #D4D4D3",
"Z  c #D1D1D4",
"A  c #D4D4D5",
"S  c #D6D6D4",
"D  c #DADAC9",
"F  c #D7D7D2",
"G  c #D9D9CD",
"H  c #DADACD",
"J  c #CFCFD0",
"K  c #D9D9D5",
"L  c #E9E9D8",
"P  c #DDDDD9",
"I  c #E5E5D8",
"U  c #D7D7D4",
"Y  c #CECED6",
"T  c #8E8EE5",
"R  c #C2C2D9",
"E  c #DFDFD2",
"W  c #A6A6DF",
"Q  c #9E9EE1",
"!  c #DEDED3",
"~  c #CFCFDC",
"^  c #9191E8",
"/  c #CBCBDD",
"(  c #A6A6E4",
")  c #A8A8E5",
"_  c #D8D8D0",
"`  c #E4E4D1",
"'  c #6464EB",
"]  c #4949F0",
"[  c #C4C4D8",
"{  c #0404FE",
"}  c #B7B7DA",
"|  c #6060EB",
" . c #5454ED",
".. c #BDBDD8",
"X. c #0000FE",
"o. c #ABABD3",
"O. c #D9D9CF",
"+. c #E1E1D2",
"@. c #8383E5",
"#. c #6767EA",
"$. c #D2D2D5",
"%. c #2323F8",
"&. c #1414FA",
"*. c #C8C8D7",
"=. c #7F7FE5",
"-. c #7474E8",
";. c #1B1BF9",
":. c #1E1EFA",
">. c #BCBCD1",
",. c #D5D5D0",
"<. c #D3D3D5",
"1. c #E2E2D2",
"2. c #C9C9D7",
"3. c #D5D5D4",
"4. c #D8D8D5",
"5. c #DEDED2",
"6. c #D3D3D4",
"7. c #D5D5D6",
"8. c #D7D7CC",
"9. c #9797E1",
"0. c #1A1AF9",
"q. c #D8D8D4",
"w. c #4242F1",
"e. c #3636F3",
"r. c #C6C6D8",
"t. c #D3D3CF",
"y. c #BFBFBD",
"u. c #D1D1CF",
"i. c #CBCBD8",
"p. c #3C3CF2",
"a. c #3E3EF4",
"s. c #C3C3CF",
"d. c #D4D4D0",
"f. c #5E5EEC",
"g. c #4444F1",
"h. c #C0C0D9",
"j. c #0202FE",
"k. c #A8A8E0",
"l. c #D2D2C6",
"z. c #9C9CA3",
"x. c #CECEC4",
"c. c #B1B1DF",
"v. c #A8A8D5",
"b. c #DADACF",
"n. c #D9D9D4",
"m. c #C2C2D8",
"M. c #6B6BE9",
"N. c #B2B2DB",
"B. c #E0E0D2",
"V. c #8A8AE3",
"C. c #8181E5",
"Z. c #8686E4",
"A. c #8787E5",
"S. c #D2D2CD",
"D. c gray82",
"F. c #E7E7D1",
"G. c #DCDCD3",
"H. c #E3E3D2",
"J. c white",
/* pixels */
"  . X o O + @ # $   $           ",
"  % X & * = - ; :   $           ",
"> , < 1 2 3 4 5 6 7 $           ",
"> 8 9 0 q w e r t 7 $           ",
"$ > y u i p a s d f $           ",
"  g h j u k l z x >           $ ",
"c v b n X m M N z B V C Z Z $   ",
"A S D F 7 G H J K L P O @ I # $ ",
"U Y T R E W Q ! ~ ^ / @ ( ) _ d ",
"` ' 4 ] [ { 4 } | 4  ...X.4 o.O.",
"+.@.4 #.$.%.&.*.=.4 -.Y ;.:.>.,.",
"<.1.2.! ! 3.$.E K a 4.5.6.7.8.d ",
"E 9.0.=.q.w.e.r.t.y.u.i.p.a.s.d.",
"` f.4 g.h.j.4 k.l.z.x.c.X.4 v.b.",
"n.m.M.N.B.V.C.U $ N 6.n.Z.A.S.D.",
"A n.F.G.<.1.H.3.  >   $ H.H.$ $ "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
};
const int n_xpm_icons = 4;
