/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 76 1 ",
"  c #010101",
". c #0D0D0D",
"X c #141414",
"o c #1E1E1E",
"O c #232323",
"+ c #2C2C2C",
"@ c #343434",
"# c #393939",
"$ c #007D00",
"% c #434343",
"& c #4C4C4C",
"* c #565656",
"= c #5C5C5C",
"- c #646464",
"; c #6A6A6A",
": c #737373",
"> c #7B7B7B",
", c #008300",
"< c #038A03",
"1 c #0B8E0B",
"2 c #0E900E",
"3 c #128C12",
"4 c #188F18",
"5 c #149114",
"6 c #1B941B",
"7 c #229722",
"8 c #259925",
"9 c #2B9A2B",
"0 c #329E32",
"q c #3BA23B",
"w c #44A544",
"e c #4BA74B",
"r c #4DA94D",
"t c #53AA53",
"y c #5CAE5C",
"u c #65B265",
"i c #6BB56B",
"p c #71B771",
"a c #73B873",
"s c #7CBB7C",
"d c #828282",
"f c #8C8C8C",
"g c #969696",
"h c #999999",
"j c #82BE82",
"k c #A4A4A4",
"l c #ABABAB",
"z c #B2B2B2",
"x c #BDBDBD",
"c c #87C087",
"v c #8CC28C",
"b c #92C492",
"n c #9AC79A",
"m c #9CC89C",
"M c #A5CBA5",
"N c #ABCEAB",
"B c #B3D1B3",
"V c #BCD5BC",
"C c #C4C4C4",
"Z c #CBCBCB",
"A c #C1D7C1",
"S c #C6D9C6",
"D c #CCDCCC",
"F c #D4D4D4",
"G c #D3DED3",
"H c #DDDDDD",
"J c #D6E0D6",
"K c #DBE1DB",
"L c #E5E5E5",
"P c #E9E7E9",
"I c #ECEBEC",
"U c #F2EBF2",
"Y c #FAEDFA",
"T c #F5F5F5",
"R c #FFF2FF",
"E c #FAFAFA",
/* pixels */
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"   .@@@@@@@@@@@#@@@@@@@@@@@@@@@#oO#@@@@@@@@@@@@@@@@@@@@@@@@@@#Oo@@@@@@@@@@@#@@@@@@@@@@@@@@@#.   ",
"   #ETTTTTTTTITTTTITTTTTTTTITTIEfkEITTUTTTITTTTTTTTITTTTTTTTTEkfETTTTTTTTTITTTUTUTTTTTTITTIE#   ",
"   @THHLHKLKLLHLLKLLKLKLLLLLHLHEphTLLLLKLKLLKLKLLLLLHLKLHLHLHTgdEHHLHKLKHLLLLKLLKLKLLLLLHLHT@   ",
"   @TLLLLLLPLPLLLPLPLLLLLLLLLLLE>gTLLLLLLPLLPPLLLLLLLLLPLLLLLThdEHLPPLLPLLLLLLLPLPLPLLLLLLLT@   ",
"   @THLLPLPLPLLLLLPLPLLLLLLLLLKEdhTLPLLLLLPLLPLLLLLLLLPLLLLLLThdELLLLLPLLLILLLLLLLLLLLLLLLLT@   ",
"   @TKPLLLLLLLLLLPLPLLPLLLLLLLLEdhYLLLPLPLLLLLLLPLPLPLPLLLLLLEhdELLLLLLPLPLLLLLLLPLPLLLLLPLT@   ",
"   @TLLPPLLPPLLPLLPLLPLLLLPLLLHEdhYHLPLPLPLPPLLLLLLLLLLLPLLPKThdEKLLLLLLPLPLLPLLPLPLPLPLPLLI@   ",
"   @TLLLLLPLLLLLLLLLLLLLPLLPPLLTdhYPLLLLLPLLLLLLLLLLLLPLLLPLLEhdELLPPLILLLLLLILLPPLLLLLLLPLI@   ",
"   @TKLLLPLPLLLLLLLLLLLLLLLPLPHEdhYLLPLLLLLLLLLLKLLLLLLLLPLPLThdEKLLLLLLPLLLLLLLLKLLLLPLLLLT@   ",
"   #TLLLLLLLLLILLLPUIILLLPLLLPKEdhTLLLLPLLLLLTTITITILLLPLLLLLEhdELLLLLLLLLPLLIUIIIILLLPLLLLT@   ",
"   @TKLLLPLPLLLLLUn78qJLLLLLPLLEdhTLLLLLLPLLLz;%+@*zILLLPLLLKThdEKPLLPLPLLLLIBy00wjLLLLPLPKT@   ",
"   @TLLPPLPLLLLLID5,<1GLLLLLLPLEdhTLLPLPLLLLLO      gILPLLLLLEhdELLLLPLLPLLIc<,,<,3GILLLLLKT@   ",
"   @TKLLLLLLLLLLIe,5<2JILLLLLLHEdhTLLLPLLLLLL@*kz*  +LLLLLLLLThdTLLLLLLPLLIN1,qBDNsGLLLPLPLT@   ",
"   @TKLLLLLLLPLUb,yy,2GILLPLLLKEdhTLLLPLLLLLLZITILO oCILLLLPKEhdELLLLLLLLKUt,6GLHIYLLLLLLLLI@   ",
"   @TLLPLLLLLLID35Ky,3GLLLLPPLLEdhTLPPLPLLILLILKIHo @LLLLLLLLThdEKLLLPPLLPK9,7w,<0NULPLLLLLT@   ",
"   @TLLLLLLLLLLr,nYt,2GPLPLLLPKEdhELLLLLLLLLLLLPI=  hTLLLPLLPThdELLLLLLPLID6<,<71,1VILLLLLLT@   ",
"   @ILLPLLPLLTb,yIUt,2GPLLPLLLLTdhTKPLLLLPLLLKIL*  fTKLLPLLPLThdEKLLLPPLLIS6,<bYv<,uILLILLLT@   ",
"   @TKLLPLLPKYu,5551,<2iILLLLLLEdhTLLLLLPLLPLIF# .gILPLLLPLLLEhdELLPLLPLLLK9,5DIJ1,eLLLLLPLT@   ",
"   @TLLLLLLLLYp,<<<,<<,yILLLLLHEdhTLLPLLLPLLPC+ XlTPPPLPPLLLKThdEKPLPLLLLLUt,3VRV1,uILLLLLKT@   ",
"   @TLPLLLLLLISMNNBw,5mSLLPLLLHEdhTLLLLLLLLLI@  @=&&*ZILLPLLLEhdELLLLLPLLLIN1,qbq,<NILLLLLLT@   ",
"   @ULLLPLPLLLIUIIYt$3KILPLLPLLEdhTLLPLLPLLLLO      .zTKLLLLLThdTLLLLLLLLLLIc2,$,1jILLPLLLLU@   ",
"   @THLLLLLLLPLKLLPMijKLLLLLPLLEdhTLLLLLLPLLLf:>>>>>dFILPLLLLThdEHLLILLLPLLLUSvsbDILLLPLLLLI@   ",
"   @THLLILLLLPLLLLLIYYLLLLLILLHEdhTLLLLIPLLPLTETEEEETPLLLLLLLThdEHLLLLPLLLLLLPYYYPLLLLLLLLLT@   ",
"   @TLLLPLPLPLLPLLLLLLLLLLLLLLHEdhTLLPLLLPLLLKLLLHLKLLPLLLLLLThdELLLLLPLPLPLLLLLKLLLPLPLLLLI@   ",
"   @TLLPLPLPLPLLLLLLLPLLPPLLLLLEdhTLPLLLLPLLLLLLLLLLLLLLPLPLLThdELLLLPLPLLLLLLLLLLPLLPLLLLLT@   ",
"   @TLLLLLLLLLLLLPLLLPPLLPLLLLHEdhTLLPLLLLLLLPLLLLLLLLLLLLLLLThdELLLLLLLPLLPLLLLLPLLPPLLLLLT@   ",
"   @TLLPPLLLLLLLLLLLLLLLLLLLLPLEdhTLPLPLLLLPLLLLLPLPLLPLLPLPLThdTLLLLLLLLLLLLLLPLLLLLLPLLLHT@   ",
"   @IKLHKLKLLHLHLHLHLKLHKLKLLHHEpfTLKLKLHLHLLHHLLHLKHLLHLHHLHYgaEHHLLLHLLKKLKLHLLLLHKLKLLLHT@   ",
"   #ETEEEEEEEEEEEEEEEEEEEEEEEETEfkETEEETEEEEEEEEEEEEEEEEEEERTYkfETEEETEEEEEEEEEEETEEEEETEETE#   ",
"   ofddddddddddddddddddddddddddf&*fddddddddddddddddddddddddddf*&fddddddddddddddddddddddddddfo   ",
"   Okghghhhhhhhhhhhhhhhhhhhhhhgl*;khhhhhhhhhhhhghhhhhhhhhhhggk;*khhhhhhhhhhhhhhhhhhghhhhhhgkO   ",
"   @ETTTTEETTETTTETETETETTTEETTEfkYYTETRTTTTETTTTTTETETTTTTTTEkfETTTETTTTTTTTETTTTTTTTTETTTE@   ",
"   @TKLLLLKLLLLLLLKLLLKLLLHLLLHTdgYHLHLLLKLLLLLLLLLLKLLLPLLLLTgdTKLLLLLLLLLLKLLLPLLLLLLLLLLI@   ",
"   @TKLPLLLLLLLLLLLLLLLLLLLLPLLEdhTLLLPLLLLLLLLILPPLPLLLLLPLLTgdEKPPLLLLLLPLPLLLLPLLLLLLLLLT#   ",
"   @TLLLPLLPLLLPLLPLLPPLLLLPLPKEdgTLLLLLILLLLLLLLLLLLPPLLLLLLThdELPLLLLLLLLPPLPLPLPLLPPLILLI@   ",
"   @TKLLLLLLLLLPLLLPLLLLLPLPLLLEdhELLPLPLLLLILLLLLLLPLPLLLLLPThdEKLLLLPLLLLLLLPLLLLLLLLLLLKT@   ",
"   @TLLLPLLPLLLLLPLLLPLLPLPLLLHEdhTLLLLLLLILLLLLLLLLLLLLLLPLLThdELLLILLLLILLLLLLLPLLLLPLLLLT@   ",
"   @TLLLLLILLLLLPLLLLLLLPLPLLLKEdhTLLLLLLLLLLLLILLLLLLPLLLPLLThdELLLLPLLLLILLILLLLLLLLLLILLT@   ",
"   @TLLLLLLLLLPKLKLLLKLLLLLPLPLEdhTLLPPLLLLLLILLLLLLPLLLILLPKEhdEKLLPLPLLLLLLLLLLPPLILLLLLKT@   ",
"   @TLLLLLLLLLLTTTTETEILLLLLLPKEdhTLLLLLLLLLLLLILILLLLPLLLLLLEhdELLPLLLLLILLLLILLLLLLLILLPKT@   ",
"   @ULLLLLLLLLIf#%%%%#hTLLPLLLLTdhTLLPLLLLLILLLLLLLLPLLPLLLPLThdEKLLPLPLLLLLILLLLLPLLLLLPPKT#   ",
"   @TLLLPLLPLLI=      :TLLLLLLHEdhTLLLLPLPLLLPLLLLILLLPLLLPLLEhdELPLLLLLLLILLILLLLILLLLLLLLT@   ",
"   @ILPLLLLLLPI- @gff>zILLLLPPHEdhTLLLPLPLLPLLLLLLLLLLLPPLLLKThdEKLLILLLLLLLLLLLLLLLLLLIPLKT@   ",
"   @TKLLPLLLLLI- #d:gLTLLLLLLLLEdhTLLLLPLLPLLLLLLLLLLLLLLLPLLEhdTLLLLLILLLLLLLLLLLILLLLLLLLT@   ",
"   @TLLLLLLLLLI=     oxILLLILLKEdhELLLPLPLLLPLLLLLLILLLLPLLLLThdTKILLLLLLLLIILLLLLLLILLLLLKT@   ",
"   @UKLLLPLLLLI-+>>@  #LLLLLILLEdhTLILLLLILLLLLILLLLLLLLILLLLThdEHPLLLLLLLLLLLLLLLLPLLLLLLLI@   ",
"   @TLPLPLLLLPLGIITHO  xILLLLLHEdhTLLLLLLLLLLLLLILLLLLLLLLLLKThdEKLPPLLPPLLPLLLIPLPLLLLPLLLT@   ",
"   @TKLLLPLPPLPILKLI=  zILLPLLLEdhTKLLILLLLIILLLLLILLILLLLILLThdELLPLLPLLLLLLILLLLLPLLLLLLLT@   ",
"   @TLPLPLLLLIFlPTIH+  CILPLPLKEdhTLLLLLLLLLLLLLILLLLLLILLLLLThdEKPLLPLPLLLPLLLLLLPLLLLPLLLT@   ",
"   @TLLLPLLLLLD.@>d#  #LPLLLLLKEdhTLLILLILLLLLLILLLLLLLLLLLILThdELLLLPLLLLLLLPLLPLPLLPLLLLLT@   ",
"   @TLLLLLLILPFo     +CILPLLLLLEdhTLLLLLLLILLLLLLLLIILLLLLLLLThdEKLLLLLPLLLPLLLLLLLLLLLLLLLT@   ",
"   @TLLLPLLLLLLFg:-;gLILLLLLLLLEdhTLLLLLILLLLLPLLLLLLLLLPLLLLThdELPLLPPLLPLLLLLLLLLLPLPLLLHT@   ",
"   @ILLLLPLLLLLPTTTTTPLLLLLPLLLTdhTLLILLLLLLLLLLILLLLLILLPLLLThdEKLLLLLPLLPPLPLPLLLLLPLPLLHT@   ",
"   @TLLLLPLLLLLLLKLKLLPLLLPLLPHEdhTLLLLPLLLLPLPLLLLLLLPLPLLLLThdELLLLLPLLPLPLLLLLLLILLLLLLLT@   ",
"   @TKPLLLLLLLLLLLLLLLLPPPLPLPHEdhTLLLPLLLLPLPLLLPLPPPLLPLLPKEhdEHLLLPLLLLLLLLLLLILLLLLILLLT@   ",
"   @ILPLLLLLLLLLPLLPLLPLLLLLLPLEdhTLLLLPLLPLPLLLLLLLLLLLLPLLLEhdELPLLLLPLLLPLLPLLLILLLLLLLHT@   ",
"   @TLLPPLLPLLLILLLPPLLPPLPLLLHEdhTLLPLLLLLLLLPLLLLLPLLLLLLLLThdEHLPLPLLLPPLPLLLLLLLLILLLLLT@   ",
"   @TKLLLLLPLLLLLLLLLLLLKLLLHLHEdhYHLLLLLLLLLLLLLLLLLLLLLLLLKThdRHLHLLLPLLLKLLLLLLLLLLLKLLHT@   ",
"   #ETTTTTTTTETTTTTTTTTTTETTETTEfkRYTTTTETTTTTTTTTTTETTTTTTTTEkfYYTETTTTTTETETTTTTTTTTETTETE#   ",
"   Okghhghhhhhghhhhhhhhhhhhhhhgl*-kghhhhhhhhhhhhhhhhhhhhhhhhgk;*kghhghhhhhhhhhhhhhhhhhhhhhgkO   ",
"   ofddddddddddddddddddddddddddf&*fadddddddddddddddddddddddddf*&fadddddddddddddddddddddddd>fo   ",
"   #ETEEEEEEEEEEEEEEEEEEEEEEEETEfkYYRETEEEEEEEEEEETEEEEETEEETEkfYYEEEEEETEEEEEEEEEEEEEEEEETE#   ",
"   @THHLKLLKKLKLHLLHKLHLLHHLHLHEagYHHLLLLHLHKLLKKLLLLHLHLKLKLTfpYHHLHLLHLKLKKLHLLHHLLKKLLKKI@   ",
"   @TLLLLLLLLLLLLLLLLPLLLLLLLLLEdhTKLLPLLLLLLLLLPLLLLLLLLPLLLThdRLLLLLLLLPPLLLLLLLLLLLLLLLLT@   ",
"   @TLLLLLLPPLLPLPLLLLPLLLLPLLHEdhELLLLLLLLLLLLLLLPLLLLLLLPPLThdELLLLLLLLLLLLPLPPLLLLPLPLLLU@   ",
"   @TLLLLPLLLLLLLPLILLLLPLLPLLLEdhTLLLLLILPLLLLPLPLLLLLLLLPLLThdTLLLPLLILPLLLLLLLLLLPLLLLLHT@   ",
"   @ILLLLLLLPPLLLLLLLLLLLLPLPLHEdhELLPLLLLLPPLLPLLLPILLLLLLPLThdEKPLLLLLPLLPLLILLPLLLPLLLLLT@   ",
"   @ILLLLPLPLPLLLLPLLPLLLLLPLLLEdhEKPLLPLPLLLLLPLPPPLPPLLLLLLThdELPLPLLLLLLLLPLLPLILPLLPLLLT@   ",
"   @TLLLLLPLLLLHLHLHLKLLPLLPLLHEdhTLLLPLLLPLLLLKLKKLLLLPILLLLThdEKLPLPLLLLLLLLLKKLLLLPLLLLLT@   ",
"   @UKLLLPLPLLIEEEEETEELLLLPLPKEdhTLLLLPLLLLLPUYTYUILLLLLLLPLTgdEHLLLLLLLILLITEEELLLPLPLLLKT@   ",
"   @TLPLPLPLLPA-==-===-FLLLLLLLEdhTLLLPLLPLLLDbauujSILLLPLLLLThdELLLLLLLLLLKld-=;KLLLLLLLILT@   ",
"   @TKLLLLLLLIk        xTLPLLLKEdhTLLLLLILLLUy$$$,,2mULLLLPLLThdEHLILLLLPLTk    XGILLLLLLLLI@   ",
"   @TLPLLLPLLIZ;----. +FPKLPLLLEdhTLLILLLLLLIiesjq<,9LLLPPLPPThdELLLLPLPLLIl+:@ XHLLLLPLLLLT@   ",
"   @TLLLPLLLLLLTIIEk  >TLLLPLPKEdhTLLPLPLPLPLLIYRL6,9KLLLLLLLThdELLLLPLLLLLLLT* XHLLLPLLPLLT@   ",
"   @TLLLLLLLLLLLLLL% XFILLPLPLLEdhTLLLLLLLLLLLHBBu1,uILLPLLLLThdEHLLPLLLLPLLLI& XHILPLPLLLKI@   ",
"   @TLLLPLLLILLLLIz  -TKLLLLLLHEdhTLLLLLLLPLLIN,$,<yILLLLLPLLThdELLLLPLPLLLLLI& XHLLLPLLLLLT@   ",
"   @ILLLLLLLLLLLKT* .xILLLLLLLLEdhTLLLLPLLLPLIVew6<1sULLLLLLLThdEHLLPLLLLLLLLI& XHPLLLPLPLLT@   ",
"   @TKLLLLPLLLLLICX &TLLLLLLPLKEdhTLLLLPLLPLPLPYID9,5SIPPLPLLThdEKLLPLLPLLLLHI& XFLLLLLPLPLT@   ",
"   @TLLPPLLLLLLLT;  lILLLLLLLLLEdhELLLLLLLLLKLUPIYw<1NUKLPLLLThdELLLLLLLPPLLIT* XLTILLLLPLLI@   ",
"   @TKLLLLLPLLLIFo #LPLLPLLPLLKEdhTKPLLPLLLISqimmy1,5GPLLLLLLThdELLLLLLLLLIFhk@ XhgVILLPLPKT@   ",
"   @TLLLPLPLLLKT>  gTKLLLPLLLLLEdhELLPLLLLLIA3,,$$,<bULLPLLLLThdEKLLLPPLLLIz       :TLLLLLLT@   ",
"   @TLLPLLLLLLLL;@*HLLPLPLPLLPKEdhTLLPLPLPLLLMirwtaSILLLLLPLLYhdEKPLPLPLLLLC%%%%%%@hTLLLLLLT@   ",
"   @TKLLLLLLPLPLTTTLLLLLLLLLPLLEdhTPPLPLLLLLLIUTYYUILPLLLLLLPYhdELLLLLLPLPPLTTTTETEILLLLPLKI@   ",
"   @TLLLLILLPLLLLLHLLLLPPLLLLLLTdhTLLLPLLLLLLLLLKLLLLLLLPLPLHYhdEHLILLLLPLPLLLKLHLHLLLLPLLLT@   ",
"   @TLLLLLLLLPLLLLLLPLPLLPLLLLLEdgTLLLLLLPLLLLLLLLLLLLPPLPLLLYhdELLLLLLLLLLLLLLLPLLLLLLLLLLT@   ",
"   @TLLLLLLPLLLLPLLLLLLLPLLLLLKEdhYLLLLLPLLLLLLLLPLLLLLLLLLLLThdELLLLPLPLLLLLLLLLLLLLLLLPLHT@   ",
"   @TLLLLLLLPLLLLLLLLLLLLLLLPPLEdhYLLPLLLLLLLLLLPLPLLPLPLLLLLTg>EHLLPLLLLLLLLPLLPLLLPPLLLLLT@   ",
"   @THLHHLKLLHLLLLLHLLLLLLKLLKHTpfTLHHLHLLLHLLLLLLLLLKKLLLLLLThpTHLLLKLKLLLLLKLLLLKLLLLHLLHT@   ",
"   #EITTTTTTTTTIITTTITTTTITTTTTEfkEIYYYTITTTITTTTIITTTTTITTTIEkfETTITTTTITTTTTTUITTTTITTTTIE#   ",
"   .#@@@#@@@@@@@@@@@@@@@@@@@@@@#OO#@@@@@@@@@@@@@@@@@@@@@@@@@@@Oo#@@@@@@@@@@@@@@@@@@@@@@@@@@#.   ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"48 48 225 2 ",
"   c black",
".  c #010101",
"X  c #111111",
"o  c gray7",
"O  c #101010",
"+  c gray5",
"@  c gray81",
"#  c #DDDDDD",
"$  c gray85",
"%  c #DADADA",
"&  c gray88",
"*  c gray77",
"=  c #A7A7A7",
"-  c gray89",
";  c #D8D8D8",
":  c #ECECEC",
">  c gray91",
",  c #E9E9E9",
"<  c #EEEEEE",
"1  c gray82",
"2  c #B2B2B2",
"3  c gray95",
"4  c #E7E7E7",
"5  c #E4E4E4",
"6  c gray90",
"7  c #E3E4E3",
"8  c #E2E4E2",
"9  c #EAEAEA",
"0  c #CDCDCD",
"q  c #AFAFAF",
"w  c #E2E2E2",
"e  c #E2E3E2",
"r  c #E6E6E6",
"t  c #E4E5E4",
"y  c #EEE9EE",
"u  c #F1EAF1",
"i  c #E8E6E8",
"p  c gray92",
"a  c #CECECE",
"s  c #EFEFEF",
"d  c gray96",
"f  c gray94",
"g  c #F3F3F3",
"h  c #E7E6E7",
"j  c #F4EBF4",
"k  c #EFE9EF",
"l  c #F0EAF0",
"z  c #F5ECF5",
"x  c #97C697",
"c  c #249824",
"v  c #BCD5BC",
"b  c gray93",
"n  c gray75",
"m  c gray25",
"M  c gray18",
"N  c gray46",
"B  c #6BB46B",
"V  c #369F36",
"C  c #69B469",
"Z  c #E8E9E8",
"A  c #E3E5E3",
"S  c #C7D9C7",
"D  c #269826",
"F  c #028602",
"G  c #A7CBA7",
"H  c #F2EBF2",
"J  c #B7B7B7",
"K  c gray55",
"L  c #989898",
"P  c #AEAEAE",
"I  c #F1F1F1",
"U  c #E1E1E1",
"Y  c #F6ECF6",
"T  c #6DB46D",
"R  c #1E941E",
"E  c #99C799",
"W  c #AFCFAF",
"Q  c #E9E7E9",
"!  c #50AA50",
"~  c #AACEAA",
"^  c #1F961F",
"/  c #AFD0AF",
"(  c white",
")  c #9F9F9F",
"_  c #EDE9ED",
"`  c #359D35",
"'  c #1A941A",
"]  c #319D31",
"[  c #54AB54",
"{  c #B6D2B6",
"}  c #108B10",
"|  c #4CA94C",
" . c #018A01",
".. c #45A545",
"X. c #E6E5E6",
"o. c gray57",
"O. c gray12",
"+. c #C8C8C8",
"@. c #2F9B2F",
"#. c #52AA52",
"$. c #DCE2DC",
"%. c #008200",
"&. c #C0D5C0",
"*. c #EDE8ED",
"=. c #E7E8E7",
"-. c #D6DFD6",
";. c #96C696",
":. c #82BD82",
">. c #048604",
",. c #AAAAAA",
"<. c gray19",
"1. c #4B4B4B",
"2. c #B1B1B1",
"3. c #F3EBF3",
"4. c #8CC28C",
"5. c #1B941B",
"6. c #47A647",
"7. c #2A9A2A",
"8. c #DEE3DE",
"9. c #E7E5E7",
"0. c #9BC89B",
"q. c #DAE1DA",
"w. c #ECE8EC",
"e. c gray79",
"r. c #929292",
"t. c gray56",
"y. c gray50",
"u. c #ADCFAD",
"i. c #87C087",
"p. c #D7E0D7",
"a. c #EBE8EB",
"s. c #E1E3E1",
"d. c #F3EAF3",
"f. c #F8F8F8",
"g. c #F0E9F0",
"h. c #F7ECF7",
"j. c #E8EAE8",
"k. c #EAEBEA",
"l. c LightGray",
"z. c #B4B4B4",
"x. c #E9EAE9",
"c. c #B9B9B9",
"v. c #9D9D9D",
"b. c #D7D7D7",
"n. c gray80",
"m. c #868686",
"M. c #B6B6B6",
"N. c #F9F9F9",
"B. c gray70",
"V. c #3A3A3A",
"C. c #1E1E1E",
"Z. c #313131",
"A. c #373737",
"S. c #202020",
"D. c gray33",
"F. c #CBCBCB",
"G. c #ACACAC",
"H. c #282828",
"J. c gray26",
"K. c gainsboro",
"L. c #2F2F2F",
"P. c #DFDFDF",
"I. c gray13",
"U. c gray83",
"Y. c #FBFBFB",
"T. c #F9EDF9",
"R. c #FAEEFA",
"E. c gray98",
"W. c #6C6C6C",
"Q. c #626262",
"!. c #6A6A6A",
"~. c #74B874",
"^. c #61B161",
"/. c #A6CCA6",
"(. c #C0C0C0",
"). c #808080",
"_. c gray42",
"`. c #0C0C0C",
"'. c #505050",
"]. c #F4F4F4",
"[. c #C2D7C2",
"{. c #6AB36A",
"}. c #008300",
"|. c #B7D3B7",
" X c gray67",
".X c gray22",
"XX c #181818",
"oX c #FEFEFE",
"OX c #B4D1B4",
"+X c #42A442",
"@X c #289A28",
"#X c #D9E1D9",
"$X c gray97",
"%X c #646464",
"&X c #353535",
"*X c #F2EAF2",
"=X c #C6D9C6",
"-X c #71B771",
";X c #BAD4BA",
":X c gray66",
">X c gray8",
",X c #D2D2D2",
"<X c gray4",
"1X c #A0A0A0",
"2X c #87BF87",
"3X c #8DC28D",
"4X c #A1CAA1",
"5X c #E1E2E1",
"6X c #CACACA",
"7X c #5A5A5A",
"8X c #090909",
"9X c #8D8D8D",
"0X c gray38",
"qX c #BBD5BB",
"wX c #51AA51",
"eX c #49A749",
"rX c #94C594",
"tX c #A5A5A5",
"yX c #464646",
"uX c #585858",
"iX c #515151",
"pX c #D5D5D5",
"aX c #F8ECF8",
"sX c #E5E7E5",
"dX c #E6E7E6",
/* pixels */
"                                                                                                ",
"        . . . . . . . . . . . .     . . . . . . . . . . . .     . . . . . . . . . . . .         ",
"                                                                                                ",
"      . X o o o o o o o o o o o O + o X o o o o o o o o X o + O o o o o o o o o o o o X .       ",
"  .   X @ # $ % % % % % % % $ & * = - ; % % % % % % % % ; - = * & $ % % % % % % % $ # @ X   .   ",
"  .   o # : > , , , , , , , > < 1 2 3 4 , , , , , , , , 4 3 2 1 < > , , , , , , , > : # o   .   ",
"  .   o $ > 5 6 6 6 7 8 5 6 5 9 0 q < - 6 6 - w - w 5 6 - < q 0 9 5 6 6 5 e 7 7 6 5 > $ o   .   ",
"  .   o % , 6 6 r t y u i 6 6 p a q s - r 5 : d f g 4 6 5 s q a p 6 r 6 h j k l r 6 , % o   .   ",
"  .   o % , 6 r 8 z x c v y 7 p a q s - 5 b n m M N r r - s q a p 6 6 h 7 B V C h t Z % o   .   ",
"  .   o % , 6 A k S D F G H 8 p a q s - 5 < J K L   P I U s q a p 6 8 Y T R E W r t , % o   .   ",
"  .   o % , t 6 Q ! ~ ^ / z 8 p a q s - r 5 , ( ) O 0 p w s q a p t t _ ` ' ] [ 6 6 > % o   .   ",
"  .   o % , 8 l { } |  ...8 X.p a q s - 6 5 s o.O.+.d w 5 s q a p 6 t H @.#.$.%.&.*.=.% o   .   ",
"  .   o % , 5 Q -.;.:.>.T Q t p a q s - - I ,.  <.1.2.s U s q a p 6 7 3.4.5.6.7.8.9.> % o   .   ",
"  .   o % , 6 6 i Y H 0.q.w.7 p a q s - 5 p e.r.t.y.+.p w s q a p 6 6 6 _ u.i.p.a.7 , % o   .   ",
"  .   o $ > 5 6 t s.8 d.h 5 5 p 0 q < - 6 5 9 d d f.p 5 - < q 0 p 5 6 6 7 g.h.i 5 5 > $ o   .   ",
"  .   o & < 9 p p p p j.k.p 9 I l.z.d , p p 9 > > > 9 p , d z.l.I p p p p x.j.k.p 9 < & o   .   ",
"      O * 1 0 a a a a a a a 0 l.c.v.b.n.a a a a a a a a n.b.v.c.l.0 a a a a a a a 0 1 * O       ",
"      + = 2 q q q q q q q q q z.v.m.M.P q q q q q q q q P M.m.v.z.q q q q q q q q q 2 = +       ",
"  .   o - 3 < s s s s s s s < d b.M.N.b s s s s s s s s b N.M.b.d < s s s s s s s < 3 - o   .   ",
"  .   X ; 4 - - 5 w w U - 5 - , n.P b U - - - - - - - - U b P n., - - - - - - - - - 4 ; X   .   ",
"  .   o % , 6 r 6 : f I 9 6 6 p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 6 6 r n.c.B.1 , 5 p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 5 5 b V.C.Z.L 3 w p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 5 5 : A.S.D.F.p - p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 6 6 4 q G.H.J.g w p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 5 > K.c.3 1.L.3 - p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 5 4 P.J.I.S.q < - p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   o % , 6 6 > , U.r < 5 6 p a q s - r r r r r r r r - s q a p 6 r r r r r r r 6 , % o   .   ",
"  .   X ; 4 - 5 - - > 5 U 5 - , n.P b U - - - - - - - - U b P n., - - - - - - - - - 4 ; X   .   ",
"  .   o - 3 < s s s < < s s < d b.M.N.b s s s s s s s s b N.M.b.d < s s s s s s s < 3 - o   .   ",
"      + = 2 q q q q q q q q q z.v.m.M.P q q q q q q q q P M.m.v.z.q q q q q q q q q 2 = +       ",
"      O * 1 0 a a a a a a a 0 l.c.v.b.n.a a a a a a a a n.b.v.c.l.0 a a a a a a a 0 1 * O       ",
"  .   o & < 9 p p p p p p p p I l.z.d , p p p p p p p p , d z.l.I p p p p p p p p 9 < & o   .   ",
"  .   o $ > 5 6 5 U U U w 6 5 p 0 q < - 6 6 t s.s.8 6 6 - < q 0 p 5 6 6 - U U 6 6 5 > $ o   .   ",
"  .   o % , 6 6 4 N.Y.f.g 6 6 p a q s - r 6 Q T.R.u 6 r - s q a p 6 r 5 b E.d r 6 6 , % o   .   ",
"  .   o % , 5 > % W.Q.!.o.9 5 p a q s - 6 Q -.~.^./.Q 6 - s q a p 6 5 : (.W.).- r 5 , % o   .   ",
"  .   o % , 5 > % _.!.`.'.].w p a q s - t *.[.~.{.}.|.k s.s q a p 6 - <  X.XXX& 4 5 , % o   .   ",
"  .   o % , 6 6 r oXK.O c.f - p a q s - r 7 k OX+X@X#XQ e s q a p 6 r U Y.,.X P.4 5 , % o   .   ",
"  .   o % , 6 r U $X%X&Xg - 6 p a q s - r 7 *X=X-X' ;Xy s.s q a p 6 r w E.:X>X3 , 5 , % o   .   ",
"  .   o % , 6 5 9 ,X<X1Xg - 6 p a q s - t k ~ 2X3X}.4X3.5Xs q a p 6 5 9 6X7X8X9X# r > % o   .   ",
"  .   o % , 6 5 s 2.0X6 r 6 6 p a q s - t *.qXwXeXrXQ 6 - s q a p 6 - f tXyXuXiXpX, > % o   .   ",
"  .   o $ > 5 6 5 9 d 6 5 6 5 9 0 q < - 6 7 w.T.aX*X6 6 - < q 0 9 5 6 - b f.d $X4 - > $ o   .   ",
"  .   o # : > , , > 6 > , , > < 1 2 3 4 , , =.sXsXdXZ , 4 3 2 1 < > , , 4 6 6 6 > > : # o   .   ",
"  .   X @ # $ % % % % % % % $ & * = - ; % % % % % % % % ; - = * & $ % % % % % % % $ # @ X   .   ",
"      . X o o o o o o o o o o o O + o X o o o o o o o o X o + O o o o o o o o o o o o X .       ",
"                                                                                                ",
"        . . . . . . . . . . . .     . . . . . . . . . . . .     . . . . . . . . . . . .         ",
"                                                                                                "
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"32 32 187 2 ",
"   c black",
".  c #010101",
"X  c gray6",
"o  c #101010",
"O  c gray5",
"+  c #111111",
"@  c #CDCDCD",
"#  c gainsboro",
"$  c #D8D8D8",
"%  c gray85",
"&  c #D8D9D8",
"*  c gray80",
"=  c gray70",
"-  c #DFDFDF",
";  c gray93",
":  c gray91",
">  c #E8E9E8",
",  c #EAE9EA",
"<  c #EDEBED",
"1  c gray86",
"2  c #C0C0C0",
"3  c #EFEFEF",
"4  c #E9E9E9",
"5  c #EEEEEE",
"6  c #ECECEC",
"7  c #E7E8E7",
"8  c #EBEAEB",
"9  c #F0ECF0",
"0  c gray89",
"q  c #E6E5E6",
"w  c #E3E4E3",
"e  c #D3DED3",
"r  c gray90",
"t  c #D7D7D7",
"y  c gray74",
"u  c gray92",
"i  c #E7E7E7",
"p  c #D0D0D0",
"a  c #CACACA",
"s  c #ECE7EC",
"d  c #DCE1DC",
"f  c #C4D8C4",
"g  c #E1E3E1",
"h  c #E9E8E9",
"j  c #E2E4E2",
"k  c #F7ECF7",
"l  c #5DAF5D",
"z  c #37A037",
"x  c #EFE9EF",
"c  c gray",
"v  c gray88",
"b  c #717171",
"n  c gray22",
"m  c gray51",
"M  c gray95",
"N  c #ECE8EC",
"B  c #C8DAC8",
"V  c #43A443",
"C  c #6FB66F",
"Z  c #D9E0D9",
"A  c #ECEAEC",
"S  c #F1E9F1",
"D  c #9EC99E",
"F  c #54AB54",
"G  c #48A748",
"H  c #E7E6E7",
"J  c #E4E4E4",
"K  c #E2E2E2",
"L  c white",
"P  c gray42",
"I  c gray48",
"U  c gray96",
"Y  c #E5E7E5",
"T  c #F7EDF7",
"R  c #7BB97B",
"E  c #2A992A",
"W  c #68B468",
"Q  c #C7D9C7",
"!  c #EFEBEF",
"~  c #E6E8E6",
"^  c #74B874",
"/  c #3CA13C",
"(  c #148D14",
")  c #BFD6BF",
"_  c #F1ECF1",
"`  c #D6D7D6",
"'  c gray37",
"]  c gray19",
"[  c gray81",
"{  c #F6ECF6",
"}  c #86BF86",
"|  c #4EA84E",
" . c #4AA24A",
".. c #97C497",
"X. c #F8F0F8",
"o. c #D6D8D6",
"O. c #CADACA",
"+. c #6F6F6F",
"@. c #656565",
"#. c #9A9A9A",
"$. c #EAEAEA",
"%. c #80BD80",
"&. c #85BF85",
"*. c #F6EEF6",
"=. c gray98",
"-. c #F9F9F9",
";. c gray94",
":. c #F8EFF8",
">. c #D7D8D7",
",. c #D5D7D5",
"<. c #CBCBCB",
"1. c #B2B2B2",
"2. c gray87",
"3. c #D5D5D5",
"4. c gray83",
"5. c gray84",
"6. c gray61",
"7. c #C3C3C3",
"8. c #BCBCBC",
"9. c #C1C1C1",
"0. c #747474",
"q. c gray56",
"w. c #E6E6E6",
"e. c #F4F4F4",
"r. c gray59",
"t. c #060606",
"y. c #686868",
"u. c #D2D2D2",
"i. c gray75",
"p. c gray16",
"a. c #A7A7A7",
"s. c #606060",
"d. c gray25",
"f. c #B6B6B6",
"g. c #F6F6F6",
"h. c #E8E7E8",
"j. c #DADADA",
"k. c #CECECE",
"l. c #D7DFD7",
"z. c #D6DFD6",
"x. c #EDE8ED",
"c. c #ECEBEC",
"v. c #E1E1E1",
"b. c #9B9B9B",
"n. c gray29",
"m. c #272727",
"M. c #84BE84",
"N. c #3AA13A",
"B. c #8CC28C",
"V. c #F2EAF2",
"C. c #E9EBE9",
"Z. c #BDBEBD",
"A. c gray18",
"S. c #848484",
"D. c #434343",
"F. c #E2E3E2",
"G. c #CCDCCC",
"H. c #309D30",
"J. c #F4EAF4",
"K. c gray49",
"L. c #FBFBFB",
"P. c #F1F1F1",
"I. c #484848",
"U. c gray62",
"Y. c #E5E4E5",
"T. c #E0E3E0",
"R. c #BAD4BA",
"E. c #5AAD5A",
"W. c #F5EBF5",
"Q. c #E8EAE8",
"!. c #5D5D5D",
"~. c #EAEBEA",
"^. c #DEE2DE",
"/. c #79B979",
"(. c #63B063",
"). c #B7D2B7",
"_. c #EAE6EA",
"`. c #E9EAE9",
"'. c #5A5A5A",
"]. c #565656",
"[. c #C5C5C5",
"{. c #F0EFF0",
"}. c #F5EEF5",
"|. c #F7EFF7",
" X c #E6E7E6",
".X c gray97",
"XX c #DDDDDD",
/* pixels */
"                                                                ",
"  . X o o o o o o o X O + o o o o o o + O X o o o o o o o X .   ",
"  X @ # $ % % & % # * = - $ % $ $ % $ - = * # % % & & $ # @ X   ",
"  o # ; : > , < > ; 1 2 3 : 4 5 3 : : 3 2 1 6 4 7 8 9 : ; # o   ",
"  o $ : 0 q w e r : t y u 0 i p a 6 0 u y t : w s d f g h $ o   ",
"  o % 4 j k l z x 7 $ c u r v b n m M 4 y $ 7 N B V C Z A & o   ",
"  o % 7 S D F G H > $ c 6 J K L P I U 4 y $ Y T R E W Q ! $ o   ",
"  o % ~ S ^ / ( ) _ ` c 6 0 3 ' ] [ i u y $ ~ { } |  ...X.o.o   ",
"  o % 4 w N O.} q : t y u r K +.@.#.u $.y $ : q w %.&.w 4 $ o   ",
"  o # ; : > < *.4 6 1 2 3 i 4 =.-.M i ;.2 1 6 : , :.:.h 6 # o   ",
"  X * 1 t $ >.,.$ 1 <.1.2.t $ 3.4.5.t 2.1.<.1 $ >.,.,.t 1 * X   ",
"  O = 2 y c c c y 2 1.6.7.8.c c c c 8.7.6.1.2 y c c c y 2 = O   ",
"  + - 3 u u : 4 u 3 2.7.M $.6 6 6 6 $.M 7.2.3 u 6 6 6 u 3 - +   ",
"  o $ : K $.U ;.J i t 8.$.0 J J J J 0 $.8.t i J J J J 0 : $ o   ",
"  o % : 6 9.0.q.K $.$ c 6 J w.w.w.w.J 6 c $ 4 r w.w.w.r 4 % o   ",
"  o % w.e.r.t.y.4 : $ c 6 J w.w.w.w.J 6 c $ 4 r w.w.w.r 4 % o   ",
"  o % : : u.i.p.y M 5.c 6 J w.w.w.w.J 6 c $ 4 r w.w.w.r 4 % o   ",
"  o % i 5 a.s.d.4.; t c 6 J w.w.w.w.J 6 c $ 4 r w.w.w.r 4 % o   ",
"  o $ i r 1 f.1 4 w.t 8.$.0 J J J J 0 $.8.t i J J J J 0 : $ o   ",
"  + - ;.$.5 g.5 $.;.2.7.M $.6 6 6 6 $.M 7.2.3 u 6 6 6 u 3 - +   ",
"  O = 2 y y 8.y y 2 1.6.7.8.c c c c 8.7.6.1.2 y c c c y 2 = O   ",
"  X * 1 t $ t t t 1 <.1.2.t $ >.>.$ t 2.1.<.1 $ $ t $ t 1 * X   ",
"  o # ; : 6 5 6 4 6 1 2 3 h.4 A A 7 : 3 2 1 6 : 4 6 $.: ; # o   ",
"  o % : w.j.k.1 0 4 t y u w H l.z.x.0 c.y $ : r J $ v.r 4 % o   ",
"  o % i 3 b.n.m.<.3 t c 6 J r M.N.B.V.C.Z.$ i u k.A.S.e.w.% o   ",
"  o % 4 K U = D.5 : $ c 6 F.N G.H.M.J.C.Z.$ 4 v.=.K.0.L.r % o   ",
"  o % 4 0 P.I.U.U w.$ c 6 Y.T.R.| E.W.Q.y $ 4 J 3 @.!.; : % o   ",
"  o $ i i 5.0.K r : t y ~.Y.^./.(.)._.`.y t i $.a '.].[.3 t o   ",
"  o # ; : $.g.$.: ; 1 2 {.7 8 }.|._  X;.2 1 ; : u .X.Xu 6 XXo   ",
"  X @ # $ % 5.% % # * = - $ % o.o.>.$ - = * # % % 5.5.$ # @ X   ",
"  . X o o o o o o o X O + o o o o o o + O X o o o o o o o X .   ",
"                                                                "
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"16 16 112 2 ",
"   c #010101",
".  c #101010",
"X  c #111111",
"o  c #0E100E",
"O  c gray6",
"+  c #0F100F",
"@  c #101110",
"#  c gray76",
"$  c #D8D8D8",
"%  c #DCD6DC",
"&  c #D5D5D5",
"*  c #BEBFBE",
"=  c #D0D0D0",
"-  c gray84",
";  c #DDDDDD",
":  c gray82",
">  c gray75",
",  c gray83",
"<  c #DBD5DB",
"1  c #DDDADD",
"2  c #C1C2C1",
"3  c #EEEFEE",
"4  c #A5CEA5",
"5  c #E7EAE7",
"6  c #D4D3D4",
"7  c gray93",
"8  c #CDCDCD",
"9  c gray66",
"0  c gray92",
"q  c #D2D3D2",
"w  c #F3EFF3",
"e  c #B0D2B0",
"r  c #C4DEC4",
"t  c #DEDADE",
"y  c #DAD5DA",
"u  c #C1D9C1",
"i  c #3D9C3D",
"p  c #D4DED4",
"a  c #D1CED1",
"s  c #EAEBEA",
"d  c #AFAFAF",
"f  c DimGray",
"g  c gray91",
"h  c #CBCCCB",
"j  c #EFEAEF",
"k  c #57A957",
"l  c #79BC79",
"z  c #DDD6DD",
"x  c #E9EBE9",
"c  c #C5D8C5",
"v  c #E2E6E2",
"b  c #D1D0D1",
"n  c #EAEAEA",
"m  c #C6C6C6",
"M  c #BBBBBB",
"N  c #EDEBED",
"B  c #CBDBCB",
"V  c #CEE0CE",
"C  c #D9D6D9",
"Z  c #D5D0D5",
"A  c #D2D1D2",
"S  c gray80",
"D  c #D7D7D7",
"F  c gray85",
"G  c #D4D0D4",
"H  c #DAD6DA",
"J  c gray",
"K  c #100F10",
"L  c #E9E9E9",
"P  c #E4E5E4",
"I  c gray90",
"U  c #E1E1E1",
"Y  c #E2E2E2",
"T  c #E0E1E0",
"R  c #E6E7E6",
"E  c gray86",
"W  c #CBCBCB",
"Q  c #6C6C6C",
"!  c gray89",
"~  c #E7E7E7",
"^  c #E4E4E4",
"/  c gray37",
"(  c #D2D2D2",
")  c #E6E6E6",
"_  c #E6E5E6",
"`  c #DFE4DF",
"'  c #E0E5E0",
"]  c #DADADA",
"[  c gray38",
"{  c #D1D2D1",
"}  c #E9E4E9",
"|  c #BBD4BB",
" . c #67B267",
".. c #E6E4E6",
"X. c #F3F3F3",
"o. c gray59",
"O. c gray87",
"+. c #A4A4A4",
"@. c gray95",
"#. c #EFEBEF",
"$. c #C0DAC0",
"%. c #80C080",
"&. c #EBE9EB",
"*. c #F8F8F8",
"=. c #A0A0A0",
"-. c #C3C3C3",
";. c #D0D2D0",
":. c #D6D5D6",
">. c #CECECE",
",. c gray7",
"<. c #131313",
"1. c white",
/* pixels */
"  . X o X O X . O X O X + @ .   ",
". # $ % & * = - ; : > , < 1 2 . ",
"X $ 3 4 5 6 7 8 9 0 q w e r t @ ",
"+ y u i p a s d f g h j k l z + ",
"X & x c v b n m M g = N B V C X ",
"O * , Z A M S D F S M = G H J K ",
"X : L P I 8 U Y Y U 8 I T R : X ",
". E W Q ! : ! ~ ~ ^ = g I 0 , X ",
". $ - / : & ! ~ ~ ^ = g I 0 , X ",
"X ( Y = ) 8 U ! ! U 8 I U g : X ",
". J D $ : M 8 A A 8 M = : & J O ",
"X - ^ : ~ : _ ` ' _ = n ] g - X ",
". & E [ & { } |  ...W X.o.d O.O ",
"X ] I +.@.{ #.$.%.&.: *.=.=.^ O ",
". -.- , & J : ;.:.A J & >., # . ",
"  . ,.. X O X ,.X X O X ,.<..   "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
};
const int n_xpm_icons = 4;
