/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 206 2 ",
"   c #000000",
".  c gray4",
"X  c #161616",
"o  c #2A3C1E",
"O  c gray16",
"+  c #3A3B39",
"@  c #313D2A",
"#  c #354E24",
"$  c #36472A",
"%  c #394F29",
"&  c #415E2E",
"*  c #465A38",
"=  c #44662D",
"-  c #476632",
";  c #4E7137",
":  c #52753A",
">  c #55793C",
",  c #587E3F",
"<  c #4C4B4C",
"1  c #545454",
"2  c #5D5D5D",
"3  c #5A6F4D",
"4  c #556E44",
"5  c #577446",
"6  c #5A7547",
"7  c #5A7B40",
"8  c #5D7949",
"9  c #5D7150",
"0  c #627455",
"q  c #666F60",
"w  c #676767",
"e  c #747474",
"r  c #7E7D7E",
"t  c #6B7366",
"y  c #965D00",
"u  c #975700",
"i  c #925300",
"p  c #A35300",
"a  c #986705",
"s  c #99730A",
"d  c #A66605",
"f  c #00AE00",
"g  c #13A700",
"h  c #01B300",
"j  c #09B606",
"k  c #07B805",
"l  c #14B80D",
"z  c #18BD11",
"x  c #38BC1C",
"c  c #478900",
"v  c #508F04",
"b  c #5EA217",
"n  c #58863A",
"m  c #63AB20",
"M  c #1FC016",
"N  c #26C21B",
"B  c #2EC421",
"V  c #38C929",
"C  c #42CB2D",
"Z  c #4BD136",
"A  c #4FD438",
"S  c #55D63D",
"D  c #49CF34",
"F  c #5A8040",
"G  c #5F8943",
"H  c #628B46",
"J  c #668C49",
"K  c #698B4B",
"L  c #69964B",
"P  c #6C9A4D",
"I  c #639344",
"U  c #739A52",
"Y  c #6F9B50",
"T  c #74AB4E",
"R  c #70A34D",
"E  c #7AAB53",
"W  c #72A251",
"Q  c #79B154",
"!  c #5CD842",
"~  c #65DE48",
"^  c #64DC47",
"/  c #6CE24D",
"(  c #79E856",
")  c #9E871D",
"_  c #9E8D23",
"`  c #A1972B",
"'  c #AB922A",
"]  c #A3A333",
"[  c #CDAE00",
"{  c #CBB301",
"}  c #CAB70A",
"|  c #C8BD13",
" . c #C7C117",
".. c #C6C21A",
"X. c #C5C722",
"o. c #C3CD2D",
"O. c #C5C925",
"+. c #C1D338",
"@. c #83BB5D",
"#. c #A7BB49",
"$. c #86BC60",
"%. c #8BBC63",
"&. c #8ACE5D",
"*. c #86CE55",
"=. c #8BD05C",
"-. c #BDDE49",
";. c #BEDC44",
":. c #AAD35D",
">. c #A7C752",
",. c #87E95C",
"<. c #BBE656",
"1. c #BCE14E",
"2. c #8ECC64",
"3. c #92CD66",
"4. c #95CE6A",
"5. c #99CD6B",
"6. c #93D169",
"7. c #99D06D",
"8. c #9BDD6F",
"9. c #96DB68",
"0. c #9DDD71",
"q. c #A1DF73",
"w. c #ADD963",
"e. c #8BEB64",
"r. c #9AEC68",
"t. c #8AF363",
"y. c #96F76B",
"u. c #9EE171",
"i. c #9DFA71",
"p. c #A2EE6F",
"a. c #B8EE66",
"s. c #B7EF69",
"d. c #B6F36D",
"f. c #B7F067",
"g. c #A5EC76",
"h. c #ACEC7A",
"j. c #A8E576",
"k. c #B3EC7B",
"l. c #A3F575",
"z. c #A4FD75",
"x. c #AEFF77",
"c. c #ADF67B",
"v. c #AFFA7D",
"b. c #A4FD79",
"n. c #B2F67A",
"m. c #B1FC7E",
"M. c #B6F979",
"N. c #807F80",
"B. c gray55",
"V. c #858585",
"C. c #959595",
"Z. c #9C979F",
"A. c #9A9A9A",
"S. c #9C97A0",
"D. c #9D99A0",
"F. c #9A8EA2",
"G. c #A39EA6",
"H. c #A2A2A2",
"J. c #ADADAD",
"K. c #B2B2B2",
"L. c #BABABB",
"P. c #B4BBAF",
"I. c #AFFE83",
"U. c #B3FF80",
"Y. c #BAFF85",
"T. c #B4FF89",
"R. c #BEFF88",
"E. c #B3F280",
"W. c #BEFF90",
"Q. c #B3EC80",
"!. c #BACAAF",
"~. c #C2FF8A",
"^. c #C8FF8E",
"/. c #C1FF87",
"(. c #C2FF92",
"). c #CCFF92",
"_. c #D0FF95",
"`. c #C3DAB4",
"'. c #CDE8BB",
"]. c #BCB6C1",
"[. c #C2BEC6",
"{. c #CBCBCB",
"}. c #C3C2C3",
"|. c #D1DACB",
" X c #D8D3DC",
".X c #DCDBDC",
"XX c #D5D3D6",
"oX c #CFD5CA",
"OX c #D3EEC1",
"+X c #D6F3C3",
"@X c #DEEDD4",
"#X c #E5F7D9",
"$X c #E8F7DC",
"%X c #DFDCE1",
"&X c #E3DFE6",
"*X c #E6E6E6",
"=X c #E7E3E9",
"-X c #E9E4ED",
";X c #EAEBEA",
":X c #E7E9E6",
">X c #F0F1EF",
",X c #EDEAF0",
"<X c #F5F5F5",
"1X c #FAFAFA",
"2X c #F7F4F9",
"3X c #F0F0F0",
/* pixels */
"*X*X*X*X*X*X*X*X*X:X*X*X:X*X:X=X*X:X*X:X*X*X=X*X*X*X:X*X:X*X*X:X*X*X*X*X*X*X*X:X*X:X*X=X:X*X*X:X*X*X*X=X*X*X=X:X*X*X*X*X*X*X*X=X*X:X*X=X:X*X:X*X*X*X*X:X*X*X*X*X*X*X*X*X:X*X:X*X:X*X*X*X*X*X*X*X",
"*X*X:X*X*X*X:X*X*X*X*X*X*X*X*X*X*X=X*X*X=X*X*X*X:X*X*X*X*X*X*X=X*X*X:X*X:X*X*X=X*X*X*X*X*X*X*X*X*X*X*X:X*X*X:X*X*X*X*X*X:X*X*X:X*X*X*X*X*X*X*X*X:X*X*X=X*X*X*X:X*X*X:X*X*X*X*X*X*X*X:X=X*X*X*X*X",
"*X*X*X*X*X*X*X*X*X*X*X*X-X*X*X*X*X*X*X:X*X*X*X*X:X*X=X*X*X*X*X*X:X*X*X*X*X*X*X*X:X*X*X*X*X*X*X:X*X*X*X:X*X*X:X=X*X:X*X:X*X*X*X*X*X*X*X*X:X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X*X:X=X:X*X:X*X:X-X*X*X",
":X*X:X*X*X*X*X*X:X*X:X=X*X*X:X*X*X:X*X=X*X:X*X:X*X*X:X*X*X*X*X*X*X*X:X*X:X:X*X*X=X*X*X*X:X*X*X=X*X*X*X*X:X*X*X*X*X*X*X=X*X*X:X*X:X=X*X*X*X*X*X:X*X:X*X*X*X*X*X*X*X*X*X*X:X*X*X*X*X*X*X*X*X*X*X*X",
"*X=X*X=X*X*X=X=X*X*X*X*X*X*X*X=X=X*X*X:X*X*X*X=X*X*X*X*X*X*X*X*X*X*X*X*X=X=X*X*X=X=X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X=X*X=X=X*X*X*X*X*X*X*X*X*X-X*X*X*X*X*X-X*X*X*X*X*X*X*X",
"*X*X*X*X:X*X:X:X;X:X:X;X;X;X:X:X:X;X:X:X:X:X*X=X:X:X:X:X;X:X;X:X:X:X;X;X;X;X:X*X:X:X*X:X:X:X:X:X;X;X;X:X:X:X:X;X:X*X:X;X;X;X:X:X;X:X:X:X:X:X:X:X;X;X:X=X*X*X*X*X*X*X*X*X*X-X*X*X*X*X*X*X:X:X*X:X",
"*X*X*X=X X&X X%X X X X X X X X X X X X X X X&X X X X X X X X X X X X X X X X X.X.X X X X X X X X X X X X X X X X X%X X X X X X X X X X X X X X X X X%X=X*X*X*X*X*X*X*X:X*X*X*X*X:X*X*X*X*X*X*X*X",
"*X*X;XoX- $ 8 6 6 6 6 6 6 6 6 6 6 6 6 6 6 8 $ 4 8 6 6 5 6 5 5 5 5 5 5 6 6 6 8 * * 8 6 6 8 6 6 6 6 6 6 6 6 6 6 6 8 $ 6 6 6 5 5 6 5 5 5 5 6 7 6 6 6 8 % J.<X*X*X=X*X:X*X*X:X*X:X*X*X*X*X=X:X*X*X*X",
"*X*X=X#X3.J ^.m.Y.Y.Y.Y.Y.Y.m.Y.Y.Y.Y.Y.M.~.> h.Y.Y./.~.~.~.~.~.~.~.~.~.R.U.^.@.U ^.E.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.: E.Y.Y.~.~.~.~.~.^.~.~.^.~.Y.Y.^.E Z.<X.X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X*X*X",
"*X*X=X#X2.H ~.c.m.m.U.m.m.U.U.M.m.m.m.m.m.Y.: g.m.Y.e.V V ^ C B Z ! B Z l.U.Y.@.L /.n.m.m.m.v.m.U.m.m.m.m.m.m.m.U.: v.v.U.,.V V ^ V B A S N S c.m.Y.T Z.<X*X*X*X*X:X*X:X*X*X*X*X*X*X*X*X*X*X:X*X",
"*X*X=X#X&.J ~.v.m.U.m.m.T.<.f.T.Y.m.U.U.m.Y.> g.Y.y.l f f f f f f f f f B m.R.$.L ~.m.U.U.m.m.U.<.d.U.U.m.m.U.m.Y.: v.Y.e.j f f h f f f f f f V m.~.T Z.<X*X*X:X*X*X*X-X*X*X*X*X%X*X*X*X*X*X*X*X",
"*X*X=X#X2.H ~.v.m.m.m.U.U.| o.I.m.m.m.U.v.Y.> g./.( f k h h h h h h h h h i.~.Q P ~.m.U.U.U.U.m.} +.T.m.m.m.U.m.U.: c.~.^ f j h h h h h j h h j l.~.T Z.<X*X*X:X*X*X*X*X*X*X*X<X1X1X;X*X*X*X*X:X",
"*X*X*X#X2.H ~.v.U.U.m.I.<.[ { f.T.m.m.m.I.Y.: g.~.( f h h h h h h h h h j l.^.@.P ~.v.m.m.m.T.-.[ } d.T.m.U.U.m.U.: v.~./ f h h h h h h h h h z v.^.T S.<X*X*X*X*X*X*X*X*X*X=XD.e e K.;X*X*X*X*X",
"*X*X=X#X&.H ~.v.m.m.U.m...{ { o.U.m.m.m.m.Y.: h.l.N f h h h h h h h h h h C R.@.P ~.m.U.U.U.M.| [ [ +.I.m.U.m.U.U.; U.y.z h h h h h h h h h h h Z ^.T Z.<X*X*X*X*X:X*X*X=X;X X$ + X   J.;X*X*X*X",
"*X*X=X#X2.H ~.m.U.m.T.<.{ { { { a.T.m.m.v.Y.: E./ f h h h h h h h h h h h f z.$.P ~.v.U.m.T.-.[ { { } d.U.m.U.U.Y.; Y.! f h h h h h h h h h h h h v.T S.<X.X=X*X*X*X*X*X*X*X%X%X1XA.  C.<X=X*X*X",
"*X*X=X#X2.H ~.m.m.U.I...[ { { [ o.T.m.U.U.Y.: n./ f k h h h h h h h h h h f i.2.L ~.v.m.U.M.| { { { { +.T.m.U.U.U.; R.! f h h h h h h h h h h h h v.E S.<X*X:X*X*X:X:X=X*X=X;X{.O . + *X*X*X*X*X",
"*X*X=X#X2.H ~.v.m.T.<.[ { { { { { f.T.m.v.Y.> h.z.N f f f h h h h h f f f C R.@.P ~.m.m.T.-.{ { { { { { d.T.U.U.U.: U.y.z f f f h h f h h f f f A (.T Z.<X.X:X*X*X*X*X*X*X*X;X%XC.w   B.3X*X*X*X",
"*X*X=X#X2.H ~.v.U.v. .{ { { { { { o.I.m.v.Y.> g.Y.c.~ / S h k k h l / ~ ( v.~.@.P ~.v.m.m.| [ { { { { { +.I.m.m.U.: v.Y.l.^ / Z f f k h z / ~ ( U.~.T Z.1X*X:X:X*X*X*X*X*X;X{.H.*XA.  e <X=X*X=X",
"*X*X*X#X2.H ~.m.T.<.{ { { { { { { { f.I.m.Y.> g.U.U.R.~.Y.r.v c b b.Y.~.Y.m.R.@.P ~.v.T.;.[ { { { { { { } d.U.m.U.: v.m.Y.Y.~.Y.,.v c m x.R.~.R.m.~.T S.<X.X*X:X:X*X*X:X*X;XL.X . . + {.;X=X*X:X",
"*X*X:X#X&.H /.v.U...[ { { { { { { [ o.T.v.Y.> g.U.m.m.m.U.M.d p ' T.v.v.m.v.R.@.L ~.v.m.| { { { { { { { { +.T.m.Y.: v.U.m.m.v.T.k.d u ' T.m.v.v.v.~.T S.<X*X*X*X*X*X*X*X*X*X:XXX{.{.*X;X*X*X*X*X",
"*X*X=X#X2.H /.I.-.[ [ [ { [ [ [ [ [ [ a.I.Y.> g.Y.m.m.m.m.c.s u _ T.m.m.U.m.R.@.P /.I.;.[ [ [ [ { [ [ { [ { d.I.U.: m.m.m.m.m.U.d.a y ] T.m.I.U.m.R.T S.2X*X=X:X*X*X:X*X*X*X*X;X;X;X*X*X*X*X*X:X",
"*X*X=X#X2.H /.I.+.|  . . . . . . .| | ;.I.Y.> g.U.m.U.m.U.c.a i ) T.m.U.U.m.R.@.P ~.v.o.|  . . . . . .|  .| -.T.m.: v.m.m.m.m.T.j.u i ` T.m.m.U.m.~.T S.<X&X*X*X*X*X*X*X*X*X*X*X=X*X*X*X*X*X*X*X",
"*X*X=X#X2.H Y.c.v.I.I.I.I.I.I.I.I.I.I.v.c.Y.: g.m.m.v.v.m.c.>.>.:.v.m.m.v.c.R.@.L Y.c.I.I.I.I.I.T.U.I.I.I.I.v.v.U.: c.v.v.v.m.m.c.>.>.:.U.v.E.v.v.R.R S.<X*X:X*X*X:X*X:X*X*X*X*X*X*X*X*X:X*X*X*X",
"*X*X&X$X5.K ).R.~././.~./.~.~.R.~.R././.R.).7 Q.~.~.~.~.~.~.(.(.(./.~.~././.).%.U _.R./.R.~.~.~.Y.~.~.~.~.~.~.R.^.: R.~.~.~.~.~.R.(.(.~.~.~.R.~.R.).E S.<X.X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X*X",
"*X*X;X|.- # L H H H H H J J G J H J H H H I $ 7 H H H G G G G G G G G H H J L - % L H H H H J G H J H J H J H H J o G H H H H H H H H H H H J H H P % H.<X%X*X*X*X:X*X*X:X*X:X=X*X*X*X*X*X*X*X*X",
"*X*X=X@XR ; 8.2.3.2.3.2.2.2.2.2.2.2.2.2.2.7.% &.6.2.2.7.7.4.7.7.4.4.7.6.2.2.9.L > 8.2.2.2.2.2.2.2.2.2.2.2.2.2.3.4.& 2.3.2.2.2.3.2.4.2.2.3.2.2.2.2.u.n D.<X*X*X*X*X*X:X*X*X*X*X*X*X*X*X*X*X:X:X*X",
"*X*X=X#X3.K ).U.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.~.5 h.R.R.R.y.t.x.y.t.i.x.t.z.~.Y.(.%.U ).Y.Y.R.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y./.: Y.Y.Y.Y.Y.R.Y.Y.Y.Y.Y.Y.Y.Y.U.).E Z.<X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X*X=X#X2.H R.v.I.E.U.U.m.U.U.m.U.I.U.U.v.Y.: g.U.v.C h h l h f k j f h ^ U.Y.@.L ~.v.m.U.v.U.U.I.U.m.m.I.U.U.m.U.: c.m.E.U.I.U.m.U.U.m.m.U.U.v.m.R.T A.<X%X:X:X-X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X*X=X#X2.H ~.v.U.U.U.U.U.U.U.m.U.U.U.U.v.Y.> g.R.( f h h h h h h h h f j i.~.$.P ~.m.m.U.U.U.m.U.m.U.U.U.m.U.m.U.: v.U.v.U.U.U.U.U.U.m.U.U.U.U.m.R.T S.1X%X*X:X*X*X*X*X:X*X=X*X:X;X*X*X*X*X*X*X",
"*X*X*X#X2.H ~.v.U.U.m.U.m.U.U.U.U.U.m.U.U.Y.: g.^.( f h h h h h h h h h j g.~.@.P ~.m.m.m.U.U.U.U.U.U.U.U.U.U.m.U.: v.U.U.U.U.U.m.U.U.U.U.U.m.U.v.~.T S.<X%X*X*X:X*X*X*X*X*X*X;X.X X*X*X*X*X*X:X",
"*X*X*X#X2.H /.v.U.U.U.U.U.U.U.U.U.m.U.U.v.Y.> g.Y.S h h h h h h h h h f h ( ~.@.P ~.m.m.U.U.U.U.U.U.U.m.U.U.U.U.Y.: v.U.m.U.U.m.U.U.U.U.U.m.U.U.I.~.T S.<X*X*X*X*X*X*X*X*X*X*X1 . . K.<X*X*X*X*X",
"*X*X=X#X2.H ~.v.U.m.U.U.U.U.m.U.U.U.U.U.m.Y.: c.,.h h h h h h h h h h h f l v.$.L ~.m.U.U.U.U.U.m.U.U.U.m.U.U.m.U.: v.U.m.U.U.U.U.U.m.U.U.U.m.U.v.~.T S.<X*X:X*X*X*X*X*X=X*X=XH.w   J.;X*X*X*X*X",
"*X*X*X#X2.H ~.v.U.U.U.U.U.U.U.m.U.U.U.U.m.Y.: E.~ f h h h h h h h h h h h f i.2.L ~.m.m.m.U.U.U.U.U.U.U.U.U.U.m.Y.: m.m.m.U.U.U.m.U.U.U.m.Y.U.U.m.~.T Z.1X.X:X*X*X*X:X*X*X*X=X1XA.  K.3X*X*X*X*X",
"*X*X=X#X&.H ~.v.U.U.m.U.m.U.U.U.U.U.U.U.v.R.: c.e.h h f h h h h h h f f f z m.@.L ~.m.m.U.U.U.m.U.m.U.U.m.U.U.m.Y.: m.m.m.U.m.U.U.U.U.U.m.m.U.U.m.~.T S.<X*X:X:X*X*X*X*X*X*X*X;XB.  J.;X*X*X*X*X",
"*X*X=X#X2.H ~.v.U.U.U.U.U.U.U.U.U.U.U.U.U.Y.> g.Y./ z N z f h h h f M M N e.^.@.P ~.m.U.U.U.U.U.U.U.m.U.U.U.U.m.m.: v.m.m.m.U.U.U.U.U.U.U.U.U.m.m.~.T S.<X.X*X:X*X*X*X*X*X*X*X1XH.  }.1X%X*X*X*X",
"*X*X*X#X2.H ~.v.U.m.m.U.U.U.U.U.m.U.U.U.v.Y.> g.U.Y.U.U.l.Z g f l ^ m.m.Y.U.R.@.P ~.m.U.U.m.U.U.m.U.U.U.U.U.U.m.Y.: v.m.U.U.U.U.U.m.U.U.m.U.U.U.v.~.T S.<X*X*X*X*X:X*X*X*X*X;Xe O   O V.>X*X*X*X",
"*X:X=X#X2.H ~.v.U.U.m.U.U.U.U.m.U.U.U.m.m.Y.> g.U.m.U.m.T.M.s y _ ~.m.U.m.v.Y.@.P ~.m.m.U.U.U.U.Y.m.U.U.m.U.U.m.U.: v.U.m.U.U.U.U.U.U.U.m.U.U.U.m.R.T S.<X=X*X*X*X*X*X*X*X*X;Xe 1 t 1 B.3X=X*X*X",
"*X*X=X#X&.H ~.v.U.U.U.U.m.U.U.U.U.U.U.U.m.Y.: g.Y.m.U.m.U.n.s u ` T.m.m.m.m.~.@.P ~.v.m.U.m.U.m.m.m.U.U.U.U.U.m.U.: v.U.m.U.U.U.U.U.U.m.U.U.U.U.v.~.T S.<X*X:X*X:X*X*X*X*X*X*X1X1X1X1X2X*X*X*X*X",
"*X*X=X#X2.H ~.m.m.Y.U.U.U.U.U.m.U.U.U.U.v.Y.> g.U.m.U.m.U.n.a i ) T.m.m.U.m.R.@.P ~.m.U.U.U.m.m.U.U.U.U.U.Y.m.m.Y.: n.U.m.U.U.U.U.U.U.U.U.U.U.U.m.R.T S.<X%X*X*X*X*X*X*X*X=X*X*X%X%X%X=X*X*X*X*X",
"*X*X=X#X2.H /.m.m.m.m.m.U.m.m.m.m.m.m.m.m.Y.> g.Y.m.U.m.T.n._ s ] T.m.U.m.m.Y.@.P ~.m.m.m.m.m.m.m.U.m.m.m.m.m.m.U.: m.U.U.m.m.m.m.m.m.U.m.m.m.U.v.~.T S.<X*X*X*X*X*X*X*X*X*X*X*X*X:X:X*X*X*X*X*X",
"*X*X=X$X3.J (.U.Y.T.Y.Y.U.Y.Y.Y.Y.Y.Y.Y.U.R.> h.Y.U.Y.Y.T.Y.Y.Y.Y.Y.U.Y.Y.U.^.$.P ).U.Y.Y.T.Y.Y.Y.Y.T.Y.U.Y.Y.Y.Y.: E.Y.Y.T.Y.Y.Y.T.Y.Y.U.Y.Y.U.U.^.E Z.<X%X*X:X*X:X*X*X*X*X*X:X*X*X*X*X*X*X*X;X",
"*X*X:X@XQ > c.7.8.0.8.8.8.8.0.8.8.8.8.0.8.j.- 3.j.8.8.8.8.8.8.0.8.8.8.8.8.8.j.R G g.9.8.8.0.8.8.8.8.8.8.8.8.8.8.q.- 9.0.8.8.8.8.8.8.8.8.8.8.8.8.7.l.I D.<X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X*X",
"*X*X;XoX& $ G , n 7 F 7 n 7 F F F F F F > H o > F F F , n 7 F n 7 n n 7 , , H & $ H 7 7 7 F n 7 n 7 n 7 F F 7 7 F o , 7 F F n 7 n 7 F 7 n 7 F F 7 H # H.<X*X*X*X*X*X*X*X*X:X*X*X*X-X*X:X*X:X*X*X",
"*X:X=X#X5.K ).Y.~.~.Y./.~.R.~.Y.R.R.R.Y.R.(.7 k.~.Y.~./.~.Y.~./.R.~.R.~.R.R.).%.U ).Y.R.R.R.~./.Y.~.~.~.Y.~.Y.R.^.: Y./.R.~.R.R.~.R.R./.~.~.R.R.R._.E A.<X%X*X*X*X;X*X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X*X=X#X&.H Y.c.m.m.m.m.m.m.m.m.m.m.m.v.c.T.: j.m.m.m.m.v.v.v.I.m.m.m.m.m.c.Y.@.L R.c.v.m.c.m.m.m.m.m.v.m.m.v.m.m.: c.m.v.m.m.v.m.m.m.m.v.m.v.v.v.R.R D.<X*X*X*X*X*X:X*X-X*X:X*X*X*X*X*X*X*X*X:X",
"*X*X=X#X2.H ~.c.U.U.m.m.m.m.m.U.m.U.m.U.n.R.> g.U.m.m.U.m.U.M.-.U.m.m.m.m.m.~.@.P ~.m.U.U.m.m.U.U.U.U.m.U.U.m.m.U.: v.U.m.U.m.U.U.m.m.m.m.U.U.U.v.R.T D.1X.X*X*X*X*X*X*X*X*X*X%X%X=X*X*X*X*X*X*X",
"*X*X=X#X2.H ~.m.m.U.U.U.U.U.U.U.m.U.U.U.m.Y.: g.Y.m.m.m.m.T.-.[ s.T.m.m.m.m.~.@.P ~.m.U.U.m.U.U.m.U.m.U.U.m.U.m.U.: v.m.m.m.U.U.U.U.U.m.U.U.U.U.U.R.T S.<X*X*X*X*X:X*X*X*X*X=X<X1X<X;X:X*X*X*X*X",
"*X*X=X#X2.H /.v.U.U.U.m.U.U.m.U.U.U.U.U.m.Y.> g.Y.m.U.m.m.m.| [ o.T.m.m.m.m.Y.@.P ~.m.m.U.U.U.U.U.U.U.U.U.U.U.m.Y.: m.U.U.U.U.U.U.U.U.U.U.U.U.U.v.~.T S.<X*X*X*X*X*X*X:X*X*X*XH.w w {.;X*X*X*X*X",
"*X*X*X#X2.H ~.v.m.U.m.U.U.U.m.U.U.U.m.U.m.Y.> g.U.U.m.m.T.;.[ { { f.T.m.U.m.R.@.P ~.m.U.m.U.U.U.U.U.m.U.m.U.U.m.Y.: m.m.m.U.U.U.U.m.U.U.U.m.m.Y.m.R.T S.<X.X:X*X*X*X*X*X*X*X*X1 X   J.3X=X*X*X*X",
"*X*X*X#X&.H ~.v.U.m.U.U.U.U.U.U.U.U.U.U.m.Y.> g.Y.m.U.U.m.| { { { o.U.m.U.m.R.@.P ~.m.U.U.U.U.m.U.U.U.U.U.m.U.m.U.: m.U.m.U.U.U.m.m.U.U.U.U.U.U.m./.T S.1X*X:X:X:X*X*X*X*X*X.X<XA.  K.>X*X:X*X*X",
"*X*X=X#X2.H ~.v.U.U.m.U.U.U.U.U.m.U.U.U.m.Y.> g.U.m.m.T.-.[ { { { { a.U.m.m.R.@.P ~.m.m.U.U.U.U.U.U.U.U.Y.m.U.U.Y.: m.m.m.U.m.U.m.Y.U.U.U.m.U.U.v.~.T S.<X.X:X*X*X*X*X:X*X*X*X;XC.  J.>X%X:X*X*X",
"*X*X=X#X2.H ~.v.U.U.U.U.U.U.m.U.U.U.U.m.m.Y.> g.T.m.U.M.| { { { { [ o.T.m.m.~.@.P ~.m.m.U.U.U.U.U.U.U.m.m.U.U.m.U.: c.m.m.U.U.U.U.U.U.m.U.U.U.U.m.~.T S.<X*X*X*X*X:X*X*X*X*X*X<XC.  K.<X*X*X*X*X",
"*X*X=X#X2.H ~.v.U.U.U.U.U.U.U.U.m.U.U.U.E.Y.> g.Y.m.T.-.[ { { { { { { f.T.v.Y.@.P ~.m.m.U.U.U.U.m.U.Y.m.m.m.U.m.U.: m.U.m.U.U.U.m.U.U.U.U.U.U.U.v.~.T S.2X*X*X*X*X*X*X*X*X*X*XXXe   B.XX*X*X*X*X",
"*X*X*X#X2.H ~.v.U.m.U.U.m.U.m.U.U.U.U.U.v.Y.> g.m.m.M.| [ { { { { { [ o.T.m.Y.@.P ~.m.m.U.U.m.U.U.U.m.U.U.U.U.U.T.: n.m.U.U.U.m.U.U.U.U.U.m.U.U.U.R.T S.<X*X:X*X*X:X=X:X*X*X:X+   X   1 <X=X=X*X",
"*X*X*X#X2.H ~.v.U.U.m.U.U.U.Y.m.U.U.U.U.I.Y.> g.m.T.-.{ { { { { { { { { s.I.Y.@.P ~.m.m.U.m.U.m.U.m.U.U.U.U.m.m.Y.; m.m.m.U.U.U.U.U.U.U.U.U.U.U.v.R.T S.<X%X*X*X*X:X*X*X*X*X:X.XXX.X.X%X*X*X*X*X",
"*X*X=X#X&.H ~.v.Y.m.U.U.U.m.U.m.U.U.m.U.m.Y.> g.Y.M.} [ { [ [ [ { [ [ [ O.U./.@.P ~.m.m.U.U.U.U.U.U.U.U.U.U.U.m.U.: m.U.U.m.U.U.U.m.U.U.U.m.m.U.v.~.T S.<X*X*X*X*X*X*X*X*X*X*X;X:X;X;X:X*X*X*X:X",
"*X*X=X#X2.H /.I.m.m.U.U.m.m.U.U.U.U.U.U.m.Y.: g.T.a...X.X.O.X.X.O.O.X.X.O.n.Y.@.P ~.m.U.U.U.U.U.m.m.U.U.U.U.U.m.Y.: n.U.U.U.U.U.m.U.U.m.U.m.m.U.m.R.T Z.1X%X:X*X*X:X-X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X*X=X#X2.G R.c.m.m.m.m.m.m.v.m.v.v.m.v.v.Y.: g.v.I.T.T.I.I.I.T.I.T.I.T.I.v.Y.@.L R.c.n.v.v.v.m.m.m.m.m.v.m.n.v.m.; c.m.v.n.m.v.v.m.m.m.m.m.v.m.v.Y.T Z.<X*X*X*X*X=X*X:X*X*X*X*X*X-X*X*X*X*X*X*X",
"*X*X=X#X3.K ).R./.R.~.Y.~.Y.Y.~.R.R.R.R.Y.).7 k.~.Y.R.Y.R.R./.Y.R.Y.~.Y.R.R.).%.U ).Y.~.R.R.~.R.~.Y.~.Y.R.R./.R.~.> R./.R.R.R.R.~.R.R.R.Y.~./.R.Y.).E A.<X%X*X*X*X*X:X*X*X*X*X*X*X*X*X:X*X*X*X:X",
"*X*X;XoX& $ G 7 n 7 , , , , , , 7 n , 7 > G o : F n F F F F 7 n 7 F F F F 7 G & # H 7 7 7 F F F F 7 F F F 7 , , F o , , F F F 7 F F 7 n 7 F F F 7 H # H.<X*X*X*X*X*X*X*X*X:X*X*X:X*X*X*X*X*X*X*X",
"*X*X*X;XG.5 h.9.9.j.j.q.j.j.j.0.j.j.0.8.7.g.- 3.q.8.8.8.8.8.8.8.8.0.8.8.8.9.g.W G g.8.8.8.0.8.8.8.8.8.8.8.8.8.8.j.& 8.8.0.0.8.8.8.8.8.8.8.8.8.8.8.h.I D.<X%X:X*X*X:X*X*X:X*X:X=X:X*X*X*X*X:X*X*X",
"*X*X*X>X].J ^.U.R.l.( t.y.( ( i.t.( v.R.U.~., h.R.T.Y.Y.T.Y.Y.Y.Y.U.Y.Y.T.Y.^.$.P ^.U.Y.Y.U.Y.Y.Y.Y.U.Y.T.Y.U.Y.Y.: U.Y.Y.U.T.Y.Y.Y.Y.Y.U.Y.Y.T.E.(.E Z.1X%X:X:X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X*X*X>X].G Y.Y.( l f j k f f j f f z y.U.Y.> g.Y.m.m.m.m.m.U.m.m.m.m.m.m.m.Y.@.P R.m.m.m.m.m.U.m.m.U.m.U.U.U.n.U.: n.U.U.m.m.m.m.m.U.m.m.m.m.U.v.~.T Z.<X=X*X:X*X:X:X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X*X*X>X].J R.U.B f h h h h h h f h f Z Y.Y.> g.U.m.m.m.U.U.U.U.U.U.U.U.U.m.R.@.P ~.v.U.U.U.U.U.U.U.U.U.U.U.U.U.U.: m.U.m.U.m.m.U.U.U.m.U.U.U.U.m.R.T Z.<X=X*X*X*X*X*X*X*X*X*X-X;X;X-X*X*X*X*X*X",
"*X*X*X;X].H R.Y.B h h h h h h h h h h Z ~.T.> g.U.m.U.U.U.m.U.U.U.m.U.U.U.m.R.@.P ~.m.U.U.U.U.m.U.U.m.U.m.U.U.m.Y.; m.U.m.U.U.U.m.U.U.U.U.m.U.U.m.R.T S.<X*X*X*X*X:X*X*X*X*X*X.X{.{..X;X*X*X*X*X",
"*X*X*X>X].G ^.e.l h h h h h h h h h h N l.R.: g.Y.m.m.U.U.U.U.U.U.U.U.U.m.m.R.@.P ~.m.m.m.U.U.U.U.U.m.Y.U.U.U.m.U.: n.U.m.U.U.U.U.U.m.U.U.U.U.U.I.~.T S.<X&X*X*X=X:X*X*X*X*X*X<     K.;X*X=X*X*X",
"*X*X*X>X].G ^.N f h h h h h h h h h h f D ~.> g.U.m.m.U.U.U.U.m.U.U.U.U.U.m.R.@.P ~.m.m.U.U.U.U.U.U.U.m.U.m.U.m.T.: v.U.m.U.U.U.U.m.U.U.U.U.U.m.m.R.T S.<X*X:X*X*X*X*X*X*X*X*XK.e   J.<X*X*X*X*X",
"*X*X*X>X].J ~.l f h h h h h h h h h h f B ^.: g.Y.m.U.U.U.U.U.U.m.U.U.U.U.m.R.@.P ~.m.U.U.U.m.U.m.U.U.U.U.m.Y.m.U.: v.U.U.U.U.m.U.U.U.U.m.U.U.U.v.~.T S.<X.X:X*X*X:X*X*X*X*X*X1XA.  K.;X*X*X*X*X",
"*X*X*X>X].G (.C f h f h h h f j h f f f ! ^.> g.Y.U.U.U.m.U.U.U.U.U.U.m.U.m.R.@.P ~.m.m.m.U.U.U.m.U.Y.m.U.U.U.m.U.: v.U.m.U.U.U.U.U.m.m.U.U.U.m.v.~.T S.<X*X*X*X=X:X*X:X*X*X*X;XB.  J.3X*X*X*X*X",
"*X*X*X>X].H ^.l.A N V j h h h f l V N ^ v.Y.: g.Y.m.m.U.U.U.Y.m.m.U.U.U.U.v.R.$.P ~.m.U.U.U.m.U.U.m.m.U.U.m.U.m.Y.: n.U.m.U.m.U.U.U.U.m.U.U.U.U.m.R.T S.<X*X*X:X*X*X*X*X*X*X=X1XH.  }.1X.X*X*X*X",
"*X*X*X;X].H ~.m.Y.Y.Y.e.x g g C y.Y.Y.Y.U.Y.> g.m.m.U.U.U.U.m.m.U.U.U.U.U.m.R.@.P ~.v.U.U.U.U.U.U.U.U.U.U.U.U.m.U.: v.U.U.U.U.U.U.m.m.Y.U.U.U.U.m.~.T Z.<X.X*X*X*X*X*X:X*X*X:Xw X   X r >X*X*X*X",
"*X*X*X>X].H ~.v.m.m.m.(.#.y u w.T.m.m.m.v.Y.> g.Y.m.m.U.U.U.U.m.U.U.m.U.U.m.R.@.P ~.v.m.U.m.U.U.U.U.U.U.m.U.U.U.U.: v.U.m.U.m.U.U.U.U.U.U.m.U.U.m.~.T Z.<X*X*X*X:X*X*X=X*X*X:XV.t V.w C.;X*X*X*X",
"=X*X*X>X].H ~.n.U.U.m.T.#.u y :.T.U.E.U.m.Y.> g.U.m.U.U.U.U.U.U.U.U.U.U.U.v.R.@.L /.m.U.U.U.U.U.m.U.U.U.U.U.m.U.U.: m.U.m.U.U.U.U.m.Y.m.U.U.U.U.v.~.T S.<X*X:X*X*X*X*X*X*X*X*X2X1X1X1X<X*X*X*X*X",
":X*X*X>X].J ~.v.U.U.m.T.#.i u :.T.v.U.U.v.R.> g.Y.m.U.U.m.U.m.U.U.U.U.U.U.m.R.@.Y /.m.m.U.U.U.U.U.U.Y.m.U.U.U.m.U.: v.U.U.U.U.U.U.U.m.m.U.U.U.U.m.R.T S.<X.X*X*X*X*X*X:X*X*X*X=X*X&X.X*X*X*X*X*X",
"*X*X*X>XL.H /.v.U.m.m.T.>.) ) j.I.m.U.U.v.Y.: g.m.m.U.U.U.U.m.U.U.U.I.U.v.v.R.@.L ~.v.I.m.m.U.v.m.m.m.m.U.U.I.E.U.; v.m.U.U.E.U.v.m.m.U.m.v.m.m.I.R.T S.<X*X*X*X;X*X*X*X*X*X*X*X=X*X*X*X*X*X*X*X",
"*X*X*X>X[.K ^.Y.R.Y.Y.Y.R.R.~.Y.Y.Y.Y.Y.Y.^.> h./.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.R.Y.Y.^.$.Y ).Y.Y.Y.Y.Y.R.Y.Y.Y.Y.Y.Y.Y.Y.~.5 E.R.~.T.Y.W.R.R.R.R.R.R.R.~.Y.).E S.<X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X",
"*X*X*X*XF.; 9.&.&.&.5.2.2.2.&.&.&.&.2.=.&.9.= @.6.2.2.2.2.2.2.3.2.2.2.2.2.2.7.L > 8.2.2.2.3.2.2.3.2.2.2.2.2.2.2.6.& &.&.&.&.%.%.&.2.&.&.&.2.&.&.&.9.n A.1X.X*X*X*X*X*X*X:X*X*X=X*X=X*X:X*X*X*X*X",
"*X*X;X|.= < V.r r r N.U r r r r r r U r r V.+ n J H G J H H J J G J H H J J L - % P G J H H H H H J H J J J H H H @ r r r r e %.N.U r r U r r r r V.< G.<X*X*X*X*X*X:X*X*X*X*X:X*X:X*X*X*X;X*X*X",
"*X*X=X#X&.V.1X<X2X<X<X<X2X2X1X1X2X1X2X2X<X1Xt h.(.R.R.~././.R.R.R.~.~./.R.R.).%.U ).R.R.~.~.~.~.~.~.R.~.R.R.~././.0 2X1X2X<X1X1X2X2X2X2X2X2X2X1X<X1XJ.C.<X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X",
"*X*X=X#X*.r 2X%X*X*X*X%X%X%X=X%X&X&X&X&X%X,Xq p.U.v.v.v.E.v.I.v.v.E.v.v.v.v.Y.@.L R.c.v.c.m.m.m.v.v.v.v.v.v.I.v.m.4 &X.X%X*X*X%X&X&X&X=X&X&X&X=X.X<XC.A.<X*X*X*X:X*X:X*X*X=X:X*X:X*X:X*X*X*X*X*X",
"*X*X=X$X2.N.<X*X:X*X*X*X*X*X*X*X=X*X:X*X*X,Xq p.Y.m.U.m.U.U.U.U.U.U.U.U.U.m.R.@.P ~.m.m.U.U.m.U.U.U.m.U.m.U.U.U.U.3 =X*X*X*X*X*X*X*X*X*X:X*X*X*X%X<XA.C.1X%X*X*X*X*X*X*X*X*X*X*X.X%X*X*X*X*X*X*X",
"*X=X=X$X2.U <X*X*X*X:X*X:X*X:X*X:X:X*X*X*X3Xq p.Y.m.U.U.U.U.U.m.U.U.m.U.U.m.R.@.P ~.m.U.U.U.U.U.U.U.U.U.U.U.U.m.U.9 %X:X*X*X*X*X*X*X*X*X*X*X*X*X*X1XA.A.<X*X*X*X-X*X*X*X*X*X*X>X1X1X;X*X*X*X*X*X",
"*X*X-X$X2.r 1X.X*X*X*X*X*X*X*X:X:X*X*X*X%X<Xq p.U.m.U.U.U.U.U.U.U.m.U.U.m.m.~.@.P ~.v.U.m.U.U.U.m.U.U.U.U.U.U.U.m.3 &X*X*X*X:X*X*X:X;X*X*X*X:X*X%X1XA.A.1X%X*X*X*X*X*X*X*X*X;XB.< 1 }.;X*X*X*X*X",
"*X*X&X@X&.r <X*X*X:X*X*X*X-X*X*X*X*X:X=X*X3Xq p.Y.m.m.U.U.m.U.U.U.U.U.m.U.m./.@.P ~.m.m.U.U.U.m.U.U.U.m.U.U.U.U.m.3 &X:X*X*X*X*X*X*X*X*X*X*X*X*X*X<XC.A.<X*X*X*X:X*X:X*X*X*X=X2 O   J.>X*X*X:X*X",
"*X*X*X$X=.r 1X%X*X*X*X*X*X-X*X*X*X*X=X:X%X<Xq p.Y.m.U.U.U.U.U.U.m.U.U.U.U.m.~.@.P ~.m.m.U.U.U.U.U.U.U.U.U.U.U.U.m.3 =X*X*X*X*X*X*X:X*X*X*X*X*X*X%X<XA.A.<X*X=X*X*X*X:X*X*X*X*X<XA.  K.3X*X*X*X*X",
"*X*X=X#X&.r <X*X*X-X*X*X*X*X*X*X*X*X*X*X*X3Xq p.Y.m.U.m.U.m.U.U.U.U.U.U.m.m.R.@.P ~.m.m.U.m.U.U.U.m.U.U.U.m.m.U.m.9 *X*X*X*X*X*X-X*X*X*X*X*X*X*X*X<XA.A.<X*X*X*X*X:X*X*X*X*X*X<XC.  J.;X*X*X*X*X",
"*X*X=X$X=.r <X*X:X*X*X*X*X:X*X=X=X*X:X*X%X3Xq p.T.m.m.U.U.U.U.U.m.U.U.U.U.U./.@.Y ~.m.U.U.m.m.U.U.U.U.U.m.U.U.U.M.9 &X*X*X*X*X*X*X*X*X*X*X*X*X*X@X<XA.A.<X*X*X*X-X*X*X*X:X*X=X1XA.  L.1X*X:X*X=X",
"*X*X=X#X*.r 2X=X*X*X*X:X*X*X*X:X:X*X*X*X*X<Xq p.M.x.x.x.m.x.x.x.x.x.v.x.x.x.m.@.L m.n.x.x.m.x.x.m.x.x.x.v.x.x.x.x.3 &X*X*X*X*X:X*X:X*X*X*X*X*X=X*X<XA.A.2X*X*X*X*X*X*X*X=X*X*XK.2   e L.:X%X*X*X",
"*X*X*X:X`.}.;X*X*X*X*X-X*X*X*X*X:X*X*X*X*X;XL.'.+XOXOXOXOXOXOXOXOXOXOXOXOXOX+X`.!.+XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXP.*X*X*X*X*X-X*X:X*X*X;X*X*X*X=X;X{.{.;X*X*X*X*X*X*X*X*X*X:XA.B.C.V.H.>X*X*X*X",
"*X*X*X*X,X;X*X*X:X*X:X*X*X*X:X*X*X*X*X*X*X*X;X-X-X-X-X:X-X-X-X-X-X-X-X-X-X-X-X;X,X=X-X-X-X-X-X:X-X:X-X:X-X-X-X-X=X3X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X;X;X*X*X*X*X*X*X*X*X*X*X*X<X1X<X1X>X*X*X*X*X",
"*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X=X*X:X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X-X*X*X*X:X-X*X:X*X*X*X*X*X*X*X=X*X*X*X*X*X;X*X*X*X*X*X-X=X*X%X*X*X*X*X*X*X",
"*X*X*X*X*X*X*X*X:X*X*X*X*X*X:X*X*X*X*X*X*X*X*X=X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X=X*X*X*X*X*X*X:X*X=X*X*X*X*X=X*X*X:X*X*X*X*X*X*X*X*X*X*X:X*X:X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X",
"*X:X*X*X*X*X*X*X:X*X-X*X*X*X:X*X*X;X*X*X*X:X*X:X*X:X*X:X*X*X*X*X:X*X*X*X*X*X*X:X:X*X:X*X*X=X:X*X*X*X*X:X*X*X*X*X:X*X*X*X*X*X:X*X*X*X*X-X*X*X*X*X*X*X*X*X:X*X*X*X*X*X*X*X*X:X*X:X*X*X*X*X*X*X:X*X",
"-X*X*X*X*X*X*X*X*X*X*X*X*X-X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X*X*X:X*X:X*X=X*X*X*X*X*X*X*X*X*X*X*X:X*X:X=X*X*X*X*X*X*X*X*X*X*X*X*X*X-X*X*X*X*X*X*X:X*X*X*X*X*X*X:X*X*X*X*X*X*X:X*X:X*X*X*X*X",
"*X*X*X*X*X*X*X*X:X*X:X*X*X*X:X*X:X*X*X*X*X:X*X=X*X:X*X*X*X*X*X*X*X*X:X*X*X*X*X*X:X*X*X=X:X*X*X:X:X*X=X*X*X*X*X*X*X*X:X*X*X*X*X*X*X*X*X:X*X*X*X*X*X*X:X*X*X*X*X*X*X*X*X*X*X:X*X*X:X*X*X*X*X:X*X*X",
"*X:X:X*X*X*X:X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X:X*X*X*X*X*X:X:X=X*X*X*X:X=X*X*X*X*X*X*X:X*X*X*X=X*X*X*X*X*X*X:X:X*X*X*X*X:X-X*X*X*X;X*X*X:X*X*X:X*X-X*X*X*X:X-X*X:X*X:X*X*X*X*X*X-X*X*X*X*X*X*X*X"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"48 48 168 2 ",
"   c gray23",
".  c #5A7F00",
"X  c #484848",
"o  c #555555",
"O  c #5B5B5B",
"+  c #656565",
"@  c #6D6D6D",
"#  c #797979",
"$  c #A35901",
"%  c #A66307",
"&  c #369701",
"*  c #00AD00",
"=  c #03B402",
"-  c #0AB607",
";  c #0CB609",
":  c #1ABE12",
">  c #418E00",
",  c #25C21C",
"<  c #2FCC22",
"1  c #31CD23",
"2  c #42D42F",
"3  c #5EC734",
"4  c #46D332",
"5  c #4CD333",
"6  c #4FD93A",
"7  c #51D535",
"8  c #56D73B",
"9  c #59D93F",
"0  c #658F48",
"q  c #669249",
"w  c #69944C",
"e  c #77B151",
"r  c #7BB455",
"t  c #7DB259",
"y  c #768F65",
"u  c #7A916A",
"i  c #7C8F70",
"p  c #5CDA42",
"a  c #62DB44",
"s  c #65DC49",
"d  c #6CDA49",
"f  c #74DC4E",
"g  c #79D94D",
"h  c #6BE247",
"j  c #76E54F",
"k  c #78E653",
"l  c #CEAC00",
"z  c #CBB301",
"x  c #CABA0C",
"c  c #C8BE15",
"v  c #BFD73F",
"b  c #C6C31E",
"n  c #C9C41B",
"m  c #C6C926",
"M  c #C4CF32",
"N  c #C3D034",
"B  c #80B75C",
"V  c #84BD5D",
"C  c #86BF60",
"Z  c #89BF64",
"A  c #84C15B",
"S  c #89C85F",
"D  c #90DF5A",
"F  c #9CD85C",
"G  c #A3C54E",
"H  c #BED741",
"J  c #BFD943",
"K  c #BEDF4C",
"L  c #A5CC55",
"P  c #B3C256",
"I  c #80E559",
"U  c #BCE04F",
"Y  c #BBE557",
"T  c #86C161",
"R  c #8AC363",
"E  c #8DC965",
"W  c #88CA69",
"Q  c #91C567",
"!  c #92C569",
"~  c #95C86C",
"^  c #93DE60",
"/  c #94CF71",
"(  c #B7DF6D",
")  c #9BE868",
"_  c #8BF064",
"`  c #97F26B",
"'  c #9FE272",
"]  c #9CF572",
"[  c #9DF872",
"{  c #A1ED6E",
"}  c #ACE96D",
"|  c #BAED62",
" . c #B8E36F",
".. c #A4F66C",
"X. c #B6F26C",
"o. c #B8F56D",
"O. c #A4EE73",
"+. c #AAEF73",
"@. c #A7EF78",
"#. c #B9EC77",
"$. c #B9EC78",
"%. c #A5F372",
"&. c #ABF275",
"*. c #ACFC76",
"=. c #ABF37A",
"-. c #AEFA7C",
";. c #A4F877",
":. c #B5F674",
">. c #B2FD7E",
",. c #B3F87A",
"<. c #838383",
"1. c #888888",
"2. c #9C9C9C",
"3. c #8FA183",
"4. c #91A386",
"5. c #93AA85",
"6. c #97B782",
"7. c #99B685",
"8. c #9BB986",
"9. c #9DB48D",
"0. c #9FB98B",
"q. c #9CA795",
"w. c #A0B78F",
"e. c #A5AD9F",
"r. c #A1B692",
"t. c #A7B995",
"y. c #AABA96",
"u. c #A4B599",
"i. c #AAAAA9",
"p. c gray64",
"a. c #ABB6A3",
"s. c #ACB8A4",
"d. c #AEB9A9",
"f. c #B3BBAA",
"g. c #B4B4B4",
"h. c #BBBBBB",
"j. c #A9F781",
"k. c #ADFF85",
"l. c #B4FF81",
"z. c #B9FF85",
"x. c #B2FF89",
"c. c #B9FF89",
"v. c #BEC2BC",
"b. c #C8DABC",
"n. c #CECECE",
"m. c #CDD7C7",
"M. c #CED7C8",
"N. c #D1D6CE",
"B. c #D4D4D4",
"V. c #DBDBDB",
"C. c #D6EDC6",
"Z. c #DFE5DB",
"A. c #E0EDD7",
"S. c #E3EBDD",
"D. c #E0E2DE",
"F. c #DFDDE1",
"G. c #E2DEE5",
"H. c #E5E6E5",
"J. c #E6E8E4",
"K. c #E7E4E8",
"L. c #EAE6ED",
"P. c #EBEAEB",
"I. c #EFECF1",
"U. c #EEE7F4",
"Y. c #F0EEF2",
"T. c #F2EBF8",
"R. c #F2F2F3",
"E. c #F9F5FB",
/* pixels */
"H.H.H.H.H.H.P.H.J.H.H.H.H.H.H.H.H.J.H.P.H.H.J.H.H.H.H.H.H.H.H.H.H.H.J.H.H.H.H.H.H.H.P.H.H.H.H.H.",
"H.H.H.H.H.H.H.H.H.H.P.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.P.H.J.H.H.H.H.H.H.H.H.H.H.H.P.H.H.H.",
"H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.J.H.H.H.H.H.H.H.H.H.P.H.H.H.H.H.H.H.P.",
"H.H.H.H.H.H.J.H.D.H.H.H.H.H.H.H.H.H.H.H.D.J.H.H.H.J.H.H.H.H.H.H.J.D.H.H.H.H.H.H.H.P.H.H.H.H.H.H.",
"H.H.H.H.Y.L.L.U.L.L.U.L.Y.P.L.L.H.L.L.L.U.L.L.U.P.U.L.L.U.P.L.L.H.L.L.U.P.H.H.H.H.H.H.H.H.H.H.H.",
"H.H.K.D.4.9.9.9.9.w.w.9.3.9.y.y.y.y.t.9.4.9.9.0.9.9.9.9.4.w.y.y.y.y.y.5.b.H.H.H.H.H.K.H.H.H.H.H.",
"H.H.K.S.V &.*.*.*.*.*.*.V *.a 7 7 7 h *.V *.*.,.*.*.*.%.A *.7 7 7 7 k { p.U.H.H.H.H.R.H.H.H.H.H.",
"H.H.K.S.R >.l.l.M ,.l.l.R ] * * * * ; &.T l.l.:.N l.z.=.~ _ * * * * , =.s.P.D.H.P.V.v.G.H.H.H.H.",
"J.H.H.J.Z -.x.Y l K x.-.! p * = = = = s Q >.x.H l | x.=.Q 4 * = = = = f f.P.H.G.P.n.o @ R.K.H.H.",
"H.H.H.S.Z -.l.b l c >.>.! 9 = = = = * a Q k.,.x l m l.=.Q 2 * = = = = f f.Y.D.H.H.P.# o R.H.H.H.",
"H.H.K.S.C k.Y l z l K x.V >.] d & f ;.-.V c.H l z z | j.T l.] 3 & I *.%.a.Y.H.H.P.h.O # P.H.H.H.",
"H.H.K.S.Z -.n l z l c >.T ,.c.( $ $.z.-.R ,.x z z l m j.T l.c.P % c.c.{ a.Y.H.H.H.H.V.P.H.H.H.H.",
"H.H.H.S.R -.:.X.X.X.X.-.T >.-.&.G =.>.-.T ,.X.o.X.o.o.&.R l.>.} L >.l.{ a.P.H.H.H.H.J.H.H.H.H.H.",
"H.H.K.Z.w V T C T T T T 0 T Q ~ / ! Q V q R R T T T R B q R V R W V T e p.I.H.H.H.H.H.H.H.H.H.H.",
"H.H.P.S.Z -.l.>.k.>.>.l.V >.p 4 5 4 s >.T l.>.>.l.l.l.=.R l.l.>.>.l.l.O.s.R.H.H.H.H.P.H.H.H.H.H.",
"H.H.H.S.Z -.l.l.>.l.>.>.R ] * * * * = %.T l.>.>.>.k.l.=.T z.>.>.>.l.l.%.s.P.H.H.H.V.g.H.H.H.H.H.",
"H.H.K.S.Z -.l.>.>.l.l.>.Q p * = = = * a ! l.>.l.>.>.l.=.R l.l.l.>.>.z.O.a.P.H.H.H.B.  g.I.J.H.H.",
"H.H.K.S.Z -.l.>.l.>.l.>.Q a = = = = = d ! l.>.l.l.>.l.=.R l.-.>.l.>.l.%.a.Y.D.H.G.E.@ i.R.H.H.H.",
"H.H.K.S.Z -.l.>.>.>.>.>.C l.*.g > k k.>.A l.>.>.-.>.l.=.T l.l.-.>.>.l.O.a.Y.H.H.H.n.X # Y.H.H.H.",
"H.H.K.S.Z -.l.l.>.l.l.>.T j.z.( $ #.c.-.Z l.l.l.l.l.l.=.R l.l.l.l.l.l.O.a.Y.H.H.H.J.H.D.H.H.H.H.",
"H.H.H.S.C =.-.-.-.-.-.-.V -.j.&.L =.-.=.C l.-.-.-.-.>.@.C l.-.-.>.=.>.{ a.I.J.H.H.H.H.H.H.H.H.H.",
"H.H.K.Z.w V Z C T T C C q A Z T W Z C C 0 C V Z C C C B w R C C T T R e p.P.H.H.H.H.K.H.H.H.H.H.",
"H.H.K.S.Z l.z.l.l.l.l.l.Z l.l.l.,.l.l.,.Z l.l.l.l.l.l.,.R z.l.l.l.l.z.O.s.Y.F.H.H.H.E.J.H.H.H.H.",
"H.H.K.S.Z =.l.>.l.>.>.l.V >.l.:.b ,.l.>.C l.l.>.l.l.l.=.T l.>.>.>.>.l.%.s.P.H.H.H.V.i.V.J.H.H.H.",
"H.H.K.S.Z -.l.>.-.l.l.l.T >.x.H l U x.=.T l.>.>.l.>.l.=.T z.>.l.l.>.l.%.a.P.F.J.H.V.  g.R.K.H.H.",
"H.H.K.S.Z -.l.>.l.l.l.-.A l.,.x l c >.>.T l.>.l.l.>.l.=.T l.>.l.l.>.l.O.a.Y.H.J.D.E.@ i.R.H.H.H.",
"H.H.P.S.R -.l.>.>.>.>.>.V x.H l z l K l.V l.>.>.>.>.l.=.T l.>.>.l.>.l.O.a.I.H.H.P.n.o # H.H.H.H.",
"J.H.H.S.Z -.l.l.l.l.l.l.T ,.n x x x m ,.R l.l.l.l.l.l.=.R l.l.l.l.l.l.O.a.I.J.K.H.H.P.P.H.H.H.P.",
"H.H.H.D.B @.=.=.=.=.&.=.B =.+.+.&.&.+.@.V =.=.=.=.=.=.O.V >.=.=.=.=.,.) a.I.H.H.H.H.H.H.H.H.H.H.",
"H.H.H.H.y V ~ R ! R Q R q R R T R R R Z q R T T T Z R V w R T T R T R r e.Y.D.H.H.H.H.H.H.H.H.H.",
"H.H.H.L.t.*.6 < 1 < 4 l.Z z.l.z.z.l.l.l.Z z.z.l.l.z.z.,.Q c.l.l.l.z.c.%.a.U.H.H.H.H.R.H.H.H.H.H.",
"H.H.H.L.r.` - * * * * ` Z >.-.l.>.>.l.,.C l.l.-.>.l.l.&.V l.>.l.l.,.>.{ s.I.H.H.H.B.2.V.P.H.H.H.",
"H.H.H.L.y.7 * = = - * 7 ! ,.l.l.l.>.>.-.C l.>.l.l.>.l.=.R l.l.>.l.>.l.%.s.Y.J.H.H.V.X g.P.J.H.H.",
"H.H.H.L.r.j : ; = - : k Z l.>.l.l.>.l.-.C l.>.l.>.>.l.=.T l.>.l.l.>.l.{ s.P.H.H.H.R.+ p.R.H.H.H.",
"H.H.H.P.9.>.z.) > F c.>.V l.>.>.l.l.l.=.C l.>.>.>.l.l.=.Z l.-.l.>.l.z.O.a.U.H.H.H.B.o 1.H.H.K.H.",
"H.H.H.L.r.-.l.#.% ( c.>.R l.l.l.l.l.z.l.Z z.l.l.l.l.l.-.R c.l.l.l.l.z.O.a.U.Z.K.H.H.R.P.J.H.H.H.",
"H.H.H.L.5.) O.{ F ) O.{ t O.@.O.@.O.@.O.t =.O.O.O.@.+.O.t %.O.{ O.{ %.^ a.P.J.J.H.H.H.H.H.H.H.H.",
"H.H.J.D.u a.s.a.f.s.s.f.y S R R R R R R w E R E R R E A i f.a.a.a.s.f.q.i.Y.H.H.H.H.H.H.H.H.H.H.",
"H.H.H.A.0.L.Y.I.I.I.P.T.w.>.c.c.l.z.z.l.Z z.z.z.c.z.c.&.a.E.P.P.Y.P.Y.G.g.P.H.H.H.H.E.H.H.H.H.H.",
"H.H.H.S.6.G.H.H.J.H.H.H.6.,.,.>.>.>.l.-.C l.-.>.>.>.l.%.u.L.H.H.K.J.H.B.g.P.H.H.H.B.1.B.P.H.H.H.",
"H.H.H.A.8.K.H.H.H.H.H.K.8.-.l.l.>.l.l.>.T l.>.l.l.l.l.&.u.U.H.H.H.H.P.B.g.P.H.H.H.H.X h.R.H.H.H.",
"H.H.L.A.6.L.H.H.H.H.J.L.7.*.-.-.-.,.-.*.A ,.-.-.-.-.>...t.Y.H.P.H.H.P.B.g.Y.H.H.H.R.O 2.R.H.H.H.",
"H.H.H.H.M.K.H.H.H.K.H.K.M.C.C.C.C.C.C.C.b.C.C.C.C.C.C.C.N.H.H.H.H.H.H.H.B.H.H.H.H.V.p.h.H.H.H.H.",
"H.H.H.H.H.H.H.H.H.H.H.H.H.L.L.H.L.L.L.L.P.L.L.L.L.H.L.L.H.K.H.H.H.H.H.H.P.H.H.H.H.H.R.Y.H.H.H.H.",
"H.H.H.H.H.H.H.H.P.H.H.H.H.J.H.H.J.J.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.",
"H.H.H.H.H.H.H.H.H.H.H.H.J.H.H.J.P.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.",
"P.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.P.H.H.H.H.H.H.P.H.H.H.H.P.H.H.H.H.H.H.H.H.H.H.H.H.H.H.",
"H.H.H.H.H.H.P.H.H.H.H.P.H.H.H.H.H.H.H.H.H.J.H.H.H.H.J.J.H.H.H.H.H.H.H.H.H.P.H.H.H.H.P.H.H.H.H.H."
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"32 32 171 2 ",
"   c gray37",
".  c #00AC00",
"X  c #03B302",
"o  c #0AB707",
"O  c #03BA03",
"+  c #0AB709",
"@  c #1ABE12",
"#  c #25BF19",
"$  c #29BF1D",
"%  c #479B0F",
"&  c #499E11",
"*  c #1DC111",
"=  c #22C115",
"-  c #29C81D",
";  c #2EC221",
":  c #38CF24",
">  c #3EC72C",
",  c #32C924",
"<  c #53C73B",
"1  c #53D938",
"2  c #7BAF57",
"3  c #7CAF58",
"4  c #7FB55B",
"5  c #7FAF60",
"6  c #5DC841",
"7  c #5AD640",
"8  c #5FDB43",
"9  c #63C749",
"0  c #63CB48",
"q  c #6ED145",
"w  c #72D84A",
"e  c #6FCF51",
"r  c #71D352",
"t  c #7FD05A",
"y  c #69E147",
"u  c #8D8F1C",
"i  c #8EA52F",
"p  c #AFA237",
"a  c #B0A53B",
"s  c #CEA600",
"d  c #CCAC00",
"f  c #C9B408",
"g  c #CAB810",
"h  c #C4CD2D",
"j  c #C5C925",
"k  c #C9D52F",
"l  c #C3D031",
"z  c #C4DA3E",
"x  c #80B75C",
"c  c #82B95D",
"v  c #87BE62",
"b  c #89BD64",
"n  c #9AC14A",
"m  c #8CD05F",
"M  c #83D85D",
"N  c #BDDE4C",
"B  c #A3C556",
"V  c #84E55E",
"C  c #BFE957",
"Z  c #BDEC5E",
"A  c #87C060",
"S  c #8AC363",
"D  c #8ECB64",
"F  c #8EC768",
"G  c #90CE67",
"H  c #93CD6B",
"J  c #8ADC61",
"K  c #8ED261",
"L  c #93D266",
"P  c #95D36B",
"I  c #99D46D",
"U  c #94D86C",
"Y  c #9ADB6E",
"T  c #96DD66",
"R  c #96C079",
"E  c #99CA7E",
"W  c #93D772",
"Q  c #9DD771",
"!  c #94DA72",
"~  c #9DDD70",
"^  c #A4D560",
"/  c #A2DD73",
"(  c #A3D773",
")  c #9CE36E",
"_  c #9FEC6B",
"`  c #87F061",
"'  c #8CF566",
"]  c #9CFB6D",
"[  c #9EE272",
"{  c #9CE678",
"}  c #AAE76E",
"|  c #A2E76D",
" . c #BAED63",
".. c #B1E86F",
"X. c #B9F064",
"o. c #A3E474",
"O. c #A5EB76",
"+. c #A8EC77",
"@. c #A6E179",
"#. c #A8E67B",
"$. c #A4EE7A",
"%. c #AAED7A",
"&. c #BBE875",
"*. c #ADFD77",
"=. c #ABF47A",
"-. c #AEFC7A",
";. c #A4F673",
":. c #B8F670",
">. c #B1FD7D",
",. c #B5F777",
"<. c #C3DE44",
"1. c #C3E148",
"2. c #C0E852",
"3. c gray54",
"4. c #858585",
"5. c #949494",
"6. c #9A9A9A",
"7. c #98AB8B",
"8. c #9EB78E",
"9. c #A2AF99",
"0. c #A3BD91",
"q. c #A8BF96",
"w. c #ACACAC",
"e. c #AFB4AA",
"r. c #B3B3B3",
"t. c #BCBCBC",
"y. c #9FCD82",
"u. c #A8CD88",
"i. c #ACD88E",
"p. c #AAC796",
"a. c #A9C595",
"s. c #B7CC9F",
"d. c #ADFF87",
"f. c #B5FE81",
"g. c #BAFF85",
"h. c #B4FF8A",
"j. c #BAFF8B",
"k. c #B6E595",
"l. c #BFF49C",
"z. c #B5C7A8",
"x. c #BEC7B8",
"c. c #BECDBC",
"v. c #BCC5B5",
"b. c #C1FF8D",
"n. c #C4FF95",
"m. c #C1F79D",
"M. c #C3FA9E",
"N. c #C2CBBC",
"B. c #C3C3C3",
"V. c #CECECE",
"C. c #C8CDC5",
"Z. c #D0CFCF",
"A. c #CCD1C9",
"S. c #CFCFD0",
"D. c #D4D4D4",
"F. c #D9D4D6",
"G. c #D7DED2",
"H. c #D8DFD4",
"J. c #D9DAD8",
"K. c #D8D5DA",
"L. c #D6E3CD",
"P. c #DAE2D5",
"I. c #E2DDE6",
"U. c #E5DEE8",
"Y. c #E5E5E5",
"T. c #E6E8E6",
"R. c #E7E5EA",
"E. c #E9E6EC",
"W. c #EBEAEB",
"Q. c #F4EEF8",
"!. c #F2F2F2",
/* pixels */
"Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.T.Y.Y.T.",
"Y.Y.W.W.W.W.W.W.W.R.T.R.W.W.W.W.W.W.W.W.W.W.Y.W.W.Y.Y.R.R.Y.R.T.",
"T.Y.V.S.V.Z.V.V.V.F.F.F.Z.V.V.V.V.S.Z.A.F.F.F.Z.F.T.Y.T.Y.Y.Y.Y.",
"E.H.v o./ { o.S P e 9 0 U S [ [ [ o.F H r 9 0 M a.E.Y.Y.!.W.Y.Y.",
"E.P.I j. .N j./ M O X X 0 ( h. .<.h...J O X . 1 s.R.Y.T.t.t.W.Y.",
"E.P.L h.j f f.@.< X O . - I d.l f f.#.< X O . # p.R.Y.!.5.  !.Y.",
"E.P.! Z d s 1.{ ) ` & w ;.U X.d s z { ) ' & q ] p.E.Y.W.6.3.W.Y.",
"T.P.W 2.h l <.~ %.j.p &.f.W C h l <./ o.n.a &.f.p.E.Y.Y.Y.W.E.Y.",
"E.G.3 U W W ! 4 S I U U H 3 I W W ~ c c P P P m 8.E.Y.Y.Y.Y.Y.Y.",
"W.P.L f.>.-.f.~ ) , # = V I >.>.>.>.) o.f.-.f.*.p.E.Y.Y.Y.T.Y.Y.",
"T.P.I f.f.>.f.@.0 . X . > Q >.f.f.f.[ o.f.d.f.*.p.E.Y.!.6.w.!.Y.",
"E.P.I f.>.>.f./ e - o @ 7 U f.>.f.f.) o.f.>.f.*.p.E.U.!.6.4.!.I.",
"E.P.U g.f.f.g.~ %.b.u ..b.H g.f.f.g.[ o.g.f.g.>.p.E.Y.W.t.r.T.Y.",
"E.H.S O.o.o.+.D P +.B | o.A +.O.o.+.P P +.O.O._ 0.E.Y.Y.T.!.Y.Y.",
"R.G.c [ Y ~ o.A G [ { [ Y c [ Y Y o.S D o.Y / T 0.E.Y.T.W.T.Y.T.",
"W.P.Q g.f.f.g./ %.j.<.,.f.L g.f.f.g.o.o.g.f.g.>.p.E.Y.W.t.Z.E.Y.",
"E.P.P f.f.>.f.Y $.:.d N d.L f.>.>.f.~ o.f.>.f.*.a.E.I.!.5.6.!.Y.",
"E.P.P f.-.>.f.Y $.h d g ,.P f.>.>.f.) o.f.f.f.*.p.E.Y.!.5.4.!.Y.",
"W.P.P f.f.f.f.~ } k h j  .W f.f.f.g./ O.g.f.f.>.p.E.T.R.P.I.Y.Y.",
"E.H.5 I Q Q ( c S ! W W G 2 U P P Y c v Y L L K 8.E.T.T.W.Y.Y.Y.",
"Y.I.u.y $ $ 1 Q o.>.=.>.=.G f.=.=.>.Y [ >.-.>.*.a.E.Y.Y.R.T.Y.Y.",
"T.U.y.* . . + M =.f.f.f.-.I f.f.f.f.[ o.f.f.>.>.a.T.Y.!.6.r.!.Y.",
"Y.U.E : + o - t %.f.>.f.-.G f.>.>.f.[ o.f.f.f.*.a.E.Y.!.6.4.!.Y.",
"T.I.u.b.n i n.( %.f.f.f.f.I f.f.f.g.o.o.g.f.f.>.p.E.Y.W.r.w.W.Y.",
"T.I.b -.^ B *.K Y =.+.+.O.S =.+.+.=.P T =._ O.| q.E.Y.Y.W.W.T.Y.",
"E.L.7.C.B.c.C.9.D ) Y Y U 4 Y Y Y ) v e.N.v.N.N.e.E.Y.Y.W.W.Y.T.",
"E.L.z.Q.W.E.!.C.+.g.g.g.f.I g.f.f.g.@.K.!.W.E.W.t.T.Y.E.B.K.W.Y.",
"E.L.z.E.Y.Y.W.x.| >.-.*.*.L >.*.-.>.Y D.T.Y.Y.Y.t.W.Y.!.5.5.!.Y.",
"R.P.N.E.Y.Y.E.A.k.M.M.m.m.i.M.m.m.M.k.K.E.T.T.Y.C.Y.Y.!.w.6.!.Y.",
"T.R.R.Y.Y.Y.Y.T.E.E.E.R.R.E.R.E.R.R.E.T.Y.Y.Y.Y.R.Y.Y.Y.Y.T.Y.Y.",
"T.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.R.Y.R.Y.Y.R.Y.Y.Y.Y.Y.Y.",
"T.Y.R.T.T.T.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.T.Y.Y.Y.Y.R.T.Y.Y.T.T."
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"16 16 224 2 ",
"   c #E6E6E7",
".  c #EAE5EE",
"X  c #EAE3ED",
"o  c #EEE6F1",
"O  c #F2E7F4",
"+  c #ECE6EF",
"@  c #EAE4ED",
"#  c #EBE6EF",
"$  c #F1E7F3",
"%  c #F0E7F2",
"&  c #E7E6E8",
"*  c gray90",
"=  c #DEE1DD",
"-  c #B8D6A6",
";  c #BBE2AA",
":  c #B9D7A5",
">  c #A9D198",
",  c #9BD08E",
"<  c #B1D29E",
"1  c #BBDDA8",
"2  c #BBDFA9",
"3  c #B5D3A0",
"4  c #9ED191",
"5  c #A2D091",
"6  c #D6DCD1",
"7  c #E8E7E9",
"8  c #EAEBEA",
"9  c #E6E6E6",
"0  c #D9DFD6",
"q  c #A6EA74",
"w  c #BFDD31",
"e  c #B0EF70",
"r  c #36C427",
"t  c #00AE00",
"y  c #6DDA53",
"u  c #BCE856",
"i  c #BEE346",
"p  c #85E364",
"a  c #00B200",
"s  c #1ABE0E",
"d  c #CBDBBF",
"f  c #EAE7ED",
"g  c #A3A4A3",
"h  c gray88",
"j  c #D9E2DB",
"k  c #AADB68",
"l  c #C9BD11",
"z  c #ACDA5C",
"x  c #97E36E",
"c  c #92CD4D",
"v  c #9CEB7B",
"b  c #BBCA35",
"n  c #C2C425",
"m  c #9EE979",
"M  c #86CD4C",
"N  c #89D854",
"B  c #CBDDC3",
"V  c #EAE6EB",
"C  c #BCBDBC",
"Z  c #E2E2E2",
"A  c #D9DED6",
"S  c #9CD872",
"D  c #A5F179",
"F  c #9FDD71",
"G  c #78CF55",
"H  c #5FCE42",
"J  c #8AD162",
"K  c #A4E876",
"L  c #A3EB77",
"P  c #97D66B",
"I  c #AEEC7B",
"U  c #A3E570",
"Y  c #C6D5BD",
"T  c #EBE7ED",
"R  c #E7E7E7",
"E  c #DADFD6",
"W  c #ACEB7F",
"Q  c #B8FF82",
"!  c #B5F382",
"~  c #40C62D",
"^  c #00B100",
"/  c #77D855",
"(  c #BDFD87",
")  c #B5FE81",
"_  c #A6E877",
"`  c #B7FF84",
"'  c #AEF979",
"]  c #CBDAC0",
"[  c #E8E5EB",
"{  c #A2A3A1",
"}  c #E4E4E4",
"|  c #A1E077",
" . c #ADF87A",
".. c #A0E474",
"X. c #9FDF6D",
"o. c #A0D35C",
"O. c #9DE272",
"+. c #A6ED76",
"@. c #AAF279",
"#. c #9BDD6F",
"$. c #ACF47B",
"%. c #A2EC71",
"&. c #C7D7BD",
"*. c #EBE8ED",
"=. c #D2D3D2",
"-. c #9FDD75",
";. c #ABF579",
":. c #9DE071",
">. c #A1E472",
",. c #B1F071",
"<. c #99DD71",
"1. c #A5EA75",
"2. c #A8F078",
"3. c #99DA6D",
"4. c #AAF17A",
"5. c #A0E96F",
"6. c #C7D6BD",
"7. c #EAE7EC",
"8. c #DBDCDB",
"9. c #ACEB7E",
"0. c #BBFF83",
"q. c #AAF282",
"w. c #B5DF56",
"e. c #D0C617",
"r. c #A8EA76",
"t. c #B4FA81",
"y. c #B7FF83",
"u. c #A7E877",
"i. c #B9FF85",
"p. c #B0F97A",
"a. c #E9E6EB",
"s. c #9FA09F",
"d. c gray89",
"f. c #D9DDD7",
"g. c #A2DC78",
"h. c #ACF278",
"j. c #9FE176",
"k. c #A2D258",
"l. c #B3D346",
"z. c #99D465",
"x. c #A2E976",
"c. c #A6EC76",
"v. c #97D76C",
"b. c #A7ED78",
"n. c #9EE66D",
"m. c #C6D5BC",
"M. c #EBE8EE",
"N. c #E4E4E3",
"B. c #EAE1E8",
"V. c #6FC85B",
"C. c #00B400",
"Z. c #57C63F",
"A. c #AFF282",
"S. c #ACFF86",
"D. c #9EE373",
"F. c #ADF77C",
"G. c #9EE071",
"H. c #B0F87F",
"J. c #A6F074",
"K. c #C9D8BE",
"L. c #C8C8C7",
"P. c #E6DFE6",
"I. c #8ADC6B",
"U. c #40C017",
"Y. c #78DC52",
"T. c #B2F57F",
"R. c #B8FF81",
"E. c #A6EA76",
"W. c #B2FA7F",
"Q. c #B6FF82",
"!. c #A3E872",
"~. c #B3FF7C",
"^. c #AAF972",
"/. c #C9DABE",
"(. c #EAE6EC",
"). c #A7A8A7",
"_. c #DADCD9",
"`. c #B3D29B",
"'. c #C7D99A",
"]. c #B1D493",
"[. c #9BDD70",
"{. c #97D56C",
"}. c #A1E474",
"|. c #A3E973",
" X c #9FD07E",
".X c #B9E09F",
"XX c #AFD992",
"oX c #CAD3C4",
"OX c #EAE9EC",
"+X c gray92",
"@X c #D7E0D1",
"#X c #CED5CB",
"$X c #EEE9F8",
"%X c #D3D6D2",
"&X c #A6F273",
"*X c #B1FF7A",
"=X c #A0E96E",
"-X c #ACFA77",
";X c #AAFF6F",
":X c #BBDAA5",
">X c #EEE2F6",
",X c #E1DDE4",
"<X c #D5D4D6",
"1X c #E6E7E6",
"2X c gray71",
"3X c #E1E4DF",
"4X c #DDE1DB",
"5X c #E8E7E7",
"6X c #DFE2DC",
"7X c #D1EAC0",
"8X c #D5F1C3",
"9X c #CFE7BE",
"0X c #D3EDC2",
"qX c #D3F0BF",
"wX c #D7E3CF",
"eX c #E7E6E7",
"rX c #E3E4E2",
"tX c #DFE0DF",
"yX c #C6C6C6",
"uX c #EAE5ED",
"iX c #E9E3ED",
"pX c #E9E4ED",
"aX c #E8E6EA",
"sX c white",
/* pixels */
"  . X . o O + @ X # $ % & * * * ",
"= - ; : > , < 1 2 3 4 5 6 7 8 9 ",
"0 q w e r t y u i p a s d f g h ",
"j k l z x c v b n m M N B V C Z ",
"A S D F G H J K L P I U Y T 8 R ",
"E W Q ! ~ ^ / ( ) _ ` ' ] [ { } ",
"A |  ...X.o.O.+.@.#.$.%.&.*.=.} ",
"A -.;.:.>.,.<.1.2.3.4.5.6.7.8.R ",
"E 9.0.q.w.e.r.t.y.u.i.p.] a.s.d.",
"f.g.h.j.k.l.z.x.c.v.b.n.m.M.N.* ",
"B.V.C.Z.A.S.D.@.F.G.H.J.K.a.L.9 ",
"P.I.U.Y.T.R.E.W.Q.!.~.^./.(.).d.",
"_.`.'.].[.b.{.}.|. X.XXXoXOX+X9 ",
"@X#X$X%X&X*X=X-X;X:X>X,X<X1X2X* ",
"3X4X5X6X7X8X9X0XqXwXeXrXtX9 yX} ",
"  eX* eXuXiXuXpXpXaX* 9 R * +X9 "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
};
const int n_xpm_icons = 4;
