/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 75 1 ",
"  c #020202",
". c #0D0D0D",
"X c #151515",
"o c #191919",
"O c #242424",
"+ c #2A2A2A",
"@ c #333333",
"# c #3C3C3C",
"$ c #007D00",
"% c #424242",
"& c #4D4D4D",
"* c #525252",
"= c #5D5D5D",
"- c #646464",
"; c #6B6B6B",
": c #727272",
"> c #7D7D7D",
", c #008500",
"< c #038B03",
"1 c #0B8E0B",
"2 c #0F900F",
"3 c #139113",
"4 c #199319",
"5 c #249724",
"6 c #279927",
"7 c #2C9B2C",
"8 c #339E33",
"9 c #3CA23C",
"0 c #45A545",
"q c #49A649",
"w c #4EA94E",
"e c #54AB54",
"r c #5BAD5B",
"t c #5FB05F",
"y c #64B264",
"u c #6AB46A",
"i c #72B772",
"p c #73B873",
"a c #7DBB7D",
"s c #818181",
"d c #8B8B8B",
"f c #929292",
"g c #9C9C9C",
"h c #84BD84",
"j c #A3A3A3",
"k c #A9A9A9",
"l c #B5B5B5",
"z c #BABABA",
"x c #86C086",
"c c #8AC18A",
"v c #95C595",
"b c #99C799",
"n c #9DC89D",
"m c #A6CCA6",
"M c #ABCEAB",
"N c #B4D2B4",
"B c #BBD5BB",
"V c gray77",
"C c #CDCDCD",
"Z c #C2D7C2",
"A c #C4D8C4",
"S c #CBDBCB",
"D c #D4D4D4",
"F c #D3DED3",
"G c #DFDFDF",
"H c #D7E0D7",
"J c #DEE3DE",
"K c #E6E6E6",
"L c #E9E7E9",
"P c #ECEBEC",
"I c #F2EBF2",
"U c #FCEFFC",
"Y c #F2F2F2",
"T c #FFF0FF",
"R c #FEFEFE",
/* pixels */
"KKKKKKKKKKKKKKKKLKKLKKKKKKKKKPKKKKKKKKKKKKKKKKKKKKKKKKKPKKKPKKKKKKLKKKKKKKLKKKKKKKKKKPKKKPKKKKKK",
"KKKKKKKLKKKKKKKKKKKKKKKKLKKKKKKKKKKKKKKKKKKKKPKKKPKKKKKKKKKKKKKKKKKKKKKKKKLKKKKKKKKKKKKKKKKKKKKK",
"KKLKKKKKKKLKKKKKKLKKKKLKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKKKKKKPKKKKKKKKKKKLKKKKKKKKKKKKKKKKKKKKKKK",
"KKKKLKKLKKKKKKKKKLKKKKKKKKLKKKKKKKKPKKKKKKPKKKKKKKKKKKKPKKKKKKKKKKLKPKKKKKKLKKKKPKKKKKKKKKKKKKKP",
"KLKKKKKKKKKKKKPKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKPKKPKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKPKKKKKK",
"KKKKLKLKKKKKKKKKKKLKKKKKKKKKKKPKKKKPKKKPKKKKKKKPKKKKKKKKKKKKKKKKKKKKKKKKKKKKKLKLKKKKKPKKKKKKKKKK",
"KKKKKKKKKKKPKKKKKKKKLKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKPKKK",
"KKKLKKLKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKLKKKKKKPKPKKKKKKKKKKKK",
"KKKKKKPKKPKPKKKKKKKKKLPPPPPKKLKKKKKKKPKKKKKKKKKKKKKKKLKKKKKKKKKKLPPPPPKKKKKKKKLKKKKKKKKKKKPKKKKK",
"KKKPKKKKKKKKKKKKKKKKKKDDCCDKKKKKKPKKKKKKKKKKKKKKKKKKKKKKKPKKKKKKGDDCCDKPKKKKKKKKKKKKKKKKKKKKKKPK",
"KKKKKKKKKKKKPKKKKKKPV*O   @PKKKKKKKKKKKKKKKPKKKKKKLKKKKKKKKKKKPM@X   +:DKKKKKKKKKKKKPKKKKKKKKKKK",
"KKKKKKKKKKKKKKKKKKKYg ..  %PKKKKKKKKKKKKKKKKPKKKKKKKKKKLKKKKKKPd .XX   %KKKKLKLKKPKKKKKKKKKKKKKK",
"KKKKKKKKPKKKKKKKKKKPz;g-  %PKKKKPKPKKKKKKKKKKKKKKKKKLKKKKKKKKKLl:gjg-  oBLKKLKKKKKKKKKKKKKKKKPKP",
"KPKKKPKKKKKKKKKKKKKKPYRd. %PKKKKKKKKKKKPKKKKKKKKKKKKKKKKKKKKKKKPRRRRj  oVLKKKKLKKKKKKKKKPKKKKKKK",
"KKKKKKKKKKKKKKKKKKKKKGPd  %LKKKKKKKKKKKKKPKKKKKKPKKKLKKKKKKKKKKKD:%%o  *LKKKKKKKKKKKKKPKKKKKKKKK",
"KKKKKKKKKKKKKPKKKKKKKKYd  %PKKKKKKKKKKKKKKKKKPKKKKKKKKLKKLKKKKKKC#    ;KKKKKKLKKKKKPKKKKKKKKKKKK",
"PKKPKKKKKKKKKKKLKKKKKKYd  %PKKKKKKKKKLKKLKKKKKKKKKKKKKKKKPKKKKKPJg:-X XsPKKKKLKKKPKKKKKKKKKKKLKK",
"KKKKKKKKKKLKKKKKKKKKKJPd  %LKKKKLKKKKKKKKKKKKLKKKKKKKKKKKKKKKKKKKKLKV. olPKKKKKKKKKKPKKKLKKKKKKL",
"KKKKKPKKKKKKKKKKKLKKLIYd. %YLKKKKKLKKKKKKKKKKKKKKPKKKKKKKKKKKLKKYPPPYO  sYGKKKLKKKKKKKKKKKLKKKKK",
"KKKKKKKKKLKKKLKKKKKLGCDi  #DCGKKKKKKKKKLKKLKKKKKKKKKKKPKKKKKKLCikCDCf   fPKKKKKKKKKKKKKKKKKKKKLK",
"KKKKKKKKKKKKKKKKKKKYz%%+. X%@dYJKKKKKKKKKKLKKKKKKKKKKKKKKKKKKIV. +%+   @DKKKKKKKKKKKKKKKKKKLKKKK",
"PKKKKKKKKKKKKKKKKKKYj        *RGKKKKKKKKLKKKKKKLKKKKKKKKKKKKKLD&.    X&lPKKKKKKKKKPKKKPKKKKKKKKL",
"KKKKKPKKKKKKKKKKKKKLDdddssssslPKKKKKKKKKKKLKKKKKKKKKKKKKKKKKGLLCkgdsfkGIKKKKKKKKKKKKKKKKKKKKKLKK",
"KKKKKKKKKKKKKKKKKKKKLYRTRRRRRYKKKKKKKKKKKKKKKKKKKKKKPKKKKKLKLKLLYYRRRYKKKKKKKKKKKKKKKKKKKKKKKKKK",
"KKKKKKKKKKKLKKKKKKKLKKGKGKKGKKKKKKLKKLLLKKKKKKKKKKKKKKKKKKKLKKKKKKGGKGKKKKLKKKKKKKKKKPKKKLKKKKLK",
"KKKKKLKLKGKGKJKGGJGJJKGJGGGGJKGGKJKJJJJJJKKGGKJKGKJKKKLKKKKLKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
"KKKKKGKDXXXXXXXXXXXoXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.GLKKKKKKKLKKKKKKKKKKKKKKKLKKKKKKKKKKKKKKKKKK",
"KKJYRYR; PPLPPPLPPPLPPPLPPPPPPPLPPPPPPPPPPLLLPPPPLRoDLKKKKKKKKKKKKKKKKKKKKKKKKKKPKKKKKKKKKKKLKKK",
"KKYZdfj+ KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKJYXDLKKKKKKLKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
"KJYj+& >XKKKKKKKKKKLKKKKKKKLKKKKKKKKKKKKKKKKKKKKKKYoCKJGGGGKGGGGGKGGGGGKKGGJGKGGGGGKJJJKGKGGKKKK",
"KKKPRR@lOGKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKYoLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRPKKK",
"KKLKFROlOJLKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKYo#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%lPKK",
"KKKKGR+lOJKKLKLKKKKKKKKKKKKKKKKKKKKLKLKKKKKPKKKKKJYosgddffffffffffffffffffffdffdfffffffffdk@>RGK",
"KKKKGR+zOJLKKKKKKKKLLKKKLKKKKLKKKKKKKKKLKKKKKKPKKKYoLRRRRRRYRYRRRYRYRRRYRYRRRYRRYRRYRYRRRIR;:RKK",
"KKKKGR+lOJKKKKKKKKKKKKLKKKLKKKKKKKKKKKKKKKKPKKKKKKYoDKJKJKKJGKGKKKKKJKKJGKGKKKKKKKKKKKJKKFR=:RKK",
"KKKKKR+lOJLKKLKKKKKKKKKKKKKKKKKKKKKKLKKKKKKKKKKKKKYoDLKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKR=:RGK",
"KKLKGR+lOGKKKKKKKKKKKLKKKKLKKKKKKKKKKKKKKKKKKKKKKJYoFPKKKKKKKKLKKKKKKKKKKKKKKKKLKKKKKKKKKKR=:RKK",
"KKKKGR+lOGKKKKLKKKKKKLKKKKKKKKKKLKKKKKKKKKKKKKKKLKYoDPKKKKLKKKKKLKKKKKKKKKLKKKKKKKKKKKKKKGR=:RGK",
"KLKKGR+lOGKKKKKKKKKKKKKKKKKKKKKJJJKKKKLKKKPKKKKKKKYoDLKKKKKKLKKKKKKKKKKKLKKKKKKKKLKKKKKKKGR=:RGK",
"KKKKKROlOKKKKLKKKKKKKLKLKKKKKPUTTRLKKKKKKKKKKKKKKJYXDPKKKKKKKKKKKKKKLKKKKKKKKLKKKKKKKKKKKKR=:RKK",
"KKKLJR+zOGKKKKKKPKPKKKKKKKKKLnqewwSKKKKKKKKKKKKKKKYoDKKKLKKKKKKKKKKKKKKKLKKKKKKKKKKKKKKKKJR=:RKK",
"KKKKJR+lOGLKKKKKKKKKKKKKKKKLB4$,,$BLKKKKKKKKLKKKKKYoDPKKKKKKKLLKKKKLKKKKKKKKKKKKKKLKKKLKKJR=:RGK",
"KKKKKR+lOJKKKKKLKKKKKKKKKKLJq,<<<,BPKKKKKKKKKKKKKKYoDPKKKKKKLKKKKKKKKKKKKKKKKKKKKKKKKKKKKGR=:RKK",
"KLKKGR+lOJKKKKKKKKKKPKKKKLLc,1<,<,BPKKKKKKLKKKKKKJYXDPKKKKLKKKLKKKKKKKKKKKKKKLKKKKKKKLKKKKR=:RGK",
"KKKKGR+lOJKKKKKKKKKKKKKKKLZ1,0w,<,BPKKKKKKKKKKKLKKPoDPKKKKKKKKKKKKLPIIYIPKKKKKKKLKKLKKKKKKR=:RGK",
"KKKKGR+lOJPKKKKKKKKKKKKKKK9,3Nu,<,BPKKKKLKLKKKKKKKYoFKKKKKKKKKKKPLFABNNBSPLKKKKKKKKKLKKKKGR=:RGK",
"KKKKKR+lOJPKKKKPKKKKKKKKIa,,iUr,2,BLKKKKKLKKKKKKKKYoDPKKKKKKKKKLAu04,,,<8hJLKKKKKKKKKKKLKGR=:RKK",
"KKKKGR+lOJKKKKKKKKKKKKKPB2,8KKr$<,BPKKKKKKKLKLKKKKYoDLKLKKKKKKKYh$<,,,<,,,eJKKKKKKLKKLKKKGR=:RKK",
"KLKKGROzOGKKKKKKKKKLKKKK9,2NKKt,<,NKJKKKKKKKKKKKKJYXDPKKKKKLKKKYx$18re4,<<,cIKKKKKLKKKKKKGR=:RKK",
"KKKKKR+lOJKKKKLKKKKKKJIa,<vRITy,<,STPKKKKKKKKKKPKKYoDLKKKKKKKKKIx9MSJKN9,2,rJKKKKKKKKKKKKKR=:RGK",
"KKKKGR+zOGKKKKKKLKKLLJYw,<78883,<<69vPKLKKPKKKKKKKYoDPKKKKKKKKKKHHILKKIb,<,0FLKKLKKKKLKLKKR=:RGK",
"KLKKGR+lOGLKKKKKKKKKKJTe,,,,,,<<<<,,pIJKKKKKKKKKKKYoDLKKKKKKKKKKLLKKKKLm,1,tKKKKKKKKKKKKKGR=:RKK",
"KKKLJR+lOJKKLKKKKLKKKJRe,<<<1<,<<<<<aYKKPKKKKKKKKKYoDLKKKKKKKKKKKKKKKKKw,<,bIKKKLLKKLKKKKGR=:RKK",
"KKKKKR+lOKKKKKKKKKKLKKLNbbbbbn9,<,anAKKKKKKKKKKKKGYoDPKKKKKKKKKKKKKJLKa,<,rJKKKKKKKKKKKKKGR=:RGK",
"KKKKGR+lOGKKKKKLKKKKKKKKLLLLLIy$2,AYKKKKPKKKKKKKKGYoDPKKKLKLKKKKKKKPJu,<,0FLKKKKKKLKKKKKKGR=:RKK",
"LKKKGR+lOGLKKKKKKLKKKKKKKKKKKLr$,$BLKKKKKKKKKKKKKKYoDPKKKKKKKKKKKKLHe,<,eFPKKKKKKKKKKKKKKKR=:RGK",
"KKKKGR+zOGKKKKKKKKLKKKKKKKKKKLnyiuSLKKKKKKKKKKKKKKYoDLKKKKKKKKKKKLS9,,,yJKJKKKKKKLKKKLKKKKR=:RGK",
"KKKKGR+lOJKKKKKKKKKKKKKKKKKKKKIRUUKKKKLKKLKKKLKKKKYoDLKKKKKKKKKKIB6,<<aPPPPPKKKKKKKKKKKKKGR=:RKK",
"KKKKGR+lOGKKKKKKKKKKKKKKKKKKKKJJKJKKKKKKKKKKKKKLKKYoDLKKKKKKKKKPM4,<,wMmmmnNJLKKKKKKKKKKKGR=:RKK",
"KKKKKR+lOGLKKKKLKKLKLKKKLKKKKKLKKKKKKKKKKKKKKKKKKJYXDPKKKPKKKKKIa,2<<3322319SPKKKKKLKKKKKKR=:RGK",
"KKKLGROzOJKKKLKKKKKKKKKKKKKKKKKKLKLKKLKKKKLLKKKKKJYoDPKKKKKKKKKPa$<,,,,,,,,6SPKKPKKKKKKKKJR=:RJK",
"KKKKKR+lOKKKKKKKLKKKKKKKKKKKKKKKKKKKKKKKKLKKKKKKKKYoDPKKKKKKKKKIh,4333323329FPJLKKKKKKKKKGR=:RKK",
"LKKKGR+lOGLKKKKKLKLKKKKKKKLKKLKKKKKLKKKKKKKKKKKKKKYoDPKKKKKKKKKKLLPLPILILLIPKKKKKKKKKKKKKGR=:RKK",
"KKKKGR+lOJKKKLKKKKKKLKPKKKKKKKKKKLKKKLKKLKKKKKKKKKYoDPKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKPKKKR=:RJK",
"KKKKKR+lOGKKKKKKKKKKKKKKKKKKKKKKLKKLKKLKKKKKKKKKKJYoDPKKKKKKKLLKKKKKKKKLKKKKKKKKKKLKKKKKKJR=:RKK",
"KKKKJR+lOGKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKLKKKKLKKKYoFPKKKKKKKKKKKLKLKKKKLKKKKLKKKKKKKKKKKKR=:RKK",
"KLKKJR+lOGKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKLKKKKKYXDPKKKLKKKLKLKKKKLKKKKKKKKKKLLKKKKKLKKJR=:RGK",
"KKKKGR+zOJKKKKKKKKKKJKKKKKKKKKKKKJKKKKKJJKKKJKKKKJYXDLKKKKKKKKKKKKKKKKKKKKKKKKKKKKKLKKKKLJR=:RGK",
"KKKKGR+lOKPPPLPPKPPPPPPPPKPPPPPLPPPLPPPPPPLKPPKPPKRoDPKKKKKKKKKKKKKKKKKKKKKLKKKKKLKLKKKKKGR=:RKK",
"KKKKGR+fO.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX GKKKKKKLKKKKKKPKKKKKKKKKKLKLKKKKKKKKKKR=:RKK",
"KKKPIR#XsYYPPYYPPPYPPPYPYPYPPPPYYPPPPYIPPYPYYYPYPY:-KKKKKKKKKKKKKKKKKKKKLKKKKLKKKKKKKKLKKKR=:RGK",
"KKLCgV@ fkkkkkkjkkkkkkkkkkkkkkkkkkkkkkkjkkkkjkkkkz+lPKKKLKKKKKKKKKKKKKKKKKKKKKKKKLKKKKKKKGR=:RGK",
"KKYgOo ##@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@# =JGGGGGGGKKGGKKJJKGGKGGGGGGGGGGGGGGGGGGFR=:RGK",
"KKKPRs DRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR%lRUURRRRRRRRRRRRRRTURRRRRRTURRRRRRRRTURYR::RGK",
"KKKKV% zKGGGGGKJGGJGGGKJJJGGGKGGJJJJGGKGGGGGGGGDR%+=&************&**&*&&****&&********&***-o>RKK",
"KKJR:=olYKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKGR#*d>>i>>sssss>s>is>sssissssiss>ssssssi>ss;ojYKK",
"KKLG+j#lYKKKKKKLKKKKKKLKLKKKKKKKKKKKKKKKKKKKKKKGR@lRRRRRRRRRRRRRUURRRRRRRRRRRRRRRRRRRRRRRRg*PKKK",
"KJYd+P@kPKKKKKKKKLKKKKKKKKKKKKKKKLLKLKKKKKKKKKKKR@gYGKKKKGKKJGGKGGGKGKKKGGJKGKGKGGGKJKKGLC&gYKKK",
"KGR>=ROlYKKKKKKKKKKKKKKKKKKKKKKKKKKLKKLKKKKLKKKGR@kRLPYPIPYPPYYPIIIYIPYPYIPYPYPYYYIPIPYYRd%YKKKK",
"KKYljR+lYKKKKLKKKKLKKKLKKKKLKKKKKLKKKKKKKKKKKKKJR#sCzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzk&jYGKKK",
"KKKGFR+kYKKKKKKKKKKLKLKKKKKKKKPKKKKPKKKKKKKKKKKJR%.+OOOOOOOO+OOOOOOOOOOOOOOOOO+OOOOOOOO+.@YKKKKK",
"KKKKKR+lYKKKKKKKKKKKKKKKKKKKKKKKKKKKKKPKKKKKLKLJR@lRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRC+RGKKKK",
"KKKKGR+lYKKKPKKKLKKKKKLKKKKKKKKKKKKPKKKKKKKKKKKJR@gIGJKGKGJGJGJKJGGKKGKJKGKGJJJJGJKGGKJPk+RGKKKK",
"LKLKGR+lYKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKPKKKKJR#jYKKKKKKKKKKKKKKKKKKKKKKKKKKKPKKKKKKKYl+RKKKKK",
"KKKKJR+lYKKKKKPKKKKKLKKKKKKKKKKKKKKKKKKPKKKKKKKJR#jYKKKKKKKKKKKKLKKKKKKLKKKKKKKKKKKKKKKYl+RKKKKK",
"KKKKJR+lYJKKKKKKKKKLKKKKKKKKKPKKKKKKKKKKKKKKKKKJR@gRKKKKKKKKPKKKKKKKKKKKKKKKKKKKLKKLKKKYl+RJKKKK",
"KKLKKLSJPKKKKKKKKKLKKKKKKKKKKKKKKKKKKKKKKKKKKPKKLDGLKKKLKKLKKKKKKKKLLKKKKLKKKKPKKKKKKKKKGCLKKKKL",
"KKKKKKPKKKKKKKKKLKKKKKLKPKPKKKKKKKPKKKKKKKPKKKKKKPKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKLKKKLPKKKKKK",
"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKLKKKKKKKKKKKKKKKKKKKKKKKK",
"KLKKKKKKKKKPKKPKKKKKKKKKKKPKKKKKKPKKKKKKKKKKKKKKKKKKKKKLKKKKKKKKKLKKKKKKKKKKKKKKKKKKKKKKKKKKKLKK",
"KKKLKKKKKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKLKKKPKKKLLKKKKKKKPKKKKPKKKKLKKKKKKKKK",
"KKKKKKLKKKKKKKKKKKPKKKKKKKKKKKPKKKKKKPKKKKKKKKKKKKKKLKKKKKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKKKKKKLK",
"KKKKKKKLKKPKKKKKPKKKKKKKKKKKKKKKPKKKKKKKPKKKKKKKLKKKKLKKKKKKKKLKKLKKKKLKKKKKKPKKKKKKKKKKKKLKKKKL",
"KKKKKKKKKKKKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKKKKKKKKKKKKLKKLKKKKKKKKKKKKLKKKKKKKKKKKKKLKKKKKKKKKKK",
"LKKKPKKKKKKKPKKKPKKKKKKKKKKKKKKPKKKKPKKKPKKKKKKKKKKKKKKKKKKKKKKLKKKKKKKKKPKKKKKKKKKKKKKKKKLKKKKK",
"LKKKKKKKKKKKKKKKKKKKPKKKKKKKKKKKKKKKKKKKKKKKKLKKKKLKKKKLKKKKLKKKKKKLKKKLKKKKKKKKKKPKKKKLKKKKLKLK"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"48 48 225 2 ",
"   c #E6E6E6",
".  c gray90",
"X  c #E4E4E4",
"o  c #E2E2E2",
"O  c #E1E1E1",
"+  c #EEEEEE",
"@  c #F9F9F9",
"#  c gray97",
"$  c #E9E9E9",
"%  c gray91",
"&  c #FBFBFB",
"*  c #F6F6F6",
"=  c gray92",
"-  c #B9B9B9",
";  c #727272",
":  c gray46",
">  c #D2D2D2",
",  c #EAEAEA",
"<  c #DADADA",
"1  c #7E7E7E",
"2  c #626262",
"3  c gray53",
"4  c gray86",
"5  c gray89",
"6  c gray94",
"7  c #8B8B8B",
"8  c gray17",
"9  c black",
"0  c #ECECEC",
"q  c #C5C5C5",
"w  c gray33",
"e  c #6A6A6A",
"r  c #505050",
"t  c gray95",
"y  c #B7B7B7",
"u  c gray74",
"i  c #EFEFEF",
"p  c gray93",
"a  c gray77",
"s  c #111111",
"d  c #717171",
"f  c #F1F1F1",
"g  c #A7A7A7",
"h  c gray",
"j  c gray69",
"k  c #4C4C4C",
"l  c #131313",
"z  c gray56",
"x  c #AAAAAA",
"c  c gray81",
"v  c white",
"b  c #3E3E3E",
"n  c #202020",
"m  c gray88",
"M  c gray51",
"N  c #0C0C0C",
"B  c #020202",
"V  c #0E0E0E",
"C  c gray58",
"Z  c #F3F3F3",
"A  c #939393",
"S  c gray8",
"D  c gray13",
"F  c gray1",
"G  c LightGray",
"H  c #B6B6B6",
"J  c #C3C3C3",
"K  c gray71",
"L  c gray85",
"P  c #BBBBBB",
"I  c #ACACAC",
"U  c #CACACA",
"Y  c #E7E7E7",
"T  c #DDDDDD",
"R  c #AFAFAF",
"E  c #B1B1B1",
"W  c gray72",
"Q  c gray68",
"!  c #646464",
"~  c gray52",
"^  c gray66",
"/  c gray65",
"(  c #9F9F9F",
")  c #7B7B7B",
"_  c #CECECE",
"`  c gray26",
"'  c #F4F4F4",
"]  c gray82",
"[  c #656565",
"{  c #868686",
"}  c #888888",
"|  c #898989",
" . c gray47",
".. c #5D5D5D",
"X. c gray78",
"o. c #DFDFDF",
"O. c gray57",
"+. c #E3E4E3",
"@. c #E2E4E2",
"#. c #E4E5E4",
"$. c #E6E5E6",
"%. c #F2EBF2",
"&. c #F7EDF7",
"*. c #EEE9EE",
"=. c #909090",
"-. c #E3E5E3",
";. c #7CBB7C",
":. c #39A139",
">. c #96C696",
",. c #F0EAF0",
"<. c #F3EBF3",
"1. c #A2CAA2",
"2. c #008400",
"3. c #007C00",
"4. c #6BB16B",
"5. c #F5ECF5",
"6. c #EDE9ED",
"7. c #F2EAF2",
"8. c #EFE9EF",
"9. c #EBE8EB",
"0. c #D6E0D6",
"q. c #1A911A",
"w. c #5DAE5D",
"e. c #008800",
"r. c #6AB46A",
"t. c #F4EBF4",
"y. c #C6D9C6",
"u. c #B1D1B1",
"i. c #BED6BE",
"p. c #E8E6E8",
"a. c #EAE7EA",
"s. c #4AA64A",
"d. c #56AB56",
"f. c #CFDDCF",
"g. c #008000",
"h. c #71B771",
"j. c #FCEFFC",
"k. c #E1E4E1",
"l. c #54AB54",
"z. c #008600",
"x. c #038803",
"c. c #008500",
"v. c #43A543",
"b. c #DDE2DD",
"n. c #A7CCA7",
"m. c #038903",
"M. c #ADCFAD",
"N. c #9AC79A",
"B. c #008200",
"V. c #DAE1DA",
"C. c #ECE8EC",
"Z. c #7DBC7D",
"A. c #C9DAC9",
"S. c #45A545",
"D. c #007E00",
"F. c #96C596",
"G. c #F6ECF6",
"H. c #8EC28E",
"J. c #008300",
"K. c #048804",
"L. c #068D06",
"P. c #65B165",
"I. c #EDE8ED",
"U. c #FFF2FF",
"Y. c #79BA79",
"T. c #007D00",
"R. c #A3CBA3",
"E. c #E9E7E9",
"W. c #D4DED4",
"Q. c #ACCEAC",
"!. c #BAD4BA",
"~. c #50A750",
"^. c #E5E6E5",
"/. c #A2CBA2",
"(. c #49A649",
"). c #E8E7E8",
"_. c #F7ECF7",
"`. c #3DA23D",
"'. c #8FC38F",
"]. c #5BAE5B",
"[. c #E7E6E7",
"{. c #81BD81",
"}. c #008100",
"|. c #2F9B2F",
" X c #A5CCA5",
".X c #C2D7C2",
"XX c #F1EAF1",
"oX c #42A142",
"OX c #078D07",
"+X c #028702",
"@X c #7ABA7A",
"#X c #F4ECF4",
"$X c #D3DED3",
"%X c #C7D9C7",
"&X c #C8DAC8",
"*X c #CADACA",
"=X c #D9E0D9",
"-X c #C6C6C6",
";X c gray87",
":X c gray76",
">X c #C8C8C8",
",X c gray55",
"<X c gray31",
"1X c gray60",
"2X c #959595",
"3X c #9A9A9A",
"4X c #818181",
"5X c gray44",
"6X c #2C2C2C",
"7X c gray99",
"8X c #979797",
"9X c gray29",
"0X c gray54",
"qX c gray64",
"wX c #777777",
"eX c gray32",
"rX c #848484",
"tX c #A2A2A2",
"yX c #AEAEAE",
"uX c #686868",
"iX c gray67",
"pX c #F8F8F8",
"aX c #B4B4B4",
"sX c #797979",
"dX c #838383",
/* pixels */
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                  .   X o O .   .                       .   . o O o .   .                       ",
"                    X + @ # $ .                           . % # & * % .   .                     ",
"                  X = - ; : > , X                       . % < 1 2 3 4 $ .                       ",
"                  5 6 7 8 9 - 6 5                       X 0 q w e 9 r t 5 .                     ",
"                    o @ y 9 u i X .                       X p a ; s d f 5 .                     ",
"                  . 5 f g 9 h i 5                         5 f j k l z 6 5 .                     ",
"                    5 t x 9 h i 5                       . $ c 4 v b n %   .                     ",
"      .   . 5 5 5 m 6 M N B V C f m 5 5 5 5 5 5 5 X   . o Z A S D F 1 + X .                     ",
"  .   . X % t f t f * G H J K L * f t t t t t f t 0 .   .   m P I U p   .                       ",
"    . Y i T R E E E j W h P h H j E E E E E E E Q U $ .   . Y i Z 0 X .   . . . . . . .         ",
"  . Y < L ! ~ E g ^ ^ g / / / g ^ ^ ^ ^ ^ ^ ^ x ( ) + X       X X X                   . .   .   ",
"  X , _ ) ` > & f Z Z Z Z Z Z Z Z Z Z Z Z Z Z ' p 7 % o 5 5 5 5 5 5 5 5 5 5 5 5 5 X 5 $ Y .     ",
"    5 t ] 2 q = O 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 [ { } } } } } } } } } } } } } } } |  .T % .   ",
"  . X p J ..X.p X                           . Y o.| p   Y Y Y Y Y Y Y Y Y Y Y Y Y . Z O.c = .   ",
"    X + q ..X.p X       .   . +.@.#.  .     . Y o.} , X . . . . . . . . . . . . . o f O.c = .   ",
"    X + q ..X.p X         $.#.%.&.*.#.      . Y o.| = X                           5 f =.c = .   ",
"    X + q ..X.p X     .   -.*.;.:.>.,.-..   . Y o.| = X   .   . #.-.-..   .       5 f =.c = .   ",
"    X + q ..X.p X   .   @.<.1.2.3.4.5.@..   . Y o.| = X     .   6.7.8.. #.  .     5 f =.c = .   ",
"    X + q ..X.p X     #.9.0.q.w.e.r.t.@..   . Y o.| = X   .     y.u.i.p.a.#.      5 f =.c = .   ",
"    X + q ..X.p X   . #.%.s.d.f.g.h.j.k.    . Y o.| = X . +.%.l.z.x.c.v.b.p..     5 f =.c = .   ",
"    X + q ..X.p X   +.%.n.m.M.N.B.l.V.. .   . Y o.| = X . #.C.Z.N.A.S.D.F.<.+.    5 f =.c = .   ",
"    X + q ..X.p X   @.G.H.J.K.z.L.J.P.t.@.  . Y o.| = X     #.,.I.U.Y.T.R.7.+.    5 f =.c = .   ",
"    X + q ..X.p X   . E.W.Q.!.H.3.~.0.  .   . Y o.| = X ^..   k.<./.J.(.).  .     5 f =.c = .   ",
"    X + q ..X.p X     . E.8._.f.`.N._.@.    . Y o.| = X   . #.<.'.z.].G.*.-.      5 f =.c = .   ",
"    X + q ..X.p X   .   . -.@.[.&.I.+.  .   . Y o.| = X . -.,.{.}.|. XN..Xa.#.    5 f =.c = .   ",
"    X + q ..X.p X         .   . @.#.  .     . Y o.| = X . -.XXoX2.OX+Xg.@X#X@.    5 f =.c = .   ",
"    X + q ..X.p X                           . Y o.| = X . . [.$X%X&X*X&X=X[..     5 f =.c = .   ",
"    X + q ..-X0 5 X X X X X X X X X X X X X X   ;X| = X     . 9.6.I.I.6.E..       5 f =.c = .   ",
"  . X p :X2 >Xi . Y Y Y Y Y Y Y Y Y Y Y Y Y Y % 5 ,X, X   .   #.#.#.#.#..   .     5 f =.c = .   ",
"    5 Z c <X| 1X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X3X4X5Xi O 5 5 5 5 5 5 5 5 5 5 5 5 5 O i z c = .   ",
"  X , ] d 6XC z z z z z z z z z z z z z z z z 2Xd h 7X6 t t t t t t t t t t t t t i v 8X_ = .   ",
"  . X + 9X0X< X.U U U U U U U U U U U U U U >X> d qXR I I I I I I I I I I I I I I x K wXG , .   ",
"  . = G eXQ @ , p p p p p p p p p p p p p p , # rXtXE yXyXyXyXyXyXyXyXyXyXyXyXyXQ E qXuX    .   ",
"  5 f iX{ Q 6 o . . . . . . . . . . . . . . 5 = 7 X 6 p p p p p p p p p p p p p = pXj E f 5     ",
"  .   Y aXqXZ 5                             5 f wXsX| { { { { { { { { { { { { { 3 dX[ X   . .   ",
"    5 t W tXZ 5                             X p 7 m 0 , , , , , , , , , , , , , , , 7 . .       ",
"  . X 6 W qXZ 5                             X p 7 4 Y X X X X X X X X X X X X X X . } .   .     ",
"    . Y m ;XY .                             .   4 X   .                         .   4 .         ",
"      . Y Y .                                 . %   .                             . %   .       ",
"    .   . .   .                             .   . .                                 . .         ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"32 32 190 2 ",
"   c #E6E6E6",
".  c gray90",
"X  c #E4E4E4",
"o  c gray91",
"O  c #ECECEC",
"+  c #E7E7E7",
"@  c gray92",
"#  c gray86",
"$  c #CDCDCD",
"%  c gray88",
"&  c gray79",
"*  c #CECECE",
"=  c gray89",
"-  c #EFEFEF",
";  c gray58",
":  c gray6",
">  c gray64",
",  c #F3F3F3",
"<  c #EAEAEA",
"1  c gray82",
"2  c #676767",
"3  c gray18",
"4  c #7C7C7C",
"5  c #F4F4F4",
"6  c gray26",
"7  c #959595",
"8  c #F6F6F6",
"9  c #EEEEEE",
"0  c gray66",
"q  c #1B1B1B",
"w  c #838383",
"e  c gray96",
"r  c #E2E2E2",
"t  c gray95",
"y  c gray24",
"u  c #939393",
"i  c #DDDDDD",
"p  c #585858",
"a  c #535353",
"s  c #979797",
"d  c #232323",
"f  c gray25",
"g  c #D2D2D2",
"h  c #F1F1F1",
"j  c #E9E9E9",
"k  c gray73",
"l  c #505050",
"z  c #3C3C3C",
"x  c #8B8B8B",
"c  c gray94",
"v  c #E1E1E1",
"b  c #D0D0D0",
"n  c #C6C6C6",
"m  c #C3C3C3",
"M  c gray80",
"N  c #D7D7D7",
"B  c gainsboro",
"V  c #C1C1C1",
"C  c #777777",
"Z  c #AEAEAE",
"A  c #B1B1B1",
"S  c #AFAFAF",
"D  c gray70",
"F  c gray60",
"G  c gray74",
"H  c #F9F9F9",
"J  c gray93",
"K  c #989898",
"L  c gray97",
"P  c #D5D5D5",
"I  c gray57",
"U  c #BCBCBC",
"Y  c #B4B4B4",
"T  c #B6B6B6",
"R  c gray71",
"E  c #B7B7B7",
"W  c #C5C5C5",
"Q  c #818181",
"!  c #E4E3E4",
"~  c #E0E2E0",
"^  c #E1E2E1",
"/  c #CACACA",
"(  c #9D9D9D",
")  c #CBCBCB",
"_  c gray50",
"`  c #F6ECF6",
"'  c #F0EAF0",
"]  c #E4E5E4",
"[  c gray72",
"{  c #B9B9B9",
"}  c #E9E7E9",
"|  c #8CC18C",
" . c #A7CDA7",
".. c #ECE8EC",
"X. c #B2B2B2",
"o. c #E2E3E2",
"O. c #E1E3E1",
"+. c #E3E4E3",
"@. c #E5E4E5",
"#. c #E2E4E2",
"$. c #8AC18A",
"%. c #007D00",
"&. c #53A653",
"*. c #F3EBF3",
"=. c #F4EBF4",
"-. c #F5ECF5",
";. c #EDE8ED",
":. c #EEE9EE",
">. c #BDD5BD",
",. c #58AD58",
"<. c #55AC55",
"1. c #4DA94D",
"2. c #FEEFFE",
"3. c #E1E4E1",
"4. c #81BD81",
"5. c #38A038",
"6. c #4AA74A",
"7. c #C2D7C2",
"8. c #F2EBF2",
"9. c #3FA03F",
"0. c #68B268",
"q. c #48A748",
"w. c #269926",
"e. c #D4DFD4",
"r. c #E7E6E7",
"t. c #7FBC7F",
"y. c #A1CBA1",
"u. c #339B33",
"i. c #369C36",
"p. c #F1EBF1",
"a. c #EAE7EA",
"s. c #6EB66E",
"d. c #43A543",
"f. c #189018",
"g. c #098909",
"h. c #B0D1B0",
"j. c #EFE9EF",
"k. c #F6EDF6",
"l. c #FEF1FE",
"z. c #359C35",
"x. c #5CAE5C",
"c. c #F4ECF4",
"v. c #FFF1FF",
"b. c #87C087",
"n. c #7ABA7A",
"m. c #F8EDF8",
"M. c #E8E7E8",
"N. c #E0E3E0",
"B. c #42A442",
"V. c #5BAE5B",
"C. c #EDE9ED",
"Z. c #E3E5E3",
"A. c #EFEAEF",
"S. c #41A141",
"D. c #008000",
"F. c #4FAA4F",
"G. c #72B772",
"H. c #7E7E7E",
"J. c #C8C8C8",
"K. c #E8E6E8",
"L. c #9CC89C",
"P. c #78BA78",
"I. c #92C492",
"U. c #F7ECF7",
"Y. c #F9EDF9",
"T. c gray77",
"R. c #6A6A6A",
"E. c #BBBBBB",
"W. c gray49",
"Q. c gray36",
"!. c #9A9A9A",
"~. c gray56",
"^. c gray46",
"/. c gray81",
"(. c #A5A5A5",
"). c gray67",
"_. c #AAAAAA",
"`. c #A9A9A9",
"'. c gray69",
"]. c gray85",
"[. c gray52",
"{. c #A0A0A0",
"}. c gray78",
"|. c #A2A2A2",
" X c #C0C0C0",
".X c #909090",
"XX c gray76",
"oX c gray",
"OX c #DFDFDF",
"+X c white",
/* pixels */
"                                                                ",
"          .   . X .   .             .   . . X .   .             ",
"            . o O + .                 .   O @ X                 ",
"          . + # $ % + .             .   . & * O . .             ",
"          = - ; : > , = .           . < 1 2 3 4 , = .           ",
"          . = 5 6 7 8 =               = 9 0 q w e r .           ",
"  .   . . . = t y u e r . . . . . . . + i 1 p a e = .           ",
"    X + @ o e s d f g h j @ @ @ @   = 9 k l z x c = .           ",
".   - v * b 1 n n m M 1 b b b b 1 r X = . N B 9 = X X X X X .   ",
"  X V C Z Z Z A A A S Z Z Z Z D F G H J - t h J - - - - - -   . ",
". < K C L J - 9 9 9 - - - - 9 e P I U Y T R R T T T T T R E v + ",
"= - W Q j = = = ! = ~ ^ X = r < / ( * W n n n n n n n W * ( ) J ",
"X 9 U _ O . .   . . ` ' ]   . O & [ L @ J J J J J J J @ L { & J ",
"X 9 G _ O . . . . } |  ...] ] O / X.9 r X o.o.O.+.@.X r 9 D & J ",
"X 9 G _ O .   #.` $.%.&.*.+.X O / D - X . =.-.` ;.]   X - D & J ",
"X 9 G _ O . ] :.>.,.<.1.2.3.. O / D - o...4.5.6.7...] X - D & J ",
"X 9 G _ O ] +.8.9.0.q.w.e.} +.O / D - = r.t.y.u.i.p.] = - D & J ",
"X 9 G _ O ] ] a.s.d.f.g.h.j.#.O / D - X ] k.l.z.x.c.+.= - D & J ",
"X 9 G _ O .   . ;.v.b.n.m.#.. O / D - = M.N.B.V.m.  . X - D & J ",
"X 9 G _ O . .   ] #.C.:.Z.  ] O / D - o.A.S.D.F.G.r.. = - D & J ",
"X 9 G H.< = = = = X o.O.X = r < J.D - = K.L.$.P.I.r.. = - D & J ",
"X 9 U w 5 O J J J J J J J J O 5 g Y - X . *.U.Y.-..   X - D & J ",
"X 9 T.R.{ Y Y Y Y Y Y Y Y Y D E.F Z c =   +.#.#.+.    X - D / J ",
". @ W.Q.!.~.I I I I I I I I I ; ^./.j X . . . . . . . = 9 E / J ",
"X J 2 E.@ % v v v v v v v v % + ; (.)._._._._._._._._.`.'.W.b @ ",
"j ].[./ 9   + + + + + + + +   O {./ 1 /./././././././.1 }.|.j . ",
"X J E. X9 X . . . . . . . . X O ; 0 '.S S S S S S S Z T .X{ c = ",
"X - G XX9 X                 . o _.O c - - - - - - - J L / oX9 X ",
".   r r   .                 .   OX= X = = = = = = = = X v r   . ",
"  .     .                     . +   .                 .     .   ",
".   . .   .                 .   . .                 .   . .   . ",
"                                                                "
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"16 16 111 2 ",
"   c #E6E6E6",
".  c gray90",
"X  c gray91",
"o  c #E9E9E9",
"O  c #E7E7E7",
"+  c gainsboro",
"@  c gray84",
"#  c #D7D7D7",
"$  c #DADADA",
"%  c gray89",
"&  c gray92",
"*  c #C6C6C6",
"=  c #767676",
"-  c #EFEFEF",
";  c gray68",
":  c gray36",
">  c #EEEEEE",
",  c #CECECE",
"<  c gray38",
"1  c #E2E2E2",
"2  c gray93",
"3  c DimGray",
"4  c #C1C1C1",
"5  c gray76",
"6  c gray75",
"7  c #B1B1B1",
"8  c #C0C2C0",
"9  c gray78",
"0  c gray77",
"q  c #D5D5D5",
"w  c #DDDDDD",
"e  c gray62",
"r  c gray85",
"t  c #E8E7E8",
"y  c #ECE7EC",
"u  c #E1E1E1",
"i  c gray72",
"p  c #C8C9C8",
"a  c #C4C6C4",
"s  c gray74",
"d  c #EAEAEA",
"f  c #EAE9EA",
"g  c #E3E4E3",
"h  c #BED6BE",
"j  c #E4E4E4",
"k  c #ECE9EC",
"l  c #F5ECF5",
"z  c #E9E7E9",
"x  c #D1D0D1",
"c  c LightGray",
"v  c #A9A9A9",
"b  c #DADBDA",
"n  c #F1ECF1",
"m  c #97C697",
"M  c #40A240",
"N  c #E7E6E7",
"B  c #E9E5E9",
"V  c #C9DAC9",
"C  c #95C595",
"Z  c #D5DED5",
"A  c #EDEBED",
"S  c gray81",
"D  c #DDDCDD",
"F  c #E5E7E5",
"G  c #63B163",
"H  c #329B32",
"J  c #CDDBCD",
"K  c #EDE9ED",
"L  c #C3C4C3",
"P  c #E0E3E0",
"I  c #65B265",
"U  c #98C698",
"Y  c #F9F0F9",
"T  c #CDCECD",
"R  c #E1E3E1",
"E  c #B1D1B1",
"W  c #B9D4B9",
"Q  c #3DA23D",
"!  c #C4D7C4",
"~  c #F0ECF0",
"^  c #CECFCE",
"/  c #AEAEAE",
"(  c gray87",
")  c #F1EBF1",
"_  c #C7C8C7",
"`  c #EAE7EA",
"'  c #CEDDCE",
"]  c #AACFAA",
"[  c #D1DED1",
"{  c #EFEDEF",
"}  c #D0D0D0",
"|  c #8E8E8E",
" . c #A4A4A4",
".. c #ACACAC",
"X. c #AAAAAA",
"o. c #A9AAA9",
"O. c gray65",
"+. c #AAA9AA",
"@. c #E5E2E5",
"#. c #EDE6ED",
"$. c #E4E1E4",
"%. c gray80",
"&. c #A2A2A2",
"*. c gray86",
"=. c #BBBBBB",
"-. c #B6B8B6",
";. c #C8C8C8",
":. c gray83",
">. c gray82",
",. c #D2D2D2",
"<. c white",
/* pixels */
"    . X o .       . o o .       ",
"  . O + @ O . . . O # $ O .     ",
"  % & * = - % . % - ; : & . .   ",
"  & > , < 1 o O X 2 ; 3 X   . . ",
"O 4 5 6 7 8 9 0 * O q w   %   O ",
"O e r   t y u   i 4 p a 0 9 s $ ",
"d ; w f g h   X 9 j k l z & x c ",
"d v b n m M N O 0 B V C Z A S c ",
"d v D F G H J K L j P I U Y T c ",
"d v + X R E R t L y W Q ! ~ ^ c ",
"& / ( o t ) t o _ ` ' ] [ { } c ",
"X |  ...X.o...O.+.g @.#.$.j %.c ",
"# &.u *.+ + w # v =.i -.i =.X.$ ",
"j ;.o X X X o 1 s :.>.,.,.>.6 O ",
"  % . . . . . j . d o o o d . . ",
".     .     .   . j . j j j     "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
};
const int n_xpm_icons = 4;
