/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"96 96 58 1 ",
"  c #000000",
". c #0C0C0C",
"X c #131313",
"o c #1B1B1B",
"O c #232323",
"+ c #2B2B2B",
"@ c #333333",
"# c #3B3B3B",
"$ c #007E00",
"% c #424242",
"& c gray30",
"* c #535353",
"= c #5A5A5A",
"- c #676767",
"; c #6D6D6D",
": c #737373",
"> c #7C7C7C",
", c #038003",
"< c #0D840D",
"1 c #138613",
"2 c #168816",
"3 c #1E8B1E",
"4 c #248D24",
"5 c #3A963A",
"6 c #3F983F",
"7 c #409740",
"8 c #459A45",
"9 c #4D9E4D",
"0 c #519F51",
"q c #55A155",
"w c #5BA45B",
"e c #62A762",
"r c #7CB17C",
"t c #848484",
"y c #8A8A8A",
"u c #959595",
"i c #9B9B9B",
"p c #85B585",
"a c #89B689",
"s c #8DB88D",
"d c #94BB94",
"f c #9BBD9B",
"g c #A3A3A3",
"h c #ACACAC",
"j c #B2B2B2",
"k c #BABABA",
"l c #A4C2A4",
"z c #AEC5AE",
"x c #B0C6B0",
"c c #B6C8B6",
"v c #BECCBE",
"b c #C3C3C3",
"n c #C4CEC4",
"m c #CCCCCC",
"M c #CCD1CC",
"N c #D5D5D5",
"B c #D9D7D9",
"V c #D8D8D8",
/* pixels */
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVNNNNNNNNNNNVNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVVVNNVVVVVNNVNVNNVNVVVNNNNNNNNNN",
"NNNhiuiiuiiuiuiiiiiiuiiuiuiiiuiiiuiiiijNNNNNNNNNNNNNNNNNjiiuiiuiiuuuuuuuuuiuiuuuuiuuuuiuiuikNNNN",
"NNNiujhjhjhjhjhjjjhjjjhhhjjjhjjjjjjjjuiNNNNNNNNNNNNNNNNNiijjhjjhhjhjhjhjjjhjhjhjjhjhjjhjjjuiNNNN",
"NNNijVVVVVVNVVVVNNNNNBBNNNBNNNNVNNNNBhgNNNNNNNNNNNNNNNNNujVVNNBNVVVVVVVVNVVVVVVVVVVVVVVNVVggVNNN",
"NNNuhVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiNNNNNNNNNmNNNNNNNujVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVhiNNNN",
"NNVijVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhgNNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVggVNNN",
"NNNuhVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNggVNNN",
"NNNijVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiVNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNggNNNN",
"NNNihVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhgVNNNNNNNNNNNNNNNNujNNNNNNNNNNNmMmnnmMnNNNNNNNNNNNNVggVNNN",
"NNNujVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiNNNNMMMNNNNNNNNNNujNNNNNNNNNMlpe632111dNNNNNNNNNNNVggNNNN",
"NNNijVNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNhiNNb#OOybNNNNNNNNNijNNNNNNNNNc91<,$$$$$dNNNNNNNNNNNVggVNNN",
"NNVuhVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNggVNm:. OtmNNNNNNNNujVNNNNNNNNz6$$$$$,$,dNNNNMNNNNNNVggNNNN",
"NNNihVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiNNmb:X OtmNNNNNNNujNNNNNNNNNz72597,$,$dNNNNNNNNNNNVggVNNN",
"NNNuhNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNBhiVNNNb;o O>mNNNNNNujNNNNNNNNNnfalzr$,$$dNNNNNNNNNNNNhiNNNN",
"NNNihVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVhiVNNNNb;X OtbNNNNNujNNNNNNNNNNNVVMa$$,$dNNNNNNNNNNNVggNNNN",
"NNNujVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVhiVNNNNNb;o OtmNNNNujVNNNNNNNNNNNNMp$,$$dNNNNNNNNNNNVgiNNNN",
"NNNihVNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNVhiVNNNNNNb;X otmNNNujNNNNNNNNNNNNNMp,$,$dNNNNNNNNNNNVggVNNN",
"NNNijVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiVNNNNNNNb;X otmNVujNNNNNNNNNNNNNmp$,$$dNNNMNNNNNNNVhgNNNN",
"NNNihVNNNNNNNNNMNNNNNNNMNNNNNNNNNNNNNhiVNNNNNNNNb:. oymVujVNNNNNNNNNNNNMp,,$$dNNNNNNNNNNNVhiVNNN",
"NNNijVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiVNNNNNNNNNh&  +kVujNNNNNNNNNNNNNMp,$,$dNNNNNNNNNNNVggVNNN",
"NNNuhVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVhiNNNNNNNNNb:. XtmVujNNNNNNNNNNNNNmp,,$$dNNNNNNNNNNNVhiNNNN",
"NNNijNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVhiNNNNNNNVb:X otmNNujNNNNNNNNNNNNNMp,$,$dNNNNNNNNNNNVggNNNN",
"NNNuhVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNgiVNNNNNNb;X otbNNNujNNNNNNNNNNNNNMp$,$,dNNNNNNNNNNNVhgNNNN",
"NNNijVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiVNNNNNb;o O>bNNNVujVNNNNNNNNNNNVMa,$,$dNNNNNNNNNNNVggNNNN",
"NNNihVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVhiVNNNVb:o O>mNNNNNujVNNNNNNNNNnvvcr,,$$pvbbmNNNNNNNBggNNNN",
"NNNujNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNVhiVNNNb:X O>mVNNNNNujNNNNNNNNNnpqww5$$,$6ww0pNNNNNNNNgiNNNN",
"NNNihVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVgiVNNk:X o>bVNNNNNNujVNNNNNNNNv8$$$$$$$$$$$$8MNNNNNNVhgNNNN",
"NNNijVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVhiVNm>. otmVNNNNNNNujNNNNNNNNNv8$$$$$$$$$$$$8NNNNNNNNggNNNN",
"NNNuhVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhgNNb#oOtbNNNNNNNNVujNNNNNNNNNb04433433434420NNNNNNNNggNNNN",
"NNNijVNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNVhiVNNmmmNNNNNNNNNNNujNNNNNNNNNNNmMMMMMMMmmMMNMNNNNNNNhgVNNN",
"NNNijVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNijNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNBhgNNNN",
"NNNujNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNggNNNN",
"NNNihNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVhiVMNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNggNNNN",
"NNNijVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVhiVNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiNNNN",
"NNNujVNNNNBVNNNNNNNNNNNNNNNNNNNNVNVVVhiNNNNNNNNNNNNNNNNNujBNBNNBNNNNNNNNNNNNBBNNNNNNNNNBNBhgNNNN",
"NNNuuhhhhghhhhhhhhhhhhhhhhhhhhhhhhhhhuiVNNNNNNNNNNNNNNNNiuhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhygNNNN",
"NNNjgiigigiiigiiigiigiigigiigigiiiiigikNNNNNNNNNNNNNNNNNjigiigiigigiigiiiigiigigiggiigiiiggkNNNN",
"NNNVVNNNNBNNBNNNNVNNBNNNNNNNNNNNVVNVNNNNNNNNNNNNNNNNNNNmNVVNNNVNNNNNNNNNNNNNNNNNNNBNNNNNNNNNNNmN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNVNNNNNVNNNNNNNNVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNhuuuiiuiuuuuuuuuuuuuuuuuiuuuiuuiuuujNNNNNNNNNNNNNNNNNhuiuuuuuiuuuuuiuuuuiuuuuuuiuuuuuuuujVNNN",
"NNNiijjjjjjjjjjjjjjjjjjjjjjjjjjjjhjjjugNNNNNNNNNNNNNNNNNiijjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjugVNNN",
"NNNijVNNNNNBNNNNNVVNVNVNNNNNNNNNNNBNNhiNMNNNNNNNNNNNNNNNujBNVNNNNNNNNNNNNNNBNNNNNNVNVNNNNBggVNNN",
"NNNijNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhgBNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiNNNN",
"NNNijNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNijVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNBhgNNNN",
"NNNijNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNBhgNNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNggVNNN",
"NNNuhNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNggVNNN",
"NNNijNNNNNNNNNNNMmmnnnnnmNNNNNNNNNNNNhgNNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNMbbbbbmNNNNNNNNNNhgNNNN",
"NNNihVNNNNNNNNMzpw5211<<dNNNNNNNNNNNNhiNNNNNNNNNMNNNNNNNujNNNNNNNNNNNNNNmyoXXX.:mNNNNNNNNNhiNNNN",
"NNNihNNNNNNNNNc0<<,$$$$$sNNNNNNNNNNNNhgVNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNj+     -mNNNNNNNNBgiNNNN",
"NNNujBNNNMNNNNk7$$$$$,$$sNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNk=      -NNNNNNNNNVhgNNNN",
"NNNijNNNNNNNNNz82509$$$$sNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNijNNNNNNNNNNNNmtX      -mNNNNNNNNVggVNNN",
"NNVuhVNNNNNNNNmfslzp$$$$sNNNNNNNNNNNNhgBNNNNNNNNNNNNNNNNujNNNNNNNNNNNBg@ .#    -mNNNNNNNNNggVNNN",
"NNNijNNNNNNNNNNNBBNs$$$$sNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNujBNNNNNNNNNNk=  @tX   -MNNNNNNNNNhiNNNN",
"NNNujVNNNNNNNNNNVNms,$$$sNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNujNNNNNNNNNNm>o otgX   -MNNNNNNNNNggNNNN",
"NNNujNNNNNNNNNNNNNMs,$,$sNNNNNNNNNNNNhgNNNNNNNNNNNNNNNNNujNNNNNNNNVVi@ .=mhX   -MNNNNNNNNVhgVNNN",
"NNNujNNNNNNNNNNNNNMs,$$$sNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNujNNNNNNNNNb&  #jNgX   -mNNNNNNNNVhiNNNN",
"NNNijNNNNNNNNNNNNNMs,$$$sNNNNNNNNNNNNhgNNNNNNNNNNNNNNNNNujNNNNNNNNN;o +tNNhX   -mNNNNNNNNVgiNNNN",
"NNNihVNNNNNNNNNNNNMa,$$$sNNNNNNNNNNNNhiBNNNNNNNNNNNNNNNNijBNNNNNNNi+ .-mNNhX   -mNNNNNNNNVhgNNNN",
"NNVujVNNNNNNNNNNNNMs,$$$sNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNujNNNNNNNN&. %hNNmg.   -mNNNNNNNNVggVNNN",
"NNVujVNNNNNNNNNNNNMs,$$$sNNNNNNNNNNNNhgNNNNNNNNNNNNNNNNNujNNNNNNNN#  .OOOOo    XO#tNNNNNNNggVNNN",
"NNVujVNNNNNNNNNNNNMs,$,$sNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNujNNNNNNNN#              o:VNNNNNNhiNNNN",
"NNNijVNNNNNNNMNNNNMs$$$$sNNNNNNMNNNNNhgNmNNNNNNNNNNNNNNNujNNNNNNNN@              o:VNNNNNNggNNNN",
"NNNuhNNNNNNNNNNnvvcr$$$$pbvvnNNNNNNNNhiNNNNNNNNNNNNNNNNNujNNNNNNNN;%%%%%%%@    O#*uVNNNNNVhgVNNN",
"NNNihVNNNNNNNNnp0005$$$$6000pNNNNNNNNhiNNNNNNNNNNNNNNNNNujVNNNNNNNjhhhhhhgt.   *gjbNNNNNNNhgNNNN",
"NNNujVNNNNNNNNv9$$$$$$$$$$$$7mNNNNNMNhgVNNNNNMNNNNNNNNNVujNNNNNNNNVNNNNNVNhX   -NVNNNMNNNBgiNNNN",
"NNVihVNNNNNNNNb9$$$$$$$$$$$$8MNNNNNNNhiVNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNMhX   -mNNNNNNNNVhgNNNN",
"NNNujVNNNNNNNNme4444444444440NmNNNNNBhiNNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNNh@O+O>MNNNNNNNNVggNNNN",
"NNNihVNNNNNNNNNMMMMNMNmMMmNMNNNNNNNNNhiVNNNNNNNNNNNNNNNNujVNNNNNNNNNNNNNNNNmMMNmNNNNNNNNNVggNNNN",
"NNNujVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhgNNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVgiNNNN",
"NNNijNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNVujVNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNVhgNNNN",
"NNNihNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhgNNNNNNNNNNNNNNNNNujNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNggVNNN",
"NNNihVVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhiNNNNNNNNNNNNNNNNNujVVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNBggNNNN",
"NNNujBVVVVVVVNVVVVNVVVVVBBVVVVVVVVVVVhgNNNNNNNNNNNNNNNNNujVVVVVVVVVNVVVVVVVVVVVVVVVVVVVVBBhiNNNN",
"NNNiugghgghghghghgggghgghhgghghggghghygNNNNNNMNNNNNNNNNNuuhggggghghghghggggggggggghgghgghhygNNNN",
"NNNjggigggiggiigigggiggggigiigigggigigkNNNNNNNNNNNNNNNNNjgigggggigigiiggggggggggggiggigggigkNNNN",
"NNNNNVNVNVNVVNVNNVVNNVNVVNVNNVVNNBVVNNNNNNNNNNNNNNNNNNNNNNVNVNNNNVNNNNVVNNVNVVNNNVNVNNVNVVNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"48 48 161 2 ",
"   c #D5D5D5",
".  c gray83",
"X  c gray84",
"o  c #D8D8D8",
"O  c #D7D7D7",
"+  c #CDCDCD",
"@  c #C8C8C8",
"#  c gray79",
"$  c #9F9F9F",
"%  c #B1B1B1",
"&  c #AEAEAE",
"*  c #AFAFAF",
"=  c gray88",
"-  c gray85",
";  c #DADADA",
":  c LightGray",
">  c #D9DAD9",
",  c #D7D9D7",
"<  c #D6D9D6",
"1  c #D6D8D6",
"2  c #D8D9D8",
"3  c #D2D2D2",
"4  c #D8D5D8",
"5  c #E0D8E0",
"6  c #E4DAE4",
"7  c #E6DBE6",
"8  c #DCD7DC",
"9  c #D2D3D2",
"0  c #D4D3D4",
"q  c #CBCBCB",
"w  c gray80",
"e  c #DDDDDD",
"r  c #D6D5D6",
"t  c #BFCCBF",
"y  c #8CB88C",
"u  c #6EAB6E",
"i  c #61A661",
"p  c #9DBE9D",
"a  c #DCD8DC",
"s  c #D3D4D3",
"d  c #ACACAC",
"f  c #010101",
"g  c gray51",
"h  c #E4E4E4",
"j  c gray82",
"k  c #DDD8DD",
"l  c #4C9C4C",
"z  c #007500",
"x  c #067B06",
"c  c #007000",
"v  c #64A464",
"b  c #E4DBE4",
"n  c #D1D3D1",
"m  c gray78",
"M  c #E1E1E1",
"N  c #818181",
"B  c black",
"V  c #838383",
"C  c gray89",
"Z  c #D8D6D8",
"A  c #95BB95",
"S  c #9BBE9B",
"D  c #53A053",
"F  c #69A969",
"G  c gray52",
"H  c #808080",
"J  c gray91",
"K  c #EDDEED",
"L  c #5DA45D",
"P  c #007200",
"I  c #68A968",
"U  c #E2E2E2",
"Y  c gray53",
"T  c #020202",
"R  c gray50",
"E  c #CECECE",
"W  c gray68",
"Q  c #D0D3D0",
"!  c #5AA35A",
"~  c gray9",
"^  c #323232",
"/  c #DED9DE",
"(  c #67A867",
")  c #E2DAE2",
"_  c gray81",
"`  c gray14",
"'  c #252525",
"]  c #E8DCE8",
"[  c #5DA55D",
"{  c #007100",
"}  c #6BAA6B",
"|  c #ECDEEC",
" . c #232323",
".. c gray87",
"X. c #C0CCC0",
"o. c #BDCBBD",
"O. c #509F50",
"+. c #007600",
"@. c #5BA45B",
"#. c #C0CDC0",
"$. c #C1CDC1",
"%. c #D7D5D7",
"&. c gray76",
"*. c gray11",
"=. c #E0DAE0",
"-. c #579F57",
";. c #007300",
":. c #037A03",
">. c #007700",
",. c #65A565",
"<. c #D0D2D0",
"1. c gray65",
"2. c gray37",
"3. c gray86",
"4. c #DBD7DB",
"5. c #6AAA6A",
"6. c #60A560",
"7. c #9CBE9C",
"8. c #D1D2D1",
"9. c #DFDFDF",
"0. c #DED7DE",
"q. c #E7DBE7",
"w. c #E5DAE5",
"e. c #DDD7DD",
"r. c #D0D0D0",
"t. c #E6E6E6",
"y. c #C6C6C6",
"u. c gray43",
"i. c gray38",
"p. c #9A9A9A",
"a. c gainsboro",
"s. c #535353",
"d. c #5F5F5F",
"f. c #909090",
"g. c #040404",
"h. c gray39",
"j. c gray5",
"k. c gray34",
"l. c DimGray",
"z. c #484848",
"x. c #111111",
"c. c #656565",
"v. c gray58",
"b. c gray55",
"n. c #585858",
"m. c #6A6A6A",
"M. c gray3",
"N. c #313131",
"B. c #929292",
"V. c #393939",
"C. c gray25",
"Z. c #444444",
"A. c gray12",
"S. c gray10",
"D. c #676767",
"F. c gray40",
"G. c gray60",
"H. c #5B5B5B",
"J. c #9B9B9B",
"K. c #E7E7E7",
"L. c white",
/* pixels */
"                                                                                                ",
"      . . . . . . . . . . . . . . . . . .             . . . . . . . . . . . . . . . . . .       ",
"      . X o O O O O O O O O O O O O o X .             . X o O O O O O O O O O O O O o X .       ",
"  . .   + @ # # # # # # # # # # # # @ +   . .     . .   + @ # # # # # # # # # # # # @ +   . .   ",
"  . X + $ % & * * * * * * * * * * & % $ + X .     . X + $ % & * * * * * * * * * * & % $ + X .   ",
"  . o @ % = - ; ; ; ; ; ; ; ; ; ; - = % @ O : .   . o @ % = - ; ; > , < 1 2 ; ; ; - = % @ o .   ",
"  . O # & - 3 : : : : : : : : : : 3 - & # ; o : . . O # & - 3 : : 4 5 6 7 8 9 0 : 3 - & # O .   ",
"  . O # * ; :                     : ; & q w # e : . O # * ; : . r t y u i p a s . : ; * # O .   ",
"  . O # * ; :                     : ; d : $ f g h j O # * ; : s k l z x c v b n . : ; * # O .   ",
"  . O # * ; :                     : ; * m M N B V C . # * ; : . Z A S D z F b n . : ; * # O .   ",
"  . O # * ; :                     : ; * #   h G B H J @ & ; :   . a K L P I b n . : ; * # O .   ",
"  . O # * ; :                     : ; * # O j U Y T R E W ; : . . Q k ! P I b n . : ; * # O .   ",
"  . O # * ; :                     : ; * # o j - : ~ ^ w * ; : . . n / ! P ( ) Q   : ; * # O .   ",
"  . O # * ; :                     : ; * #   ; _ ` ' _ w W ; :   . r ] [ { } | . . : ; * # O .   ",
"  . O # * ; :                     : ; * m = j `  .w ..m * ; : . r X.o.O.+.@.#.$.%.: ; * # O .   ",
"  . O # * ; :                     : ; W + &.*.' E ;   # * ; : 9 =.-.;.:.>.:.P ,.b <.; * # O .   ",
"  . O # * ; :                     : ; W j 1.2.# 3.j o # * ; : s 4.A i } 5.} 6.7.k 8.; * # O .   ",
"  . O # & - 3 : : : : : : : : : : 3 - & @ 9.J O : . O # & - 3 : 9 0.q.w.w.w.q.e.9 3 - & # O .   ",
"  . o @ % = - ; ; ; ; ; ; ; ; ; ; - = % # X r..   . o @ % = - ; ; 2 1 < < < 1 2 ; - = % @ o .   ",
"  . X + $ % & * * * * * * * * * * & % $ + X .     . X + $ % & * * * * * * * * * * & % $ + X .   ",
"  . .   + @ # # # # # # # # # # # # @ +   . .     . .   + @ # # # # # # # # # # # # @ +   . .   ",
"      . X o O O O O O O O O O O O O o X .             . X o O O O O O O O O O O O O o X .       ",
"      . . . . . . . . . . . . . . . . . .             . . . . . . . . . . . . . . . . . .       ",
"                                                                                                ",
"                                                                                                ",
"      . . . . . . . . . . . . . . . . . .             . . . . . . . . . . . . . . . . . .       ",
"      . X o O O O O O O O O O O O O o X .             . X o O O O O O O O O O O O O o X .       ",
"  . .   + @ # # # # # # # # # # # # @ +   . .     . .   + @ # # # # # # # # # # # # @ +   . .   ",
"  . X + $ % & * * * * * * * * * * & % $ + X .     . X + $ % & * * * * * * * * * * & % $ + X .   ",
"  . o @ % = - ; ; > , < 1 2 ; ; ; - = % @ o .     . o @ % = - ; ; ; ; - X X o ; ; - = % @ o .   ",
"  . O # & - 3 : : 4 5 6 7 8 9 0 : 3 - & # O .     . O # & - 3 : : : 3 X h t.e 3 : 3 - & # O .   ",
"  . O # * ; : . r t y u i p a s . : ; * # O .     . O # * ; : .   : o y.u.i.p.a.: : ; * # O .   ",
"  . O # * ; : s k l z x c v b n . : ; * # O .     . O # * ; : . . 3 9.s.B B d.C j : ; * # O .   ",
"  . O # * ; : . Z A S D z F b n . : ; * # O .     . O # * ; :   j M f.g.` B h.C j : ; * # O .   ",
"  . O # * ; :   . a K L P I b n . : ; * # O .     . O # * ; : : - y.j.k.l.B h.U j : ; * # O .   ",
"  . O # * ; : . . Q k ! P I b n . : ; * # O .     . O # * ; : : 9.z.x.- c.B c.t.j : ; * # O .   ",
"  . O # * ; : . . n / ! P ( ) Q   : ; * # O .     . O # * ; j = v.B b.h n.B d.a.j : ; * # O .   ",
"  . O # * ; :   . r ] [ { } | . . : ; * # O .     . O # * ; _ t.m.B M.B B T B N.  . ; * # O .   ",
"  . O # * ; : . r X.o.O.+.@.#.$.%.: ; * # O .     . O # * ; j 9.B.V.C.Z.A.B S.D.. : ; * # O .   ",
"  . O # * ; : 9 =.-.;.:.>.:.P ,.b <.; * # O .     . O # * ; : . O ; o J i.B F.J j : ; * # O .   ",
"  . O # * ; : s 4.A i } 5.} 6.7.k 8.; * # O .     . O # * ; :   . : 3 ; G.H.J.3.: : ; * # O .   ",
"  . O # & - 3 : 9 0.q.w.w.w.q.e.9 3 - & # O .     . O # & - 3 : : : : 3 e K.a.3 : 3 - & # O .   ",
"  . o @ % = - ; ; 2 1 < < < 1 2 ; - = % @ o .     . o @ % = - ; ; ; ; ; o X o ; ; - = % @ o .   ",
"  . X + $ % & * * * * * * * * * * & % $ + X .     . X + $ % & * * * * * * * * * * & % $ + X .   ",
"  . .   + @ # # # # # # # # # # # # @ +   . .     . .   + @ # # # # # # # # # # # # @ +   . .   ",
"      . X o O O O O O O O O O O O O o X .             . X o O O O O O O O O O O O O o X .       ",
"      . . . . . . . . . . . . . . . . . .             . . . . . . . . . . . . . . . . . .       ",
"                                                                                                "
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"32 32 190 2 ",
"   c gray83",
".  c gray84",
"X  c gray85",
"o  c #D5D5D5",
"O  c #D8D8D8",
"+  c #D0D0D0",
"@  c gray75",
"#  c #C0C0C0",
"$  c #C1C1C1",
"%  c LightGray",
"&  c #CDCDCD",
"*  c #C3C3C3",
"=  c #B7B7B7",
"-  c #C8C8C8",
";  c gray77",
":  c #C5C5C5",
">  c #B1B1B1",
",  c #CACACA",
"<  c gray73",
"1  c #BBBBBB",
"2  c gray78",
"3  c #C3C4C3",
"4  c #C4C5C4",
"5  c #AFAFAF",
"6  c gray81",
"7  c gainsboro",
"8  c #D7D7D7",
"9  c #DDDDDD",
"0  c #E6E6E6",
"q  c #DADADA",
"w  c gray82",
"e  c #BCBCBC",
"r  c gray86",
"t  c #E2DCE2",
"y  c #E6DEE6",
"u  c #E1DCE1",
"i  c #DBD9DB",
"p  c #CECECE",
"a  c #CBCBCB",
"s  c gray51",
"d  c #B9B9B9",
"f  c #DFDFDF",
"g  c gray79",
"h  c #D5D6D5",
"j  c #DCD7DC",
"k  c #88B588",
"l  c #2E912E",
"z  c #258D25",
"x  c #9CBE9C",
"c  c #DED8DE",
"v  c #D1D2D1",
"b  c #D2D2D2",
"n  c gray52",
"m  c #1E1E1E",
"M  c gray74",
"N  c #E4E4E4",
"B  c #DBD7DB",
"V  c #88B688",
"C  c #53A053",
"Z  c #007600",
"A  c #8BB68B",
"S  c #E2DAE2",
"D  c #ECECEC",
"F  c #898989",
"G  c #252525",
"H  c gray76",
"J  c #D1D3D1",
"K  c #E8DCE8",
"L  c #BFCCBF",
"P  c #007900",
"I  c #8DB88D",
"U  c #F4F4F4",
"Y  c #646464",
"T  c #343434",
"R  c #D3D4D3",
"E  c #D9D6D9",
"W  c #ABC4AB",
"Q  c #8AB68A",
"!  c #E0D9E0",
"~  c #C6C6C6",
"^  c #EAEAEA",
"/  c #9F9F9F",
"(  c #232323",
")  c #AEAEAE",
"_  c #E7DCE7",
"`  c #C0CCC0",
"'  c #007A00",
"]  c #99BD99",
"[  c #F0DFF0",
"{  c #D0D2D0",
"}  c #989898",
"|  c #191919",
" . c #A9A9A9",
".. c gray91",
"X. c #DDD8DD",
"o. c #89B689",
"O. c #309130",
"+. c #007700",
"@. c #278C27",
"#. c #71AD71",
"$. c #D7D8D7",
"%. c gray80",
"&. c gray44",
"*. c gray66",
"=. c gray89",
"-. c #D4D5D4",
";. c #499C49",
":. c #63A663",
">. c #4E9D4E",
",. c #72AC72",
"<. c #D9D5D9",
"1. c #D6D7D6",
"2. c gray72",
"3. c gray87",
"4. c #E4DDE4",
"5. c #EDE1ED",
"6. c #E8DFE8",
"7. c #B4B4B4",
"8. c gray",
"9. c #BABBBA",
"0. c #B8BBB8",
"q. c #B9BBB9",
"w. c #BBBCBB",
"e. c #CAC9CA",
"r. c #C9CAC9",
"t. c #CBCACB",
"y. c #DEDADE",
"u. c #DDDADD",
"i. c #D5D7D5",
"p. c #8DB78D",
"a. c #1E8B1E",
"s. c #0D840D",
"d. c #7FB27F",
"f. c #DAD6DA",
"g. c #A1C0A1",
"h. c #74AD74",
"j. c #70AB70",
"k. c #E5DBE5",
"l. c gray88",
"z. c #4C4C4C",
"x. c #070707",
"c. c #090909",
"v. c #D2D3D2",
"b. c #007D00",
"n. c #70AC70",
"m. c #818181",
"M. c gray22",
"N. c #7B7B7B",
"B. c black",
"V. c #D7D5D7",
"C. c #6FAB6F",
"Z. c #E3DAE3",
"A. c #161616",
"S. c #A7A7A7",
"D. c #767676",
"F. c gray70",
"G. c #DFD9DF",
"H. c #D0D3D0",
"J. c #007E00",
"K. c #78AF78",
"L. c #F0E0F0",
"P. c #E1E1E1",
"I. c #0E0E0E",
"U. c #060606",
"Y. c gray13",
"T. c #DFD8DF",
"R. c #1F8B1F",
"E. c #027902",
"W. c #128312",
"Q. c #4D9E4D",
"!. c #D4D3D4",
"~. c gray36",
"^. c gray62",
"/. c #A6C1A6",
"(. c #66A766",
"). c #7BB07B",
"_. c #6EAB6E",
"`. c #7CB07C",
"'. c gray69",
"]. c gray46",
"[. c #E0DCE0",
"{. c #ECE0EC",
"}. c #E8DEE8",
"|. c #EADFEA",
" X c #E9E9E9",
".X c #B7B8B7",
"XX c #B5B7B5",
"oX c #B6B8B6",
"OX c gray71",
"+X c white",
/* pixels */
"  . X X X X X X X X X X X o   o o   . X X X X X X X X X X O o   ",
". + @ # # # # # # # # # $ % o     . & @ # # # # # # # # @ * o o ",
"X @ = - ; : : : : : ; - > ,   %   X < 1 2 : 3 3 3 4 : ; - 5 6 . ",
"X # - 7 O O O O O O 8 9 @ - 0 q w X e & r 8 t y u i O 8 7 1 p . ",
"X # ; O %           % O e a s d f o e g h j k l z x c v O d p . ",
"X # : O   o o o o o   X 1 b n m M N d , . B V C Z A S v O d p . ",
"X # : O   o o o o o   X e 2 D F G H # g 8 J K L P I S v O d p . ",
"X # : O   o o o o o   X e g + U Y T : g 8 R E W P Q ! v O d p . ",
"X # : O   o o o o o   X e ~ ^ / ( ) $ g 8 J _ ` ' ] [ { O d p . ",
"X # : O   o o o o o   X 1 w } |  ...d , h X.o.O.+.@.#.E $.d p . ",
"X # ; 8 %           % O e %.&.*.=.o e g -.j Q ;.:.>.,.<.1.2.p . ",
"X # - 9 O X X X X X O 3.@ - 0 7 w X 1 p 7 $.4.5.6.5.6.$.9 1 & . ",
"X $ > @ e e e e e e e @ ) %.  b   X e 7.8.e 9.0.q.0.9.e 8.) + . ",
"o % , g g g g g g g g g a o       o b g g g g g g g g g - & o   ",
"  o 8 8 8 8 8 8 8 8 8 8 8     o o   o 8 8 8 8 8 8 8 8 8 8 .   o ",
"o                           o o   o                         o o ",
"o   %                       o     o   %                       o ",
"  . X X X X X X X X X X X o   o o   . X X X X X X X X X X X o   ",
". & < e e e 1 1 w.e e 1 e b o     . , d e e e e 1 1 e e 1 M   o ",
"X @ 1 & e.g r.t., , g p 7.g 8   % X d @ & , , g , a , g & > p . ",
"X # 2 r . y.u.h 8 8 . 7 8.g 8     X e & q 8 . q r o 8 . r 1 p . ",
"X # : i.X.p.a.s.d.S { X e g 8     X e , 8 b X ~ ( m $ O 8 d p . ",
"X # : $.f.g.h.' j.k.{ X e g 8     X e , 8 b l.z.x.c.M X 8 d p . ",
"X # : O J S v.b.n.k.{ X e g 8     X e ,   N m.M.N.B.: X 8 d p . ",
"X # : O R V.L b.C.Z.{ X e g 8     X e g 7 * A.S.D.B.F.O 8 d p . ",
"X # : O v.G.H.J.K.L.{ X e g 8     X e - P.*.B.I.U.B.Y.a r 2.p . ",
"X # : 1.T.I R.E.W.Q.!.X e g 8     X e , X & *.F.~.B.^.. O d p . ",
"X # ; 1.f./.(.)._.`.!.O e g 8     X e g . o r N '.].% . 8 d p . ",
"X @ - 7 1.[.{.}.|.6.8 9 8.- 8     X 1 & r 8 . o 3. XO 8 7 < & . ",
"O * 5 1 d .XXXXXXXoX2.1 ) & .     X M > 1 d d d = OXd d < ) w . ",
"o o 6 p p p p p p p p & + o   o   o   p p p p p p p p p & w o   ",
"  o . . . . . . . . . . .   o o o   o . . . . . . . . . . .   o "
};

/* XPM */
static const char *const xpm_icon_3[] = {
/* columns rows colors chars-per-pixel */
"16 16 106 2 ",
"   c LightGray",
".  c #CACACA",
"X  c gray79",
"o  c gray81",
"O  c gray83",
"+  c #CDCDCD",
"@  c #CCCBCC",
"#  c #CBCACB",
"$  c #CBCBCB",
"%  c #C5C5C5",
"&  c #CECECE",
"*  c gray80",
"=  c gray76",
"-  c gainsboro",
";  c #D7D7D7",
":  c #C1C1C1",
">  c #C7CAC7",
",  c #CACBCA",
"<  c #C3C3C3",
"1  c #D8D8D8",
"2  c gray84",
"3  c #C6C6C6",
"4  c gray52",
"5  c gray78",
"6  c #DEDADE",
"7  c #68AA68",
"8  c #57A357",
"9  c #E3DDE3",
"0  c #C8CAC8",
"q  c #D2D2D2",
"w  c #BBBBBB",
"e  c gray38",
"r  c #C6C7C6",
"t  c #DED9DE",
"y  c #B4C7B4",
"u  c #529E52",
"i  c #E7DDE7",
"p  c #C5C7C5",
"a  c #D5D5D5",
"s  c gray56",
"d  c #8D8D8D",
"f  c #DDD8DD",
"g  c #82B382",
"h  c #288D28",
"j  c #C3CFC3",
"k  c #CDCBCD",
"l  c #AFAFAF",
"z  c #DADADA",
"x  c #C4C5C4",
"c  c #D6D5D6",
"v  c #A0BFA0",
"b  c #8BB68B",
"n  c #BCCBBC",
"m  c #CCC9CC",
"M  c #CCCDCC",
"N  c gray77",
"B  c gray87",
"V  c #D0CAD0",
"C  c #D4CCD4",
"Z  c #CBC8CB",
"A  c #D4D5D4",
"S  c #D3D5D3",
"D  c #D2D3D2",
"F  c #D0D2D0",
"G  c #D0D0D0",
"H  c #C1C2C1",
"J  c #CAC8CA",
"K  c #D6CCD6",
"L  c #C3C4C3",
"P  c #C8C8C8",
"I  c gray82",
"U  c #C8C9C8",
"Y  c #D1CED1",
"T  c #C5D0C5",
"R  c #73AE73",
"E  c #BECCBE",
"W  c #D9D6D9",
"Q  c #7B7B7B",
"!  c #C9CAC9",
"~  c #CDCCCD",
"^  c #D5D6D5",
"/  c #439743",
"(  c #98BB98",
")  c #E1D9E1",
"_  c #C3C5C3",
"`  c #848484",
"'  c gray14",
"]  c #5EA25E",
"[  c #8AB58A",
"{  c #E0D9E0",
"}  c gray73",
"|  c #3E3E3E",
" . c #232323",
".. c gray58",
"X. c #D3D0D3",
"o. c #C1CFC1",
"O. c #479C47",
"+. c #66A966",
"@. c #C7C6C7",
"#. c #5F5F5F",
"$. c #B6B6B6",
"%. c #D0CCD0",
"&. c #CECBCE",
"*. c #CDCECD",
"=. c #CECDCE",
"-. c white",
/* pixels */
"  . . . . X o O O + X @ # . $ O ",
". % & * + $ = - ; : + > , & < & ",
". & 1 2 ; 2 3 4 5 $ 6 7 8 9 0 & ",
". * 2 O O q + w e r t y u i p & ",
". + ; O a   $ s d , f g h j k + ",
"X $ a   O   : l z x c v b n m M ",
"o < 3 3 3 N X B   3 % V C Z < q ",
"a 2 2 2 2 2 2   O 2 2 A S a 2 a ",
"a O D F D   a a a O     G q O a ",
"+ H J K J L 3 2 O < % 5 a P : I ",
"U Y T R E W x 2   % z * Q & $ + ",
"! ~ ^ / ( ) _ 2   N - ` ' % & + ",
". ! i ] [ { _ 2 q * } |  ...O * ",
"U X.o.O.+.a @.^   5   } #.$.I * ",
"$ < . %.&.5 N 2 O = . G O o : o ",
"O & & M *.=.q a a I + * * + o a "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
    xpm_icon_3,
};
const int n_xpm_icons = 4;
